### ISSUE TITLE
Filtering with logical OR and related tables

### ISSUE THREAD

**Issue by jkirkwood** [directus/api#1000]
I have 3 tables: a `tool_models` table which has a foreign relation to `brands` (which has a `brand_name` field) and `manufacturers` (which has a `manufacturer_name` field).

I am trying to query `tool_models` by `brand_name` and `manufacturer_name` via the API. Since the `q` query parameter only works for root fields, I'm trying to do what I need via filtering. Here is the API call I am attempting:

```
/_/items/tool_models
  ?filter[manufacturer.manufacturer_name][logical]=or
  &filter[manufacturer.manufacturer_name][like]=dewalt
  &filter[brand.brand_name][logical]=or
  &filter[brand.brand_name][like]=dewalt
```

This does not appear to work — no results were returned when I expected several. I turned on MySQL logging and can see that the query generated by this API call looks like this:

```sql
SELECT `tool_models`.`id` AS `id`,
       `tool_models`.`brand` AS `brand`,
       `tool_models`.`manufacturer` AS `manufacturer`
FROM `tool_models`
WHERE `tool_models`.`manufacturer` IN
    (SELECT `manufacturers`.`id` AS `id`
     FROM `manufacturers`
     WHERE `manufacturers`.`manufacturer_name` LIKE '%dewalt%')
  AND `tool_models`.`brand` IN
    (SELECT `brands`.`id` AS `id`
     FROM `brands`
     WHERE `brands`.`brand_name` LIKE '%dewalt%')
ORDER BY `tool_models`.`id` IS NULL,
                               `tool_models`.`id` ASC,
                               `tool_models`.`id` ASC LIMIT 200
OFFSET 0;
```

It appears the query generator is ignoring the `logical=or` when relations are involved. If the `AND` between the two subqueries was an `OR` instead, everything would work properly.

# Bug Report

## Steps to Reproduce

See above

## Expected Behavior

Generated SQL should contain `OR` instead of `AND`

## Actual Behavior

Generated SQL contains `AND` instead of `OR`

## Technical Details

- Device: Desktop
- OS: MacOS 10.14.2
- Web Server: Apache 2.4.29
- PHP Version: 7.2.17
- Database: MySQL 5.7.26
- Install Method:  cloned `master` branch

**Comment by bjgajjar** [comment]
Fixed in #1034
