### ISSUE TITLE
Unicode Characters changed after changing a field to "Required"

### ISSUE THREAD

**Issue by abukhams** [directus/api#1003]
# Bug Report
Some of the data in my app is in Arabic, so, I had to alter the collation of those field in mysql from latin1_swedish_ci to utf8mb4_unicode_ci. That works perfectly fine till I decided to change some of the fields to "Required" in Directus. As a result, Directus changed back the collation to the default latin1_swedish_ci which resulted in a permanent data corruption. 
Luckily, I have a 2 days old backup that help to limit the data loss.

## Steps to Reproduce

- Change any field in my sql from  latin1_swedish_ci to utf8mb4_unicode_ci
- in Directus, make the field "Required"
- Notice how the collation is changed back to latin1_swedish_ci.

**Comment by benhaynes** [comment]
Hmm, that's odd. We should be using UTF8-MB4 I default for everything, and we should never be changing the coalition after the database and/or fields have been created.

**Comment by abukhams** [comment]
It happened again this morning but this time after updating the note of one field using Directus app.
I used to do this all the time with no issue before. This started after updating Directus to 190325A. I built my database using v7.0.18 and altered many field before with no issue.

**Comment by ambu50** [comment]
I have solved the issue by changing the collation of the entire table to utf8mb4_unicode_ci.

**Comment by abukhams** [comment]
I have solved the issue by changing the collation of the entire table to utf8mb4_unicode_ci.
