### ISSUE TITLE
"Failed generating the SQL query" when inserting Arabic characters

### ISSUE THREAD

**Issue by khaledalissa** [directus/api#1004]
# Bug Report

## Steps to Reproduce  

1. Download the example docker-compose.yml provided by [directus/docker](https://github.com/directus/docker/blob/master/examples/thumbs-local/docker-compose.yml) repo.  
2. run `docker-compose up`  
3. create a new table with a field (text input)  
4. attempt to create a record using some Arabic characters/words (e.g. أبجد هوز)  
5. See error `Failed generating the SQL query.`

## Expected Behavior
Record should be created. 

## Actual Behavior
Error received: `Failed generating the SQL query`  

## Other Context & Screenshots

Error log
```
api[_].ERROR: Directus\Database\Exception\InvalidQueryException: Failed generating the SQL query. in /var/www/html/src/core/Directus/Database/TableGateway/BaseTableGateway.php:812
Stack trace:
#0 /var/www/html/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(264): Directus\Database\TableGateway\BaseTableGateway->executeInsert
#1 /var/www/html/src/core/Directus/Database/TableGateway/BaseTableGateway.php(390): Zend\Db\TableGateway\AbstractTableGateway->insert
#2 /var/www/html/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(410): Directus\Database\TableGateway\BaseTableGateway->addRecordByArray
#3 /var/www/html/src/core/Directus/Services/ItemsService.php(29): Directus\Database\TableGateway\RelationalTableGateway->createRecord
#4 /var/www/html/src/endpoints/Items.php(69): Directus\Services\ItemsService->createItem
#5 [internal function]: Directus\Api\Routes\Items->create
#6 /var/www/html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func
#7 /var/www/html/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke
#8 /var/www/html/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#9 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#10 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#11 [internal function]: Slim\DeferredCallable->__invoke
...
```

### Other contexts  
Error also produced using the following:
- text input (string, varchar), text area (string, text), wysiwyg (string, text).  
- using Japanese characters (平仮名).

However, the problem did not occur when attempted on the demo environment: https://directus.app/

## Technical Details

- Device: Macbook Pro
- OS: MacOS 10.13.2  
- docker-compose: using the example provided by [directus/docker](https://github.com/directus/docker/blob/master/examples/thumbs-local/docker-compose.yml) repo.  
- Install Method: copied `docker-compose.yml`, then ran `docker-compose up`

**Comment by benhaynes** [comment]
Maybe there is an issue with the database/table/field charset or collation? I would assume this would silently fail (just saving some out-of-range chars), but who knows. Could you confirm those are all `utf8-mb4` in your database?

**Comment by khaledalissa** [comment]
```mysql
SELECT schema_name, default_character_set_name FROM information_schema.SCHEMATA;
+--------------------+----------------------------+
| schema_name        | default_character_set_name |
+--------------------+----------------------------+
| information_schema | utf8                       |
| mysql              | latin1                     |
| performance_schema | utf8                       |
| somedb             | latin1                     |
| sys                | utf8                       |
+--------------------+----------------------------+
```
The follow query is for a table I created (called `examples`) with the column `name`:  

```mysql
SHOW FULL COLUMNS FROM EXAMPLES;
+------------+------------------+-------------------+
| Field      | Type             | Collation         |
+------------+------------------+-------------------+
| id         | int(15) unsigned | NULL              |
| status     | varchar(20)      | latin1_swedish_ci |
| created_by | int(10) unsigned | NULL              |
| created_on | datetime         | NULL              |
| name       | varchar(200)     | latin1_swedish_ci |
+------------+------------------+-------------------+

```

**Comment by hemratna** [comment]
@khaledalissa 

To store Arabic characters/words in the database, Please make sure you set the `CHARSET=utf8mb4` and  `COLLATE=utf8mb4_unicode_ci` for the table as well as for DB.

I test on my local machine and it worked fine.

Please check that once and let us know if the issue occurs.
Feel free to reopen 🙂
