### ISSUE TITLE
[v2.1.1] - Error: Trouble processing request. Try again after refreshing the page.

### ISSUE THREAD

**Issue by yarick2000** [directus/api#1006]
# Bug Report

## Steps to Reproduce

1. Click on any collection
2. Click on 'Info' button
3. Select  Table view
4. Select any unchecked field

## Expected Behavior
No error

## Actual Behavior
Popup error message with the following text: 
Trouble processing request. Try again after refreshing the page.

## Other Context & Screenshots
In developer console collection_presets call contains the following html:
![image](https://user-images.githubusercontent.com/13006578/59199878-ff6f8580-8b64-11e9-971a-b13b787e4bcf.png)
 
I've made some debugging and so here is a place where it fails:
![image](https://user-images.githubusercontent.com/13006578/59200373-0fd43000-8b66-11e9-9d01-d6a56bb55588.png)

'tabular-extended' is my custom layout that I've created in order to implement some custom functionality, like export/import data and translations...

## Technical Details

- Device: Desktop
- OS: Windows 10.1803 WSL
- Web Server: NGINX
- PHP Version: 7.3.4
- Database:  MySQL 5.7.25
- Install Method: cloned build branch

**Comment by bjgajjar** [comment]
Hey @yarick2000 

I am not able to replicate this error in my local environment as well as on the [directus app](https://directus.app) also. So it will be a great help if you can provide your DB. You can provide in the slack private message also.

**Comment by yarick2000** [comment]
I don't think its related to DB, but to custom extensions. I have a custom layout called 'tabular-extended' and so probably because the name is similar to original core extension (tabular) this issue is happens... You can try to duplicate existing core extension as a custom one with the name that I've mentioned above and see what happens...

**Comment by itsmerhp** [comment]
@yarick2000 
You're right, this issue is taking place due to the code snippet which you have shared in second screenshot.
But, that code has been modified recently in [commit](https://github.com/directus/api/commit/5535cffb3ec7558ea17bc54eb62fcd22ce87e7ce), please update your API code and check again.
