### ISSUE TITLE
Duplicate translation items for same language

### ISSUE THREAD

**Issue by mebenhoehta** [directus/api#1008]
# Bug Report

It is possible to create multiple translations with the same language and parent key.
Any downstream system pulling and rendering the content cannot tell which of the duplicates is the correct translation.
Duplicate content like that is effectively hidden from users since the parent collection would not display both entries for the same language

E.g. we have a test collection setup of blog_language, blog and blog_translations (jsons attached)
[example-blog-translation-setup.txt](https://github.com/directus/api/files/3275208/example-blog-translation-setup.txt)

In our case, the content editor mentioned that they entered blog content including a blog_translation for English, but when going back, it showed the translated content as blank and the content editor then entered and saved again.
In the Directus App, everything looked fine but our downstream system didn't know which content to pick.
While I was not able to reproduce the exact cause, the duplicate entry can be reproduced when two users edit the same collection and add the same translated content.

We will work around this by adding a custom MySQL unique constraint, but it would be good to have this handled from within Directus if possible

## Steps to Reproduce

1. setup of blog_language, blog and blog_translations 
2. Create a new blog, without any translations
3. Open the blog entry as two different users in two different browser and add English content with both of them
4. Check blog_translations and find two entries

## Expected Behavior

Duplicated translated content for the same language is prevented.

## Actual Behavior

It is currently possible to create duplicate translations for the same language.
While the above described scenario is using multiple users, the actual problem occurred with a single user and a single browser, though I don't know how.,

## Technical Details

- Device: Desktop
- OS:  MacOS 10.13.6, Linux
- Web Server: nginx
- PHP Version: 7.2.0
- Database:  MySQL 5.7
- Install Method: custom docker image from release artifacts

**Comment by bjgajjar** [comment]
Fixed in #1021
