### ISSUE TITLE
Add methods to cors

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#101]
I just got `Failed to load https://api.directus.io/_/collection_presets/40: Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response.`. Adding `Access-Control-Allow-Methods` with `GET,POST,PATCH,PUT,DELETE` as value fixes it.

**Comment by rijkvanzanten** [comment]
This didn't do it for me.. Adding it manually to `config/api.php` did the trick though. Maybe we can add this to the default example setup in `api_sample.php`?

**Comment by WellingGuzman** [comment]
What didn't do it? what should I add to `api_sample.php`? the `cars` config sample is in `api_sample.php` https://github.com/directus/api/blob/master/config/api_sample.php#L95-L102

**Comment by rijkvanzanten** [comment]
```php
// before
  'cors' => [
        'enabled' => false,
        'origin' => ['*'],
        'headers' => [
            ['Access-Control-Allow-Headers', 'Authorization, Content-Type, Access-Control-Allow-Origin'],
            ['Access-Control-Allow-Credentials', 'false']
        ]
    ],

// after
  'cors' => [
        'enabled' => false,
        'origin' => ['*'],
        'headers' => [
            ['Access-Control-Allow-Headers', 'Authorization, Content-Type, Access-Control-Allow-Origin'],
            ['Access-Control-Allow-Credentials', 'false'],
            ['Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE']
        ]
    ],
```

**Comment by WellingGuzman** [comment]
This should be added by the server, can you give me a example code I can use to reproduce this?

**Comment by WellingGuzman** [comment]
I added the `Access-Control-Allow-Methods` to the config file (default and template)

Ref: https://github.com/directus/api/commit/5e944254d1dd6027725cda1c29f58b90427bf151
