### ISSUE TITLE
What does the `signed` field option do?

### ISSUE THREAD

**Issue by vuhrmeister** [directus/api#1010]
I couldn't find any documentation about what that field actually does. This name is pretty generic so I can't imagine what it is for.

**Comment by benhaynes** [comment]
https://stackoverflow.com/questions/478235/signed-or-unsigned-in-mysql

We can add this to the Docs, but since Directus is a Database wrapper, most admins setting it up should be familiar with settings like this.

**Comment by vuhrmeister** [comment]
Now that you said this I remember I wanted to check on mysql docs, but totally forgot 🙈
But thx for clarification. 

It's long time ago since I worked with SQL so I'm not too deep into it anymore. So maybe it would be a good idea to at least reference the SQL docs.

**Comment by benhaynes** [comment]
Yeah, absolutely! I've added it here:

https://github.com/directus/docs/blob/master/guides/fields.md
