### ISSUE TITLE
Preview Interface, should never be required

### ISSUE THREAD

**Issue by aswincoolsaet** [directus/api#1011]
if you have a preview field.
and you add something through the API you get; "this field is required" => it shouldn't it's a generated field.

**Comment by benhaynes** [comment]
This should be setup as a "recommended" setting in the interface's `meta.json`. Is that possible @rijkvanzanten ?

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
