### ISSUE TITLE
Can't save an item after an image is selected

### ISSUE THREAD

**Issue by lcdss** [directus/api#1014]
# Bug Report

## Steps to Reproduce

1. Go to `Collections & Fields` and create a `articles` collection
3. Insert a `cover` field using the File interface
3. Save the collection
4. Go to the articles collection page and access the New page
5. Select a new file or an existent one and save
6. Access the new item Edit page
7. Select a new file or existent one
8. Try to save

## Expected Behavior

- The selected image is shown in the dropzone (step 6) - or not?
- The item is saved and the file id is attached to the item

## Actual Behavior

- The request fail with HTTP 500 error and nothing happens

## Other Context & Screenshots

Request URL: `[PATCH] https://demo-api.directus.app/_/items/articles/3?fields=%2A.%2A.%2A.%2A`

Request body:
```json
{"cover":{"id":13,"filename":"73d3776d73adcbe4b55f10dd7ddfc778.jpg","title":"73d3776d73adcbe4b55f10dd7ddfc778","description":"","location":"","tags":[],"width":3000,"height":1687,"filesize":549566,"duration":null,"metadata":null,"type":"image/jpeg","charset":"binary","embed":null,"folder":null,"uploaded_by":{"id":1,"status":"active","first_name":"Admin","last_name":"User","email":"admin@example.com","email_notifications":true,"avatar":null,"company":null,"title":null,"locale":"en-US","high_contrast_mode":false,"locale_options":null,"timezone":"America/New_York","last_access_on":"2019-06-13T04:31:07+00:00","last_page":"/collections/tickets","token":"demo","external_id":null,"roles":[{"id":1,"user":1,"role":1}]},"uploaded_on":"2019-06-13T04:22:14+00:00","storage":"local","checksum":"0a6c583a56a23a5aa73c4507a714f804","data":{"full_url":"https://demo-api.directus.app/uploads/_/originals/73d3776d73adcbe4b55f10dd7ddfc778.jpg","url":"/uploads/_/originals/73d3776d73adcbe4b55f10dd7ddfc778.jpg","thumbnails":[{"url":"https://demo-api.directus.app/thumbnail/_/200/200/crop/good/73d3776d73adcbe4b55f10dd7ddfc778.jpg","relative_url":"/thumbnail/_/200/200/crop/good/73d3776d73adcbe4b55f10dd7ddfc778.jpg","dimension":"200x200","width":200,"height":200}],"embed":null}}}
```
Response: 
```json
{"error":{"code":null,"message":"Internal Server Error"}}
```

*Obs*: The issue above was executed in the official Directus App Demo, but the same happens in my local installation.

I'm facing others errors too:

Everytime I save an item that have a column using the File interface, I get an error response and a log error in the logs directory (the same error as above, but in my local installation).

<details>
<summary>Log</summary>
[2019-06-12 22:17:20] api[_].ERROR: TypeError: Argument 3 passed to Directus\Database\TableGateway\RelationalTableGateway::recordActivity() must be of the type array, null given, called in /var/www/bj/src/core/Directus/Database/TableGateway/RelationalTableGateway.php on line 547 in /var/www/bj/src/core/Directus/Database/TableGateway/RelationalTableGateway.php:2300
Stack trace:
#0 /var/www/bj/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(547): Directus\Database\TableGateway\RelationalTableGateway->recordActivity
#1 /var/www/bj/src/core/Directus/Services/ItemsService.php(161): Directus\Database\TableGateway\RelationalTableGateway->updateRecord
#2 /var/www/bj/src/endpoints/Items.php(121): Directus\Services\ItemsService->update
#3 [internal function]: Directus\Api\Routes\Items->update
#4 /var/www/bj/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func
#5 /var/www/bj/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke
#6 /var/www/bj/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#7 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#8 /var/www/bj/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#9 [internal function]: Slim\DeferredCallable->__invoke
#10 /var/www/bj/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#11 /var/www/bj/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(81): Slim\Route->Slim\{closure}
#12 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#13 /var/www/bj/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#14 [internal function]: Slim\DeferredCallable->__invoke
#15 /var/www/bj/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#16 /var/www/bj/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#17 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#18 /var/www/bj/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#19 [internal function]: Slim\DeferredCallable->__invoke
#20 /var/www/bj/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#21 /var/www/bj/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#22 /var/www/bj/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack
#23 /var/www/bj/vendor/slim/slim/Slim/App.php(515): Slim\Route->run
#24 /var/www/bj/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#25 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#26 /var/www/bj/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#27 [internal function]: Slim\DeferredCallable->__invoke
#28 /var/www/bj/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#29 /var/www/bj/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#30 /var/www/bj/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#31 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#32 /var/www/bj/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#33 [internal function]: Slim\DeferredCallable->__invoke
#34 /var/www/bj/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#35 /var/www/bj/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#36 [internal function]: RKA\Middleware\IpAddress->__invoke
#37 /var/www/bj/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#38 [internal function]: Slim\DeferredCallable->__invoke
#39 /var/www/bj/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#40 /var/www/bj/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#41 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#42 /var/www/bj/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#43 [internal function]: Slim\DeferredCallable->__invoke
#44 /var/www/bj/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#45 /var/www/bj/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(47): Slim\App->Slim\{closure}
#46 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#47 /var/www/bj/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#48 [internal function]: Slim\DeferredCallable->__invoke
#49 /var/www/bj/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#50 /var/www/bj/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#51 /var/www/bj/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack
#52 /var/www/bj/vendor/slim/slim/Slim/App.php(313): Slim\App->process
#53 /var/www/bj/src/core/Directus/Application/Application.php(161): Slim\App->run
#54 /var/www/bj/public/index.php(5): Directus\Application\Application->run [] []
</details>

Request URL: `http://directus.local/_/items/authors/1?fields=%2A.%2A.%2A.%2A`

<details>
<summary>Request PATCH data</summary>
{
  "avatar": {
    "id": 8,
    "storage": "s3",
    "filename": "samor.jpg",
    "title": "Samor",
    "type": "image/jpeg",
    "uploaded_by": {
      "id": 1,
      "status": "active",
      "first_name": "Admin",
      "last_name": "User",
      "email": "admin@example.com",
      "token": null,
      "last_page": "/collections/authors/1",
      "external_id": null,
      "timezone": "America/Sao_Paulo",
      "locale": "en-US",
      "locale_options": null,
      "avatar": null,
      "company": null,
      "title": null,
      "email_notifications": true,
      "last_access_on": "2019-06-13T01:16:01+00:00",
      "roles": [
        {
          "id": 1,
          "user": 1,
          "role": 1
        }
      ]
    },
    "uploaded_on": "2019-06-13T01:15:30+00:00",
    "charset": "binary",
    "filesize": 26435,
    "width": 480,
    "height": 480,
    "duration": null,
    "embed": null,
    "folder": null,
    "description": "",
    "location": "",
    "tags": [],
    "checksum": "cae46113d12fd06be5b1b2c79745b8f7",
    "metadata": null,
    "data": {
      "full_url": "https://bossabox.s3.amazonaws.com/directus/samor.jpg",
      "url": "https://bossabox.s3.amazonaws.com/directus/samor.jpg",
      "thumbnails": [
        {
          "url": "http://directus.local/thumbnail/_/200/200/crop/good/samor.jpg",
          "relative_url": "/thumbnail/_/200/200/crop/good/samor.jpg",
          "dimension": "200x200",
          "width": 200,
          "height": 200
        }
      ],
      "embed": null
    }
  }
}
</details>

Response:
```json
{"error":{"code":null,"message":"Argument 3 passed to Directus\\Database\\TableGateway\\RelationalTableGateway::recordActivity() must be of the type array, null given, called in \/var\/www\/bj\/src\/core\/Directus\/Database\/TableGateway\/RelationalTableGateway.php on line 547","class":"TypeError","file":"\/var\/www\/bj\/src\/core\/Directus\/Database\/TableGateway\/RelationalTableGateway.php","line":2300}}<br />
<b>Warning</b>:  array_intersect_key(): Expected parameter 2 to be an array, null given in <b>/var/www/bj/src/core/Directus/Database/TableGateway/RelationalTableGateway.php</b> on line <b>521</b><br />
```

Another error I had was trying to add a new field to a collection. The field is added correctly but the modal keeps opened because a response couldn't be parsed and I have to refresh the page to see the changes:

Response
```json
{
  "data": {
    "collection": "articles",
    "field": "exclusive",
    "datatype": "TINYINT",
    "unique": false,
    "primary_key": false,
    "auto_increment": false,
    "default_value": "0",
    "note": null,
    "signed": false,
    "id": 167,
    "type": "boolean",
    "sort": null,
    "interface": "toggle",
    "hidden_detail": false,
    "hidden_browse": false,
    "required": true,
    "options": {
      "labelOn": "",
      "checkbox": false
    },
    "locked": false,
    "translation": null,
    "readonly": false,
    "width": "full",
    "validation": null,
    "group": null,
    "length": "3"
  }
}<br />
<b>Warning</b>:  strlen() expects parameter 1 to be string, array given in <b>/var/www/bj/src/core/Directus/Services/AbstractService.php</b> on line <b>504</b><br />
```

As a temporary fix, I added a check for arrays in the AbstractService.php file to stop this error:

```php
protected function validateFieldLength($field, $value)
{
    if (is_array($value)) {
        return;
    }

    // ...
}
```

I recorded a 4 minutes gif file that can help:

![Peek 2019-06-13 00-38](https://user-images.githubusercontent.com/6903590/59404583-74b5a300-8d7d-11e9-890f-68da0d59c3cc.gif)

## Technical Details

- Device: Desktop
- OS: Arch Linux
- Web Server: Nginx
- PHP Version: 7.3.4 - php-fpm
- Database: MariaDB 10.3
- Install Method: directus/directus (master branch)
- Execution method: using docker

[Fork Repository](https://github.com/lcdss/directus)

**Comment by lcdss** [comment]
Another bug happens when you set App Logo, save it and delete the logo in the File Library. Now refresh the page. You will see:

![Screenshot_2019-06-13 Directus](https://user-images.githubusercontent.com/6903590/59405578-4f2a9880-8d81-11e9-9456-51573da28b23.png)

**Comment by lcdss** [comment]
Another bug happens when you set App Logo, save it and delete the logo in the File Library. Now refresh the page. You will see:

![Screenshot_2019-06-13 Directus](https://user-images.githubusercontent.com/6903590/59405578-4f2a9880-8d81-11e9-9456-51573da28b23.png)

Screenshot taken on official demo: https://directus.app/#/files

**Comment by shealavington** [comment]
Might be worth a new issue for that comment.

**Comment by shealavington** [comment]
Cheers for the detailed issue and the error log.

Based on that error and an _"Ongoing Investigation"_ haha, I'm going to go ahead and say it's the same issue as https://github.com/directus/api/issues/1015 and should be resolved soon.

I'll close this issue as there's an ongoing conversation in the linked issue and you can check there for status-updates on this.
