### ISSUE TITLE
[Broken] Saving Files

### ISSUE THREAD

**Issue by shealavington** [directus/api#1015]
On the latest suite & the demo the files and file interfaces are not saving the relation to `directus_files.id`

Using the `files` interface will insert NULL into the mapping table where the file ID should be, and the `file` interface will throw 'internal server error'.

I'm unsure if this is app or api, I think it's the app providing the API with an object which fails, where it should only be and ID passed through.

https://www.loom.com/share/47487a7fcb084f2ca7f813ef6d4d1838

**Comment by shealavington** [comment]
@bjgajjar Awesome! Thanks for that, there's some good information in the two referenced issues above. :smile:

**Comment by dev7ch** [comment]
Sorry, but still have error, now i a unable to create a file field, in the most case i got an error about invalid format (also when saving uploaded files)

Have you test it?

i am on the latest master versions (api/app), and run the update script.
Could you please confirm, that creating a new file Filed and adding a file is working..

![image](https://user-images.githubusercontent.com/15183757/59546966-f7ce2900-8f36-11e9-95bc-465e1bf7f127.png)

**Comment by dev7ch** [comment]
upps, somehow on the server is working,  it might be related to the local env i have

**Comment by visualcookie** [comment]
I still have this issue, even after upgrading.

**Comment by shealavington** [comment]
There have been no releases to the suite since this fix was implemented. I'm afraid you'll have to wait for the next release which could happen anytime between now and next week.

**Comment by onlinelessons** [comment]
When will this be released? Can't save any files in my relations....

**Comment by shealavington** [comment]
This was released three days ago. 

https://github.com/directus/directus/releases
