### ISSUE TITLE
Add item status to item action hook payload

### ISSUE THREAD

**Issue by GeospatialMax** [directus/api#1017]
# Feature Request

## What problem does this feature solve?

**Without the feature**
- I am calling a webhook whenever an item is created or updated
- Need to know the status of the item
- Status is not submitted as part of the payload though, therefore I have to make a separate API call to get it

**With the new feature**
- I don't need to make a duplicate call, but can submit the status straight to the webhook

## How do you think this should be implemented?

- probably needs to inject the status of an item here: https://github.com/directus/api/blob/master/src/core/Directus/Application/CoreServicesProvider.php#L241

## Would you be willing to work on this?

- sorry, my knowledge of the inner workings of the directus API is not deep enough to work on this

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
@bjgajjar — any reason we can't add this?
