### ISSUE TITLE
Warning after json API response for json and array field types

### ISSUE THREAD

**Issue by Kinzi** [directus/api#1019]
# Bug Report

When I have a field set to json or array and post something to that collection, it will execute the post but add the following warning after the json response:

```
{
... the expected json object of the collection
}
<br/ > ↵ < b > Warning </b>:  strlen() expects parameter 1 to be string, array given in <b>/api/ src/core/Directus/Services/AbstractService.php </b> on line <b>500</b> <br / > ↵
```

I get the same error when using the app to update in some collections. The error reads:

`API returned invalid JSON` 

when i inspect it it's because of the same error as above: first the JSON object, then the error message.

## Steps to Reproduce

1. set up a collection with an array field and/or json field (for interfaces tags or code)
2. API post to collection
3. see response

## Expected Behavior
Just correct json response

## Actual Behavior
json response plus added error message

## Technical Details

Latest build branch of the API

- Device: Desktop
- OS: MAC
- Web Server: MAMP / Apache
- PHP Version: 7.2.8
- Database: [eg: MySQL 8.0.12]
- Install Method: cloned api build

**Comment by Kinzi** [comment]
Probably not very elegant but a quick fix is to add:

```
 $testvalue = '';
            if (is_string($value)) {
                $testvalue = $value;
            } else {
                $testvalue = json_encode($value);
            }
```

to `src/core/Directus/Services/AbstractService.php` in line 500 (beginning of the `else` clause)

**Comment by bjgajjar** [comment]
Fixed in #1024

**Comment by Kinzi** [comment]
@bjgajjar Thanks for fixing - when will this be in the build branch?

**Comment by bjgajjar** [comment]
Hey @Kinzi 

If everything will work as per the plan; then we will make it live at today EOD.
