### ISSUE TITLE
Filters behavior with relationship fields

### ISSUE THREAD

**Issue by 24js** [directus/api#1025]
Whenever you search directly in collections it doesn't work with relationships, But if you filter directly using field name it's working, I'm not sure if I'm tripping or something but I'm kinda sure the previous version had this feature
 
Also, there is a style artifact when a search doesn't have a result and you clear the filter the table view wildly jumps from bottom to top of the page ( I checked using latest chrome and firefox )

https://www.loom.com/share/9c6761cbd37548bd82045b37ed54747f

**Comment by bjgajjar** [comment]
@rijkvanzanten - Yes the flow is the same which you have mentioned. 

> The text input search is using the `q` parameter. I'm assuming the `q` parameter doesn't search through the related data, while using the filter does.

And we can consider it as a feature request to give the API support.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
