### ISSUE TITLE
Cannot delete items with custom primary key field name

### ISSUE THREAD

**Issue by phoenixtechnam** [directus/api#1026]
# Bug Report
Seems to be a similar issue as
https://github.com/directus/api/issues/705
present in version 7.5.0.

I have a managed collection "pages" using custom primary key INT. The field is named "page_id" instead of "id". Deleting items from that collection fails.

## Steps to Reproduce

1. Go to a collection ("pages" in my case)
2. Select one item
3. Click Delete

## Expected Behavior
The item should be removed from the db and from the interface.

## Actual Behavior
An error is displayed and no item is removed.
"Trouble processing request. Try again after refreshing the page."

Same behavior when using JS SDK, error:
"Error deleting a record in pages with id 8":
"id" should be "page_id"...

## Technical Details

- Device: vServer
- OS: CentOS 7
- Web Server: Apache
- PHP Version: 7.3
- Database: MariaDB
- Install Method: cloned `master` branch

**Comment by phoenixtechnam** [comment]
@benhaynes : yes it shows as primary_key interface in APP and it's also the primary key in SQL

**Comment by phoenixtechnam** [comment]
when changing the primary key from "page_id" back to "id" things work as expected !

**Comment by bjgajjar** [comment]
@phoenixtechnam  Agree with you. I am getting the same error. Able to add the primary key with any name but not able to delete it. Trying to resolve that. :)

**Comment by bjgajjar** [comment]
Fixed in #1042
