### ISSUE TITLE
File is longer than the field's supported length (10)

### ISSUE THREAD

**Issue by rafaellincoln** [directus/api#1027]
# Bug Report

## Steps to Reproduce

1. Open collection
2. Add file
3. Save collection

## Expected Behavior
Success save.

## Actual Behavior
Error: `The value submitted (Json / Array) for 'Logo' is longer than the field's supported length (10). Please submit a shorter value or ask an Admin to increase the length.`

## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/6615134/59615899-be91e680-90f9-11e9-97d6-c6773c8eb424.png)

## Technical Details

- Device: Desktop
- OS: MacOS 10.14.5
- Web Server: Apache/2.4.29 (Ubuntu)
- PHP Version: 7.2.19
- Database: MySQL 5.7.26-0
- Install Method: cloned `master` branch

**Comment by bjgajjar** [comment]
Fixed in #1029
