### ISSUE TITLE
Can't save files

### ISSUE THREAD

**Issue by mimamuh** [directus/api#1032]
# Bug Report

## Steps to Reproduce

1. Have a file field
2. Change file or add a new one
3. Save file

## Expected Behavior
Save file

## Actual Behavior
Error Frontend:
```js
PATCH http://localhost/_/items/shows/7?fields=%2A.%2A.%2A.%2A 500 (Internal Server Error)
item.vue:750 Uncaught (in promise) TypeError: Cannot read property 'message' of undefined
```

Log api backend
```md
"OPTIONS /_/items/shows/7?fields=%2A.%2A.%2A.%2A HTTP/1.1" 200 0
WARNING: "PHP Warning:  strlen() expects parameter 1 to be string, array given in /Directus/Services/AbstractService.php on line 500"
WARNING: "PHP Warning:  array_intersect_key(): Argument #2 is not an array in /Directus/Database/TableGateway/RelationalTableGateway.php on line 522"
WARNING: "PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /Directus/Util/ArrayUtils.php on line 92"
```
## Other Context & Screenshots
https://www.loom.com/share/0687a8457e65478c9c2f4b3fb7c27d5f

## Technical Details

- Device: MacBook Pro
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Web Server: Nginx
- PHP Version: 7.2.18
- Database: mysql 5.7
- Install Method: docker

**Comment by shealavington** [comment]
I'm pretty certain this is the same as the linked below which should be ready for next-release (later today). 
I'm closing as duplicate, please re-open if the issue persists after the next release or if you know for sure that it's not that.

Ref: https://github.com/directus/api/issues/1015
