### ISSUE TITLE
'mine' permissions on directus_files

### ISSUE THREAD

**Issue by phoenixtechnam** [directus/api#1047]
# Feature Request
'mine' permissions on directus_files to separate file access per user

## What problem does this feature solve?
I am trying to achieve full api data separation based on user accounts. That works well so far by setting access permissions to 'mine' for custom collections and non-admin users.
I also want users to see 'their' files only. Using the 'mine' permission on directus-files is not supported at this stage although the "uploaded_by" field would allow owner tracking.

## How do you think this should be implemented?
Use existing "uploaded_by" field or create a new one like 'created_by' for collections to track the owner user id.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
