### ISSUE TITLE
[Feature Request] Watermarks

### ISSUE THREAD

**Issue by Nitwel** [directus/api#1049]
Hey,
it would be nice to be able to generate watermarks onto images, nothing more.

How should this work:
- have a PNG file as a watermark
- this watermark is set in the project settings
- if the watermark is set, it gets added to all images

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
