### ISSUE TITLE
'Attempting to write an array as the value for field 'X' for collection 'Y' when adding multiple files

### ISSUE THREAD

**Issue by mebenhoehta** [directus/api#1052]
# Bug Report

Saving a collection while adding more than one file throws error:
```
{"error":{"code":213,"message":"Attempting to write an array as the value for field \"file2\" in \"testimages\"","class":"Directus\\Database\\Exception\\SuppliedArrayAsColumnValue","file":"\/var\/www\/html\/src\/core\/Directus\/Database\/TableGateway\/BaseTableGateway.php","line":1785}}
```
I believe this is neither like directus/api#1015 nor  directus/app#1573 because I can save to the collection as long as I only add one file at a time and I can change a file without any issues.

this is like : https://github.com/directus/app/issues/1714#issuecomment-499149850

## Steps to Reproduce

On APP 7.6 and API 2.2

1. Create a new collection "testimages" with two optional file fields "file1", "file2"
2. Add a new item with two files, save
4. See error __Attempting to write an array as the value for field "file2" in "testimages"__

It works when saving testimages with only one file  and the second file in a second edit attempt

## Expected Behavior

When saving  a collection with two file fields, it saves correctly

## Actual Behavior

The item is not saved.

## Other Context & Screenshots

[testimages-collection-schema.json.txt](https://github.com/directus/api/files/3327818/testimages-collection-schema.json.txt)
[single-file-working-payload.patch.txt](https://github.com/directus/api/files/3327808/single-file-working-payload.patch.txt)
[two-file-failing-payload.patch.txt](https://github.com/directus/api/files/3327809/two-file-failing-payload.patch.txt)
[directus-api-info.txt](https://github.com/directus/api/files/3327811/directus-api-info.txt)

## Technical Details

Directus API:  2.2.0
Directus APP: 7.6.0
with new DB schema

also see [directus-api-info.txt](https://github.com/directus/api/files/3327811/directus-api-info.txt)

- Device: Desktop 
- OS: Linux
- Web Server: nginx
- PHP Version: 7.3.6
- Database: Mysql 5.7??
- Install Method: custom docker container based on release artefacts

**Comment by mebenhoehta** [comment]
fyi, I was not able to log in to https://www.directus.app/#/login and the nightly site has a different version

**Comment by benhaynes** [comment]
The demo is down due to a config issue in the App — it will be fixed after our next release.
