### ISSUE TITLE
CORS missing on image/thumbnails request

### ISSUE THREAD

**Issue by TargetTaiga** [directus/api#1058]
CORS headers are not being attached to thumbnails and images responses, e.g:
```
/uploads/_/originals/file-1.jpg
/thumbnail/_/50/50/contain/poor/file-1.jpg
```
I'm using the :latest docker version of app and api. Is it possible to turn CORS for these responses?

**Comment by rijkvanzanten** [comment]
This will also take care of https://github.com/directus/app/pull/1655#issuecomment-497847036

**Comment by rijkvanzanten** [comment]
I'm not sure if we can base the cors for regular files on the config of the API. The static files are being served through whatever webserver you're using, not the API. The thumbnails should base their cors on the config file though.

**Comment by rijkvanzanten** [comment]
@directus/7-span
