### ISSUE TITLE
Missing error msg when PHP Memcache module not installed

### ISSUE THREAD

**Issue by pgl** [directus/api#1064]
# Bug Report

## Steps to Reproduce

1. Go to`config/api.php` in directus app
2. Uncomment the settings for memcached
3. Try to load a page

## Expected Behavior

Directus will use Memcached for caching.

## Actual Behavior

API dies.

## Other Context & Screenshots

These are the settings in `config/api.php`:

```
        // 'pool' => [
        //    'adapter'   => 'memcached',
        //    'host'      => 'localhost',
        //    'port'      => 11211
        // ],
```

Memcached is running fine:

```$ telnet localhost 11211
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
stats
STAT pid 15949
... truncated
```

There doesn't seem to be anything in `logs/<date>.log`, or in `/var/log/apache/directus.local.error.log`.

## Technical Details

- PHP Version: 7.3
- memcached 1.5.6
- Install Method: cloned `master` branch

**Comment by itsmerhp** [comment]
Hey @pgl 
To use Memcached settings, it must be installed and configured in your server. To install Memcached in ubuntu please follow [this link](https://tecadmin.net/install-memcached-with-php-on-ubuntu/).

If you have already installed Memcached and even though you are facing the issue, please share exact error details.

**Comment by pgl** [comment]
hi @itsmerhp. Details are in the bug report above: Memcached is installed and running fine (as demonstrated by the paste of my connecting to localhost on port 11211.

And as per the report, there are no errors that I can see. The application just crashes with the standard "there was a problem" page - nothing in any error logs:

![image](https://user-images.githubusercontent.com/1181139/60416974-81d8eb80-9bdf-11e9-9787-e1bae23966db.png)

The API is returning 500 Server Error.

**Comment by bjgajjar** [comment]
@pgl 

May I have your log file?

**Comment by pgl** [comment]
@bjgajjar Which one, `logs/error.<date>.log`? Because I just tried enabling the Memcached settings again, and the error log wasn't created for today. Also there is nothing in the Apache logs.

**Comment by itsmerhp** [comment]
@pgl 
Can you please execute API in `postman` as shown in below attachment and check if any error is returning?
![oie_HN0jvmbB1xxX](https://user-images.githubusercontent.com/49250107/60461580-914e4800-9c64-11e9-9309-bc91f24eb37f.png)

**Comment by pgl** [comment]
@itsmerhp I don't have Postman, but I since it's a GET request, can you paste the URL and I'll just show the output from Chrome inspector?

**Comment by pgl** [comment]
I tried accessing this URL:

 * http://directus.local/_/users?filter%5Blast_access_on%5D%5Bgte%5D=2019-07-02%2009%3A06%3A19&filter%5Blast_page%5D%5Beq%5D=%2Fcollections%2Ftest%2F1&filter%5Bid%5D%5Bneq%5D=1

No error was returned, except 500 server error headers. I tried copying the request as a `curl` command, again no error. There is nothing in the Directus error logs. Apache access logs show:

`127.0.0.1 - - [02/Jul/2019:11:11:19 +0200] "OPTIONS /_/users?filter%5Blast_access_on%5D%5Bgte%5D=2019-07-02%2009%3A06%3A19&filter%5Blast_page%5D%5Beq%5D=%2Fcollections%2Ftest%2F1&filter%5Bid%5D%5Bneq%5D=1 HTTP/1.1" 500 185 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"`

There is nothing in the Apache error logs.

However! I think the issue is that yes, I don't have the PHP Memcached module installed. It's *very* weird that there's absolutely no error messages though.

**Comment by hemratna** [comment]
@pgl I was facing the same issue with `redis` cache driver when `redis` PHP module is not installed/ properly configured.  

Please check the `phpinfo()` and make sure the `Memcache` is installed and accessible from PHP.

**Comment by pgl** [comment]
@hemratna It's definitely not installed. I think the bug here is the lack of error message? I don't think this is a PHP problem:

```
$ php -r '$m = new Memcache;'
PHP Fatal error:  Uncaught Error: Class 'Memcache' not found in Command line code:1
Stack trace:
#0 {main}
  thrown in Command line code on line 1
$ php -r '$m = new Memcached;'
PHP Fatal error:  Uncaught Error: Class 'Memcached' not found in Command line code:1
Stack trace:
#0 {main}
  thrown in Command line code on line 1
```

**Comment by hemratna** [comment]
@pgl I tested with local setup and working fine with `memcached` adapter.

**Comment by pgl** [comment]
@hemratna if you disable the `memcached` extension, do you see any errors?

**Comment by hemratna** [comment]
Getting 500 error same as you mentation in https://github.com/directus/api/issues/1064#issuecomment-507143624

No logs in Directus `log` directory.

**Comment by pgl** [comment]
Should I update the issue title to something more relevant, do you think?
