### ISSUE TITLE
Translations are of type `String!` in GraphQL

### ISSUE THREAD

**Issue by stalinkay** [directus/api#1069]
# Bug Report
Translations are of type String! in 
## Steps to Reproduce

1. Create a collection
2. Create related translation collection adn setup translations
3. Try to retrieve data using graphql

## Expected Behavior
The schema of the collection will have translations of type String!

## Actual Behavior
The schema of the collection should have an array of TranslationsItem

## Technical Details

- Docker container API: 2.2.1 and APP: 7.6.1

**Comment by stalinkay** [comment]
@hemratna

**Comment by hemratna** [comment]
Thanks, @stalinkay for pointing out the issue. 
I am working on this, will keep you posted

**Comment by hemratna** [comment]
@stalinkay I added the support for `translation` for GraphQL.

**Comment by stalinkay** [comment]
@hemratna Thank you. There was also an internal server error when trying to get the foreign key of the translated collection, in case you missed that.

```
{
  article_translations {
    article
  }
}
```

**Comment by stalinkay** [comment]
@hemratna Hi, GraphQL seems to be having a latency of about 11 seconds. Is there a way around this?

**Comment by hemratna** [comment]
@stalinkay In the GraphQL the `article` become node the `articleItem` 
You will get all the property of `article` by adding them as shown below.

```
{
  article_translations {
    article {
		id
	}
  }
}
```

I am suggesting, kindly use GUI like [GraphiQL](https://electronjs.org/apps/graphiql) which help you with autocomplete.

Regarding the latency, Actually, Directus collections are dynamic in nature. 
Current implementation generates the GraphQL schema on each call.

You can try `cache` the response on the client side.

**Comment by stalinkay** [comment]
@hemratna Thanks for your kind reply. Yeah, I will try caching. On the query you posted that is not the case in API version 2.2.1. article is of type `Int!` not `ArticleItem`. If you have resolved that in the PR then please disregard this. See attachments for context.

<img width="1312" alt="Screen Shot 2019-07-02 at 10 03 33 AM" src="https://user-images.githubusercontent.com/198020/60495531-41e23900-9cb1-11e9-9512-34dca84eb3b6.png">
<img width="566" alt="Screen Shot 2019-07-02 at 10 02 40 AM" src="https://user-images.githubusercontent.com/198020/60495532-427acf80-9cb1-11e9-9a7d-6d8460d6586e.png">

**Comment by hemratna** [comment]
@stalinkay Can you please try with the latest API?

**Comment by stalinkay** [comment]
@hemratna I'll have to wait for the next release since I'm running API 2.2.1 in a docker container. Otherwise, it will take a bit of work to get up and running. Thank you. I'll keep you posted if anything.
