### ISSUE TITLE
Tracking endpoint saves to activity and revision

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#107]
We need a special endpoint to track the users last page / last online. This info is saved in `last_page`, `last_access`, and `last_ip`.

``` 
POST /_/users/tracking/page

{
  "last_page": "/collections/projects"
}
```

The API should add the `last_access` (date) and `last_ip` when saving this to `directus_users`.

This update **should skip directus_activity**, seeing the endpoint is going to be used every ~5 seconds

**Comment by rijkvanzanten** [comment]
Note: This was implemented as a `PATCH` request instead of the above mentioned `POST`

**Comment by rijkvanzanten** [comment]
Note 2:

The endpoint is `/users/{id}/tracking/page` instead of the one mentioned above

**Comment by rijkvanzanten** [comment]
@benhaynes for the docs 🔔

**Comment by benhaynes** [comment]
Updated.
