### ISSUE TITLE
After passing filter_count, Do not query to return the fields limit links offset page_count and page

### ISSUE THREAD

**Issue by cdwmhcc** [directus/api#1075]
# Feature Request
Do not query to return the fields `limit ` `links` `offset` `page_count` `page`
There may be other reasons, but for me, I don't need them.
![image](https://user-images.githubusercontent.com/8030134/60488475-a95db000-9cd4-11e9-91ff-06b703a0138d.png)

## What problem does this feature solve?
These fields are of no value to me, and I can get them all through JS calculations.
` limit ` , ` offset `: I define them myself, and I confirm that they are known and do not need to return.
`links` `offset` `page_count` `page`:  I can get them through JS splicing calculation and other methods

## How do you think this should be implemented?
After passing filter_count, Do not query to return the fields `limit ` `links` `offset` `page_count` and `page`

**Comment by bjgajjar** [comment]
Fixed in #1086

**Comment by cdwmhcc** [comment]
> Fixed in #1086

Thank you  very much!
