### ISSUE TITLE
Time Zone for Turkey (aka Istanbul or Ankara or etc) is wrong.

### ISSUE THREAD

**Issue by anelad** [directus/api#1077]
Some years ago Turkey stopped using Daylight saving and set it's Time Zone to UTC +3 for good. It should be corrected.

Plus, where can I edit it in my own server?

Directus 7.6.1
PHP 7.2.14

**Comment by kaushal-im** [comment]
Hello @anelad Please give us more idea where you are using this timezone and where it showing you wrong. Any screenshot or more details will be helpful in debugging that asap.

**Comment by anelad** [comment]
In the user directory, while creating / editing users. 

Also while editing `api.php` manually; API settings have a timezone value. Possibly making it `Europe/Istanbul` has the same problem.

Both screenshots:

![Screen Shot 2019-07-03 at 18 53 06](https://user-images.githubusercontent.com/5767654/60606364-e654a000-9dc3-11e9-8ad0-df9c12ab1105.png)
![Screen Shot 2019-07-03 at 18 49 21](https://user-images.githubusercontent.com/5767654/60606366-e654a000-9dc3-11e9-8ab1-e6cab8480002.png)

**Comment by bjgajjar** [comment]
Fixed in #1087
