### ISSUE TITLE
Add sort column field to directus_collections table

### ISSUE THREAD

**Issue by dev7ch** [directus/api#1079]
# Feature Request

Add sort column field to directus_collections table

https://github.com/directus/app/issues/1813

## What problem does this feature solve?

plz see https://github.com/directus/app/issues/1813

## How do you think this should be implemented?

Add a new column `sort` to `directus_collections`

## Would you be willing to work on this?
Yes if approved

**Comment by benhaynes** [comment]
@rijkvanzanten @bjgajjar — how do we want to handle features (and bugs, I suppose) that require updates to both the App and API? Do we want _two_ tickets? Or just one that we both work from?

**Comment by dev7ch** [comment]
it would be a nice to have, so i ll let this open to discuss internally, just close it.

I am able to override the nav, which solves my initial problem.
thanks

**Comment by hemratna** [comment]
I am suggesting two different issues (ticket) separately each for App and Api will be more manageable.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
