### ISSUE TITLE
Preview Image is not regenerated after modifying the image

### ISSUE THREAD

**Issue by Lapsus** [directus/api#1080]
# Bug Report
If you modify an image, the preview is not updated accordingly.

## Steps to Reproduce

1. Upload a image to the file browser.
2. access the image via the file browser.
3. edit the image, crop, rotate etc.

## Expected Behavior
The preview image in the file browser (or a files interface) should show the updated, modified image.

## Actual Behavior
The original image before the modification is shown.

## Technical Details
API Version: 2.2.1
APP Version: 7.6.1
- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Web Server: [eg: Apache 2.4.37]
- PHP Version: [eg: 7.2.0]
- Database: [eg: MySQL 8.0.12]
- Install Method: [eg: cloned `master` branch]

**Comment by hemratna** [comment]
We are planning to change the underlying structure to create thumbnail #813. 
So we might need to rework on this issue when we will make changes. 
@benhaynes I am suggesting let's move this as a feature request dependent on #813.

**Comment by benhaynes** [comment]
I agree, this is not a bug since that's expected behavior. What we need is a thumbnail parameter to force generate. Something like:

`200/200/contain/80?force=true`
or...
`200/200/contain/80?refresh=true`

#813 is for the configuration of the thumbnail whitelist... so this `refresh` param doesn't rely on it. We could add this in before the new config if we wanted to.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by avonian** [comment]
Hi there just wanted to follow up on this issue since it appears to be dependent on #813. Are there any workarounds we can use in the interim, or anything I or others can do to help bring about a resolution?

**Comment by benhaynes** [comment]
A PR would help! 😉

Otherwise, will get to this as soon as most of the larger bugs are closed.
