### ISSUE TITLE
Can't filter on JSON data (map interface field)

### ISSUE THREAD

**Issue by steve-rait** [directus/api#1085]
I'm not able to fetch some data with a filter on a map interface field. All rows of my collection have an interface of type `Map` (with latitude & longitude). It's just a list of places.

Data structure:

- Collection01
  - Row01
    - ID
    - ... other fields
    - Map interface
  - Row02
    - ID
    - ... other fields
    - Map interface

For customer needs, I want to fetch all rows according a given point. For example, if my user lives in Paris, I want to show him all nearby POI and not all points.

Is it possible to request collection with a filter on map interface?

Example:

- User location is: [48.8566, 2.3522]
- API'll search for all POI based on a rectangle around him
- User can see related points

Actually, I don't know how to make a good query with this interface.

I'm trying to request with Postman and all I can do is to fetch ALL rows in `poi` collection...

```bash
curl -X GET \
  http://localhost:7000/_/items/poi \
  -H 'Authorization: Bearer [TOKEN]' \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: 0c308605-1294-45b3-bb93-0b1df3f813b1,58860dc8-de18-411f-9a58-05c194c00640' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache'
```

JSON result:

```json
{
  "data": [
    {
      "id": 1,
      "location": {
        "lat": 40.72384384060296,
        "lng": -73.99532318115236
      },
      "name": "New York"
    },
    {
      "id": 2,
      "location": {
        "lat": 43.69776051859191,
        "lng": 7.263891398906709
      },
      "name": "Nice"
    },
    {
      "id": 3,
      "location": {
        "lat": 48.83579746243093,
        "lng": 2.3620605468750004
      },
      "name": "Paris"
    }
  ]
}
```

I know how to search with some filters (`filter[name][eq]=Paris`):

```
curl -X GET \
  'http://localhost:7000/_/items/poi?filter[name][eq]=Paris=,Paris' \
  -H 'Accept: */*' \
  -H 'Authorization: Bearer [TOKEN]' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Host: localhost:7000' \
  -H 'Postman-Token: fae0574d-2011-4b77-b874-8e7b6a3a0bd6,44328b12-c203-4139-875f-2ed2d2e7d047' \
  -H 'User-Agent: PostmanRuntime/7.13.0' \
  -H 'accept-encoding: gzip, deflate' \
  -H 'cache-control: no-cache'
```

JSON result:

```json
{
  "data": [
    {
      "id": 3,
      "location": {
        "lat": 48.83579746243093,
        "lng": 2.3620605468750004
      },
      "name": "Paris"
    }
  ]
}
```

But I don't know how to find POI where latitude >= X **or** longitude <= Y

Any ideas on a good mean to do this, which is not in the documentation ?
Do you know if it's just possible to do that?

Thanks!

**Comment by shealavington** [comment]
I believe you're looking for `Greater than`, and `Less than`, which are documented here.
https://docs.directus.io/api/reference.html#filter-operators

For questions like this, they're usually best asked on StackOverflow. 
You can also join the Slack if you like (Directus.chat).

**Comment by steve-rait** [comment]
@shealavington 

> I believe you're looking for Greater than, and Less than, which are documented here.
https://docs.directus.io/api/reference.html#filter-operators

Sorry but the problem is : you cannot use filter like this on a object with lat and lng.
Indeed, how could you filter on a property inside the field ? 

For example : 
`http://localhost:7000/_/items/poi?filter[coordinates.lng][gt]=50.3`

This query cannot work because the api returns : 
`{
    "error": {
        "code": 202,
        "message": "Unable to find field \"coordinates\""
    }
}`
It's logic because the syntax x.y in a filter is reserved for relations.
So How can filter the data for a map interface field ? 

I want to write something like : 
`http://localhost:7000/_/items/poi?filter[coordinates.lng][gt]=50.3&filter[coordinates.lng][lt]=60.2&filter[coordinates.lat][gt]=8.4&filter[coordinates.lat][lt]=12.5&`

A request like this would return all poi in a area.

**Comment by shealavington** [comment]
The key is `location` not `coordinates`, it would be `location.lat` not `coordinates.lat`

**Comment by shealavington** [comment]
We've worked out that the issue is that the api thinks `[location.lng]` is a relational field and doesn't know that it's JSON therefore doesn't filter. 

@bjgajjar Do you know if we have a way to filter against JSON data? _(You know significantly more about the API than I do haha)_
If not, then this could be an enhancement, I'm not sure I would consider it a bug.

**Comment by bjgajjar** [comment]
Hey @steve-rait 

We don't have any way to filter the JSON data right now. So I think as per the current code you will not able to filter your `coordinates`.

@shealavington I quite agree with you. We can not consider it as a bug.

**Comment by bjgajjar** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by cesasol** [comment]
Maybe this could be solved after the migration to Laravel, they provide ways to query JSON on MySQL and MariaDB https://laravel.com/docs/6.x/queries#json-where-clauses although  the later is not really polished

**Comment by nashtu3000** [comment]
This would be very nice to have in Directus. Bumped into this myself a few times.

**Comment by timrosskamp** [comment]
The `JSON_EXTRACT` function could be used to filter json data in mysql.

Given this example data-set:
```
+----+----------------+
| id |    content     |
+----+----------------+
|  1 | {"text":"foo"} |
|  2 | {"text":"bar"} |
+----+----------------+
```

You could use this function to filter the results by json data:
```mysql
SELECT * FROM `example` WHERE JSON_EXTRACT(content, "$.text") LIKE "\"bar\"" 
```


I would really appreciate this feature, since saving JSON-Data is really useful. Sadly right now there is no way to filter items with specific json values.

**Comment by steve-rait** [comment]
Hi, 
Another approach would be to create dynamically 2 other fields dedicated to be "latitude" and "longitude" when we create a field of type "Map"
Theses fields could be updated by a trigger if we want to keep the original field. These could be indexables to improve performances on large databases
today it's possible to do that "manually" (creating other extra fields, doing triggers) but if you could manage it automatically, I think it would be a great alternative
