### ISSUE TITLE
S3 service does not work

### ISSUE THREAD

**Issue by cdwmhcc** [directus/api#1100]
# Bug Report
S3 service does not work,Loss of `root_url` (config/api.php)

## Steps to Reproduce

1. `git clone https://github.com/directus/api .`
2. `composer install`
3. `composer require league/flysystem-aws-s3-v3`
4. Copy the old version of the configuration file(api.php) to config/
5. Setting log and public/upload 777 permissions
6. See `/#/files/1`

![image](https://user-images.githubusercontent.com/8030134/60942435-2e6c4900-a315-11e9-8721-0b8aede4d420.png)

## Expected Behavior
S3 files can be displayed

## Actual Behavior
Loss of `root_url`

## Technical Details

- Device: [Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.2.2]
- APP Version: [7.6.2]
- Install Method: [cloned `master` branch]

**Comment by bjgajjar** [comment]
This will resolve with #1096. @WoLfulus is working on that :)

**Comment by hemratna** [comment]
This issue has been fixed as #1096 is merged to master.
