### ISSUE TITLE
How to create Phinx migration file for ugprade?

### ISSUE THREAD

**Issue by JbalTero** [directus/api#1101]
How to create Phinx migration file for ugprade?

**Comment by bjgajjar** [comment]
May I have more details? 

Are you trying to migrate your site from one server to another?

**Comment by JbalTero** [comment]
I am thinking of creating migration file for collections so that I will only run the collections instead of manually adding them every time.

**Comment by bjgajjar** [comment]
Let me clear the stuff here; If I am not wrong then you are trying to transfer the user-generated collection from one server to another. 

That is not possible in the directus for now.

**Comment by JbalTero** [comment]
Yes kind of like that. thanks for the answer.
