### ISSUE TITLE
Add transaction support to API?

### ISSUE THREAD

**Issue by jkirkwood** [directus/api#1103]
# Feature Request

Add support to perform several API calls under a single MySQL transaction.

## What problem does this feature solve?

Sometimes I need to create several item in different collections via the API in response to a user action. Often it is desired that if one of the steps fails each of the other steps performed should be undone as well. Using MySQL transactions would allow several API requests to be applied in an "all or nothing" sort of way.

## How do you think this should be implemented?

Add endpoints to the API to manage transactions. Maybe something like this:

This would start a transaction and return a MySQL connection id that the transaction is active on:
```
POST /transaction/start

Response:
{
  data: {connection_id: 12345}
}
```

You could then pass the connection id to other api calls i.e.
```
POST /_/items/widgets?connection_id=12345
```

Finally you could commit or rollback the transaction using these:
```
POST /transaction/12345/commit]
POST /transaction/12345/rollback
 ```

## Would you be willing to work on this?

Maybe. I'm not super familiar with the Directus internals, or PHP for that matter, but I would be open to taking a look.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
