### ISSUE TITLE
Support `limit`, `offset` for sub-collections

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1105]
# Feature Request

## What problem does this feature solve?

You can currently limit how many items the API spits out in order to improve the performance by only getting the items you need. However, relational fields will always fetch every single item that matches. In the case of O2M and M2M fields, this can result in thousands and thousands of nested records.

https://github.com/directus/api/issues/998

## How do you think this should be implemented?

Currently, we have a `limit` parameter to set how many items we want to fetch. This is `200` by default. We also have an `offset` parameter to offset the amount of items to fetch, which enables pagination. I propose we extend `limit` and `offset` with the nested object syntax so we can set the pagination per field as well:

```
// current

// Fetch 200 items per call, fetch items 400-600

limit=200
offset=400


// proposed

// Fetch 200 items per call, fetch items 400-600
// of subfield `images`, fetch 5 (10-15)

limit=200
offset=400
fields=*,images.*
limit[images]=5
offset[images]=10
```

The defaults for these should be the same as for the "normal" limit and offset parameters

Potential issues:
* We don't have nested `meta` objects, so there wouldn't be a way to retrieve that information for sub-collections
* Might be a breaking change ⚠️ Changing the default limit will change the API output in certain cases. (when you have _a lot_ of relational records).

**Comment by rijkvanzanten** [comment]
Thoughts @directus/team?

**Comment by benhaynes** [comment]
This makes sense to me, and should be a helpful parameter for large relational datasets. We could have it "opt-in" to avoid a breaking change... so that it returns all unless you add the param. Though That might cause confusion/slowness in most cases.

I'd still like to hear from the API team on how complex this is.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by KULTI1995** [comment]
Is this possible yet? This is not extremely useful!

**Comment by rijkvanzanten** [comment]
Nope, it's an open feature request

**Comment by keesvanbemmel** [comment]
How about now @rijkvanzanten ? :) (in v9 that is)

**Comment by rijkvanzanten** [comment]
> How about now @rijkvanzanten ? :) (in v9 that is)

Yeah! V9 has this! 🎉🎉 my years old desires are finally coming true

**Comment by keesvanbemmel** [comment]
That is using the "deep" parameter yes? I'm too trigger happy with discussions today!

**Comment by rijkvanzanten** [comment]
> That is using the "deep" parameter yes? I'm too trigger happy with discussions today!

Yup! That's exactly what it's for 🙂  The `deep` param allows you to set a full query for the nested sub-collection, so for example `?deep[categories]` then takes a full query object (`_` prefixed) to set those settings, like `?deep[categories][_filter][etc][etc]=x`. You can also chain multiple fields to add the query on sub-sub-sub collections, like `?deep[featured_image][uploaded_by][favorite_articles][_filter][title][_contains]=Directus`
