### ISSUE TITLE
Add /update endpoint

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1108]
It would be great to have an endpoint that will pull the latest release from Git, overwrite the correct files, and run the migrations. That way, the application can have a card in settings that truly updates the API for you.

Main issue though: How to update the application.

If the application is inside the API (as is the case with the combined build), we can do the same trick for the application, and update the whole suite as whole. However, if you're hosting the application on a separate server from the API, there's no way the API can update the application automatically.

**Comment by benhaynes** [comment]
If we can _detect_ the combined build (or App within API) then we can conditionally show/adapt this feature. If most users use combined build, then this is a _really_ nice feature to have! For the others, we can update the API and inform them that they still need to update the App too.

**Comment by bjgajjar** [comment]
@benhaynes 
 
If we are going with https://github.com/directus/api/issues/1107#issuecomment-512720177 then this issue would be a substitute of #1107

**Comment by benhaynes** [comment]
Sure, if you want to keep everything in one place/ticket, that's fine by me.

**Comment by bjgajjar** [comment]
OK. Let's close this and have a discussion on #1107 :)
