### ISSUE TITLE
Add lang filter to GraphQL collection when translation is inside the content.

### ISSUE THREAD

**Issue by Bedotech** [directus/api#1110]
# Feature Request
Hi to all, I'm seeing that there isn't a way for query content based on language in Directus via GraphQL, I think the better way for doing this is to add `lang` filter when the content has some `translation` filed in and transform this filter work like `lang` filter like REST API.

Pay attention, if the field has multiple `translation` fields we cannot select a different language on the same content, but I think this behavior is what we want when we consume translated content, simply define the language a get it.

## What problem does this feature solve?
Allow better GraphQL query for translated content, using always the same filter as happen for REST API.

## How do you think this should be implemented?

Add `lang` string filter to content when they have `translation` filed in his definition.

## Would you be willing to work on this?

I will try to work on this.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
