### ISSUE TITLE
Allow relations to directus_settings

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#112]
Throwing you a curveball here 😉 

I'd like to be able to have relational items _in_ directus settings. For example, for the `logo` setting, I would use a `directus_files` relationship, so I can fetch the logo information directly when fetching `directus_settings`.

**Comment by WellingGuzman** [comment]
Can we go back and talk about how the `directsus_settings` items and `directus_fields` going to work? on insert/delete there will be a insert/delete on `directus_fields`?

**Comment by benhaynes** [comment]
I know we have Logo in the global settings now... is this working/done? @rijkvanzanten @WellingGuzman

**Comment by rijkvanzanten** [comment]
For `file` type interfaces it's working as expected. As of right now, it's not yet possible to have a relationship directly to directus_setttings, but we have no use for it as of right now either (seeing that the `file` type suffices for our use case).
