### ISSUE TITLE
S3 storage generates both local and s3 thumbnail + uses the local thumbnail to display

### ISSUE THREAD

**Issue by jbitsch** [directus/api#1127]
# Bug Report

## Steps to Reproduce

1. git clone `https://github.com/directus/api .` and setup scheme based on src/scheme.sql
2. `composer install`
3. Copi version of api.php and setup to s3 upload
4. Upload image either from a created collection with file field or from File Library
5. Check that image + thumbnails is uploaded on S3 to verify the setup

## Expected Behavior
Image and thumbnail is uploaded to Amazon S3 and directus use S3 source to display both the thumbnail and the full image. Furthermore it should not generate a local thumbnail.

## Actual Behavior
Image and thumbnail are uploaded to amazon S3 _(Which is correct)_  at path:
**Original image:** https://`<bucket>`.s3.`<zone>`.amazonaws.com/directus/storage/uploads/`<generated_file_name>`.`<file_type>`
**Thumbnail**: https://`<bucket>`.s3.`<zone>`.amazonaws.com/directus/storage/uploads/thumbnails/200/200/crop/good/`<original_file_name>`.`<file_type>`

Directus do also create a thumbnail locally (If possible) at path:
https://<directus_app_url>/thumbnail/_/200/200/crop/good/<original_file_name>.<file_type>
If i am right this should not happen when storage is set to S3, and you now have the thumbnails two places.

Furthermore it is the local thumbnail which is used to display the image, which gives a blank image on for example Google App Engine where local storage is not possible
![image](https://user-images.githubusercontent.com/1073322/61488254-0ed5c000-a9a8-11e9-97dc-5865ea303677.png)

When opening the file at path <directus_app_url>/files/<file_id> the full image is displayed correctly from the S3 source

## Technical Details

- Device: Desktop
- OS: MacOS + Google App Engine
- Web Server: Apache 2.4.37
- PHP Version:  7.2.0
- Database:  MySQL 8.0.12
- Install Method:  cloned `master` branch
- Use the master branch for both the app and the api

**Comment by bjgajjar** [comment]
Hey @jbitsch,, 

> Directus do also create a thumbnail locally (If possible) at path:
> https://<directus_app_url>/thumbnail/_/200/200/crop/good/<original_file_name>.<file_type>
> If i am right this should not happen when storage is set to S3, and you now have the thumbnails two places.

I tried to replicate this but not able to do so. If the adapter is `s3` then the thumb will generate in `s3`; not in the local machine.

Although the URL for the thumbnail is always  like `https://<directus_app_url>/thumbnail/_/200/200/crop/good/<original_file_name>`

And it is correct. As it is not containing the path of a thumbnail but it pointing out a `PHP` file. We have PHP file named thumbnail which will check the current adapter of your system and generate thumbnail over there as well as return too. 

Hence the thumbnail URL does not depend on your adapter. 

Please confirm so I can close this issue.

**Comment by bjgajjar** [comment]
It's not an issue so closing this. Feel free to reopen it if you have any query.
