### ISSUE TITLE
Implement reset-request

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#113]
`/auth/reset-request` throws a 404..

**Comment by WellingGuzman** [comment]
What's this endpoint? can you give more details?

**Comment by rijkvanzanten** [comment]
It's the reset password endpoint. Or is that in there under another name?

**Comment by WellingGuzman** [comment]
`POST /auth/forgot_password` for request the token `GET /auth/reset_password/<token>` for resetting the password.

Both sends email to the user.

**Comment by rijkvanzanten** [comment]
Ah, in that case it's wrong in the docs 🔔 @benhaynes

**Comment by benhaynes** [comment]
Updated!

**Comment by WellingGuzman** [comment]
It's implemented, but we are renaming the endpoints. Ref: https://github.com/directus/api/issues/116
