### ISSUE TITLE
Files not honoring storage adapter when changing the adapter

### ISSUE THREAD

**Issue by hemratna** [directus/api#1130]
# Bug Report

## Steps to Reproduce

1. Set the `local` as a storage adapter in `api.php` 
2. Upload file (For example `local.jpg`)
3. Change the storage adapter as `s3`
4. Upload file (For example `s3.jpg`)

## Expected Behavior

`local.jpg` should be served from the local path as the value of `directus_files.storage` says the `local`.
`s3.jpg` should server from S3 path.

## Actual Behavior
`local.jpg` is trying to serve from s3, But the file is not available on s3, So getting `404`  error. 

## Other Context & Screenshots

This behavior is also applicable in vice-versa, change in adapter from `s3` to `local`

## Technical Details

- Device: Desktop
- OS: macOS 10.14.5
- Web Server: Apache, MAMP Pro
- PHP Version: 7.2.14
- Database: MySQL 5.7.25
- Install Method: cloned `master` branch

**Comment by bjgajjar** [comment]
I think this can not be achieved at this moment. For this functionality, we required the support of multiple storage adaptors.

Currently, we have a one adapter at a time. So if you are switching it in between then you will not have details of an older one. 

As per the current codebase, if the user wants to switch the adapter in between then they have to move their files from one adapter to another manually; as we have support for a single adapter only. 

I guess we should move this as a feature request for adding support of multiple adapters.

@hemratna  Thoughts?

**Comment by hemratna** [comment]
> I think this can not be achieved at this moment. 

Agreed

>For this functionality, we required the support of multiple storage adaptors.
> 

Which is tricky (any time consuming) as per the current structure.

@benhaynes Let's move this issue as a feature request and close this one.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
