### ISSUE TITLE
Deleting the logo file from file manager gives server error

### ISSUE THREAD

**Issue by hemratna** [directus/api#1131]
# Bug Report

## Steps to Reproduce

1. Go to Admin setting, Set logo. 
2. Go to files and delete the logo file
3. Refresh the App in the browser
4. See the error shown in the screenshot

## Actual Behavior
`/settings` endpoint throwing `404 - file not found` for logo file. 

## Expected Behavior
If the logo file not found, `/setting` should return default logo or blank value
The app should not break, because the current user is in deadlock situation until they update `directus_settings.keys.logo` to blank directly in the DB.

## Other Context & Screenshots

![image](https://user-images.githubusercontent.com/1333346/61516417-93fdbb00-aa22-11e9-8ba0-6985ef30d79c.png)

![image](https://user-images.githubusercontent.com/1333346/61516437-9e1fb980-aa22-11e9-91fc-ea35d481a41d.png)

## Technical Details

- Device: Desktop
- OS: macOS 10.14.5
- Web Server: Apache, MAMP Pro
- PHP Version: 7.2.14
- Database: MySQL 5.7.25
- Install Method: cloned master branch

**Comment by bjgajjar** [comment]
Fixed in #1135
