### ISSUE TITLE
Error while dragging or sorting

### ISSUE THREAD

**Issue by cdwmhcc** [directus/api#1136]
Bug Report

Error while dragging or sorting

## Steps to Reproduce

1、Enter a collection at will
2、Sort or drag as shown，See it
![image](https://user-images.githubusercontent.com/8030134/61380186-82f66200-a8db-11e9-872a-d059e6f741fd.png)

## Expected Behavior
Fix it

## Technical Details

- Device: [eg: Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.2.2]
- APP Version: [7.6.2]
- API and App Install Method: [cloned `master` branch]

**Comment by rijkvanzanten** [comment]
@directus/api-team nothing changed on the application side regarding this. I just checked it myself, the application sends `{"view_query":{"tabular":{"sort":"-id","fields":"id,section"}}}` which is JSON as is required by the API.

**Comment by rijkvanzanten** [comment]
It looks like it's trying to validate `view_query` / `view_options` when only one of the two is set. EG when posting `{"view_options":{"tabular":{"widths":{"note":200,"card_type":200,"section":200,"category":200,"in_takeaway":200,"id":200}}}}`, it complains about `view_query` not being JSON, but it's not there to begin with

**Comment by bjgajjar** [comment]
Closed in #1138
