### ISSUE TITLE
"Couldn't reach api". /server/ping returns error 500 after fresh new installation

### ISSUE THREAD

**Issue by criscmaia** [directus/api#1139]
# Bug Report

## Steps to Reproduce

1. Clean install
2. Goes through the admin setup without any problem
3. The tables are created on the DB
4. Redirects to the /admin/#/login
5. show error message "couldn't reach API". Fields are disabled.
6. Console shows the following error:
![image](https://user-images.githubusercontent.com/9072422/61594950-028c7580-abe9-11e9-87fb-7603ae3e0829.png)

## Expected Behavior
The login form should be enabled so I can log-in to the system.

## Technical Details

- Device: any
- OS: Ubuntu 18.04
- Web Server: 2.4.29
- PHP Version: 7.2.19
- Database: MySQL 14.14
- Install Method: cloned `master` branch

**Comment by shealavington** [comment]
After providing log information in Slack:
`PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/html/directus/src/core/Directus/Config/Schema/Types.php on line 10`

This seems to be related to the following fix I provided (https://github.com/directus/api/pull/1124), where `const` and `public` do not need to be used together, therefore this should be fixed for the next release.

The only thing that confuses me is that this post mentions the use of PHP 7.2, however, this should work for `>= PHP 7.1`, therefore I'm unsure if you're actually using 7.2 or not, as this issue would theoretically only happen for anyone on `< PHP 7.1`.

I'm closing this for now as Fixed. Either:
1) Wrong PHP version, less than the minimum
2) It'll be fixed for the next release anyway.

**Comment by criscmaia** [comment]
For future googlers:
**It's not enough to run "apache -v" to see what version of PHP you are running.**
It will only show the latest version, even if you have more than one version enabled.

Go to your apache settings (/etc/apache2/mods-enabled/) do an `ls -lhi `to check if only shows `php7.2.conf` and `php7.2.load `, and not any previous version (especially if below 7.0 as it's not supported).

If it shows an older version, run `sudo a2dismod php7.0` to disable it (replace 7.0 to whatever older version you have)
