### ISSUE TITLE
Aliyun OSS does not work

### ISSUE THREAD

**Issue by cdwmhcc** [directus/api#1142]
# Bug Report
Aliyun OSS does not work
I confirm that my information is correct and that I can upload files normally in other programs.

## Steps to Reproduce

1. `composer require aliyuncs/aliyun-oss-flysystem`
2. Edit the api.php configuration file and fill in information about aliyun OSS
3. After uploading files,See error

## Expected Behavior
I think it has something to do with the last S3 not working. Some previous versions were working.

## Actual Behavior
![image](https://user-images.githubusercontent.com/8030134/61627955-9460b500-acb3-11e9-8370-e0528c850891.png)
![image](https://user-images.githubusercontent.com/8030134/61628021-bbb78200-acb3-11e9-8414-5596c7a53769.png)

## Technical Details

- Device: [eg: Desktop]
- OS: [Windows 10.1809]
- Web Server: [Nginx:1.17.0]
- PHP Version: [7.3.6]
- Database: [5.7.26]
- API Version: [2.3.0]
- APP Version: [7.7.0]
- API and App Install Method: [cloned `master` branch]

**Comment by hemratna** [comment]
Hi @cdwmhcc `aliyun-oss-flysystem` is not officially supported storage adapter for Directus.

We don't have any `aliyun-oss-flysystem` supported service provider where we can test.
If possible can you send some PR or we can ask the @benydc for help.

**Comment by cdwmhcc** [comment]
> Hi @cdwmhcc `aliyun-oss-flysystem` is not officially supported storage adapter for Directus.
> 
> We don't have any `aliyun-oss-flysystem` supported service provider where we can test.
> If possible can you send some PR or we can ask the @benydc for help.

It's available in previous versions, but it hasn't worked since the last S3 service was unavailable

**Comment by benhaynes** [comment]
Hey @cdwmhcc — it doesn't matter if it used to work, this isn't an officially supported feature so it's not a bug. You can submit a feature request if you'd like.

**Comment by cdwmhcc** [comment]
@benydc 
Ask for your help.
Thank you very much

**Comment by cdwmhcc** [comment]
> Hey @cdwmhcc — it doesn't matter if it used to work, this isn't an officially supported feature so it's not a bug. You can submit a feature request if you'd like.

Thank you, 
If so，
Hope it's a plug-in，
Do not couple in the system
