### ISSUE TITLE
How to abort item creation?

### ISSUE THREAD

**Issue by AstralProgrammer** [directus/api#1143]
I'm want to have the ability to create new OR show existing via POST method on the collection. I'm trying to accomplish this via hook filters but I don't know how to abort the creation of the data.

Any idea on how I could accomplish this? Any better approach?

Thanks in advance.

**Comment by benhaynes** [comment]
I'll close this as it's not a bug... but maybe @bjgajjar has some thoughts around how to cancel an item creation from within a hook?

**Comment by bjgajjar** [comment]
Hey @AstralProgrammer 

I am not sure what exactly the issue is; but payload will fetch from **$payload->getData()** only. You can ping me in our slack [channel ](https://directus.chat) to discuss the stuff briefly. :)
