### ISSUE TITLE
Authentication stopped working

### ISSUE THREAD

**Issue by zeusstl** [directus/api#1144]
# Bug Report

Not able to authenticate a user anymore.

## Steps to Reproduce

1. Create a new user via the admin or the api.
2. Try to log in with the same user.

## Expected Behavior

Should be able to create a user and then authenticate with the pw used to create the user.

## Actual Behavior

GET /_/auth/authenticate
RESPONSE: {"error":{"code":100,"message":"Invalid user credentials"}}

## Other Context & Screenshots

1. I debugged it down to the password_verify method in the Authentication Provider class which fails to verify the password. Can confirm that the method receives the password and the password hash correctly. Which means that the issue is on the password creation side.

2. I've researched this issue for many hours and the most common issue is related to PASSWORD_BCRYPT occasionally making a hash that is too long and gets truncated by the db. The db field `password` is varchar(255), so shouldn't be a problem, but wondering if maybe the code or query is truncating it (but I'm having a hard time debugging that part of the code).

## Technical Details

- Web Server: Apache 2.4.18
- PHP Version: 7.1.27
- Database: MySQL 5.7.26
- Install Method: git cloned

**Comment by zeusstl** [comment]
Well. It was all on my end. rsync to production didn't have the delete flag, so it was leaving old code on production alongside the new code. In this case, it left the interface/hashers/hooks.php in public/extensions/core. So both versions of the hashing were occurring.

**Comment by benhaynes** [comment]
Thanks for following up!

**Comment by zeusstl** [comment]
Learned a bit more of the source code :-)
