### ISSUE TITLE
Update seed + add migration for directus_settings note

### ISSUE THREAD

**Issue by Pelletan** [directus/api#1148]
In Admin settings > Global settings > Field : Default Limit
The tool tip say: 

> "How many minutes before an idle user is signed out."

Should be replace by the right description.
![Capture d’écran 2019-07-10 à 15 21 05](https://user-images.githubusercontent.com/9443918/60972971-92980880-a327-11e9-80bd-b0878d197f20.png)

**Comment by rijkvanzanten** [comment]
https://github.com/directus/api/blob/develop/migrations/db/seeds/FieldsSeeder.php#L1041

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1152
