### ISSUE TITLE
filter dot notation does not work in combination with logical or

### ISSUE THREAD

**Issue by Lapsus** [directus/api#1149]
# Bug Report

## Steps to Reproduce

1. create a regular n:1 relation between two collections.
2. use the items endpoint with filter to fetch from collection

## Expected Behavior
https://.../_/items/[collection1]?filter[collection2.id][eq]=3 -> returns for example 2 records from collection1
https://../_items/[collection1]?filter[name][like]=test&filter[collection2.id][logical]=or&filter[collection2.id][eq]=3 -> also returns the two entries from collection1 

## Actual Behavior
https://.../_/items/[collection1]?filter[collection2.id][eq]=3 -> returns the 2 records from collection1 as expected

https://../_items/[collection1]?filter[name][like]=test&filter[collection2.id][logical]=or&filter[collection2.id][eq]=3 -> does not return the 2 records

## Technical Details

- API: 2.3.0
- APP: 7.7.0
- Install Method: build branch

**Comment by bjgajjar** [comment]
Fixed in #1156
