### ISSUE TITLE
Cant upload new images in the Files dialog while adding a new Entry to a table

### ISSUE THREAD

**Issue by edenprojectde** [directus/api#1161]
Steps to reproduce:
1. Create Table with Files Field and use the auto-generate mehod for it.
2. Try to add File(s)
Result:
![image](https://user-images.githubusercontent.com/6115966/62069728-38f57080-b239-11e9-9f23-9da6346e4fec.png)

"filename: This value should not be blank. uploaded_by: This value should not be blank. uploaded_on: This value should not be blank."

Seems like the connected File Table is not receiving the correct Query.
The File(s) get uploaded though.

Directus v7.8.0
PHP Zend Engine v3.3.7 with Zend OPcache v7.3.7-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c)
Nginx Server
OS: Ubuntu

**Comment by rijkvanzanten** [comment]
`filename` and `uploaded_by` are both fields that are auto-populated by the API. @directus/api-team could we verify the fields are indeed being auto populated correctly and not throw an error if that's the case?

**Comment by bjgajjar** [comment]
Fixed in #1165
