### ISSUE TITLE
API is very slow when querying large sets

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#117]
The API takes a solid `5550ms` to retrieve 1000 items. Even when fetching just the `id` field, it takes 4.5 seconds.

Querying the same data set in MySQL directly takes `8.8ms`. I don't know what the API is doing, but it's adding _a lot_ of latency 😬

**Comment by rijkvanzanten** [comment]
Let's make sure the API doesn't add anymore than `100 - 150ms` overhead compared to raw SQL to each request.

**Comment by WellingGuzman** [comment]
We have been trying to take the API to take less time, it takes time and lots of refactor and cache layers.

**Comment by WellingGuzman** [comment]
Moved to #179
