### ISSUE TITLE
Creating item with relational O2M not able to create multiple, only 1 relational

### ISSUE THREAD

**Issue by JbalTero** [directus/api#1173]
# Bug Report

## Steps to Reproduce

* Fresh install of v2.3.1
* Create `members` collection with `name` text field
* Create `projects` collection with `name` text field and `members` O2M relationship such that collection fields look like this:
![image](https://user-images.githubusercontent.com/3615746/62382266-c7425d00-b57f-11e9-8092-e3e1e288b880.png)

* And the members O2M relation properties look like this:
![image](https://user-images.githubusercontent.com/3615746/62382678-a3cbe200-b580-11e9-9b96-17128e8fcac4.png)

* Now create TWO `member` items via `project` creation form
![image](https://user-images.githubusercontent.com/3615746/62382777-dd9ce880-b580-11e9-89c4-f5f08f4bc51f.png)

* Save the `project` item
* Check the saved `project` item and you will see only 1 `member` item.

## Expected Behavior

TWO members created should display

## Actual Behavior

Only one member is displayed.

## Other Context & Screenshots

You can contact me for the screenrecording

## Technical Details

- Device: Desktop
- OS: Win 10  10.0.18362.145
- Web Server: Apache/2.4.29
- PHP Version: PHP 7.1.30
- Database: 10.1.40
- Install Method: v2.3.1 build

**Comment by bjgajjar** [comment]
@JbalTero 

> * And the members O2M relation properties look like this:
>   ![image](https://user-images.githubusercontent.com/3615746/62382678-a3cbe200-b580-11e9-9b96-17128e8fcac4.png)

When you have added `O2M` field in the collection then you must have `M2O` field in the related collection.

Here, You mapped `id` of `projects` collection with `id` of `members` collection which causes this issue. Kindly add `M2O` field in `Members` collection and map that field here.

You can get more detail from [here](https://docs.directus.io/guides/relationships.html#one-to-many).

**Comment by JbalTero** [comment]
Ohh ok I will try it thanks

**Comment by benhaynes** [comment]
This seems like a configuration issue, let us know if you still are having issues.

**Comment by JbalTero** [comment]
@bjgajjar your suggestion means I have to create the project first before the member? it is not possible to create project + create member?

**Comment by JbalTero** [comment]
@bjgajjar I added m2o in `members` collection like this:

![image](https://user-images.githubusercontent.com/3615746/62595046-51d3e500-b90f-11e9-9668-cc8f44f89ee6.png)

Now when I add `Project` item, the `Add new` button doesn't make sense because it asks for `Project` selection which I am still yet to create.

And the problem is still the same. Watch [here](https://drive.google.com/file/d/1R6P2mu5o2CWvnxwoJbvr0A2ydD-QznIj/view?usp=sharing)

What am I missing?

**Comment by bjgajjar** [comment]
@JbalTero 

You want to create `O2M` relation of `member` collection in `project` collection.

Kindly follow the below steps to add this relation in your collection.

- Add `M2O` filed with name `project_id` in `member` collection which has a relation with `project` collection
- Add `O2M` field in `project` collection which has a relation with `member` collection and map `M2O` filed `project_id` of `member` collection here.

**Comment by JbalTero** [comment]
@bjgajjar the steps above still yields the same issue, only 1 member is added even adding multiple. Like the screenrecording from above comment

**Comment by bjgajjar** [comment]
@JbalTero 

Can you please check that your `project` collection has a `projects` field as a relational field? 

![image](https://user-images.githubusercontent.com/19200178/62595884-c30a9c80-b8fd-11e9-86b0-3926dd73e51c.png)

**Comment by JbalTero** [comment]
@bjgajjar It is set to `id`

![image](https://user-images.githubusercontent.com/3615746/62595929-e25ff480-b912-11e9-8e0f-7f870919a3e9.png)

**Comment by JbalTero** [comment]
BTW I'm using App version: 7.8.0

**Comment by bjgajjar** [comment]
@JbalTero 

That's the cause of issue.

Kindle set the `M2O` field over there.

**Comment by JbalTero** [comment]
@JbalTero THANK YOU! it works now

**Comment by shealavington** [comment]
This pretty much comes back round to the app again and (PEBKAC): Can we disable the option of being able to select the primary key as a relation here? @directus/app-team

**Comment by JbalTero** [comment]
Right during creation of the relation, id is pre-selected and cannot be modified. Not until it is updated.

**Comment by benhaynes** [comment]
Yes @shealavington — that would solve a lot of these issues and _should_ be pretty easy to do. I'll look into doing it (😬) but no promises!

@rijkvanzanten you agree with this approach?

**Comment by rijkvanzanten** [comment]
Yup!

**Comment by benhaynes** [comment]
Ask and ye shall receive! We're releasing in a few hours and you can no longer select the PK as "field_many" when setting up O2M relationships. 😄
