### ISSUE TITLE
Time Validation does not accept 0s

### ISSUE THREAD

**Issue by hakkurishian** [directus/api#1174]
# Bug Report

Not sure whether this belongs to API or app.

Time validation fails is time string contains 0 values.

## Steps to Reproduce

1. Create a collection with a TIME (not date time) field
2. Create an object and try to enter a valid time value

## Expected Behavior

Expectations: "15:00:00" as well as "09:00:00" and "09:30:00" valid

## Actual Behavior

All the expected tigmestrings are invalid, Server returns "end_time: This value is not a valid time."

What works though are the following values:

"15:01:01" or "15:30:02"

Somehow it does not allow 0 values for any time component.

## Technical Details

- Device: Desktop
- OS: MacOS
- Web Server: Apache
- PHP Version: 7.2
- Database: MySQL
- Install Method: Docker

**Comment by bjgajjar** [comment]
It seems like it is not reproduced at API side. I checked in local as well as in the live demo. But not able to replicate it.

Tried for below time which successfully added in the system.
- 15.00.00
- 15.02.00
- 15.02.02

May I have a screen recorder? 

@WoLfulus can you please confirm that this is not a Docker related issue?

**Comment by benhaynes** [comment]
Maybe it's on the App side? @rijkvanzanten

**Comment by bjgajjar** [comment]
Hey @benhaynes 

I don't think so. As its working fine in the live demo. If it's the issue at `APP` or `API` then it would not work as expected over there.

**Comment by hakkurishian** [comment]
@bjgajjar I'll clean my docker system and refetch the latest image and retry, if it persists I'll post a screen recording.

**Comment by hakkurishian** [comment]
My Directus image is now at 7.0.18. 
It seems like the format expected from the API is expected to be "h:mm:ss". However when ss or mm equals 0, the request sent by the client ( Using Chrome on MacOS) is reduced to e.g. "15:30" instead of "15:30:00" which causes the API to not accept the value, see the attached screenshot.

<img width="648" alt="Screenshot 2019-08-05 at 15 57 11" src="https://user-images.githubusercontent.com/6708117/62470156-149a1680-b79a-11e9-95a6-bf6fe7eea455.png">

**Comment by rijkvanzanten** [comment]
Does this still happen in the latest version of the API? (v2.3.1)

**Comment by benhaynes** [comment]
This is most likely an issue because you're on such an old version of Directus. Not your fault, our Docker is stuck in an older version... but we should be releasing a new one the next few days!

Let's hold off on debugging this until then.

**Comment by hakkurishian** [comment]
@benhaynes thank for the explanation. Is it safe to use docker for directus on the long run? I'm currently developing a project relying a lot on directus based on the docker image. I'm excited about the new version since the one I have also has numerous bugs regarding many to many relations. I guess this can be closed then and I'll reopen it after the release in case I'm still having the problem which seems to be unlikely at time.

**Comment by benhaynes** [comment]
Yes, @WoLfulus has been working hard on the new Docker version and it's just about done. Once it is released, Docker will always be using the most up-to-date version of Directus. So it will certainly be reliable.
