### ISSUE TITLE
File title is incorrect after upload

### ISSUE THREAD

**Issue by benhaynes** [directus/api#1176]
When uploading a file, the `filename` should follow the naming convention (eg: original, id, etc)... but the `title` should always save a cleaned up version of the uploaded file name (not the NEW filename).

You can see below that the `title` is being set tot the same string as the `filename`...
![Screen Shot 2019-08-05 at 3 03 39 PM](https://user-images.githubusercontent.com/522079/62488533-7bb3cd00-b792-11e9-92ae-3c208ceecfc6.png)

But `title` should have been set to:

`Clouds Floating Over Himalaya Mountains`

From this original file name:
`Clouds-floating-over-himalaya-mountains.gif`

We should use the standard Directus Title Formatter for this (same as used on Field/Collection names) after stripping the extension.

**Comment by bjgajjar** [comment]
Fixed in #1177
