### ISSUE TITLE
Make settings->logger->path configurable through /projects

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1179]
The `/projects` endpoint allows you to configure a lot of the fields in the config file, except for the `settings->logger->path` variable. This combined with https://github.com/directus/api/issues/1178 results in the fact that newly created projects may or may not be able to write logs.

https://github.com/directus/api/blob/f542f2f458825709dcb9e9ebe3ceb39e5af5350d/src/core/Directus/Util/Installation/InstallerUtils.php#L873-L939

I've tagged it both a bug and a feature request, as the `/projects` endpoint is pretty useless if a newly created project can't work.

**Comment by bjgajjar** [comment]
@rijkvanzanten 

We can achieve this in 2 ways.

1. We can take user input same as `db_name`  and other fields at an installation time and pass it in `/projects` endpoint.
2. We can generate folder inside the `logs` folder which contains the same name as `project_name`.

Let me know your thoughts here.

**Comment by rijkvanzanten** [comment]
Option 1 please. `logs_path` would be a fitting name

**Comment by bjgajjar** [comment]
Fixed in #1181
