### ISSUE TITLE
Email sending to live email instead of target host in php7.3

### ISSUE THREAD

**Issue by AstralProgrammer** [directus/api#1187]
I'm trying out the mail function on a new project. I noticed that the mails are sent directly to the actual live email instead of the target host.

Here is my config:
`'transport' => 'smtp',
            'host' => 'smtp.mailtrap.io',`

I have the same configuration on a different project but it works just fine. The difference that I see is that the one with issue is **php7.3** the other is **php7.2**.

OS: Ubuntu 16.04
PHP: 7.3
Directus: 2.3.0

**Comment by urvashithakar** [comment]
Hi @AstralProgrammer,

I think this is fixed in [#1223](https://github.com/directus/api/pull/1223). So please update to the latest version.

**Comment by bjgajjar** [comment]
As this issue is not reproducible in the latest version; I am closing this. Feel free to reopen it.
