### ISSUE TITLE
Server error when removing all M2M fields from table layout

### ISSUE THREAD

**Issue by ghost** [directus/api#1191]
I created "Articles" collection and added multiple M2M fields: categories, authors, and keywords. When removing categories, authors, and keywords from the table layout, a server error is shown and the following error is logged:

`
<b>Notice</b>:  Undefined index: authors in <b>/mnt/d/www/directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php</b> on line <b>2052</b><br />
<br />
<b>Notice</b>:  Undefined index: categories in <b>/mnt/d/www/directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php</b> on line <b>2052</b><br />
<br />
<b>Notice</b>:  Undefined index: keywords in <b>/mnt/d/www/directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php</b> on line <b>2052</b><br />
`

Project environment is set to staging.

Bug **does not** occur when environment is set to production.

PHP 7.3
MariaDB 10.3.11
Apache 2.4.29

**Comment by bjgajjar** [comment]
Fixed in #1192
