### ISSUE TITLE
Data not stored as per timezone

### ISSUE THREAD

**Issue by urvashithakar** [directus/api#1196]
# Bug Report
After updating timezone in `api.php` of config; not able to store the time of that timezone in DB.
## Steps to Reproduce

1. Go to 'api.php' config
2. Update the `timezone`
3. Store any collection record
4. Check the `created_on` field with Datetime Created interface.

## Expected Behavior
It must store the time of the `timezone` which have been set in config file.

## Actual Behavior
It is store in `UTC` timezone instead of the updated one.

## Technical Details

- Device: Desktop
- OS: MacOS
- Web Server: Apache 
- PHP Version: 7.2.14
- Database: MySQL 5.7.25
- Install Method: Cloned `master` branch

**Comment by bjgajjar** [comment]
Fixed in #1197

**Comment by benhaynes** [comment]
Interesting. I thought we were always storing in UTC no matter what. Are we allowing this to change based on the config?

@rijkvanzanten ?

**Comment by bjgajjar** [comment]
@benhaynes 

> I thought we were always storing in UTC no matter what.

As per the code before this PR may be **YES**. 

But it should be there as in the real world there might be the case in which user need to store the data based on their own timezone.
