### ISSUE TITLE
Add support for extension hooks / endpoints

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#12]
Each extension should have the ability to add hooks and/or endpoints dynamically to the api. 

For example, the `slug` interface has an option to mirror the content of another field. As of right now, this feature only works from the Directus app, seeing the interface doesn't have any say over the api.

This enhancement would mean that the interface has it's own entry point to the APIs hooks system.

```
.
├── Interface.js
├── Readonly.js
├── hooks.php  <<<<<<<<<<<<
├── meta.json
├── package-lock.json
└── package.json
```

that allows it to modify values in the API as well. This would mean that interface settings are both for the app _and_ for the API. A very _very_ powerful feature.

The extension hooks could / should look the same as "regular" hooks:

```php
'hooks' => [
    'postInsert' => function ($TableGateway, $record, $db) {
        // ...
    },
]
```

It would be very handy if _interfaces_ could get their options (as set in `directus_fields.options`) passed as well. BUT, seeing this is only valid for interfaces (and not all other extensions), it might not be worth it. (It can also be fetched from $db if needed).

Next to Hooks, it's also crucial for extensions to be able to add endpoints directly. Again, the `slug` interface would add a `/slug` endpoint that would sluggify the value, so the application can use that endpoint to dynamically show the to-be-saved slugged value.

Just like hooks, these endpoints would look the same as "regular" custom endpoints:

```php
$app->post('/slug', function () {
    // ...
});
```

and would reside in the their own file:

 ```
.
├── Interface.js
├── Readonly.js
├── endpoints.php  <<<<<<<<<<<<
├── meta.json
├── package-lock.json
└── package.json
```

**Comment by rijkvanzanten** [comment]
This is a big one I would really really love to see in the api @WellingGuzman 😄 

We have had so many questions about the slug interface auto-populating / user-created / etc / etc, this is huge 🎉

**Comment by WellingGuzman** [comment]
Hey @rijkvanzanten @benhaynes, questions:

- Does Interfaces, Pages and Listings has the option to add `endpoints` and `hooks`?
- Are we still going to name the route `/customs/<name>` for customs endpoints? and `/pages/<name>` for pages endpoints?

**Comment by rijkvanzanten** [comment]
> Does Interfaces, Pages and Listings has the option to add endpoints and hooks?

Yes! All extensions should have the ability to add both endpoints and/or hooks

> Are we still going to name the route /customs/<name> for customs endpoints? and /pages/<name> for pages endpoints?

Very good question. On the application side, we haven't decided on the route yet. Could be `/ext/<id>`, or maybe `/page/<id>` or we could even decide that pages can choose their own slug and nice url, but we would have to figure out some way to limit the url so it doesn't conflict with the core pages.

In terms of the API, pages are going to be downloaded in exactly the same way as interfaces and listings, so `/core/pages/<name>/meta.json` etc

**Comment by WellingGuzman** [comment]
> we would have to figure out some way to limit the url so it doesn't conflict with the core pages.

Right now to prevent collision with other endpoints within extensions pages, the directory name is is used as "unique id".

In the API we allow the pages to have a file (`endpoints.php`) that will be use to register a new endpoint. this file _should not_ be downloadable, but we have to find a way to prevent this file from being executed as these are going to be public (direct access).

**Comment by WellingGuzman** [comment]
Hooks and Endpoints can be added from within any extensions.

Inside interfaces or pages directory there's a reserved name for endpoints and hooks, `endpoints.php` and `hooks.php` respectively.

The hooks and extensions file must return an array.

For hooks, it should look like this:

```php
<?php

return [
    'actions' => [
        'table.insert:before' => function ($tableName, $data) {
            // some code
        }
    ],
    'filters' => [
        'table.insert:before' => function (\Directus\Hook\Payload $payload) {
            // some code
            return $payload;
        }
    ]
];
```

And endpoints should look like this:

```php
return [
    '' => [
        'method' => 'GET',
        'handler' => function ($request, $response) {
            return $response->withJson([
                'data' => [
                    'item 1',
                    'item 2'
                ]
            ]);
        }
    ]
]
```

More of this will be In the docs
