### ISSUE TITLE
Unable to edit file duration from File Library UI

### ISSUE THREAD

**Issue by darrenzhu** [directus/api#1203]
When we uploaded a video file (MP4) via the File Libary, the "Duration" property of the file isn't set. Neither can it be edited afterwards.  I'm logged in as an admin.

The only way to change the value appears to be editing the database record directly. Is it expected behavior? I can't seem to find much documentation about the duration property other than it is an integer.

![image](https://user-images.githubusercontent.com/3039321/62893704-33a82380-bd19-11e9-9ebc-1ac981cbb979.png)

Thanks

**Comment by bjgajjar** [comment]
Fixed in #1204
