### ISSUE TITLE
FilesystemCachePool error: Invalid key "Valid filenames must match [a-zA-Z0-9_\.! ]" 

### ISSUE THREAD

**Issue by JbalTero** [directus/api#1206]
# Bug Report

## Steps to Reproduce

* Enable filesystem caching as
![image](https://user-images.githubusercontent.com/3615746/63340475-b6645a80-c379-11e9-8a07-3ddfbf48de3a.png)

* Create a `cache` collection with `modified_on` field
* Add an item
* Update the item

## Expected Behavior

It should be updated successfully

## Actual Behavior

Error: `Invalid key "tag!entity_cache_2019-08-20 07:03:40". Valid filenames must match [a-zA-Z0-9_\.! ].`

![image](https://user-images.githubusercontent.com/3615746/63340603-0e02c600-c37a-11e9-8fe2-82722cf136ae.png)

## Other Context & Screenshots

[Screen recording](https://drive.google.com/file/d/19Qvg2TmwancOWyxMpbaGzehNoNfmB69N/view?usp=sharing)

## Technical Details

- Device: Desktop
- OS: Win 10  10.0.18362.145
- Web Server: Apache/2.4.29
- PHP Version: PHP 7.1.30
- Database: 10.2.26
- Install Method: v2.4.0 build
- Directus App: 7.9.0

**Comment by hemratna** [comment]
fixed in #1224
