### ISSUE TITLE
Add Avg/Min/Max parameters

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#121]
Based on field Get the avg, min or max value

**Comment by rijkvanzanten** [comment]
How would that parameter work? Is it a `meta` field?

**Comment by WellingGuzman** [comment]
I haven't thought this through yet, but any way we can get these values, as it may be quicker to let the database calculate this instead of fetching it all and then calculate.

**Comment by rijkvanzanten** [comment]
That's definitely true. I feel like it should add an additional field in the `meta` object in the response. Maybe something like:

`GET /items/projects?meta[avg][avgRating]=sentiment`

```json
{
  "meta": {
    "avgRating": 3
  },
  "data": [
    { "rating": 5 },
    { "rating": 1 }
  ]
}
```

?

The info we would need is:
`field`: name of the field to use for the "operation"
`operation`: operation type (avg, min, max)
`output-name`: name of the key how it's put in `meta`

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
