### ISSUE TITLE
Issue logging in after install

### ISSUE THREAD

**Issue by zas9vf** [directus/api#1212]
# Bug Report
I'm new to configuring CMS' and I'm having an issue where I am unable to log in after installing Directus for the first time
## Steps to Reproduce
install Drectus using clone
follow Apache install steps
go through the first time install steps
try logging in 
3. Scroll down to '...'

## Expected Behavior
Expected to be brought to the admin page after logging.

## Actual Behavior
Getting "Unknown server error. Try again later" 

## Other Context & Screenshots

In the console I see:
directus-sdk.umd.min.js:1 POST http://ec2-<IP>.compute-1.amazonaws.com/_/auth/authenticate 500 (Internal Server Error)

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
Ubuntu 18.04
- Web Server: [eg: Apache 2.4.37]
Apache/2.4.29 (Ubuntu)
- PHP Version: [eg: 7.2.0]
PHP 7.1
- Database: [eg: MySQL 8.0.12]
5.7.27-0ubuntu0.18.04.1
- Install Method: [eg: cloned `master` branch]
git clone ...

I've been reading through the issues and I've seen example where people have suggested  setting RewriteBase / in my .htaccess file but I'm not sure where to put it or the proper syntax. I also have mod_rewrite enabled

Any help would be greatly appreciated.

**Comment by bjgajjar** [comment]
Hey @zas9vf 

Maybe there is some configuration issue. As you are going towards `Directus` first time; kindly verify the step from [here](https://docs.directus.io/getting-started/installation.html) to reinforce your steps. 

And still, if you face this issue then kindly provide your `Log` file here.

**Comment by hemratna** [comment]
@zas9vf "Unknown server error. Try again late" is a generic error. 
Did you get any error in log files?

**Comment by hemratna** [comment]
@zas9vf Can you give me Directus logs?

**Comment by zas9vf** [comment]
sure. Here's the output from my last error log:

[2019-08-29 01:35:53] api[].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in /home/ubuntu/directus/src/helpers/app.php:268
Stack trace:
#0 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(530): Directus\{closure}
#1 /home/ubuntu/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->__invoke
#2 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#3 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#4 [internal function]: Slim\DeferredCallable->__invoke
#5 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#6 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#7 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack
#8 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(313): Slim\App->process
#9 /home/ubuntu/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#10 /home/ubuntu/directus/public/index.php(5): Directus\Application\Application->run [] []
[2019-08-29 01:51:44] api[].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in /home/ubuntu/directus/src/helpers/app.php:268
Stack trace:
#0 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(530): Directus\{closure}
#1 /home/ubuntu/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->__invoke
#2 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#3 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#4 [internal function]: Slim\DeferredCallable->__invoke
#5 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#6 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#7 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack
#8 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(313): Slim\App->process
#9 /home/ubuntu/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#10 /home/ubuntu/directus/public/index.php(5): Directus\Application\Application->run [] []
[2019-08-29 03:57:07] api[].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in /home/ubuntu/directus/src/helpers/app.php:268
Stack trace:
#0 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(530): Directus\{closure}
#1 /home/ubuntu/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->__invoke
#2 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#3 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#4 [internal function]: Slim\DeferredCallable->__invoke
#5 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#6 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#7 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack
#8 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(313): Slim\App->process
#9 /home/ubuntu/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#10 /home/ubuntu/directus/public/index.php(5): Directus\Application\Application->run [] []
[2019-08-29 04:04:21] api[].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in /home/ubuntu/directus/src/helpers/app.php:268
Stack trace:
#0 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(530): Directus\{closure}
#1 /home/ubuntu/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->__invoke
#2 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#3 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#4 [internal function]: Slim\DeferredCallable->__invoke
#5 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#6 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#7 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack
#8 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(313): Slim\App->process
#9 /home/ubuntu/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#10 /home/ubuntu/directus/public/index.php(5): Directus\Application\Application->run [] []
[2019-08-29 04:36:00] api[].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in /home/ubuntu/directus/src/helpers/app.php:268
Stack trace:
#0 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(530): Directus\{closure}
#1 /home/ubuntu/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->__invoke
#2 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#3 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#4 [internal function]: Slim\DeferredCallable->__invoke
#5 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#6 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#7 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack
#8 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(313): Slim\App->process
#9 /home/ubuntu/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#10 /home/ubuntu/directus/public/index.php(5): Directus\Application\Application->run [] []
[2019-08-29 04:43:08] api[].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in /home/ubuntu/directus/src/helpers/app.php:268
Stack trace:
#0 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(530): Directus\{closure}
#1 /home/ubuntu/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->__invoke
#2 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#3 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#4 [internal function]: Slim\DeferredCallable->__invoke
#5 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#6 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#7 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack
#8 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(313): Slim\App->process
#9 /home/ubuntu/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#10 /home/ubuntu/directus/public/index.php(5): Directus\Application\Application->run [] []
[2019-08-29 06:15:21] api[].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in /home/ubuntu/directus/src/helpers/app.php:268
Stack trace:
#0 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(530): Directus\{closure}
#1 /home/ubuntu/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->__invoke
#2 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#3 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#4 [internal function]: Slim\DeferredCallable->__invoke
#5 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#6 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#7 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack
#8 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(313): Slim\App->process
#9 /home/ubuntu/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#10 /home/ubuntu/directus/public/index.php(5): Directus\Application\Application->run [] []
[2019-08-29 07:10:05] api[].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in /home/ubuntu/directus/src/helpers/app.php:268
Stack trace:
#0 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(530): Directus\{closure}
#1 /home/ubuntu/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->__invoke
#2 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#3 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#4 [internal function]: Slim\DeferredCallable->__invoke
#5 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#6 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#7 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack
#8 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(313): Slim\App->process
#9 /home/ubuntu/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#10 /home/ubuntu/directus/public/index.php(5): Directus\Application\Application->run [] []
[2019-08-29 09:01:29] api[].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in /home/ubuntu/directus/src/helpers/app.php:268
Stack trace:
#0 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(530): Directus\{closure}
#1 /home/ubuntu/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->__invoke
#2 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#3 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#4 [internal function]: Slim\DeferredCallable->__invoke
#5 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#6 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#7 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack
#8 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(313): Slim\App->process
#9 /home/ubuntu/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#10 /home/ubuntu/directus/public/index.php(5): Directus\Application\Application->run [] []
[2019-08-29 09:47:58] api[].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in /home/ubuntu/directus/src/helpers/app.php:268
Stack trace:
#0 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(530): Directus\{closure}
#1 /home/ubuntu/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->__invoke
#2 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#3 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#4 [internal function]: Slim\DeferredCallable->__invoke
#5 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#6 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#7 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack
#8 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(313): Slim\App->process
#9 /home/ubuntu/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#10 /home/ubuntu/directus/public/index.php(5): Directus\Application\Application->run [] []
[2019-08-29 13:17:33] api[].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in /home/ubuntu/directus/src/helpers/app.php:268
Stack trace:
#0 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(530): Directus\{closure}
#1 /home/ubuntu/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->__invoke
#2 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#3 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#4 [internal function]: Slim\DeferredCallable->__invoke
#5 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#6 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#7 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack
#8 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(313): Slim\App->process
#9 /home/ubuntu/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#10 /home/ubuntu/directus/public/index.php(5): Directus\Application\Application->run [] []
[2019-08-29 14:35:46] api[_].ERROR: Error: Call to undefined function Directus\curl_init() in /home/ubuntu/directus/src/helpers/request.php:64
Stack trace:
#0 /home/ubuntu/directus/src/helpers/request.php(107): Directus\request_send
#1 /home/ubuntu/directus/src/core/Directus/Application/CoreServicesProvider.php(740): Directus\request_send_json
#2 [internal function]: Directus\Application\CoreServicesProvider->Directus\Application\{closure}
#3 /home/ubuntu/directus/src/core/Directus/Hook/Emitter.php(291): call_user_func_array
#4 /home/ubuntu/directus/src/core/Directus/Hook/Emitter.php(119): Directus\Hook\Emitter->executeListeners
#5 /home/ubuntu/directus/src/core/Directus/Services/AuthService.php(51): Directus\Hook\Emitter->run
#6 /home/ubuntu/directus/src/endpoints/Auth.php(49): Directus\Services\AuthService->loginWithCredentials
#7 [internal function]: Directus\Api\Routes\Auth->authenticate
#8 /home/ubuntu/directus/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func
#9 /home/ubuntu/directus/vendor/slim/slim/Slim/Route.php(356): Slim\Handlers\Strategies\RequestResponse->__invoke
#10 /home/ubuntu/directus/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->__invoke
#11 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#12 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#13 [internal function]: Slim\DeferredCallable->__invoke
#14 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#15 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#16 /home/ubuntu/directus/vendor/slim/slim/Slim/Route.php(334): Slim\Route->callMiddlewareStack
#17 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(515): Slim\Route->run
#18 /home/ubuntu/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#19 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#20 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#21 [internal function]: Slim\DeferredCallable->__invoke
#22 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#23 /home/ubuntu/directus/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#24 /home/ubuntu/directus/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#25 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#26 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#27 [internal function]: Slim\DeferredCallable->__invoke
#28 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#29 /home/ubuntu/directus/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#30 [internal function]: RKA\Middleware\IpAddress->__invoke
#31 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#32 [internal function]: Slim\DeferredCallable->__invoke
#33 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#34 /home/ubuntu/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->Slim\{closure}
#35 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#36 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#37 [internal function]: Slim\DeferredCallable->__invoke
#38 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#39 /home/ubuntu/directus/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(54): Slim\App->Slim\{closure}
#40 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#41 /home/ubuntu/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array
#42 [internal function]: Slim\DeferredCallable->__invoke
#43 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#44 /home/ubuntu/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#45 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(405): Slim\App->callMiddlewareStack
#46 /home/ubuntu/directus/vendor/slim/slim/Slim/App.php(313): Slim\App->process
#47 /home/ubuntu/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
#48 /home/ubuntu/directus/public/index.php(5): Directus\Application\Application->run [] []

**Comment by bjgajjar** [comment]
@zas9vf 

It seems like, it's the issue with CURL. Can you please check whether the CURL is enabled at your server or not using `phpinfo()`?

**Comment by zas9vf** [comment]
@bjgajjar that was the issue...curl wasn't installed. Thank you for your help!
