### ISSUE TITLE
Tree structures are not searchable

### ISSUE THREAD

**Issue by Tobsic** [directus/api#1216]
# Bug Report

## Steps to Reproduce

1. Create a new collection (e.g. Nodes)
2. Add a Many to One field, that relates to the same collection again (e.g. field parent that relates to a Node)
3. Add a One to Many field (inverse of the field above, e.g. children)
4. Create a node
5. Type something in the searchbar (or do a get request with a given `q` parameter)

## Expected Behavior

App: See a list of nodes that match the given search criteria.
Direct API access:  Get a json encoded list of nodes.

## Actual Behavior

App: See a "Server Error"
Direct API access: 500 error with message "Failed generating the SQL query." and query like this (the collection is named `a` in this case)
```
SELECT `a`.`id` AS `id`, `a`.`status` AS `status`, `a`.`created_by` AS `created_by`, `a`.`created_on` AS `created_on`, `a`.`parent` AS `parent` FROM `a` WHERE (`a`.`id` LIKE '%a%' OR `a`.`id` IN (SELECT `a`.`parent` AS `parent` FROM `a` RIGHT JOIN `a` ON `a`.`id` = `a`.`parent` WHERE `a`.`id` LIKE '%a%')) AND `a`.`status` IN ('published', 'draft') ORDER BY `a`.`id` IS NULL, `a`.`id` ASC, `a`.`id` ASC LIMIT 100 OFFSET 0
```
The problematic part is ```SELECT `a`.`parent` AS `parent` FROM `a` RIGHT JOIN `a` ON `a`.`id` = `a`.`parent` WHERE `a`.`id` LIKE '%a%'```. The collection name is used twice.

## Technical Details

Demo at directus.app and self hosted:

- Device: vServer
- OS: Debian 10.0
- Web Server: Apache 2.4.38-3
- PHP Version: 7.3.4-2
- Zend Engine: v3.3.4
- OPcache: v7.3.4-2
- Database: MySQL 8.0.17
- Install Method: cloned `build` branch

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1259
