### ISSUE TITLE
New Status Mapping Format

### ISSUE THREAD

**Issue by benhaynes** [directus/api#122]
This is the new default, which also shows the new option names:

```json
{
   "published":{
      "name":"Published",
      "text_color":"#FFFFFF",
      "background_color":"#039BE5",
      "listing_subdued":false,
      "listing_badge":false,
      "soft_delete":false,
      "published":true
   },
   "under-review":{
      "name":"Under Review",
      "text_color":"#FFFFFF",
      "background_color":"#FF9800",
      "listing_subdued":true,
      "listing_badge":true,
      "soft_delete":false,
      "published":false
   },
   "draft":{
      "name":"Draft",
      "text_color":"#78909C",
      "background_color":"#CFD8DC",
      "listing_subdued":true,
      "listing_badge":true,
      "soft_delete":false,
      "published":false
   },
   "deleted":{
      "name":"Deleted",
      "text_color":"#FFFFFF",
      "background_color":"#F44336",
      "listing_subdued":true,
      "listing_badge":true,
      "soft_delete":true,
      "published":false
   }
}
```

**Comment by WellingGuzman** [comment]
We don't have default status mapping anymore. are we adding it back to the API? or is this meant for the placeholder on the status interface option?

**Comment by WellingGuzman** [comment]
Also, which one would be the default for numeric field?

**Comment by rijkvanzanten** [comment]
@WellingGuzman I'll use this in the default options of the status interface. The api doesn't have to worry about it 😉 

@benhaynes How does `published` actually work? The API still needs to be able to return items, even non-published ones of course. How does that work right now @WellingGuzman? It just returns published by default and shows the others if you filter for them?

**Comment by WellingGuzman** [comment]
@rijkvanzanten by default to prevent showing "non-published" items, the api only returns all the items with status value set to `published=true`

**Comment by rijkvanzanten** [comment]
Yeah I get that, but how do we tell the api to return all items now?

**Comment by rijkvanzanten** [comment]
We used to have status=<CSV>, but we deprecated that in favor of filters. I feel like published is a Boolean (it’s either published or not). Should we add a dedicated endpoint for it? 

Thoughts @benhaynes?

**Comment by WellingGuzman** [comment]
Setting the query parameter `status` to `*`:

Ex: `http://localhost/api/_/items/projects?status=*`

**Comment by benhaynes** [comment]
I think that the published parameter should be definitive. I don't think that there should be a way for the API to return non-published items for security reasons. Otherwise that defeats the purpose. If someone wants to return deleted items from the database they can use a different status as a soft soft delete, or something like that.

You guys agree?

**Comment by benhaynes** [comment]
The problem is right now we don't have a way to define whether or not published or soft deleted items can be returned by the API. I don't think that that's worth adding a new permission for, but I'm open to discuss.

**Comment by WellingGuzman** [comment]
I agree, the only reason you set the status is to fetch "non-published" items. (for security reason)

**Comment by WellingGuzman** [comment]
> I don't think that that's worth adding a new permission for, but I'm open to discuss.

@benhaynes What kind of permission are you referring to?

**Comment by benhaynes** [comment]
Haha, it wouldn't make sense to have a permission to allow unpublished to be returned by the API... Nevermind!

**Comment by WellingGuzman** [comment]
This can be easily solved by setting each status to `published=true` (or not setting anything as `true` is the default value for `published`)

**Comment by rijkvanzanten** [comment]
ho wait guys, there is a difference between published and soft-delete. Soft deleted will never be returned, but non-published includes draft etc. If the api doesn't return non-published items at all, there is no way for the application to work

**Comment by WellingGuzman** [comment]
Using `status=*` will return all items no matter the status. `soft-delete` doesn't mean anything different from any other statuses beside setting the action to `SOFT_DELETE` in `directus_activity`.

What I think we are saying is that by default only "published" items are going to be returned from the API.

**Comment by benhaynes** [comment]
Good catch Rijk!! Soooooorry...

**Published** is just the default items to get returned by the API. But you can override that with parameters. We need to be careful here... the app uses the API, so it needs all the other non published items, but projects should never worry about their users somehow getting access to unreleased content.

**Soft delete** will never get returned by the API. Ever. Even with params.

**Comment by WellingGuzman** [comment]
> **Soft delete** will never get returned by the API. Ever. Even with params.

Understood!

**Comment by rijkvanzanten** [comment]
> Soft delete will never get returned by the API. Ever. Even with params.

But...... didn't we decide that it should be able for administrators to _undo_ soft-delete from _within_ Directus? By blocking all soft-delete items in the API, this is impossible.... @benhaynes

**Comment by benhaynes** [comment]
We'll need to discuss is there's a way to allow the app to do things that projects and external API calls can't. 

Then we can with the difference between admins restoring soft deleted items in the database only or Directus.

**Comment by rijkvanzanten** [comment]
> We'll need to discuss is there's a way to allow the app to do things that projects and external API calls can't.

Even if we could, I don’t think that’s something we should _want_. The Directus app is just another project that used the Directus API IMO.

**Comment by benhaynes** [comment]
We can forget about Admins "restoring" soft-deleted items and just make sure the API never returns them. Admins can adjust in the DB directly.

**Comment by rijkvanzanten** [comment]
What about Directus Cloud ☁️ @benhaynes

**Comment by benhaynes** [comment]
Then we can allow it, but only Admin's have access to items with that status... and the Directus app MUST NOT allow users/projects to change those permissions.
