### ISSUE TITLE
When deleting a relationship item: FilesystemCachePool error: Invalid key "Valid filenames must match [a-zA-Z0-9_\.! ]"

### ISSUE THREAD

**Issue by JbalTero** [directus/api#1229]
## Steps to Reproduce

`events` one-to-many with `schedules`

* Create events item with 2 schedules
* Update the item, remove 1 schedule

## Expected Behavior

should save without error

## Actual Behavior

```
FilesystemCachePool error: Invalid key "Valid filenames must match [a-zA-Z0-9_\.! ]"
```

## Other Context & Screenshots

[screenrecording](https://drive.google.com/file/d/1a9pUGmwJ954Mz6knJDbi2KF1Wa11OoX1/view?usp=sharing)

## Technical Details

- Device: Desktop
- OS: Win 10  10.0.18362.145
- Web Server: Apache/2.4.29
- PHP Version: PHP 7.1.30
- Database: 10.2.26
- Install Method: v2.5.0 build
- Directus App: 7.10.0

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1224
