### ISSUE TITLE
Deletion of m2o/o2m field error: Invalid key "tag!entity_directus_fields_many-to-one". Valid filenames must match [a-zA-Z0-9_\.! ].

### ISSUE THREAD

**Issue by JbalTero** [directus/api#1234]
## Steps to Reproduce

* Enable caching
* `artists` one-to-many with `artworks`
* Add m2o field in artworks
* Delete the m2o field

Also happens with o2m
* Add o2m field in artists
* Delete the o2m field

## Expected Behavior

There should be no error

## Actual Behavior

Invalid key "tag!entity_directus_fields_many-to-one". Valid filenames must match [a-zA-Z0-9_\.! ].

## Other Context & Screenshots

[screenrecording](https://drive.google.com/file/d/1wXIYAcZqg8ioiahtByj5_vOdDHvXOdm5/view?usp=sharing)

## Technical Details

- Device: Desktop
- OS: Win 10  10.0.18362.145
- Web Server: Apache/2.4.29
- PHP Version: PHP 7.1.30
- Database: 10.2.26
- Install Method: v2.5.0 build
- Directus App: 7.10.0

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1241

**Comment by JbalTero** [comment]
Thanks
