### ISSUE TITLE
Automatic post to multiple dependent collections

### ISSUE THREAD

**Issue by m13robert** [directus/api#1236]
# Feature Request

Hello! I would like to request a way to insert into a collection that has a lot of M2O relationships.

## What problem does this feature solve?

This feature would be great for the instances when you have to insert/post a lot of data in the database.
My case is that I have an excel file which required a complex data model(see the screenshot below) and the client would like to have a way of importing the data from the excel to the database without having to insert it manually.

## How do you think this should be implemented?

Maybe it would be a good idea to have this as a paid separate module that only requires the parameters of the data separated by a comma for the specific collections and it inserts them as the VALUES. 
Something like:

Collection1 params
Dependent m2o Collection2 params

## Would you be willing to work on this?

If I will manage to build this on my own, I'd be more than happy to provide it.

I hope I didn't sound too stupid. 

![image](https://user-images.githubusercontent.com/35663982/64023690-2b355280-cb39-11e9-8ecb-0b248a2b7205.png)

**Comment by m13robert** [comment]
I forgot to add the screenshot with the fields.

![image](https://user-images.githubusercontent.com/35663982/64023796-633c9580-cb39-11e9-9607-0917be35016c.png)

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
This seems like it would be an extended part of the import tool we're discussing here: https://github.com/directus/api/issues/31

Since Directus works with pure SQL, you can probably find tools that exist for this sort of migration — and then it would "just work" in our CMS. Still it's an interesting idea to figure out in an import extension.

**Comment by mikitnt** [comment]
what type of tools are you meaning? could you provide an example?

**Comment by benhaynes** [comment]
https://stackoverflow.com/questions/1310166/how-to-import-an-excel-file-in-to-a-mysql-database
