### ISSUE TITLE
Improve database performance

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#124]
- [ ] Reorder columns
- [ ] Add indexes
- [ ] Add Foreign keys

Reordering columns, and adding index where is needed can improve database performance.

_More details will be added later when is time to work on these performance points._

**Comment by rijkvanzanten** [comment]
@WellingGuzman Have we considered adding a caching layer between the API and the database?

**Comment by WellingGuzman** [comment]
@rijkvanzanten We did agree on a caching layer between the API and the database, but mostly for schema information (which is not done yet) and we have one for results which I need to implement from 6.x to 7.x

**Comment by rijkvanzanten** [comment]
Perfect 👍 

This is separate from the caching layer between the project and the API right?

[project] / Directus App -> CACHE -> API -> CACHE -> DB

**Comment by WellingGuzman** [comment]
Exactly, this cache layer is between the database and the API.

**Comment by WellingGuzman** [comment]
Moved to #179
