### ISSUE TITLE
Invalid RegEx validation on smallint datatype

### ISSUE THREAD

**Issue by mrsteffenjo** [directus/api#1242]
I tried to put a RegEx Validation on a datatype Integer, and when I try to save I get the error message saying invalid regex, i've tried these:
* `[0-9]{4}`
* `[0-9]{4,4}`
* `^[0-9]{4}$`

These are valid RegEx', so what's the case here? If RegEx is not supported for integers then the field should not be visible in the advanced options?

**Comment by bjgajjar** [comment]
It seems like there is some issue on validation the regex at `API`. I'll check and resolve it ASAP.

**Comment by bjgajjar** [comment]
There isn't any issue with `API`. You just need to use delimiters for regex validation. Kindly check the [doc](https://docs.directus.io/api/reference.html#validation) for more details.

- /[0-9]{4}/
- /[0-9]{4,4}/
- /^[0-9]{4}$/

**Comment by mrsteffenjo** [comment]
Thanks, according to the php docs I could also use:

- /foo bar/
- #^[^0-9]$#
- +php+
- %[a-zA-Z0-9_-]%
