### ISSUE TITLE
Chinese characters are not supported out-of-the-box

### ISSUE THREAD

**Issue by johnhorsema** [directus/api#1243]
# Bug Report

## Steps to Reproduce

1. Create a collection
2. Create an entry containing Chinese characters
3. "Failed generating the SQL query"

## Expected Behavior

Successful creation of entry.

## Actual Behavior

Error message shown.

## Solution

Have to run the following SQL queries before using the system, which should be set as default to save developers' time!

```
ALTER DATABASE <directus-api-database> CHARACTER SET utf8 COLLATE utf8_bin;
ALTER TABLE <collection-1> CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;
ALTER TABLE <collection-2> CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;
ALTER TABLE <collection-3> CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;
```

## Suggestion

All collections created should have utf8 collation!

**Comment by bjgajjar** [comment]
@johnhorsema 

By default, we have `utf8mb4` as a charset. You can find it from `api.php` config. And you can update it as per your requirement.
