### ISSUE TITLE
Demo Web Hook

### ISSUE THREAD

**Issue by benhaynes** [directus/api#125]
We already have Event Hooks, but I would like to have one DEMO Web Hook ready for use out-of-the-box. That way people can see how they work and we can say "we have them". Any new ones can be created by users.

**Comment by benhaynes** [comment]
@WellingGuzman – did you add a note into the API Docs about this example so people know it's there?

**Comment by WellingGuzman** [comment]
Where should this be written? the api reference here `/docs` or the `docs` repo?

**Comment by rijkvanzanten** [comment]
The docs and api-docs repos will be deprecated completely in favor of the docs folder in the main repo

**Comment by benhaynes** [comment]
All set.
