### ISSUE TITLE
Google Auth stuck at Logging In ...

### ISSUE THREAD

**Issue by RyanPrice-King** [directus/api#1252]
# Bug Report

## Steps to Reproduce

Login Google Auth

## Expected Behavior
Logs In successfully
## Actual Behavior
Stuck "Signing In..."
## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/34060058/51744364-8250e180-2097-11e9-9478-fabdcc87439a.png)

If I switch to Directus App 7.0.11 it immediately works until I switch to another version from 7.0.12 - 7.0.15, it doesn't log in and I get this issue again.  

I can login manually with same username.

I cannot see anything added to API logs when this happens and I cannot find the docker APP logs to check them.

## Technical Details

- Device: Desktop
- OS: Windows and Ubuntu
- Browser: [eg: Chrome 68.0.3440.106]
- Directus App: 7.0.15 (docker)
- Directus API: 2.0.15
- Install Method: Git clone seperate API and APP with Clean fresh install of DB

**Comment by bjgajjar** [comment]
After analaysing the code; I able to find out that; Google Auth is working as expected.

- Generally, social login works as the role of `FindOrCreate` [Return the user if exists or create a new with those details] but here the functionality exists for Admin Panel and Admin cant register themselves. 
- The social login works perfectly for those users who are already registered and don't want to login with email and password.
    - Let's assume there is an account with email `noah@gmail.com` and one tried to login with the same google id. Then that user will able to login with google.
    - But if that user doesn't have an account in the system and tried to login with google then the system will redirect them to login page with exception that user is not exists in the system. Which is the expected behaviour. As `Admin` cant register themselves. 

- Thus we just need to provide an alert or proper message at app side in this scenario.

**Comment by theharshin** [comment]
Submitted a PR https://github.com/directus/app/pull/2022 which will display auth errors for SSO.

**Comment by bjgajjar** [comment]
As this issue is not reproducible in the latest version; I am closing this. Feel free to reopen it.
