### ISSUE TITLE
Return SSO error as object

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#126]
Right now, an invalid login is returned as an (English) string:
`http://localhost:8080/login?error=User%20with%20email%20%22rijkvanzanten%40me.com%22%20not%20found`

With i18n in mind, there is no way to accurately translate this right now.

It would be perfect if the API would return 
```json
{
  "error": {
    "code": 111,
    "email": "rijkvanzanten@me.com"
  }
}
```

that way, the app can map `111` to the string `User with email "${email}" not found`.

**Comment by WellingGuzman** [comment]
Using the error code won't make it useful in this case at least? you already have the email you use to make the request.

**Comment by rijkvanzanten** [comment]
The app doesn't have anything. It's like someone opening the page fresh. The only info the app has is the info you provide it in the query parameters 🙂

**Comment by WellingGuzman** [comment]
Ah you are right! Would this work:

```
{
  "error": {
    "code": 111,
    "attributes": {
      "email": "rijkvanzanten@me.com"
    }
  }
}
```

That way we can add more attributes for future errors.

**Comment by rijkvanzanten** [comment]
Yep, looks good! 

We could maybe drop the `error` nested key to save some bytes. We already know it's an error seeing it's in the `error` query parameter!

```json
{
    "code": 111,
    "attributes": {
      "email": "rijkvanzanten@me.com"
    }
}
```

**Comment by WellingGuzman** [comment]
oh wait, These are passed through query strings, so it will ended up: `error=message&code=111&attributes[email]=rijkvanzanten@me.com` or maybe change `code` to `errorCode`?

**Comment by WellingGuzman** [comment]
I can, I was trying not to use json. I will update to fit your needs.

One more question does the original error message will be gone or be inside with the `message` key?

**Comment by WellingGuzman** [comment]
Okay, I will change it to `?error=true&code=111&attributes[email]=rijkvanzanten@me.com`

**Comment by WellingGuzman** [comment]
One thing `error=true` will be changed to `error=true`, because `true` (boolean) will be converted to `1`.

**Comment by rijkvanzanten** [comment]
> One thing error=true will be changed to error=true

![wat](https://media.giphy.com/media/Sam2iFOFOv2Vy/giphy.gif)

**Comment by WellingGuzman** [comment]
Hahaha, I am out.

`error=true` will be changed to `error=1`

**Comment by WellingGuzman** [comment]
Already implemented as `?error=true&code=111&attributes[email]=rijkvanzanten@me.com`
