### ISSUE TITLE
wysiwyg-full - add image - Call to a member function isOneToMany() on null

### ISSUE THREAD

**Issue by JbalTero** [directus/api#1279]
## Steps to Reproduce

* Fresh install from https://github.com/directus/api/commit/1cf64403d53e3bf0b6db7ea98402ddae3a94da80
* Enable development mode
* Create collection with wysiwyg-full field
* Add item
* Add image

## Expected Behavior

It should successfully add image

## Actual Behavior

Error: `Call to a member function isOneToMany() on null`

```
[2019-09-12 17:14:10] api[_].ERROR: Error: Call to a member function isOneToMany() on null in /webroot/src/core/Directus/Database/TableGateway/RelationalTableGateway.php:405
Stack trace:
#0 /webroot/src/core/Directus/Services/FilesServices.php(59): Directus\Database\TableGateway\RelationalTableGateway->createRecord
#1 /webroot/src/endpoints/Files.php(84): Directus\Services\FilesServices->create
#2 [internal function]: Directus\Api\Routes\Files->create
#3 /webroot/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#4 /webroot/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#5 /webroot/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#6 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
```

## Other Context & Screenshots

[Screenrecording](https://drive.google.com/file/d/1NQTlatm6dzYDp9-mNp3XL3WrnnspScrl/view?usp=sharing)

## Technical Details

- Device: Desktop
- OS: Win 10  10.0.18362.145
- Web Server: Apache/2.4.29
- PHP Version: PHP 7.1.30
- Database: 10.2.26
- Install Method: https://github.com/directus/api/commit/1cf64403d53e3bf0b6db7ea98402ddae3a94da80
- Directus App: 7.9.0

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1288
