### ISSUE TITLE
Failed to send email

### ISSUE THREAD

**Issue by andriansandi** [directus/api#1283]
# Bug Report

## Steps to Reproduce
1. Update config api.php on key *mail*
```
'mail' => [
    'default' => [
    'transport' => 'smtp',
     'host' => 'smtp.sendgrid.net',
     'port' => '587',
     'username' => 'xxxx',
     'password' => 'xxxx',
     'from' => 'xxxx',
     'encryption' => 'tls',
     'verify_peer' => false
   ],
]
```
2. Do API call to /mail with the params
```
{
  "to": "anu@gmail.com",
  "subject": "New Password",
  "body": "Hello <b>{{name}}</b>, this is your new password: {{password}}.",
  "type": "html",
  "data": {
    "name": "John Doe",
    "password": "secret"
  }
}
```

## Expected Behavior
Email send with SMTP using sendgrid

## Actual Behavior
Failed to send email with smtp using sendgrid, following error:
```
{
    "error": {
        "code": null,
        "message": "Expected response code 250 but got code \"550\", with message \"550 Unauthenticated senders not allowed\r\n\"",
        "class": "Swift_TransportException",
        "file": "/var/www/directus/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php",
        "line": 383
    }
}
```

## Technical Details
- OS: Ubuntu 18.04
- Web Server: Apache/2.4.29 (Ubuntu)
- PHP Version: 7.2.19-0ubuntu0.18.04.2
- Install Method: cloned `master` branch

**Comment by rijkvanzanten** [comment]
Did you verify the credentials you used in the config + the setup in Sendgrid? The error `550 Unauthenticated senders not allowed` makes me think that either the credentials are invalid, or Directus isn't sending the credentials correctly

**Comment by JannieT** [comment]
Looks like [the fix][1] has not made it to the [master branch][2] yet.

[1]:https://github.com/directus/api/pull/1223
[2]:https://github.com/directus/directus/blob/master/src/core/Directus/Config/Schema/Schema.php#L70

**Comment by rijkvanzanten** [comment]
I'll push out a new release before the end of the week 👍

**Comment by JannieT** [comment]
@rijkvanzanten looks like the fix was not included in the latest release. Any ETA?

**Comment by rijkvanzanten** [comment]
@JannieT Right now

**Comment by JannieT** [comment]
Works like a dream 👍 . Thank you!
