### ISSUE TITLE
Broken user related fields (created_by, modified_by)

### ISSUE THREAD

**Issue by WoLfulus** [directus/api#1284]
# Bug Report

## Steps to Reproduce

- Create a collection with created_by and modified_by (just mark them on collection creation dialog)
- Insert one row to that collection
- Try removing the fields

## Expected Behavior

Able to delete and recreate created_by and updated_by fields from a collection

## Actual Behavior

The delete is broken for some reason. It's not possible to delete those fields and it gets to a state that we're unable to even  create the field again later because it doesn't remove it from directus_fields table.

## Other Context & Screenshots

There's 3 errors, first two are when I tried deleting created_by then updated_by, the last one was I trying to delete created_by again.

![image](https://user-images.githubusercontent.com/412397/64844020-ffa47480-d5dc-11e9-8e29-b2dce496fbe6.png)

## Technical Details

Reproducible in demo (directus.app)

There may be more issues related to those fields, for example: directus/app#2058

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1287
