### ISSUE TITLE
New hook item.read.query

### ISSUE THREAD

**Issue by devova** [directus/api#1286]
# Feature Request
Introduce a new hook `item.read.query` which will allow to modify db query based on http request params.

## What problem does this feature solve?
There is already hook `item.read:before` which suppose to do something similar.
From https://github.com/directus/api/blob/develop/src/core/Directus/Database/TableGateway/BaseTableGateway.php#L727-L732
```
protected function executeSelect(Select $select)
            ...
            $selectState = $this->applyHooks([
                'item.read:before',
                'item.read.' . $selectCollectionName . ':before',
            ], $selectState, [
                'collection_name' => $selectCollectionName
            ]);
            ...
```
Here it is passed only `$selectState` which custom extension/hook can modify before actual sql call. Unfortunately it is not enough to build some specific filters, based on custom request params.

## How do you think this should be implemented?
According to call stack request `$params` exists at two steps above,  in `RelationalTableGateway.php`. It would be good to introduce new hook, for instance 
```
'item.read.query',
'item.read.query.' . $selectCollectionName ,
```
Pass into the hook `$builder` and `$params`, expect to receive `$builder`, and call it before execution of
https://github.com/directus/api/blob/develop/src/core/Directus/Database/TableGateway/RelationalTableGateway.php#L1171

## Would you be willing to work on this?
I would love to.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
