### ISSUE TITLE
LDAP integration

### ISSUE THREAD

**Issue by jfbelisle** [directus/api#1289]
# Feature Request
Add LDAP integration for authenticating users

## What problem does this feature solve?
We could be able to authenticate users using our LDAP dictionnary and at the same time assign roles based on user's groups

## How do you think this should be implemented?
I think it should be implemented the same way the other auth extension(facebook, github, ...) are implemented, with a core auth extension. 

Otherwise, maybe using your SCIM Endpoints. 

## Would you be willing to work on this?
Probably, yes. I guess I could help.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by ddavidebor** [comment]
My two cents: LDAP is where the big business money is (together with big-business friendly databases)

**Comment by richardt3** [comment]
agree with @ddavidebor - another password is annoying for business users. For SysAdmins, helps with staff leaver processes.

**Comment by mfcanovas** [comment]
LDAP integration would be awesome!

**Comment by bloigge** [comment]
this - yes please!

**Comment by youssef-ali** [comment]
Any updates about LDAP integration?
