### ISSUE TITLE
Recommended to develop sort by views

### ISSUE THREAD

**Issue by cdwmhcc** [directus/api#1291]
Add views filter（Sort by views）

## What problem does this feature solve?
Sort by number of clicks is not supported. I don't know why.

## How do you think this should be implemented?

Add views filter to the filter

**Comment by benhaynes** [comment]
@cdwmhcc — can you add a bit more info please? Version numbers, OS, etc... and some more detailed steps to reproduce, screenshots, etc.

**Comment by cdwmhcc** [comment]
@benhaynes 
Wow, it's not BUG, it's a suggestion.

**Comment by benhaynes** [comment]
Haha, even more of a reason to add details.

It's not clear what you mean by this ticket... what are `views`, etc?

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by cdwmhcc** [comment]
@benhaynes 

I don't know how to express it. I tried a few translation tools,that didn't satisfy me.
I'll describe it and see if you can understand it. I'll edit it if I can.
Statistics item clicks times,
It can be sorted by the number of clicks through a filter.

**Comment by benhaynes** [comment]
Your project/app can track any views in a regular "number" field by writing/incrementing to the API. Then you can order by views in the Layouts.

**Comment by cdwmhcc** [comment]
> Your project/app can track any views in a regular "number" field by writing/incrementing to the API. Then you can order by views in the Layouts.

Yeah!!!! Yes!!!!
