### ISSUE TITLE
Unable to upload files due to 0 size limit

### ISSUE THREAD

**Issue by evrimoztamur** [directus/api#1292]
Error message on the message popup when attempting to upload a file reads as "_[file]_.png can't be uploaded. Your server is not configured to handle uploads of this size." with the upload dialog displaying "Max. Size: 0 B." I read in a previous issue that this could be caused by the API failing to read the server information due to a blocked OPTIONS request, but network trace on browser yields no `OPTIONS` requests except against [telemetry.directus.io](https://telemetry.directus.io/).

My `cli/php.ini` and `apache2/php.ini` both read the default 2 MB upload limit, and attempting to override it by uncommenting the `.../directus/public/.htaccess` snippet does not yield any changes.

I am using PHP 7.3 with the latest versions of MySQL and Apache2. I'm not necessarily sure what the root of the problem is, but could it be due to 7.3 handling server configurations differently?

Let me know if I can provide more information or if there are any debug snippets I can run.

**Comment by rijkvanzanten** [comment]
It seems to be working on my machine on PHP 7.3 🤔

Not too sure what's going on (yet), but I'm suspecting it's a environment problem @directus/api-team

**Comment by evrimoztamur** [comment]
This can be closed now; for future reference to people who want to access the app on a different path than the default `/admin` in the suite, do not try to edit your `.htaccess` for redirecting `/` to `/admin`. The API uses the root path of itself to query the server for its settings. When that page was proxied to `/admin`, the methods requesting upload file limit (and likely other settings) were 'confused' because they didn't receive the correct response.

I'm not sure if you would intend to use a special path for querying server information, but the way I resolved this in the end was just running the API on a different secured port (same certificate) and querying that instead. Has not yielded any problems since. Alternatively, the suite could install API on the more specific path instead of using root and `<domain>/admin` for the app.

Regardless, exemplary case for future deployers, issue can be closed.
