### ISSUE TITLE
Translations are not getting deleted

### ISSUE THREAD

**Issue by inta** [directus/api#1294]
I have a collection with translations and if I delete one article, the translations (inside the translation table) are not deleted. I'm not sure if this belongs to the App oder API.

Given the following tables:

```
language
--------
language (char, primary key)
name (varchar, text input)

article
-------
id (int, primary key)
translation (translation)

article_translation
-------------------
id (int, primary key)
article_id (int, numeric)
language (char, lang)
title (varchar, text input)
```

I've added two languages and an article with two translations. If I delete the article, it is removed from the article table but both translations remain inside the article_translation table. I would have expected that they will be removed as well.

Translation setup is done as described here: https://docs.directus.io/guides/relationships.html#translations

**Comment by benhaynes** [comment]
This is a duplicate feature request of: https://github.com/directus/api/issues/384 and https://github.com/directus/api/issues/873
