### ISSUE TITLE
Use UTF8MB4 as default for table/column names

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#13]
Because we really _really_ want to be able to call our tables  `directus_❤️`.

Or on a more serious note: https://github.com/directus/directus/issues/2061#issuecomment-366307209

**Comment by WellingGuzman** [comment]
MySQL only supports unicode from `U+0080` to `U+FFFF`.

<img width="249" alt="screen shot 2018-04-05 at 4 54 52 pm" src="https://user-images.githubusercontent.com/1531291/38391764-313b5a96-38f3-11e8-8e21-606367a25c00.png">

Ref: https://dev.mysql.com/doc/refman/5.7/en/identifiers.html

**Comment by WellingGuzman** [comment]
Closed by https://github.com/WellingGuzman/zend-db/commit/ef55371343a85e5cd0937d0ab9d30da7e86f5ab3
