### ISSUE TITLE
Add Regex fields validation

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#130]
Using `fields.validation` column

**Comment by rijkvanzanten** [comment]
Can you document this too? Thankssssssssssss 💪

**Comment by rijkvanzanten** [comment]
@wellingguzman :bell:

**Comment by WellingGuzman** [comment]
Thanks @lrkwz, I updated the documentation.

Ref: https://github.com/directus/docs/commit/c7dfa6a0be7dfaaffe300093e40cd410079b616f

**Comment by WellingGuzman** [comment]
Also the delimitar doesn't have to be `/`, it could be almost anything including `#`, `%`. 

I added links to the docs: https://github.com/directus/docs/commit/193d3bd9c2798cf1b38d86f6944fe88f8c970c49.

- [PCRE Patterns](http://php.net/manual/en/pcre.pattern.php)
- [Delimiters](http://php.net/manual/en/regexp.reference.delimiters.php)
