### ISSUE TITLE
Internal server error when selecting/checking a Checkbox Relational field after deleting some of the related items

### ISSUE THREAD

**Issue by JbalTero** [directus/api#1302]
## Steps to Reproduce

This happens in latest develop branch and also in direcus demo

Create `page` and `labels` collections
Add Checkbox relational in page m2m with labels collection

Check [screenrecording ](https://drive.google.com/file/d/1r0pAk7jchF0bLmaWY7rQjdHoOKivgWwD/view?usp=sharing) for the additional steps to reproduce. Too complex to describe in text.

## Technical Details

- Device: Desktop
- OS: Win 10  10.0.18362.145
- Web Server: Apache/2.4.29
- PHP Version: PHP 7.1.30
- Database: 10.2.26
- Install Method: develop branch commit 8a1187ff0b3559ab7281c4990d5329d47d8835dd
- Directus App: App develop branch commit [2107f04d9984c6efa5577775bd12f869ed1270a4](https://github.com/directus/app/commit/2107f04d9984c6efa5577775bd12f869ed1270a4)

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1307
