### ISSUE TITLE
Session timeouts intrupting work

### ISSUE THREAD

**Issue by gurumark** [directus/api#1306]
Hi,
Thanks for the project! It's been working great.

One big issue I have found is the session timeouts. It is constantly logging me out of the app. I could not find any configuration option. The backend "Auto Sign out" is  set to 95 minutes still it is useless. I think it has not been implemented yet.

I read the related issues and there is a concern about the security. I just want to remind you guys that security without usability is useless. At this point, if someone writing a text directly in the app, there is huge risk of loosing data since there is no autosave option. I have tried firefox session alive extension. No help!!

Anyways, I am willing to change the hardcoded 5 minutes period someone said in an issue and have less security.

Please let me know how I can do that.
Thanks

**Comment by rijkvanzanten** [comment]
Duplicate of https://github.com/directus/app/issues/2029
