### ISSUE TITLE
Checkbox-relational field issue when unchecking value

### ISSUE THREAD

**Issue by JbalTero** [directus/api#1308]
[Screenrecording](https://drive.google.com/file/d/10hxKKvr1sg3A3RF3ErfAMQKK51FJfMal/view?usp=sharing)

## Technical Details

- Using Directus Demo
- Device: Desktop
- OS: Win 10  10.0.18362.145
- Web Server: Apache/2.4.29
- PHP Version: PHP 7.1.30
- Database: 10.2.26
- Install Method: develop branch commit 8a1187ff0b3559ab7281c4990d5329d47d8835dd
- Directus App: App develop branch commit [2107f04d9984c6efa5577775bd12f869ed1270a4](https://github.com/directus/app/commit/2107f04d9984c6efa5577775bd12f869ed1270a4)

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1308
