### ISSUE TITLE
Nestd m2o/o2m/m2m issue with updating

### ISSUE THREAD

**Issue by JbalTero** [directus/api#1310]
[Screenrecording of what happened](https://drive.google.com/file/d/1EwKLBrO5_v64IQZkS-v1lXr92-4lnqA_/view?usp=sharing)

## Steps to Reproduce

Artist collection

![image](https://user-images.githubusercontent.com/3615746/65572559-03e86e80-df9b-11e9-9064-f40b09f6531d.png)

Artwork collection

![image](https://user-images.githubusercontent.com/3615746/65572580-1662a800-df9b-11e9-84e4-a33c11e1947a.png)

Events collection

![image](https://user-images.githubusercontent.com/3615746/65572603-267a8780-df9b-11e9-80ce-324838d1678a.png)

## Technical Details

- Using Directus Demo
- Device: Desktop
- OS: Win 10  10.0.18362.145
- Web Server: Apache/2.4.29
- PHP Version: PHP 7.1.30
- Database: 10.2.26
- Install Method: develop branch commit 8a1187ff0b3559ab7281c4990d5329d47d8835dd
- Directus App: App develop branch commit [2107f04d9984c6efa5577775bd12f869ed1270a4](https://github.com/directus/app/commit/2107f04d9984c6efa5577775bd12f869ed1270a4)

**Comment by bjgajjar** [comment]
@JbalTero - Not able to replicate in the latest develop branch. 
You can check [here](https://drive.google.com/file/d/1DWKNv_73Dj1QHhnUlDbxGoCNvS2Tg58a/view?usp=sharing)

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1320
