### ISSUE TITLE
System Information for Debugging

### ISSUE THREAD

**Issue by benhaynes** [directus/api#1315]
We have a separate ticket for Installation Requirements here: https://github.com/directus/app/issues/860

But I propose we add another way to get all your system information in one place. This would help users give us all the info we need to debug issues on an easy to _copy_ page. We'd need an API endpoint to return all of this, but it should be available in the App Settings. Below is an example of what kind of information it could include:

```
Server: Apache 2

PHP Version: 7.2
* pdo: Enabled
* mysql: Enabled
* cURL: Enabled
* gd: Enabled
* fileinfo: Enabled
* mbstring: Enabled
* xml: Enabled

Database Type: MySQL
Database Version: 5.7
Database Connection: Success

Directus App: 7.6.1
Directus API: 2.2.0
Current Migration: XXXXXXXXXX
Install Type: Docker
Mode: Development
Project: _
Ping: 560ms
Ownership: www-data
Root: /etc/www/var/directus

Current User Role: Admin

Storage: Local
Storage Path: /etc/www/var/public/uploads
* /logs: Writable (775)
* /public/uploads: Writable (775)

Logs:
[print the most recent directus error logs here]
```

**Comment by JbalTero** [comment]
@benhaynes I suggest to include a boolean to determine if there are any plugins/hooks/extensions enabled. Often times I stumbled into issues that are actually caused by my own.

**Comment by benhaynes** [comment]
Ahh, good point! It would be great to include as much info about extensions as possible without making the data too "sensitive" (so it can still be posted publicly in GitHub).

**Comment by hemratna** [comment]
Ref #1225

**Comment by benhaynes** [comment]
Haha, I knew we had one already... I looked for five minutes and didn't find it, not sure why. Thanks Hem!

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
