### ISSUE TITLE
Authentication token issue after upgrade to 2.6.0

### ISSUE THREAD

**Issue by yarick2000** [directus/api#1316]
# Bug Report

## Steps to Reproduce
1. Setup 2.5.0 API/7.10 app with the following authentication configuration to your project:
        'secret_key' => 'SL4GRCccZfAIHpApiAD1MbLUWzQkROKX',
        'public_key' => '78333833-86d7-4604-b3d7-da0806c95910'
2. Create admin user admin@example.com with 'password' as a password.
4. Login and ensure that everything ok.
5. Upgrade your API to 2.6.0 and App to 7.11
Try to login, you will see the server error screen
If you will roll back (just code) to 2.5/7.10 you will be able to login again.

## Expected Behavior
Application should load normally

## Actual Behavior
Application fails with authentication errors
## Other Context & Screenshots

Hi, it seems like after upgrade to the latest API version some secret key/public key combinations stopped to work. I've 2 projects with 2 different set of keys - after upgrade one of them still working, another fails if I'm trying login to the App. If I'm rolling back to the previous version (I mean just code, no DB touch), things starting to work again. The problems seems in decode() method of Firebase\JWT class - for some reason static::verify call returns false instead of true for API 2.6.0. Probably something wrong with hash_equals method...
![image](https://user-images.githubusercontent.com/13006578/65646420-0cf03480-dfc9-11e9-9a43-d99ff0a4e13d.png)

UPDATE 1:
Here a parameters for the functions that are on the screenshot for 2.6.0:
hash_hmac() function params
algorithm = SHA256
msg = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTY5NDU1MDE2LCJ0eXBlIjoiYXV0aCIsImtleSI6Ijc4MzMzODMzLTg2ZDctNDYwNC1iM2Q3LWRhMDgwNmM5NTkxMCIsInByb2plY3QiOiJjYXNpbm8ifQ
key = "SL4GRCccZfAIHpApiAD1MbLUWzQkROKX"
hash_hmac() function result= "���d3�C�H�͚cB��Ök�����8�Q�'"

hash_equals() function params
hash = "���d3�C�H�͚cB��Ök�����8�Q�'"
signature = "gk�[.��35YC�l]dT��e�b�j�;^��"

For 2.5.0 parameters are following:
hash_hmac() function params
algorithm = SHA256
msg = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTY5NDU1NDc3LCJ0eXBlIjoiYXV0aCIsImtleSI6Ijc4MzMzODMzLTg2ZDctNDYwNC1iM2Q3LWRhMDgwNmM5NTkxMCIsInByb2plY3QiOiJjYXNpbm8ifQ
key = "SL4GRCccZfAIHpApiAD1MbLUWzQkROKX"
hash_hmac() function result = "�Ȯv�r�1�Q%��~��XXJ���S�� ��R"

hash_equals() function params:
signature = "�Ȯv�r�1�Q%��~��XXJ���S�� ��R"
hash = "�Ȯv�r�1�Q%��~��XXJ���S�� ��R"

As you can see values for hash and signature are different between different versions of API. I'm not sure that this is a reason of the problem, but may be it's worth to look into it...

![image](https://user-images.githubusercontent.com/13006578/65646930-c4397b00-dfca-11e9-8122-f26d5e73b93c.png)

UPDATE 2:
It seems like I've figured out what's the problem:
The only difference between old a new version of API in scope of authentication is within the following function:
    v.2.6.0:
    public function getSecretKey($project = '_')
    {
        if ($project) {
            $config = get_project_config($project);
            return $config->get('auth.secret_key');
        }
        return $this->secretKey;
    }

  v.2.5.0:
    public function getSecretKey($project = NULL)
    {
        if ($project) {
            $config = get_project_config($project);
            return $config->get('auth.secret_key');
        }
        return $this->secretKey;
    }

The problem is that getSecretKey was never called with parameter, though it should, and so in case if there are more than one projects, after this fix it will always use the secret key of the default one, instead of taking the appropriate one, and so signature/hash are incorrectly generated.

So you guys need to fix the call to that function and add a parameter there, I think there is only one place where it's used.  I think this is also a reason why the night build project doesn't work on your demo site now.

## Technical Details

- Device: Desktop
- OS:  Windows 10.1803 with Ubuntu 16.04 LWS
- Web Server: NGINX
- PHP Version:  7.3.8
- Database:  MySQL 5.7.27
- Install Method: cloned `build` branch

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1326
