### ISSUE TITLE
Bug with datetime_created and datetime_updated interfaces

### ISSUE THREAD

**Issue by avonian** [directus/api#1321]
The datetime_created and datetime_updated interfaces are not behavior as expected.

It appears that when either interface is 'required' the user receives an error during record creation, saying the datetime_created (or datetime_updated) field can't be blank. If you turn off 'required' then the record saves, but the timestamps remain null.

This happens on both my local instance as well as the demo instance at https://directus.app.

Also I imagine that ideally, the user should not be able to decide whether these interfaces are required or not (since if the field exists the assumption is it should always be set).

**Comment by bjgajjar** [comment]
> It appears that when either interface is 'required' the user receives an error during record creation, saying the datetime_created (or datetime_updated) field can't be blank.

https://github.com/directus/api/pull/1322 will resolve this issue.

> If you turn off 'required' then the record saves, but the timestamps remain null.

Can you please make sure that you have a single `Date Created` field?  As it is working as expected for a single field and the case which you have mentioned is only occurring if you have a multiple `Date Created` field. In real-world its not necessary to have a multiple `Date Created` field. So just confirm that do you have a single/multiple field?

**Comment by avonian** [comment]
I do have a single date created field (deleted the default 'created on' field) and still experiencing the same behavior.

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1322

**Comment by avonian** [comment]
Thank you @bjgajjar :)
