### ISSUE TITLE
Expanding SSO to use AWS Cognito

### ISSUE THREAD

**Issue by SnowCommerceBrand** [directus/api#1324]
Cognito provides lots of support in connecting to many other identity providers "Users can sign in through social identity providers such as Google, Facebook, and Amazon, and through enterprise identity providers such as Microsoft Active Directory via SAML."

SAML and Active Directory Support will help expand Directus into larger organizations and also include AWS's SSO using Microsoft Active Directory via SAML or even AWS Single Sign-On (https://aws.amazon.com/single-sign-on/) as a connection using SAML.

Amazon Cognito supports multi-factor authentication and encryption of data-at-rest and in-transit. Amazon Cognito is HIPAA eligible and PCI DSS, SOC, ISO/IEC 27001, ISO/IEC 27017, ISO/IEC 27018, and ISO 9001 compliant.

Cognito is affordable and possibly free for small enough organizations. Folks hosting on AWS I think it would help organizations who already have adopted Cogntio. 

Found a Provider for oauth2-cognito that might be able to be used. Have not tested anything but looks like it might be a pretty easy drop in. (Leverages the league/oauth2-client ) https://github.com/CakeDC/oauth2-cognito

Maybe can be used here with the other providers. https://github.com/directus/api/tree/master/public/extensions/core/auth

**Reference:** https://aws.amazon.com/cognito/

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
