### ISSUE TITLE
"Undefined index" message when saving collection with divider

### ISSUE THREAD

**Issue by markus-mnm** [directus/api#1330]
# Bug Report

I could only reproduce this in our installations because of set error reporting is set differently on directus.app (probably 'app.env' production mode)

When saving a collection with a  divider called e.g. separator4, the API returns warnings like:

```
<b>Notice</b>:  Undefined index: separator4 in <b>/var/www/html/src/core/Directus/Services/ItemsService.php</b> on line <b>176</b><br />
```

I am considering turning off the notices by patching web.php, to show all messages apart from NOTICE, but I found that sometimes NOTICE messages are useful and it also seems to be the recommended setting to include notice when looking at the php.ini production defaults : `Production Value: E_ALL & ~E_DEPRECATED & ~E_STRICT` 

## Steps to Reproduce
1. Create a new collection and add a separator (or use https://github.com/markus-mnm/directus-demo-article-schema):
2. Create a new item in the collection an save and reopen the new item 
3. Open the developer tools of your browser and go to the network tab
4. Update the item and save
5. In case error report is not turned off, you will see an api error message in the app
5. Go to the network tab and find the PATCH or POST See error
```
<b>Notice</b>:  Undefined index: separator4 in <b>/var/www/html/src/core/Directus/Services/ItemsService.php</b> on line <b>176</b><br />
```

(the actual save was successful)

## Expected Behavior

There is no api error and no notice message when saving items on collections with dividers

## Actual Behavior

There is an api error when saving items on collections with dividers

## Other Context & Screenshots

On on latest API  develop branch 

A pull request is following in a bit.

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1331
