### ISSUE TITLE
API returns error 300 when not logged in

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1333]
As per [the docs](https://docs.directus.io/api/reference.html#error-codes), there's a difference in errors for when you're not logged in (`0003 - Unauthorized (401)`) and when you're not allowed to read items (`0300 - Reading Items Denied (403)`).

Right now, the API returns the 300 when you're not authenticated. 

Opening https://demo-api.directus.app/_/items/movies in the browser (with no access token or cookie) will return a `300` error. This should be error `3`

**Comment by bjgajjar** [comment]
@rijkvanzanten - We had introduced the `public` role. So when the user is `UnAuthorised` the system will check for the `public` access. That's why the `API` returning 300 as the `public` role doesn't have access. Thus, the `API` is working as expected.

**Comment by rijkvanzanten** [comment]
I don't think that makes sense. If a collection can't be accessed by the public group and you're not logged in, it should return the unauthorized error

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1336
