### ISSUE TITLE
Can't read items from a collection on the API

### ISSUE THREAD

**Issue by RafaelQuintanilla** [directus/api#1335]
Hi there, 

just wonderfing if im missing a step here. I'm trying to send a Get to the API but everytime i tried, i get the same response. I'm working on the following enviorment,
Windows 10
WampServer 3.1.9
Apache 2.4.39
Php 7.2.18
MySQL 5.7.26
phpMyAdmin 4.8.5
On the second post I show that I have collections to show on the database. Also that i created a static token for the admin user on the database as the documentation says. But even if I put the token or not, the response is the same.
I also attach the log error in case.

![Captura de pantalla 2019-10-02 16 58 52](https://user-images.githubusercontent.com/10001883/66077494-78d91c80-e536-11e9-98e0-42b76de59af3.png)

![Captura de pantalla 2019-10-02 16 59 13](https://user-images.githubusercontent.com/10001883/66077591-a02fe980-e536-11e9-981f-a4469a8634b8.png)

[error.2019-10-02.log](https://github.com/directus/api/files/3683115/error.2019-10-02.log)

**Comment by bjgajjar** [comment]
Hey @RafaelQuintanilla - You are executing the correct steps. "Access denied" will only throw if you are using the `token` of restricted role's user. Kindly confirm once that you are using the permission granted user's token.

If you need any help, or just have general `Directus` or `PHP` questions, we have a vibrant Slack
community that typically always has someone willing to help. You can connect in our slack [channel](https://directus.chat)

**Comment by RafaelQuintanilla** [comment]
> Hey @RafaelQuintanilla - You are executing the correct steps. "Access denied" will only throw if you are using the `token` of restricted role's user. Kindly confirm once that you are using the permission granted user's token.
> 
> If you need any help, or just have general `Directus` or `PHP` questions, we have a vibrant Slack
> community that typically always has someone willing to help. You can connect in our slack [channel](https://directus.chat)

Hi bjgajjar,
thanks for your answer.
This are the permissions in public,
![image](https://user-images.githubusercontent.com/10001883/66122962-5fc48000-e5b7-11e9-909c-8bd96dccb054.png)

This is the token i'm saving on the database and also putting on the Postman GET
![Captura de pantalla 2019-10-03 08 26 23](https://user-images.githubusercontent.com/10001883/66123079-9dc1a400-e5b7-11e9-9d1c-71ab599e5e98.png)

![Captura de pantalla 2019-10-03 08 27 51](https://user-images.githubusercontent.com/10001883/66123135-b6ca5500-e5b7-11e9-980c-da7a14e53e5b.png)


Is everything fine? or am I putting the token with a wrong format?

Thanks a lot!

**Comment by bjgajjar** [comment]
You have given permission for particular collections [User generated] but trying to fetch all collections `/collections` endpoint.

If you want to fetch all the collections publically you need to give the `all` permission to `collection` collection. 

![image](https://user-images.githubusercontent.com/19200178/66124406-e8680e00-e601-11e9-8b82-ca657ba37222.png)
