### ISSUE TITLE
Thumb creation error - local Storage

### ISSUE THREAD

**Issue by WebMago** [directus/api#1338]
**Environment:** Docker/Kubernetes
**Version:** v2-apache
**Component:** API

After uploading a file through the **BACKEND** the thumbnail appears as broke.
A directory inspection display files with 0 bytes.

```
admin@api-cms-webmago:/var/www/public/uploads/_/thumbnails/200/200/crop/good# ls -la
total 8
drwxr-xr-x 2 www-data www-data 4096 Oct  3 16:06 .
drwxr-xr-x 3 www-data www-data 4096 Oct  3 16:06 ..
-rw-r--r-- 1 www-data www-data    0 Oct  3 16:06 9a7e82ce-ae0b-594c-a95c-f296ac8b7c0f-1.png
-rw-r--r-- 1 www-data www-data    0 Oct  3 16:06 9a7e82ce-ae0b-594c-a95c-f296ac8b7c0f.png
```

**Comment by bjgajjar** [comment]
Maybe [this](https://github.com/directus/api/issues/1339#issuecomment-538337689) will help you here. :)

**Comment by bjgajjar** [comment]
This may resolve with #813. @benhaynes Thoughts?

**Comment by benhaynes** [comment]
Haha, maybe? That is beyond my skillset. @WoLfulus ... does that seem specific to Docker?

**Comment by bjgajjar** [comment]
In our new release, we have `/assets` instead of thumbnails.

Closing this issue on the reference to that. Feel free to reopen if you have this issue with the `assets` endpoint in the latest version.
