### ISSUE TITLE
Thumb path url 404 Error - local Storage

### ISSUE THREAD

**Issue by WebMago** [directus/api#1339]
**Environment:** Docker/Kubernetes
**Version:** v2-apache
**Component:** API

After uploading a file through the **BACKEND** the thumbnail appears as broke, the web browser console inspection gets an Error HTTP 404, Not Found.
Eg.
`https://api.mydomain.dev/thumbnail/_/200/200/crop/good/9a7e82ce-ae0b-594c-a95c-f296ac8b7c0f.png
`

The Original file displayed appears with the link URL:
`https://api.mydomain.dev/uploads/_/originals/9a7e82ce-ae0b-594c-a95c-f296ac8b7c0f.png`

**Comment by bjgajjar** [comment]
Hey @WebMago - It's neither replicated in local nor in dev server. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19200178/66199789-19f1df80-e6bd-11e9-8e03-cf70d2890467.gif)

Let us know the version of the `Docker` you have used.

**Comment by WebMago** [comment]
**Docker version fix:**

I used port **8000** on **proxy** and **app** services to avoid collisions with my local apache.

>`
proxy:  
    image: jwilder/nginx-proxy:alpine  
    ports:  
      - 80:80  
`
>`
app:  
    image: directus/app:v7-node  
    environment:  
          DIRECTUS_APP_URL: "http://api.webmago.me:8000/_/"  
`

To fix I stop the local apache, adjust ports on **proxy** service, remove port on the **app** environment variable.

**Kubernetes version fix:**

The storage for the **originals** and **thumbnails** has been linked to an NFS filesystem using symlinks.
The originals work after made an apache modification.
The thumbnails went unlinked from the NFS storage, this is a challenge to solve when you need to scale the replicas, the thumbnails keep on the container filesystem while is live.

**Comment by WebMago** [comment]
> Hey @WebMago - It's neither replicated in local nor in dev server.
> 
> ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19200178/66199789-19f1df80-e6bd-11e9-8e03-cf70d2890467.gif)
> 
> Let us know the version of the `Docker` you have used.

Client: Docker Engine - Community
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        6a30dfc
 Built:             Thu Aug 29 05:26:49 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.8
  Git commit:       6a30dfc
  Built:            Thu Aug 29 05:32:21 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by WebMago** [comment]
@bjgajjar 
Steps to Reproduce:

1. Create a directory path directus
2. Clone the API code into directus/api 
3. Create the docker-compose.yml as sibbling directus directory
4. Adjust to the docker-compose.yml with the enviroments to use, 
5. Link the volume MySQL to my "data" storage created for otther projects and same version MySQL `../data:/var/lib/mysql`
6. Link the API Service volume `./directus/api:/var/www`
7. Define my Storage local variables as:

# Storage
  DIRECTUS_STORAGE_ADAPTER: "local"
  DIRECTUS_STORAGE_ROOT: "public/uploads/_/originals/"
  DIRECTUS_STORAGE_ROOTURL: "/uploads/_/originals"
  DIRECTUS_STORAGE_THUMBROOT: "public/uploads/_/thumbnails"
8. Run the composer install on the OSX enviroment terminal
9. Run the command `docker-compose -f docker-compose.dev.yml up -d`
10. Run the installation command `docker-compose run api install --email your@email.com --password somepass`
11. Test the File Library

The new version of this file don't use the proxy and use **ports**; when I used ports the broken thumbs appears.
`https://github.com/directus/docker/blob/master/examples/simple/docker-compose.yaml`

**Comment by WoLfulus** [comment]
This is probably due to the mismatch of the port running inside the container (80) and the different port exposed and it can happen in any environment that has load balancer or changes the url behavior from the gateway to the webserver itself. I had a similar case, but mine was with SSL, and not ports.
The api probably detects the port 80 running in the container and api generates a wrong thumbnail url. 

@WebMago can you please check which is the thumbnail URL that the browser is requesting in network inspector? Just to confirm this is really the case. If it is, we should also support a config variable `thumb_url` to override the autodetection.

In my case as it was an http/https problem I solved by tricking api into thinking it was being served through https on its end.

**Comment by WebMago** [comment]
@WoLfulus on my local Docker environment with ports used, the path returned by the API not include the port on the response, after the port removed the thumbnail is returned and generated.

On Kubernetes with a symlink NFS storage, the upload works like a charm, the thumbnail generated appears as 0 (zero bytes) on the NFS resource with a result of HTTP 404 error code. Using the pod storage the thumbnail is generated and returned as a success.

I use for Kubernetes a GKE cluster, Ingress Nginx with SSL Let's encrypt.

**Comment by WoLfulus** [comment]
So if I understood it correctly, it confirms what I thought right?

**Comment by WebMago** [comment]
> So if I understood it correctly, it confirms what I thought right?

It is correct, are you right, the port throws the broken thumbnail in docker.

**Comment by gianniskarmas** [comment]
I think I have a relevant problem with plesk obsedian, nginx and ofcourse latest directus.
App displays thumbnails when using only apache but not when using only nginx with the recommended directives:
```
location ~/ {
	try_files $uri $uri/ /index.php?$args;
}
location ~/thumbnail {
	try_files $uri $uri/ /thumbnail/index.php?$args;
}
etc...

```

**Comment by benhaynes** [comment]
Possibly related to this? https://github.com/directus/api/issues/1341

**Comment by JbalTero** [comment]
This happened to me just recently, it was because of the thumbnails folder write permissions

**Comment by bjgajjar** [comment]
This may resolve with #813. @benhaynes  Thoughts?

**Comment by benhaynes** [comment]
Perhaps! Let's get #813 implemented and then have OP and this thread's users test to see! :)

**Comment by bjgajjar** [comment]
In our new release, we have `/assets` instead of `thumbnails`.

Closing this issue on the reference to that. Feel free to reopen if you have this issue with the `assets` endpoint in the latest version.
