### ISSUE TITLE
Disable app access for specific user roles

### ISSUE THREAD

**Issue by onlinelessons** [directus/api#1340]
# Feature Request

## What problem does this feature solve?
I have a user role "frontend users" which should not be able to access the directus app

## How do you think this should be implemented?
Maybee a checkbox in user roles to disable the app access

**Comment by benhaynes** [comment]
Thanks @onlinelessons — we would add this to the API, and then can have the App support it.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
