### ISSUE TITLE
There is no way of hiding files.

### ISSUE THREAD

**Issue by edenprojectde** [directus/api#1343]
I need to be able to show files to the user he himself uploaded. This seems to be impossible to setup though.

The Frontend Website needs to be able to access the file. This can be handled trough a different group than public which has read access to the images. (This way i thought i can stop other groups from being able to see ALL files)

After that: Making a role for the Editor's i can allow and disallow using the files table, but not set it up to only use "Mine".
Any other way to realize this right now?

Also another Subissue: **If you hide the Files table in a group, the menu to log out will be missing on login to the account (at least with an Avatar being uploaded). The public group has access to the file though.** 
Feel free to make another issue out of this, but i think this is linked to the same problem.

Using Directus v7.11
Apache2 for the App
Nginx for the API
Host System is Ubuntu 18.04.1 LTS

Edit:
Im assuming i could set up a filter like this: ["uploaded_by":?] but i can't find the current logged in user as a variable in the docs.

**Comment by bjgajjar** [comment]
@benhaynes - It seems like there must be some confusion here.

`directus_files` table has a `uploaded_by` field with type `integer` and `user` interface.
Thus, when the user tries to fetch the object of `uploaded_by` it will return the same object which `user` interface will return.

Kindly help me if I misinterpret something.

**Comment by bjgajjar** [comment]
Whoops! Forgot that. Thanks for pointing out.

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1346
