### ISSUE TITLE
Env variable for redis password

### ISSUE THREAD

**Issue by nachogarcia** [directus/api#1345]
# Feature Request
Have a environment variable for redis password

## What problem does this feature solve?
Connect to redis with a password

## How do you think this should be implemented?
Create a variable 'password' under the pool adapter 'redis'

## Would you be willing to work on this?
I've just tried to do it, but since I don't have that many knowledge in php and this project I couldn't make it work.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
