### ISSUE TITLE
Project not considered for oauth callback url

### ISSUE THREAD

**Issue by zyclonite** [directus/api#1348]
# Bug Report

## Steps to Reproduce

1. create two project configs
2. configure both with one oauth provider (can be the same but different callback urls - matching the project urls)
3. login with the "non default /_/" project
4. the ui calls the correct sso url e.g. `/<project>/auth/sso/google` but gets a redirect to the oauth provider with the wrong project callback `/_/auth/sso/google/callback` as redirect url

## Expected Behavior

login to the project selected before initiating the oauth flow

## Actual Behavior

always logged in the default project independently what project is selected in the ui

## Technical Details

- Install Method: docker container for app and api in version 2.6.0

**Comment by benhaynes** [comment]
Thanks @zyclonite — I believe this will be resolved with the upcoming Auth Flow refactor, but I'm pinging @rijkvanzanten and @bjgajjar to make sure. 👍

**Comment by bjgajjar** [comment]
@benhaynes  - No it'll not be resolved in a new flow.

Fixed in https://github.com/directus/api/pull/1353
