### ISSUE TITLE
Add Google Cloud Storage as a storage adapter

### ISSUE THREAD

**Issue by medteck** [directus/api#1349]
I noticed FlySystem is used here for FileSystem abstraction. And Directus limits storage providers to S3, aliyun-oss, and local only. But there is a simple way to add Google Cloud Storage. I'm using it right now and it's working well.

**Comment by benhaynes** [comment]
I believe this PR will need to be on the `api` repo... but we'll see what @bjgajjar says. Thanks @medteck!

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
