### ISSUE TITLE
Params: add lang

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#135]
> `lang` is a CSV of languages that should be returned with the response. This parameter can only be used when a Translation field has been included in the collection. This parameter supports the wildcard (`*`) to return all translations.

**Comment by WellingGuzman** [comment]
Will `lang` support filtering language for child/related items? If so:

- Is the translation field type unique per collection?
- How the `lang` CSV will work?
  - A list of language for the parent item?
  - A dot-notation approach for its child? _if we are going to go this path._
- Beside working as a `O2M`, will `TRANSLATION` works differently in any way?
- When filtering by one language, should translation field be a object instead of an array of one element?

Ping @rijkvanzanten + @benhaynes

**Comment by benhaynes** [comment]
I feel like we'll need to treat languages globally so the keys/ids/options are consistent. But if the requested children don't have the correct language data then I guess they would return the fallback language. We should have the languages used int he response, so you know if the API had to use a fallback language instead.

The other questions I will defer to @rijkvanzanten!

**Comment by WellingGuzman** [comment]
> But if the requested children don't have the correct language data then I guess they would return the fallback language.

I believe this is wrong, if you are requesting data based on a language, you shouldn't get any fallback language (_unless that's a configuration_).

> We should have the languages used int he response, so you know if the API had to use a fallback language instead.

The response will always have the language field with its language code, so you will know the language the item is related to.

**Comment by benhaynes** [comment]
Yeah, you're right. We should keep the languages consistent... `NULL` if it's not there.

**Comment by rijkvanzanten** [comment]
How can we configure those fallback languages? For example, when querying Mexican Spanish, I want to fallback to Spanish-Spanish, but I don't want to fallback to Spanish-Spanish when querying American-English.

**Comment by WellingGuzman** [comment]
To make something like this works, the interface should have a option to add fallback languages based on the language code.

The languages collection doesn't have a standard for its reference code, it can anything, Ex. a number,  the language name or any ISO 639 format.
