### ISSUE TITLE
Support for redis cluster

### ISSUE THREAD

**Issue by nachogarcia** [directus/api#1351]
# Feature Request
Add support for a redis cluster. Might be worth implement as the same time as https://github.com/directus/api/issues/1345
## What problem does this feature solve?
Allow to have a cluster of redis
## How do you think this should be implemented?
Changing the line https://github.com/directus/api/blob/8980182425d3d657d7e365123207b336b9864764/src/core/Directus/Application/CoreServicesProvider.php#L995 for a `new RedisCluster`
## Would you be willing to work on this?
Didn't make a PR with this because I guess that might break current Redis. Don't know if you want to have a new env variable or there is another way. I don't know that much PHP.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
