### ISSUE TITLE
Missing logout endpoint?

### ISSUE THREAD

**Issue by jreid06** [directus/api#1358]
# Bug Report

This is all happening on my local machine

The bug i'm currently facing is i can't logout using the SDK. I get a 404 not found error when trying to hit the `http://something.com/_/auth/logout` endpoint. 

file `/src/core/Directus/Services/AuthService.php` looks like its missing a logout method?
` public function __invoke(Application $app)
    {
        $app->post('/authenticate', [$this, 'authenticate']);
        $app->post('/password/request', [$this, 'forgotPassword']);
        $app->get('/password/reset/{token}', [$this, 'resetPassword']);
        $app->post('/refresh', [$this, 'refresh']);
        $app->get('/sso', [$this, 'listSsoAuthServices']);
        $app->post('/sso/access_token', [$this, 'ssoAccessToken']);
        $app->get('/sso/{service}', [$this, 'ssoService']);
        $app->post('/sso/{service}', [$this, 'ssoAuthenticate']);
        $app->get('/sso/{service}/callback', [$this, 'ssoServiceCallback']);
    }`

no logout endpoint has been added.

if thats not the case then how do you logout using the SDK as logout & reset methods both return a 404 not found error.

## Expected Behavior

logged out successfully with a 200 response from the endpoint 

## Actual Behavior
404 error from server

## Other Context & Screenshots

![Screenshot 2019-10-19 at 15 23 37](https://user-images.githubusercontent.com/19251469/67146581-873c6d80-f284-11e9-8605-4c946cdf1250.png)

## Technical Details

- Device: [MacbookPro 2015]
- Web Server: [Apache 2.4.33]
- PHP Version: [7.2.0]
- Database: [MySQL 8.0.12]
- Install Method: cloned `master` branch directus suite

**Comment by benhaynes** [comment]
I believe we just added a `logout` endpoint as part of our new (upcoming) auth flow. It should be in the next release! All this look good @bjgajjar @rijkvanzanten ?

**Comment by bjgajjar** [comment]
@benhaynes - Yes. We included `logout` in our new Auth flow.

**Comment by sebj54** [comment]
What are the consequences of this? The session remains active? 

No way to logout with API with the current version?

I am facing this error with the JS SDK (last version too)

**Comment by rijkvanzanten** [comment]
I've written a little doc outlining the problems / adjustments: https://github.com/directus/api/wiki/Session-Auth-Flow

**Comment by sebj54** [comment]
I just downgraded sdk-js to ^5.0.0 (based on your advice: https://github.com/directus/sdk-js/issues/113#issuecomment-540609897) and it is working fine now.

Thanks for the clarification anyway!
