### ISSUE TITLE
API returns Error 215 for some collections

### ISSUE THREAD

**Issue by stein99** [directus/api#1366]
# Bug Report

Hello all,
I am using the directus api to access some collection, this collection has a relations "Many to one"  with other collections. I am able to filter collection members thrue the all relationships with the some exceptions.
Error:{"error":{"code":215,"message":"Unable to access \"code\" related data"}}
I already spent a lot of time looking the diferences between the relationships that works  and the relationships  that dont works, and the only difference that i find is that first does not have status and the other have.

Query that works:
http://localhost:7000/_/items/labels?fields=*.*&filter[status][eq]=published&filter[languages.code][eq]=en&filter[channels.code][eq]=mvb
Query that does not works:
http://localhost:7000/_/items/labels?fields=*.*&filter[status][eq]=published&filter[languages.code][eq]=en&filter[channels.code][eq]=mvb&filter[pages.code][eq]=unbilled

All the collections have permission in public role to "all"
Directus version: 7.0.18

Did anyone have this problem?

**Comment by benhaynes** [comment]
Hey @stein99 — is there a reason you're on such an old version? `7.0.18` is from February.

**Comment by stein99** [comment]
Hi Ben,

Iam using docker and in my compose file the configuration is 
" api:image: directus/api:latest" i assume that the version that i have is the last.

**Comment by stein99** [comment]
Hi Ben,

You are 100% right i am using an older version, i didn't know i have to do the "docker-compose pull" to update the images versions.
Sorry to boring you.

**Comment by benhaynes** [comment]
No bother at all! Mistakes like these are just as much an issue with our organization and docs... glad it worked out!

@WoLfulus — any way we can make this more clear to Docker users?
