### ISSUE TITLE
Nested Filtering (eg: by Status)

### ISSUE THREAD

**Issue by hakkurishian** [directus/api#1371]
# Feature Request

Filter nested fields when retrieving from the API.

Assume a collection author and a collection books nested like:

```
[
   {
      "id":1,
      "name":"Author 1",
      "status":"published",
      "books":[
         {
            "id":1,
            "title":"Book 1",
            "status":"published"
         },
         {
            "id":2,
            "title":"Book 2",
            "status":"draft"
         }
      ]
   },
   {
      "id":2,
      "name":"Author 2",
      "status":"published",
      "books":[
         {
            "id":3,
            "title":"Book 3",
            "status":"draft"
         },
         {
            "id":4,
            "title":"Book 4",
            "status":"draft"
         }
      ]
   }
]
```

In order to view a list of all (published) authors and their respective **published** books I would try a query like:

items/author/status=published&filter[books.status]=published

## What problem does this feature solve?

The above query returns a list of all published authors which **have** published book which is in the case above:

```
[
   {
      "id":1,
      "name":"Author 1",
      "status":"published",
      "books":[
         {
            "id":1,
            "title":"Book 1",
            "status":"published"
         },
         {
            "id":2,
            "title":"Book 2",
            "status":"draft"
         }
      ]
   }
]
``` 

with the requirements above I'd rather expect the following result: 

```
[
   {
      "id":1,
      "name":"Author 1",
      "status":"published",
      "books":[
         {
            "id":1,
            "title":"Book 1",
            "status":"published"
         }
      ]
   }
]
``` 

## How do you think this should be implemented?

Regarding the API I propose a syntax like:

field.filter[nestedField(s)]=value

in my case resulting in 

books.filter[status]=published

## Would you be willing to work on this?

if it makes sense I could contribute to this.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by prikr** [comment]
@benhaynes or @rijkvanzanten Is this feature already being implemented in the newer version? Need this very badly.

**Comment by rijkvanzanten** [comment]
@prikr It'll be added to the alpha of v9 either later this week, or next (keep an eye on https://github.com/directus/next/issues/178)

**Comment by prikr** [comment]
@rijkvanzanten Cool, thanks for the update. Won't be using it yet, because I'm already using Directus in production.
