### ISSUE TITLE
Filter by Empty/Length Relational M2M

### ISSUE THREAD

**Issue by FRSgit** [directus/api#1372]
# Feature Request

Add possibility to filter M2M fields by field metadata (or relation array's length at least).

## What problem does this feature solve?

My use case is: I want to filter out items, which does not have anything attached to M2M field - now it's not possible.

## How do you think this should be implemented?

There are few possibilities:

- make `empty` filter to cover case of empty M2M relation,
- create new filter e.g. `length` which will check for M2M relation's length,
- create new filter `meta` which will allow to filter out by relations metadata (e.g. length).

## Would you be willing to work on this?

Maybe, but unfortunately I have no idea what going on in Directus API codebase & I'm not sure which one of 3 solutions above should be used.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
