### ISSUE TITLE
Error when adding a User via Role - Duplicate key for collection "directus_user_roles"

### ISSUE THREAD

**Issue by eudora-fabia** [directus/api#1376]
Error when adding a User via Role - Duplicate key for collection "directus_user_roles"

## Steps to Reproduce

- Add a new role
- Add a new user via the newly created role
- Watch the [screenrecording for more](https://drive.google.com/file/d/1ic6_p8rKrJDqbIg6RH_MSfhGwSosKM76/view?usp=sharing)

## Technical Details

- Using Directus Demo

**Comment by bjgajjar** [comment]
We removed the `directus_user_roles` table in our latest release. Closing this issue on ref. of that.
