### ISSUE TITLE
uploading files in the admin - is throwing this message :  checksum: This value should not be blank

### ISSUE THREAD

**Issue by joejanho** [directus/api#1377]
# Bug Report

## Steps to Reproduce

1. Go to admin and trying to upload any file
2. Getting the checksum: This value should not be blank

## Expected Behavior
file uploaded
## Actual Behavior
no file uploaded 

## Technical Details

- Device: Desktop
- OS: MacOS
- Web Server: Apache (bluehost hosting)
- PHP Version: 7.3.10
- Database: [eg: MySQL 8.0.12]
- Install Method: cloned `master` branch

**Comment by bjgajjar** [comment]
Hey @joejanho,

I tried to replicate this issue in develop branch as well master branch (Live demo). But not able to replicate it. You can check it from the provided screen recording.


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19200178/68110167-6295f600-ff12-11e9-9372-8cb5f784d8aa.gif)

**Comment by joejanho** [comment]
@bjgajjar  thanks for this but can you let me know what environment you are using 
Also is there a way to make the checksum optional so at least i can continue working 
thanks

**Comment by bjgajjar** [comment]
@joejanho - I tried in `development` as well as `production`; both of them provided the desired response. IMO, we should not make the checksum optional. Let's connect to the slack channel for further discussion of your issue.

**Comment by urvashithakar** [comment]
By connecting @joejanho in the slack channel, We solved this issue. I think some changes in the database performed directly by him.

@bjgajjar, You can close this issue.
