### ISSUE TITLE
Allow setting a folder when uploading fields

### ISSUE THREAD

**Issue by dev7ch** [directus/api#1378]
# Bug Report

- i can create new virtual folders as expected
- i am not able to set `folder` on POST submit for image upload
- i can not see virtual folder in the filemanager in Admin UI

... same behaving for `metadata`

## Steps to Reproduce
- POST an image to `api.com/_/files`

```
{
  "folder": [1],
  "location": "sdfsdfsdf",
  "tags": ["dsfsdfsd", "assadf"],
  "filename": "asdfsddf.png",
  "data": "<bse-64-data>"
}
```

Getting 500, error code null

I think its maybe missing here?
 https://github.com/directus/api/blob/644039f708587ed5f75f530cce93ee0cbaf1ea53/src/core/Directus/Filesystem/Files.php#L89

## Expected Behavior
Add the folder ID to file

## Actual Behavior

If array error message if not array is show, string stay null, array produces uncovered 500

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Web Server: [eg: Apache 2.4.37]
- PHP Version: [eg: 7.2.0]
- Database: [eg: MySQL 8.0.12]
- Install Method: [eg: cloned `master` branch]

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by dev7ch** [comment]
@rijkvanzanten and @itsmerhp do you thing this is a feature request?

this should be a Bug, due it is not working for metadata as well

**Comment by rijkvanzanten** [comment]
Well, folders haven't been implemented, and aren't mentioned in the docs anywhere. I know the collection and column exist in preparation of it being released, but it's expected not to work yet. Implementing support for folders is therefore a feature request.


What do you mean about the metadata? If there's something wrong with that, we can open a new issue about that

**Comment by dev7ch** [comment]
ok ok, i just tested it in the rest Client, and realized I was not able to set metadata as desired.

when i looked in the Data Transfer Object and the Filesystem "controller" (file mentioned above) it looked likes it was missing as well there, where i expected folder to be ..

if i really need this i ll tweak for me and create PR to give you a better overview abt what i thought here ..
