### ISSUE TITLE
CORS problems in global endpoints

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1379]
Global endpoints `/interfaces`, `/server/ping`, etc are having some more problems regarding CORS still. Most notably: 

* Should return `Access-Control-Allow-Credentials: true` header in (preflight) requests
* Should allow `X-Directus-Project` header in (preflight) requests

**Comment by bjgajjar** [comment]
@rijkvanzanten  - Can we close this too?

**Comment by rijkvanzanten** [comment]
Yup!
