### ISSUE TITLE
stored relations result in db-error

### ISSUE THREAD

**Issue by Wendenburg** [directus/api#1384]
# Bug Report

## Steps to Reproduce

1. Create collection with a text input, add some items
2. Create an other collection with an many to one relation to the first collection
2. Delete this collections
3. Create first collection (same name) again and try to add item 

## Expected Behavior
no issues expected, items should be added

## Actual Behavior
a database error occurs

## Other Context & Screenshots
Seems that the relations are still stored in the table **directus_relations**, even after collections were deleted. Deleting this relations from the table solves the problem

## Technical Details

- Device: desktop, chrome latest
- OS: OSX 10.13.6
- Web Server: Apache, MAMP 5
- PHP Version: 7.3.8
- Database: MySql 5.7.2.6
- Install Method: cloned `master` branch

**Comment by itsmerhp** [comment]
@Wendenburg I have followed the mentioned steps but not able to reproduce the issue.
Can you please check [this screen recording](https://drive.google.com/file/d/1GNaCwpbOzSG-CL7a4gz6P3p6hCCNqMGP/view) and highlight that any steps are missing from my side?

**Comment by Wendenburg** [comment]
seems that is not as easy to reproduce as i thought, although i run into that several times while creating collections and relations, deleting and recreating them again. However, the relations in the DB are not deleted with the collections. So for now i will close this, until i find proper steps to reproduce...

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1386
