### ISSUE TITLE
PHP Session Cookie - SameSite Attribute

### ISSUE THREAD

**Issue by MyneLife** [directus/api#1385]
# Feature Request

## What problem does this feature solve?
Chrome started to log warnings if a website sets 3rd-party-cookies with version 77 which do not have the `SameSite` attribute explicitly set. Google plans to block any cookies with version 80 (february 2020) which didn't set this value explicitly. See this [Chromium blogpost](https://blog.chromium.org/2019/10/developers-get-ready-for-new.html) for more information. Other browser vendors announced to implement similiar behavious.
The PHP session cookie, set by the Directus API, does not have the `SameSite` attribute maintained so the current behaviour would block all web applications which access any Directus API as soon as the blocking behaviour gets released by Google.

## How do you think this should be implemented?
PHP allows to change the default params for the session cookie, see [PHP documentation](https://www.php.net/manual/de/function.session-set-cookie-params.php). The parameter should probably be set by default, maybe some custom configuration can be added to the app too which allows to set the domain explicitly.

## Would you be willing to work on this?
I don't really have time for this, sorry

**Comment by benhaynes** [comment]
Thanks @MyneLife — I believe this is a big part of what we're addressing in this next release (with a completely new auth flow). But correct me if I'm wrong @rijkvanzanten @bjgajjar

**Comment by rijkvanzanten** [comment]
Yeah. The app is going to be served by the API at all times negating the CORS issue mentioned above. Also heads up @bjgajjar, I believe the version of Slim we use doesn't support same-site

**Comment by wboehl** [comment]
Is there a temporary workaround for this? Chrome (current version 80) is now blocking cookies without the SameSite attribute. Same issue with Safari. Any ideas?

**Comment by rijkvanzanten** [comment]
Use JWTs instead of cookies by passing `mode: 'jwt'` to the /auth/authenticate endpoint
