### ISSUE TITLE
When use repeater dont get "file/image object"

### ISSUE THREAD

**Issue by acamenhas** [directus/api#1392]
Hi all,

I've a repeater in my collection "informacoes_gerais":

![img1](https://user-images.githubusercontent.com/14015712/68311304-42e50600-00a9-11ea-8d83-3531bd4bd06e.png)

a) With a input file (icon) and a text field (link):
![img2](https://user-images.githubusercontent.com/14015712/68311348-555f3f80-00a9-11ea-887b-33e5560ab764.png)

b) The app is working well like in this example:
![img3](https://user-images.githubusercontent.com/14015712/68311486-86d80b00-00a9-11ea-98f8-ba41992d3ce0.png)

c) The problem is when i need to grab the collection via API, the "redes_sociais" repeater dont show the image object of the input file, just an id. There is an example of Directus API response:
![img4](https://user-images.githubusercontent.com/14015712/68312151-85f3a900-00aa-11ea-8bf1-e1cf4292279b.png)

If tryed to call:
`items/informacoes_gerais?fields=*.*`

With no success.
Can anyone give me a hint?

Thank you

**Comment by itsmerhp** [comment]
Hi @acamenhas 
Please check in the web application, in edit record two APIs are called:
1) To get record details : items/COLLECTION_NAME/RECORD_ID?fields=FIELD_NAMES
2) To get file details : files/FILE_ID
Therefore, you can follow the same process to get file details in your case.

**Comment by acamenhas** [comment]
Hi @itsmerhp thank you for your reply!
I'm using the first method that you describe, with no success (reason why i opened this issue).
If you notice on the console print screen above, i receive just the id of file data.
We shouldnt receive all the file data info (url, thumb, type,...)?
I can get the remain info making another API call, but if i could avoid that, my web app will appreciate :)

**Comment by urvashithakar** [comment]
Hello @acamenhas 
IMO it is not possible in current directus structure. You have to call another API(files/{id}) to get file info.

**Comment by acamenhas** [comment]
Ok @urvashithakar thank you.
Closing...

**Comment by benhaynes** [comment]
@acamenhas — we're working on a relational repeater now, that will be able to fetch all the data in one single call.

**Comment by acamenhas** [comment]
@benhaynes - that's it what I'm looking for!!!
When you have news about it please notify me.
Thanks
