### ISSUE TITLE
Some environment variables are not working (eg. DIRECTUS_STORAGE_THUMB_ROOT)

### ISSUE THREAD

**Issue by nigimaxx** [directus/api#1393]
# Bug Report

## Steps to Reproduce

The environment variables `DIRECTUS_STORAGE_THUMB_ROOT`, `DIRECTUS_STORAGE_ROOT_URL`, ... don't work.

As far as I can tell, the problem seems to be a combination of the `explode` function
in the `from_map` method of the `Context` class (`/Users/niklasmack/projects/directus/api/src/core/Directus/Config/Context.php:74`) 
and configuration in the `Schema` class (`/Users/niklasmack/projects/directus/api/src/core/Directus/Config/Schema/Schema.php`).

The env keys are split (exploded) at `_`, but there are config keys with an underscore (eg. `root_url`).

**Comment by bjgajjar** [comment]
@WoLfulus - Can you help here? Maybe this is the `Docker` related issue. Though we need to implement the changes in API only - but it'll be easy for you to resolve it as you are aware of the `Docker` configuration.

**Comment by WoLfulus** [comment]
we have a gotcha on the env variables. still trying to figure out a way solve this:

basically the variables that contains "_" gets it stripped, so in your case the variables are

DIRECTUS_STORAGE_THUMBROOT and DIRECTUS_STORAGE_ROOTURL

sorry this is not properly documented right now.

**Comment by nigimaxx** [comment]
Thanks for the quick response.
