### ISSUE TITLE
/server/ping should ignore project

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1395]
The API currently returns a 500 server error with

```
code: 22
message: "Unknown project: _"
```

Seeing that the /server/ping endpoint will only verify that the server is reachable, I think it should ignore the `X-Directus-Project` header completely.

(PS: This should probably be a 404 instead of a 503 error too)

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1416

**Comment by rijkvanzanten** [comment]
See https://github.com/directus/api/issues/1395

It's still trying to use the current project in it's usage of CORSMiddleware
