### ISSUE TITLE
Don't rely on `_` when project is unknown 

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1396]
Currently, the api still tends to default to `_` when project key is unknown, we should make sure that it doesn't, seeing that we can't know for sure it exists:

https://github.com/directus/api/blob/483e065d00ed307f3f25d06ff1aa924633fe9fae/src/core/Directus/Authentication/Provider.php#L612

**Comment by bjgajjar** [comment]
Resolved in `new_projects_flow`.
