### ISSUE TITLE
500s on create / update

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1397]
in `develop`

It's trying to use this function:

https://github.com/directus/api/blob/483e065d00ed307f3f25d06ff1aa924633fe9fae/src/core/Directus/Util/DateTimeUtils.php#L110-L114

`get_project_config()` requires the first parameter to be the key of a project.

Full error:

```
[2019-11-06 15:40:28] api[api].ERROR: ArgumentCountError: Too few arguments to function Directus\get_project_config(), 0 passed in /var/www/html/src/core/Directus/Util/DateTimeUtils.php on line 112 and at least 1 expected in /var/www/html/src/helpers/app.php:70
```

<details>
  <summary>Stack trace</summary>
  <pre>
    Stack trace:
#0 /var/www/html/src/core/Directus/Util/DateTimeUtils.php(112): Directus\get_project_config
#1 /var/www/html/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(324): Directus\Util\DateTimeUtils::nowInTimezone
#2 /var/www/html/src/core/Directus/Services/TablesService.php(876): Directus\Database\TableGateway\RelationalTableGateway->manageRecordUpdate
#3 /var/www/html/src/core/Directus/Services/TablesService.php(820): Directus\Services\TablesService->updateFieldInfo
#4 /var/www/html/src/core/Directus/Services/TablesService.php(796): Directus\Services\TablesService->addOrUpdateFieldInfo
#5 /var/www/html/src/core/Directus/Services/TablesService.php(384): Directus\Services\TablesService->addColumnsInfo
#6 /var/www/html/src/endpoints/Collections.php(43): Directus\Services\TablesService->createTable
#7 [internal function]: Directus\Api\Routes\Collections->create
#8 /var/www/html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#9 /var/www/html/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#10 /var/www/html/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#11 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#12 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#13 [internal function]: Slim\DeferredCallable->__invoke
#14 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#15 /var/www/html/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(121): Slim\Route->Slim\{closure}
#16 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#17 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#18 [internal function]: Slim\DeferredCallable->__invoke
#19 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#20 /var/www/html/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#21 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#22 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#23 [internal function]: Slim\DeferredCallable->__invoke
#24 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#25 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#26 /var/www/html/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#27 /var/www/html/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#28 /var/www/html/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#29 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#30 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#31 [internal function]: Slim\DeferredCallable->__invoke
#32 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#33 /var/www/html/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#34 /var/www/html/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#35 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#36 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#37 [internal function]: Slim\DeferredCallable->__invoke
#38 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#39 /var/www/html/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#40 [internal function]: RKA\Middleware\IpAddress->__invoke
#41 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#42 [internal function]: Slim\DeferredCallable->__invoke
#43 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#44 /var/www/html/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(15): Slim\App->Slim\{closure}
#45 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
#46 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#47 [internal function]: Slim\DeferredCallable->__invoke
#48 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#49 /var/www/html/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
#50 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#51 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#52 [internal function]: Slim\DeferredCallable->__invoke
#53 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#54 /var/www/html/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
#55 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#56 /var/www/html/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#57 [internal function]: Slim\DeferredCallable->__invoke
#58 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#59 /var/www/html/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#60 /var/www/html/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#61 /var/www/html/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#62 /var/www/html/src/core/Directus/Application/Application.php(161): Slim\App->run
#63 /var/www/html/public/index.php(5): Directus\Application\Application->run [] []
    ```
  </pre>
</details>

**Comment by rijkvanzanten** [comment]
Caused by removing the default value of `$name` in `get_project_config()` in https://github.com/bjgajjar/api/commit/863861365a55f2395eea6f0dec3c937f7de1e923#diff-5be1b1c96a9f0cbb384addcc8a0afcd9R70

**Comment by bjgajjar** [comment]
Resolved in `new_projects_flow`.
