### ISSUE TITLE
Allow string type for permission status name

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#14]
See [this Gist](https://gist.github.com/rijkvanzanten/993a4dba3046e47389d30657ff0b67ad) for the new status mapping structure

**Comment by WellingGuzman** [comment]
If we have a global status mapping using string type status value and there's a collection with a numeric `status` interface but it has a empty status mapping. We cannot store the string status into the numeric field.

what should be the approach? Ignore the global status mapping when this case happens and treat field as if there were never any status in that field? if that's the case what the fallback to no having status mapping?

**Comment by rijkvanzanten** [comment]
I think status should be a string type at all times? That would solve this problem correct? Seeing we’ll provide the default status map (that is string based) we basically tell the user that is best practice.

@benhaynes

**Comment by benhaynes** [comment]
Hmm, I don't know about forcing strings... especially since that's the opposite of what we support now. We want to extend abilities, not flip them (even if this is broader). I think there are a lot of use cases where a DB schema might use an `INT` for a status... and we should work with that.

My recommendation would be to check/try the status key for the datatype and if it won't work we throw an error. That is a misconfiguration (not our fault) and they need to correct the key or datatype themselves. Smart/clear errors are the answer here IMO.

**Comment by benhaynes** [comment]
Also, I forget (my brain is fried right now), but I remember talking about doing something with `hardDelete` in status... maybe removing it and using permissions instead?? I can't remember, but wanted to add a note here so we don't forget to discuss and confirm how it will work.

**Comment by rijkvanzanten** [comment]
> Hmm, I don't know about forcing strings... especially since that's the opposite of what we support now. We want to extend abilities, not flip them (even if this is broader). I think there are a lot of use cases where a DB schema might use an INT for a status... and we should work with that.

A text-datatype can hold a numeric value, a numeric-datatype can't hold a text-based value

**Comment by rijkvanzanten** [comment]
(wrong button whoops)

**Comment by benhaynes** [comment]
Correct. But as with all/most interfaces, we can support multiple allowed datatypes and let the admin choose. They can choose INT if they have numeric keys, and VARCHAR if they have string keys. We warn them if they choose a bad status config.

**Comment by WellingGuzman** [comment]
@benhaynes about `hard_delete`, we removed those from status mapping and we are relying on permission for deletion.

I prefer ben idea, this is a configuration issue and we should warn them. I think this should answer my fallback question.

Now to add another question to the pile, when do we warn them? every time they want to use the collection/field in any way?

Creating/Updating/Deleting/Getting data, throw an exception, "interface X in this collection has misconfigured interface" type of error. "This status interface has status mapping or the global status mapping has different values type"?

**Comment by WellingGuzman** [comment]
Another thing as number can be in either string or numeric type doesn't make more sense to have the global as numeric values?

**Comment by benhaynes** [comment]
We warn admins when they are setting it up (or force them to set it up properly). If they DON'T (direct DB edits) then we can warn when trying to save:

* Shows user: `The "status" interface on this page is misconfigured`
* Shows admin (console): Full issue details
* API Response: An error code for misconfigured interface

### As for status datatype:
We will have a Directus default that we use, that can be INT and save `0`, `1`, `2`, or `3`. BUT, this is overridable in the config and can be changed to VARCHAR for string statuses. Unless you guys want to use strings (eg: `active`, `draft`, etc) for our status defaults from 7.0 forward. @WellingGuzman @rijkvanzanten ?

**Comment by WellingGuzman** [comment]
Having it string looks more clear, but I always prefer to take the easy path on default configuration values to prevent random misconfiguration and prevent this to be confused with bugs on new users, also current users are used to have status interface as numeric.

If that doesn't bother anyone else, I'm okay we keep it as string.

**Comment by rijkvanzanten** [comment]
I prefer using string based keys. I know it makes more sense to use numbers in a SQL based database (it feels more.. SQL), but seeing we set it up as a JSON object I feel like:

```js
{
  draft: {
    accentColor: '#eee',
    ...
    translation: {
      'en-US': 'Draft',
      'nl-NL': 'Concept'
    }
  },
  published: {...},
  underReview: {...}
}
```

makes more sense than

```js
{
  0: {
    accentColor: '#eee',
    ...
    translation: {
      'en-US': 'Draft',
      'nl-NL': 'Concept'
    },
  1: {...},
  2: {...}
}
```

**Comment by benhaynes** [comment]
Well if there's a time to shift the default status it's with 7.0... and I agree that the string-based approach is pretty nice. So let's plan on moving to that!

But I do want to confirm that our JSON Status Mapping will allow for _whatever_ keys admins choose to use... including with spaces, etc.

**Comment by rijkvanzanten** [comment]
> But I do want to confirm that our JSON Status Mapping will allow for whatever keys admins choose to use... including with spaces, etc.

That's technically fine, although we should recommend against doing it.

```js
{
  "super weird, but still-valid key@!": {
    ...
  }
}
```

is valid JSON

**Comment by WellingGuzman** [comment]
Hey @rijkvanzanten I'm seeing new keys in your example compared to 6.x keys. for example `accentColor` and `translation`. Does the format of these objects changed?

**Comment by rijkvanzanten** [comment]
I remember us discussing this a long time ago. I remember making a gist about it:

https://gist.github.com/rijkvanzanten/993a4dba3046e47389d30657ff0b67ad

Not sure if this is "final" though. I'm not even sure what keys are actually needed in the front-end app anymore. For example, the `text_color` key feels a bit unnecessary in the new design, seeing it's predefined. This needs more attention.

Ref @benhaynes

**Comment by benhaynes** [comment]
`text_color` is important because the status placard is a custom background color, and might need white/black/other foreground colors to have contrast.

**Comment by rijkvanzanten** [comment]
@benhaynes Isn't that something we can programmatically do in the app? If bg color is dark, render white text, if bg color is light, render dark text etc

**Comment by benhaynes** [comment]
Fiiiine, but it would also be kind of nice to have a consistent black
background and change the foreground color to yellow red or blue. For
instance.
