### ISSUE TITLE
PATCH /files creates new instead of updates old

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1427]
When patching the `/files/:id` endpoint with new `data` in base64, I expected the old image to be replaced with the new data. Instead, the API saved them as new files:

![image](https://user-images.githubusercontent.com/9141017/68789145-dde26080-0612-11ea-8f68-9182122ae23c.png)

**Comment by bjgajjar** [comment]
@rijkvanzanten  - It seems like API updates the image but the APP is not refreshing the component.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19200178/69122242-52f6df80-0ac4-11ea-8a82-6544aa9a220c.gif)

**Comment by rijkvanzanten** [comment]
That was the issue I was working on when I noticed the API creates a new copy of the image instead of updating the existing one. The app reloads the same image to refresh the view, but the API didn't modify the image.

See my screenshot above, see how there's 10 copies of the same slightly more cropped in image? That should've been 1

**Comment by bjgajjar** [comment]
Can't we close this? We are going to update our thumbnail structure. So it'll be resolved with #813 itself.

**Comment by rijkvanzanten** [comment]
No, this doesn't have anything to do with thumbnails as it's using the original file. The way it generates thumbnails is not related to the way it's updating the "original" file on patch
