### ISSUE TITLE
Add random number endpoint

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#143]
`POST /[env]/utils/random/number`

Generates a random number

**Comment by rijkvanzanten** [comment]
Do we need this in the core endpoints? Any reason to have it?

**Comment by benhaynes** [comment]
I agree – seems like a nice util to have... especially if we give it some nice options.

**Comment by rijkvanzanten** [comment]
We don’t use for the app, and it doesn’t feel like an 80% use case. I don’t agree that this should be in core. Instead, it should be a custom endpoint provided by the directus team in the marketplace

**Comment by benhaynes** [comment]
Won't fix
