### ISSUE TITLE
Use JSON for config files

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1443]
Right now, the API config is managed in PHP files. This makes it hard to manage the config from external sources, as we have to write the config into PHP format. 

By moving to JSON, it's easier to read from and write to the config file from the API and other sources.

---

There is one thing that needs to be supported before we can make this change: Scoped Extensions.

Right now, the config file is the only way you can create hooks that are scoped to a single project. 

---

When moving to the new config format, we should also get rid of names with underscores in them, like `root_url` in `storage`. This needs to be done to make mapping from environment variables in instances like Docker easier. Currently, we can't infer the config option from the environment name, for example:

`DIRECTUS_DATABASE_HOST`

can automatically map to

```
[
  'database' => [
    'host' => X
  ]
]
```

, yet `DIRECTUS_STORAGE_ROOT_URL` can not be inferred as 

```
[
  'storage' => [
    'root_url' => X
  ]
]
```

because of the underscore in the name

**Comment by bjgajjar** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
