### ISSUE TITLE
Lack of triggers on relations

### ISSUE THREAD

**Issue by anelad** [directus/api#1446]
On v8 -possibly on v7 too- Items having relations does not appear on UI after their related item deleted. (lack of triggers)

Let's say we have a collection for nested categories. (using m2o) It might look like this (will use swift-like language to represent reproducing the issue at code level):

``` swift
struct Category {
    let id: UUID // auto set
    var name: String // required
    var parent: UUID? // optional id of another category

    init(name: String, parent: UUID?) {
        self.name = name
        self.parent = parent
    }
}

// assume that id auto set to "asdasdasd"
let secondHand = Category.init(name: "Second Hand")
// save secondHand category
save(secondHand)

// id auto set to something we do not need to know
let electronics = Category.init(name: "Electronics", parent: "asdasdasd")
// save electronics category
save(electronics)

// lets delete secondHand which has id "asdasdasd"
delete(id: "asdasdasd")

// now if you check the DB, category named "electronics" still have the parent "asdasdasd"
```

Now let's reload the UI.

"electronics" category still has a parent; value of "asdasdasd", but there is no category with id "asdasdasd" since we deleted it. So, category "electronics" is not visible on UI because its parent does not exist anymore.

This issue is actually an API issue but maybe UI should bypass this issue without handling triggers. This is why I opened the issue to APP, not to API.

# Workaround

Use [hooks](https://docs.directus.io/extensions/hooks.html) to handle the problem (still using swift-like explanation):

``` swift
// on deleteion of a collection
onDelete(collection: String, data: Item) {
    // if deleted item is from categories collection and if the item really is a category 
    if (collection == "categories" && let data = data as? Category) { // assume that **Category** implements **Item**
        // find child categories of deleted category
        let children = findChildCategories(categoryID: data.id)
        // set each child categories parent to nil/null
        for (child in children) {
            child.parent = nil
            save(child)
        }
    }
}

```

**Comment by rijkvanzanten** [comment]
Directus doesn't handle relationship integrity currently. https://github.com/directus/api/issues/873 is the feature request regarding this
