### ISSUE TITLE
Updating password doesn't work

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#145]
**Describe the bug**
When updating the users password through the API, it doesn't seem to save it.

**To Reproduce**
1. Send a PATCH request to `https://demo-api.directus.app/_/users/1 with body using an admin api key
  ```json 
  {
    "password": "password"
  }
  ```
2. Shed some tears when you find out the password didn't save

**Expected behavior**
Password should be updated. Even when the password interface doesn't hash the value yet, I would've at least expected the api to insert the raw value

**Additional context**
Could it be because the API ignored the `password` field completely?

**Comment by WellingGuzman** [comment]
The API always hash the value for the `password` field, the interface doesn't need to hash this value anymore.

How did you check that the password isn't changing?

If I do this:

```
PATCH https://demo-api.directus.app/_/users/1

{
    "password": "new-password"
}
```

Then I try to authenticate:

```
POST https://demo-api.directus.app/_/auth/authenticate

{
    "email": "demo@example.app",
    "password": "new-password"
}
```

It returns the token back.

If I change the password one more time:

```
PATCH https://demo-api.directus.app/_/users/1

{
    "password": "another-new-password"
}
```

And then authenticate with my old password:

Then I try to authenticate:

```
POST https://demo-api.directus.app/_/auth/authenticate

{
    "email": "demo@example.app",
    "password": "new-password"
}
```

It fails.

**Comment by rijkvanzanten** [comment]
> The API always hash the value for the password field, the interface doesn't need to hash this value anymore.

Why is this? Why does the `directus_users` password field have special preference over any other field using a password / encrypted interface?

**Comment by rijkvanzanten** [comment]
I tried changing the password through the app & logging in again with the new password. Then I changed the password through postman and tried logging in through the app. Seeing it's working as expected on your end, I probably made a mistake somewhere 👍

**Comment by rijkvanzanten** [comment]
Ohhh weird, I tried changing it without `http`, which seemingly succeeded (because it returned a 200), but logging in (using https), failed. 

When trying to login over http, I get `method not allowed`.

What's the policy here on http vs https?

**Comment by WellingGuzman** [comment]
> Why is this? Why does the directus_users password field have special preference over any other field using a password / encrypted interface?

I didn't say it has special preference over anything. There wasn't anything that attached the users password field to be a `password` field until later. Any field gets hashed if it has a `password` interface. Now that `users.password` defaults to `password` interface, it would not different to anything.

> I tried changing the password through the app & logging in again with the new password. Then I changed the password through postman and tried logging in through the app. Seeing it's working as expected on your end, I probably made a mistake somewhere

I didn't tested locally I tested it on https://demo-api.directus.app

> What's the policy here on http vs https?

Nothing should be different, unless it was configured that way on the web server.

**Comment by rijkvanzanten** [comment]
Interesting! I get different behavior on `http` than I get on `https`. Worth checking out!

**Comment by rijkvanzanten** [comment]
Why?

**Comment by WellingGuzman** [comment]
I looked into the API using apache, and what we are experiencing here is an issue with the web servers. When we access `http` it gets redirect to `https` with new headers and empty body.

What we want here is proxy the request to the secure host, but what ideal should happen is that request should be denied on http.

**Comment by woeterman94** [comment]
Got the exact same issue. How can I fix this?

**Comment by rijkvanzanten** [comment]
@woeterman94 did you read the thread above? If you have the exact same problem, the solution should be the exact same as well

**Comment by woeterman94** [comment]
Can you help me out here? I'm using HTTPS.

**Comment by woeterman94** [comment]
> The API always hash the value for the `password` field, the interface doesn't need to hash this value anymore.
> 
> How did you check that the password isn't changing?
> 
> If I do this:
> 
> ```
> PATCH https://demo-api.directus.app/_/users/1
> 
> {
>     "password": "new-password"
> }
> ```
> 
> Then I try to authenticate:
> 
> ```
> POST https://demo-api.directus.app/_/auth/authenticate
> 
> {
>     "email": "demo@example.app",
>     "password": "new-password"
> }
> ```
> 
> It returns the token back.
> 
> If I change the password one more time:
> 
> ```
> PATCH https://demo-api.directus.app/_/users/1
> 
> {
>     "password": "another-new-password"
> }
> ```
> 
> And then authenticate with my old password:
> 
> Then I try to authenticate:
> 
> ```
> POST https://demo-api.directus.app/_/auth/authenticate
> 
> {
>     "email": "demo@example.app",
>     "password": "new-password"
> }
> ```
> 
> It fails.

Tried the exact same. Set the password using the API. I get an http success response. But logging in with the password using the api or web interface doesn't work. (Invalid user credentials)

**Comment by woeterman94** [comment]
Tried:
* turning off https and use http only. (and visa versa)
* disabled cloudflare proxy
* tried changing the password in the app

Neither of these seem to make a difference. However the "old" users still work. So if I manually copy and paste the hash from one user to another it works.

Could it be that the hashing changed somehow when upgrading to the new version?

**Comment by rijkvanzanten** [comment]
That'll depend on what version you upgraded from, but that hasn't changed since at least v6.3.1. Anyway, lets not discuss that on a 2 year old issue that's caused by an unrelated issue
