### ISSUE TITLE
Installer creates format issues in config file

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1450]
![image](https://user-images.githubusercontent.com/9141017/69161975-f0004b00-0ab9-11ea-9a95-baa902d2219d.png)

This should've been

```php
[
  'social_providers' => [
    'okta' => [],
    // etc
  ]
]
```

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1451

**Comment by rijkvanzanten** [comment]
The PR that fixed this broke setting social providers on install and had to be reverted

**Comment by rijkvanzanten** [comment]
Strange, I guess github doesn't un-close it in a PR if it was reverted later, oh well
