### ISSUE TITLE
API Endpoint mail tries to use 'frontend' as address

### ISSUE THREAD

**Issue by gewlar** [directus/api#1456]
# Bug Report

Using the Directus Suite the mail sender uses 'frontend' as address and subsequently fails on its own test. 

## Expected Behavior

Mail is sent through my own Mailserver.

## Actual Behavior

API returns:
```
{
    "error": {
        "code": null,
        "message": "Address in mailbox given [frontend] does not comply with RFC 2822, 3.6.2.",
        "class": "Swift_RfcComplianceException",
        "file": "/var/www/internal/directus/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php",
        "line": 345
    }
}
```

## Other Context & Screenshots

api.php
```
'mail' => [ 
        'default' => [
            'transport' => 'smtp',
            'from' => 'noreply@ateon.ch',
            'host' => 'mail.ateon.ch',
            'port' => 587,
            'username' => 'noreply@ateon.ch',
            'password' => 'xxxx',
            'encryption' => 'starttls'
        ],
    ],
```

## Technical Details

- OS: Ubuntu 16.04.6 LTS
- Web Server: nginx/1.14.2
- PHP Version: 7.8.3
- Install Method: cloned master branch
- DIrectus Version: tags/190927A

**Comment by urvashithakar** [comment]
Hey @gewlar,
It is not replicated in the latest directus version. From your error, it seems like you are set frontend as an email - which is wrong and maybe the culprit for your issue.
Kindly verify it once and still you get this error then let me know is this error persists in Forgot Password or Mail API?

**Comment by gewlar** [comment]
Where would frontend be set as an email? My mail configuration is set in api.php as posted above.

**Comment by bjgajjar** [comment]
@gewlar - Closing this on a ref. of https://github.com/directus/api/issues/1562
