### ISSUE TITLE
v8 gives "401: Unauthorized request" even if I give reading permissions

### ISSUE THREAD

**Issue by anelad** [directus/api#1458]
# Bug Report

Title says all.

## Steps to Reproduce

1. Create a collection
2. Inside "roles & permissions" give reading permission to "Public" user
3. Try to send a "GET" request to the relevant URL. ex: `mywebpage.com/_/items/magazines` 
4. See the error

## Other Context & Screenshots

1. The image shows I have given the reading permissions
![Screen Shot 2019-11-21 at 20 48 20](https://user-images.githubusercontent.com/5767654/69362888-6eb6dd00-0ca0-11ea-88e7-cf92962f6f73.png)

2. This image shows where I'm sending the get request and what is the respose
![Screen Shot 2019-11-21 at 20 50 18](https://user-images.githubusercontent.com/5767654/69362946-8e4e0580-0ca0-11ea-9b09-eb5ee9bd251d.png)

## Technical Details

- Server: centOS 7 
- PHP Version:  7.3

**Comment by anelad** [comment]
Tried with PHP 7.2 - same

**Comment by anelad** [comment]
Error stack:

```
[2019-11-21 20:52:48] api[_].ERROR: Directus\Exception\UnauthorizedException: Unauthorized request in /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/helpers/app.php:286
Stack trace:
#0 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/App.php(518): Directus\{closure}
#1 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->__invoke
#2 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#3 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#4 [internal function]: Slim\DeferredCallable->__invoke
#5 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#6 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#7 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#8 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#9 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/src/core/Directus/Application/Application.php(161): Slim\App->run
#10 /var/www/vhosts/uflymarket.com/cms.uflymarket.com/public/index.php(5): Directus\Application\Application->run [] []
```

**Comment by bjgajjar** [comment]
@anelad  - Can you please verify that your `project_name` is `_`? As I am not able to replicate this issue! So it'll be great help if you can provide the SQL dump for this. :)

**Comment by anelad** [comment]
Yes, I've tried `_` also `project_name`

**Comment by bjgajjar** [comment]
I guess you are using the wrong `project_name`. Right @anelad ?

**Comment by anelad** [comment]
Yes, @bjgajjar. I was. Closing. Thanks.
