### ISSUE TITLE
Running api in distributed k8s replicas

### ISSUE THREAD

**Issue by javo2222** [directus/api#1459]
In our environment directus api (version 2.0.18) is running in a kubernetes cluster. At the moment we use 1 replica and the api is connected to an aurora/mysql database hosted in the aws cloud. We consider switching to 2 or more replicas. 

Are there any known problems or issues on that topic? 

Thanks.

**Comment by bjgajjar** [comment]
TBH, I didn't see this kind of issue. So feel free to implement it and if you find any issue then kindly report it. We are here to help you out :) 

@benhaynes @rijkvanzanten - Can you please provide your thoughts here? Did you see any issues regarding this?

**Comment by benhaynes** [comment]
I'll defer to to @rijkvanzanten and @WoLfulus — this is out of my depth. 😳

**Comment by WoLfulus** [comment]
I think there shouldn't be any issues in that case, just make sure to setup stuff as any other distributed application (for example, making use of redis for caching, storing files in a properly distributed manner like NAS or S3-compatible storage and stuff like that)

let me know if you find any issues!

**Comment by bjgajjar** [comment]
As this issue is not persist at this moment in Directus; I am closing this. Feel free to reopen it.
