### ISSUE TITLE
move /auth/access_token to /auth/sso/access_token

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#146]
`/auth/access_token` only works for sso request token.

**Comment by rijkvanzanten** [comment]
This is the route that verifies the SSO response right? We could also consider naming it `/auth/verify`. @benhaynes any naming thoughts?

**Comment by benhaynes** [comment]
`/auth/sso/verify` sounds good to me...

**Comment by WellingGuzman** [comment]
You are not verifying anything at this point everything has been verified. you use a request token you can use to get the actual `access_token`.

**Comment by rijkvanzanten** [comment]
Ahhhh right, that makes sense 👍
