### ISSUE TITLE
Can't login with directus 8.0.0-rc2

### ISSUE THREAD

**Issue by hufon** [directus/api#1460]
# Bug Report

## Steps to Reproduce

1. Install directus-api and app with 8.0.0-rc2 tag
2. Use docker or use DIRECTUS_USE_ENV=1
3. run install script with ./bin/directus install:database and ./bin/install:install
4. Go to http://xxx/admin

## Expected Behavior
Login form should display
## Actual Behavior
![Sélection_162](https://user-images.githubusercontent.com/1788150/69439556-82694e80-0d47-11ea-9850-f556bef6b899.png)

## Other Context & Screenshots
![Sélection_163](https://user-images.githubusercontent.com/1788150/69439587-92812e00-0d47-11ea-8c58-79c0e17e705b.png)

`[2019-11-22 16:19:07] api[api].ERROR: Directus\Database\Exception\ItemNotFoundException: Item not found in /opt/app-root/src/src/core/Directus/Services/ItemsService.php:138
Stack trace:
#0 /opt/app-root/src/src/core/Directus/Services/UsersService.php(145): Directus\Services\ItemsService->findByIds
#1 /opt/app-root/src/src/endpoints/Users.php(92): Directus\Services\UsersService->findByIds
#2 [internal function]: Directus\Api\Routes\Users->read
#3 /opt/app-root/src/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
#4 /opt/app-root/src/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#5 /opt/app-root/src/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#6 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#7 /opt/app-root/src/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#8 [internal function]: Slim\DeferredCallable->__invoke
#9 /opt/app-root/src/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#10 /opt/app-root/src/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(124): Slim\Route->Slim\{closure}
#11 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#12 /opt/app-root/src/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#13 [internal function]: Slim\DeferredCallable->__invoke
#14 /opt/app-root/src/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#15 /opt/app-root/src/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#16 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#17 /opt/app-root/src/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#18 [internal function]: Slim\DeferredCallable->__invoke
#19 /opt/app-root/src/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#20 /opt/app-root/src/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(15): Slim\Route->Slim\{closure}
#21 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
#22 /opt/app-root/src/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#23 [internal function]: Slim\DeferredCallable->__invoke
#24 /opt/app-root/src/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#25 /opt/app-root/src/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#26 /opt/app-root/src/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
#27 /opt/app-root/src/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
#28 /opt/app-root/src/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#29 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#30 /opt/app-root/src/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#31 [internal function]: Slim\DeferredCallable->__invoke
#32 /opt/app-root/src/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#33 /opt/app-root/src/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#34 /opt/app-root/src/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#35 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#36 /opt/app-root/src/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#37 [internal function]: Slim\DeferredCallable->__invoke
#38 /opt/app-root/src/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#39 /opt/app-root/src/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
#40 [internal function]: RKA\Middleware\IpAddress->__invoke
#41 /opt/app-root/src/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#42 [internal function]: Slim\DeferredCallable->__invoke
#43 /opt/app-root/src/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#44 /opt/app-root/src/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
#45 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#46 /opt/app-root/src/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#47 [internal function]: Slim\DeferredCallable->__invoke
#48 /opt/app-root/src/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#49 /opt/app-root/src/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
#50 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#51 /opt/app-root/src/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
#52 [internal function]: Slim\DeferredCallable->__invoke
#53 /opt/app-root/src/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
#54 /opt/app-root/src/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#55 /opt/app-root/src/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
#56 /opt/app-root/src/vendor/slim/slim/Slim/App.php(297): Slim\App->process
#57 /opt/app-root/src/src/core/Directus/Application/Application.php(161): Slim\App->run
#58 /opt/app-root/src/public/index.php(5): Directus\Application\Application->run [] []
10.128.0.1 - - [22/Nov/2019:15:19:07 +0000] "GET /api/users/me?fields=*.* HTTP/1.1" 404 203 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"`
## Technical Details

- Web Server: Apache 2.4
- PHP Version: 7.1
- Database: Mysql 5.7
- Install Method:cloned 8.0.0-rc2 tag

**Comment by benhaynes** [comment]
@bjgajjar @WoLfulus — API or Docker specific? Let's take a look asap so it's resolved for our official release next week.

**Comment by hufon** [comment]
Some others information : 
- I've put an empty api.php file in ./config/directory otherwise the request /server/projects fails

The request /api answer : 

`{"data":{"api":{"version":"8.0.0-rc.1","requires2FA":false,"database":"mysql","project_logo":null,"project_color":"blue-grey-900","project_foreground":null,"project_background":null,"default_locale":"fr-FR","telemetry":true},"server":{"max_upload_size":209715200,"general":{"php_version":"7.1.30","php_api":"apache2handler"}}}}`

**Comment by hufon** [comment]
It seems the server think i'm authenticated...;

**Comment by bjgajjar** [comment]
@hufon - `CMD` doesn't support the new project flow. Which I implemented in https://github.com/directus/api/pull/1464. 

But the error you are getting is different from what it should. As I explained - the `CMD` doesn't have support - so you should not able to get the login screen. Currently, you are able to get a response [200 status code] from `api`,`projects` and all other endpoints except `me` and `user` related. Which is also not expected. If you installed the `Directus` from the command line then you'll get 500 status code from the `/api` itself. 

As this is not the expected behavior; I am not sure that #1464 will resolve your issue or not.
But the API is working with the command line with #1464.

@WoLfulus - It'll be a great help if you can take a look once in this issue.

**Comment by hufon** [comment]
In fact, /api and /projects doesn't work directly. To make it working i've:
- Created an empty api.php file in config folder (as i use DIRECTUS_USE_ENV=1 because i'm working on an dockerised environment)
- I delete project_foreground and project_background lines in the directus_field table. because of https://github.com/directus/api/issues/1440

**Comment by bjgajjar** [comment]
@WoLfulus - 🔔

**Comment by hufon** [comment]
Here's a dump of my BDD
[dump.zip](https://github.com/directus/api/files/3885629/dump.zip)

**Comment by hufon** [comment]
It works with my MR : https://github.com/directus/api/pull/1470

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1470
