### ISSUE TITLE
Custom SSO provider not listing on loginpage.

### ISSUE THREAD

**Issue by aswincoolsaet** [directus/api#1468]
I created a new auth provider under 

/public/extensions/core/auth/
or
/public/extensions/custom/auth/

I added the name in config.php
auth.socialproviders =>  [  'azure'  => [] ] 

the auth provider doesn't get listed when visiting
"_/auth/sso"

after debugging; I managed that the issue is the Parsing of the $config file

in \src\core\Directus\Config\Schema\Schema.php 
 near line 140
I added;
new Group('social_providers', [
      .... 
 new Group('azure?', [
                        new Value('client_id', Types::STRING, ''),
                        new Value('client_secret', Types::STRING, ''),
                        new Value('base_url', Types::STRING, ''),
                    ]),

from that moment,  everything works.
So the Schema doesn't allow custom added auth providers.
While this was the case before. 

Now my provider 'azure' placed 
/public/extensions/custom/auth/   -> /_/auth/sso   says   class provider azure not found
placed it under 
/public/extensions/core/auth/   ->   /_/auth/sso  says   all perfect  

in version  7.4.0 I didn't had to edit schema.php

**Comment by bjgajjar** [comment]
Just for the confirmation - You have added the `Provider` for `Azure` in the `custom` folder. Am I right?

**Comment by nicam** [comment]
We're facing the same problem

**Comment by bjgajjar** [comment]
@WoLfulus @rijkvanzanten - I think we need to think about providing the support of custom providers. As the current Schema doesn't have the functionality of that.

**Comment by nicam** [comment]
Would be cool if there'd be a folder where you could supply a custom Schema.php that gets merged with the default Schema

**Comment by benhaynes** [comment]
@rijkvanzanten @bjgajjar — do we want to consider this a feature request? We'll want to eventually add support for modular SSO providers, but I'd like to get the API stable first.

**Comment by bjgajjar** [comment]
I agree with you Ben. We should consider it as a feature request as API have so many stuff to complete in a priority.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
