### ISSUE TITLE
Unable to login without removing Cookie directus-_-session (on 8.0)

### ISSUE THREAD

**Issue by hufon** [directus/api#1473]
# Bug Report

## Steps to Reproduce

When working on a kubernetes environment, the host name correspond to the pod name

1. Login into the App 
2. Trigger a new deployment
3. Hit F5 et try to login again

## Expected Behavior
1. Login again and ok!

## Actual Behavior
1. When you try to log in, you've the message : API could not be reached
2. PHP log file has some : 
Failed generating the SQL query. :SELECT `directus_user_sessions`.* FROM `directus_user_sessions` WHERE `token` = '�#�QZ�W+���1�Y��^C�*�W�' LIMIT 1 [] []

It seems that the app doesn't remove the directus-_-session cookie when it no more valid.

**Comment by hufon** [comment]
Screen recorder for the problem
[screen-capture (1).zip](https://github.com/directus/api/files/3902037/screen-capture.1.zip)

**Comment by hufon** [comment]
The problematic code is : https://github.com/directus/api/blob/develop/src/helpers/all.php#L392

The php_uname() function return a different result when redeployed because pod name changes ([DEPLOYMENT-NAME]-[RANDOM-STRING])

**Comment by hufon** [comment]
`php > echo php_uname();
Linux directus-cms-27-vbsqt 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64`

- Redeployment

`php > echo php_uname();
Linux directus-cms-28-7dcfc 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64
php >`

**Comment by bjgajjar** [comment]
We really appreciate you taking the time to debug an issue. Thanks. I'll look into it. :)

**Comment by hufon** [comment]
When php_uname change, the decryption method failed and return a bad token name (with non UTF-8 characters...)

**Comment by everyx** [comment]
Maybe is the same problem https://github.com/directus/app/issues/2251

**Comment by hufon** [comment]
your problem is more like https://github.com/directus/api/issues/1473

**Comment by rijkvanzanten** [comment]
> It seems that the app doesn't remove the directus-_-session cookie when it no more valid.

The app can't read / modify the cookie (it's httpOnly). @bjgajjar when the API comes across an invalid cookie, it should remove it from the client.

**Comment by philleepflorence** [comment]
Yes, seems to be the same issue as the #1507 
I can verify that removing the cookies (manually) does solve it.
Perhaps a middleware on the API to remove if the App cannot remove.
