### ISSUE TITLE
Slug should be unique index

### ISSUE THREAD

**Issue by dur41d** [directus/api#1474]
# Feature Request

Creating a slug should create a field with a unique index to enhance performance. 

## What problem does this feature solve?

Slug fields are used often in the `WHERE` clause in database queries. It's important to create a unique index to avoid table scans which are very costly.

## How do you think this should be implemented?

Creating a slug field should create a unique index and the API should respond to unique index errors on insert or update and notify the client with appropriate error messages. The app should also be aware of these errors and display them properly.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by dur41d** [comment]
I did more research and found the cause of the problem. This is not an API bug as the API does allow creating a unique index. The problem is that the slug field is created with a default varchar(200) and utf8_general_ci which only allows a maximum of varchar(190) for unique index due to mysql limitation for innodb tables.

I suggest changing the slug interface in the app to default to:
- varchar(190)
- required
- unique 

I also suggest moving this issue to the app project as it is not an api issue.

**Comment by benhaynes** [comment]
@rijkvanzanten — sound good to move this to App?
