### ISSUE TITLE
Field update hook action not launched

### ISSUE THREAD

**Issue by Veiss** [directus/api#1478]
Hook for field update doesnt work. I check other hooks like item creation o item update and works fine but with fields i cant made work.

### Step to reproduce:
- Create new folder public/extensions/custom/hook/test
- Create new file under previus folder: hooks.php
- Add new hook 'field.update.[collection-name]'
- Put error_log or dump 
- Update collection field from app collection

### Expected Behavior:
Error log or dump is visible on log file and hook features are launched

### Actual Behavior:
Nothing happens.

Directus Release Version: 8.0.0-rc.2

**Comment by bjgajjar** [comment]
@Veiss  - May I know the syntax of hook which you used? As I tried to execute the `field.update.{collection}` the hook which is working as expected at my end. 

Many users getting the issue with the `hook` cause of a wrong `arguments`. So let me know the syntax of your hook - it'll be helpful to resolve it.

**Comment by Veiss** [comment]
@bjgajjar 
I use this code:

`<?php

use Directus\Custom\veiss\Utils;

return [
    'actions' => [
        'application.error' => function (Exception $error) {
            $utils = new Utils();
            $utils->sendEmail($utils->getOption('admin_email'), 'Error en el sistema', $error);
        },
        'item.create.buzon' => function ($data) {
            // WORKS!!
            $utils = new Utils();
            $content = 'Se ha creado un nuevo buzon ' . $data['texto'];
            $utils->sendEmail($utils->getOption('buzon_email'), 'Nuevo item buzon creado: ', $content);
        },
               
        'field.update.timeline' => function ($fieldname, $data) {
            // NOT WORKS!!
            error_log("Field updated " . $fieldname);
        },
    ],

    'filters' => [     
    ],
];`

Thanks

**Comment by bjgajjar** [comment]
`error_log` will sends an error message to the web server's error log or to a file instead of `Directus` log. I hope you are aware of that.
 
I am getting that in my server's log file. 

Let's communicate in our slack [channel](https://directus.chat) for

**Comment by Veiss** [comment]
@bjgajjar Yes i know. Other hooks action write correctly on my server error_log
Thanks

**Comment by bjgajjar** [comment]
@Veiss - Can you please try to execute  ` echo $fieldName; die; ` over there. I tried to run the hook from `api.php` [Configuration file] as well as public extension.

I am getting the result for both.

**Comment by Veiss** [comment]
@bjgajjar I put the code but still not getting log or hook execution advice. Yesterday a used new hooks and filters and work fine, the only issue if with field.update hook.
I dont know how to help reproduce it.
Sorry

**Comment by bjgajjar** [comment]
Can you please connect to our slack channel for further discussion? It'll be better for debugging the issue.

**Comment by bjgajjar** [comment]
@Veiss -  🔔  

As I mentioned in the above comments - I am not able to replicate the issue. Can you please check it in the V8? 

If you get the same error again then let's figure out this issue. I tried to find you on slack but it seems like you are not there!

**Comment by bjgajjar** [comment]
@Veiss - May I have an update on this? Are you facing the same issue in `V8.3.1`?

**Comment by Veiss** [comment]
@bjgajjar 
Hello, i´m on holidays, i will check asap.
Thanks a lot!

**Comment by bjgajjar** [comment]
@Veiss  - Any good luck?

**Comment by Veiss** [comment]
Hi! @bjgajjar 
No good luck today :(
My file is located at \httpd\public\extensions\custom\hooks\veiss\hooks.php (maybe could be relationed with de issue)

**Comment by bjgajjar** [comment]
@Veiss - Let's connect to the slack channel for further discussion.

**Comment by bjgajjar** [comment]
@Veiss - 🔔
