### ISSUE TITLE
Add thumbnail caching settings to directus_settings

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#148]
**Is your feature request related to a problem? Please describe.**
> How can I leverage browser caching for images served from the thumbnailer? I've enabled caching for apache but the thumbnailer is not picking it up:
'/storage/....' gets cacheded
'/thumbnail/2000/800/crop/...' does not

**Describe the solution you'd like**
The caching settings for the thumbnailer should be in `directus_settings`, just like the other settings for the thumbnailer.

**Describe alternatives you've considered**
n/a

**Additional context**
Thanks to Sebastian for the idea 🙂

**Comment by WellingGuzman** [comment]
Allow user to add "time to live" for thumbnail in directus settings.

**Comment by WellingGuzman** [comment]
What are the settings that should be in `/config/api.php`? we agreed on moving everything to `directus_settings`.

**Comment by rijkvanzanten** [comment]
Updated 😉

**Comment by WellingGuzman** [comment]
There are already on `directus_settings`. Is there anything besides custom `ttl` for the http cache?
