### ISSUE TITLE
activity_skip doesnt work on /files endpoint

### ISSUE THREAD

**Issue by cesasol** [directus/api#1483]
# Bug Report

## Steps to Reproduce

Make any modifying request (POST, DELETE, PATCH) to the files endpoint with the `activity_skip=1` query parameter.

## Expected Behavior

No record on the `directus_activity` nor `directus_revisions` about the request.

## Actual Behavior

The activity is logged like if there was no `activity_skip` parameter

## Other Context & Screenshots

The reason to skip activity on some operations is because I synchronize my data on another service with directus in order to access said data from my site and as a backup mechanism in case said service goes dark. This synchronization is automated and runs every few hours making those tables way to big to handle.

## Technical Details

- Device: Digital Ocean droplet
- OS: Ubuntu 18.04 LTS
- Web Server: nignx 1.14
- PHP Version: 7.2.24
- Database: MySQL 5.7.28-0ubuntu0.18.04.4
- Install Method: Cloned release branch

**Comment by bjgajjar** [comment]
@cesasol - Yes the issue occurs but only for `delete` the files. Which is resolved in https://github.com/directus/api/pull/1491

When the `activity_skip` param was passed for `patch` or `post`; that activity will not be stored into the `directus_activity` table.
