### ISSUE TITLE
File view: editing an image in the does not change the thumbnail

### ISSUE THREAD

**Issue by dur41d** [directus/api#1493]
When editing an image through the file view interface and saving the thumbnail is not updated in the list view. 

# Steps to reproduce

1. Upload a file through the File Library.
1. Click on the image to edit it and crop the image. 
1. Go back to the File library and you will see that the old thumbnail is still showing.

I think the problem is that the thumbnail needs to be deleted when the image is edited so that a new thumbnail is generated.

**Comment by rijkvanzanten** [comment]
This might've been addressed in the fix for https://github.com/directus/api/issues/1427. @bjgajjar @urvashithakar can we check how this related to https://github.com/directus/api/pull/1467 ?

**Comment by dur41d** [comment]
I was able to reproduce this issue on the demo app which has 8.0.0-rc2.

**Comment by bjgajjar** [comment]
Yes, @rijkvanzanten - this is a known issue. I already mentioned [here](https://github.com/directus/api/pull/1469#issue-345054528)

Once #1427 is stabilized - we'll do all the other related bugs.

**Comment by rijkvanzanten** [comment]
Perfect. I guess the API can "simply" delete the thumbnail on a file update. That'll cause the thumbnail to regenerate on next use

**Comment by bjgajjar** [comment]
Yes - we were supposed to change the path of the thumbnail. That's why I was waiting for #1467.
