### ISSUE TITLE
Add ability to enter JSON in repeater fields

### ISSUE THREAD

**Issue by MrKyHn1** [directus/api#1496]
Hi everyone,

I would like to suggest a feature, or if it already exists, i would like you to show me how to use it:
I want to add a country list(in a dropdown interface from directus)
 (FR, US as value and France , United States as name for example) or any other long dropdowns with 100+ values with JSON(currently, checkboxes are configurable that way), right now it is only available manually (set list name and value one-by-one).

# Feature Request
JSON configuration in dropdown fields

## What problem does this feature solve?
Avoiding errors when manually entering long list of options in dropdowns
and also gaining time in this process

**Comment by benhaynes** [comment]
@rijkvanzanten — isn't this what we created with the new key-value interface?

**Comment by MrKyHn1** [comment]
do you mean this by key value interface?
![image](https://user-images.githubusercontent.com/56399506/69871785-fd84b480-12b3-11ea-8a50-39dc77018902.png)
This is what i am talking about: currently , you can only put them one by one. but for checkboxes it can be done this way:
![image](https://user-images.githubusercontent.com/56399506/69871852-2b69f900-12b4-11ea-87b6-10d77ccf25ca.png)

the latter should be available for every multiple choice fields, in my current case, i want to add a country list (the JSON file is ready) but i want it in the dropdown interface not checkbox

**Comment by MrKyHn1** [comment]
do you mean this by key value interface?
![dropdown](https://user-images.githubusercontent.com/56399506/69872268-3c673a00-12b5-11ea-8ae7-893baf7df215.PNG)

This is what i am talking about: currently , you can only put them one by one. but for checkboxes it can be done this way:
![Checkbox](https://user-images.githubusercontent.com/56399506/69872259-35402c00-12b5-11ea-8a73-03e400f268ec.PNG)

the latter should be available for every multiple choice fields, in my current case, i want to add a country list (the JSON file is ready) but i want it in the dropdown interface not checkbox

**Comment by benhaynes** [comment]
I agree, and think the solution is to add a JSON toggle option to the repeater and key-value interfaces. That way you get the convenience of the UI for most easy setups, and JSON for longer or more complex ones.

@rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
