### ISSUE TITLE
v8.0.0.rc2 - login failed after installing Windows 10 update kb4523205.

### ISSUE THREAD

**Issue by yarick2000** [directus/api#1498]
# Bug Report
I agree that it's can be a pretty exceptional case, but its probably need to be reviewed. I have Directus v8.0.0rc2 installed locally on my machine within WLS (Ubuntu 16.04) under NGINX and PHP 7.3. MySQL 5.7 running within the same box. Everything worked fine till today, when Windows installed the latest updates and did reboot. After that I wasn't able to make login anymore to Directus - was getting an error. I've investigated the issue a bit and it seems like when DIrectus was trying to create a new session it was creating a session token and trying to find this token in directus_user_sessions table. I guess in case if record with such token was not found Directus supposed to create a new one. The thing is that the SQL statement that was called for checking if there is already an active session with such token in DB was failed, because generated token had utf8mb4_general_ci encoding for some reason and directus_user_sessions table had utf8_general_ci charset. I think that this Windows update (https://support.microsoft.com/en-us/help/4523205/windows-10-update-kb4523205) was changing some default system settings related to charsets and so Directus using them for creating session token, instead of using DB settings. I hope the problem is only WLS related, but who knows, may be all Windows setups are affected.  I will try to provide with more information, including screenshots, during a week.

## Steps to Reproduce

1. Install windows update kb4523205 
2. Restart the machine
3. Open the App and try to login with any user

## Expected Behavior
User still should be able to login after installing update
## Actual Behavior
User cannot login to the app after installing update

## Other Context & Screenshots
Will provide later

## Technical Details

- Device: Desktop
- OS: Windows 10.0.17763 WLS (Ubunto 16.04)
- Web Server: NGINX
- PHP Version: 7.3.0
- Database:  MySQL 5.7
- Install Method: cloned `master` branch

**Comment by bjgajjar** [comment]
Hey @yarick2000! Maybe it is duplicate of https://github.com/directus/api/issues/1473

**Comment by bjgajjar** [comment]
Apologize. Closed by mistake!

**Comment by yarick2000** [comment]
I don't think its a duplicate of #1473 , I was trying to clear all content/cookies, login in a private session window - nothing helped, except of uninstalling this update.

**Comment by yarick2000** [comment]
Here is an exception that happens when user trying to login after update has been installed:
{"error":{"code":9,"message":"Failed generating the SQL query. Statement could not be executed (HY000 - 1267 - Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '=')","query":"SELECT `directus_user_sessions`.* FROM `directus_user_sessions` WHERE `token` = 'O\u009f\u00ef,F\fD\u0082_\u0083\u0003\u00af\u001br\u00b4\u0017D\u00ef\u00b5\u00bd\\\"\u00a8\u009aX\u00ac' LIMIT 1","class":"Directus\\Database\\Exception\\InvalidQueryException","file":"\/mnt\/c\/Projects\/Directus\/directus-api\/src\/core\/Directus\/Database\/TableGateway\/BaseTableGateway.php","line":746}}

**Comment by rijkvanzanten** [comment]
@yarick2000 What happens if you change the collation in the database? I'm wondering how much we can do to prevent external factors changing core database level settings like this.

(Also I have no idea how to reproduce this..)

**Comment by rijkvanzanten** [comment]
Secondly, does it still happen in v8.1+? We pushed a fix that will unset cookies if they're expired, so maybe it's not even trying to read it anymore in the first place

**Comment by yarick2000** [comment]
Sorry, I've thought Binal closed the ticket. It has been fixed in 8.1.0
