### ISSUE TITLE
Type of fields cannot be NULL, but non-managed fields have a NULL type

### ISSUE THREAD

**Issue by mpfrenette** [directus/api#1501]
# Bug Report

## Steps to Reproduce

Bug found in Directus 8.0.0 RC2, when re-ordering the fields in a collection, where some of the fields are non-managed?

The API response is:
```
{
  "error": {
    "code": 9,
    "message": "Failed generating the SQL query.",
    "query": "INSERT INTO directus_fields (collection, field, type, interface, required, sort, note, hidden_detail, hidden_browse, options) VALUES ('jobs', 'id', NULL, NULL, '', '2', NULL, '0', '0', NULL)"
  }
}
```

## Expected Behavior

That the re-order works.

## Actual Behavior

It fails because the INSERT fails.

**Comment by rijkvanzanten** [comment]
Actually, normally the API sets the type field correctly based on the MySQL datatype. When trying the OP with a `VARCHAR`, the API (correctly) set the `type` to `string` on update. However, when I used the (obscure) type `GEOMETRY` in MySQL, the API crashes as it doesn't know what to fill in for type.

**Comment by rijkvanzanten** [comment]
I think `type` is required, as the API uses that to cast DB values to API output. @bjgajjar could you confirm that? Setting `type` to not-required (nullable) sounds like an easy fix, but I'm not sure if that has unwanted side effects

**Comment by rijkvanzanten** [comment]
This is fixed by https://github.com/directus/api/pull/1517. It adds support for the other MySQL types that were missing before
