### ISSUE TITLE
Required doesn't work with O2M type

### ISSUE THREAD

**Issue by anelad** [directus/api#1502]
If you use `O2M Files interface` you cannot update the item. You should deselect files and reselect them.

[Link to the video - since the gif becomes 170MB](https://drive.google.com/file/d/1s3Bv-7ruGB2IK3VRqv_ANGtf385Lt04W/view?usp=sharing)

![Screen Shot 2019-11-27 at 16 16 17](https://user-images.githubusercontent.com/5767654/69726630-f9c92480-1131-11ea-84cd-be3d301533e2.png)

**Comment by rijkvanzanten** [comment]
The API doesn't follow relationships when doing the required check for one to many type relationships. The app doesn't send any data (which is correct, as you didn't change anything) which causes the API to return an error because the required value is missing. However, this field already has a value, so the API shouldn't throw an error about it.

**Comment by anelad** [comment]
@rijkvanzanten, yes API does not throw an error about it. I thought I added this issue to the app repo, sorry about it :/ Should I close and re-open in app repo?

**Comment by rijkvanzanten** [comment]
>  I thought I added this issue to the app repo, sorry about it

You did! I moved it to the API, as this issue is caused by the API not checking the required state for O2M fields correctly 🙂

**Comment by anelad** [comment]
![giphy](https://user-images.githubusercontent.com/5767654/69915418-ae7b8280-145f-11ea-8cd1-92e9e5dd31f5.gif)

**Comment by bjgajjar** [comment]
@rijkvanzanten - `APP` is passing `[]` as a payload data although it's not getting updated for `files` interface. Can you please check it once?

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19200178/70137990-47efa200-16b5-11ea-8776-a25c5fe16242.gif)

**Comment by rijkvanzanten** [comment]
That shouldn't matter though. Passing an empty array doesn't delete anything on the API side. Only trying to delete all the related o2m items should throw the required error

**Comment by bjgajjar** [comment]
As per the flow, for the `update` action; `API` will get only those field which should be updated. Here, the `name` field was getting updated but still, the `file` was getting passed as `[]`. Technically`[]` should be considered as `null` itself.

**Comment by rijkvanzanten** [comment]
That's incorrect. Passing an empty array to the API doesn't delete any of the existing relations to the o2m, which means that the field still has a value, which means that the required constraint is met.
