### ISSUE TITLE
Can't DELETE /fields/:collection/:file-field

### ISSUE THREAD

**Issue by Veiss** [directus/api#1503]
Hello!!
When i try deleting file field from App collection, the app show an error and entire collection disappear from collection list.
It still in DDBB but not displaying on collection list, if i put manually in DDBB file filed to null its appear again

### Step to reproduce:
- Create new collection with image file field
- Fill all data and save it.
- Access to edit that collection item and try deleting image field and save item.
- Error throw and when go back to collection list the items isnt appear.

### Expected Behavior:
Back to collection items list with all items.

### Actual Behavior:
Previous edited item is missing

Directus Release Version: 8.0.0-rc.2

Thanks a lot!!

**Comment by rijkvanzanten** [comment]
The API returns

```
{
  "error": {
    "code": 203,
    "message": "Item not found",
    "class": "Directus\\Database\\Exception\\ItemNotFoundException",
    "file": "/var/www/html/src/core/Directus/Database/TableGateway/BaseTableGateway.php",
    "line": 1391
  }
}
```

for a field that does in fact exist.

I do notice that it deletes the database column, so it must fail when it's trying to remove the column from `directus_fields`
