### ISSUE TITLE
POST to /activity/message creates duplicate record

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#151]
It saves the message, and an activity record saying the message was created.

![image](https://user-images.githubusercontent.com/9141017/40263016-de93da52-5ada-11e8-8bb2-cb76f5562e0e.png)

It also creates a revision record for the message:

![image](https://user-images.githubusercontent.com/9141017/40263017-eb1994e2-5ada-11e8-92fd-3d1cfd7e0e64.png)

**Comment by rijkvanzanten** [comment]
Changes in `directus_activity` should be excluded from adding records to.. directus_activity

**Comment by WellingGuzman** [comment]
I was wondering now that we are allowing the user to update and delete comments, should we allow to record the revisions to keep track of comments editing?

**Comment by rijkvanzanten** [comment]
Lets discuss this further in #153
