### ISSUE TITLE
current develop branch - couldn't disable 2fa

### ISSUE THREAD

**Issue by everyx** [directus/api#1511]
# Bug Report

## Steps to Reproduce

1. Go to 'http://api.example.com/admin/#/demo/users/1'
2. Click on 'Disable 2FA' and save
3. Logout and login again
4. after input email and password, page redirect to http://api.fengsi.io/admin/#/setup-2fa to setup a new 2FA

## Expected Behavior
2FA is disabled and login to admin page.

## Actual Behavior
2FA is disabled and we need set a new 2FA 

## Other Context & Screenshots

1. User 1 is administrator role and "Enforce 2FA" is disable default.
![image](https://user-images.githubusercontent.com/1665522/70035861-a30a9180-15ee-11ea-8156-c9db593e8190.png)

2. Disable 2FA button
![image](https://user-images.githubusercontent.com/1665522/70035974-d51bf380-15ee-11ea-87ab-d7ac71269b12.png)

3. the setup 2FA page
![image](https://user-images.githubusercontent.com/1665522/70034173-b9631e00-15eb-11ea-8949-11a7e0b3fb48.png)

## Technical Details

- OS: Linux on Docker
- Web Server: Caddy with PHP-FPM
- PHP Version: 4.7
- Database: MySQL 8
- Install Method: cloned `develop` branch (Latest commit 8a361fd), manual build and install

**Comment by bjgajjar** [comment]
Can you please verify that is 2FA forcefully enabled for your role?

**Comment by everyx** [comment]
@bjgajjar This is the role setting, 2FA is not forcefully enabled, and I have this problem from a fresh install.

https://user-images.githubusercontent.com/1665522/70035861-a30a9180-15ee-11ea-8156-c9db593e8190.png

**Comment by bjgajjar** [comment]
Can you please verify the steps @everyx - I am not getting the `2FA` screen after disabling the 2FA
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19200178/70054222-1a472200-15fd-11ea-8692-4c1215591738.gif)

**Comment by everyx** [comment]
> Can you please verify the steps @everyx - I am not getting the `2FA` screen after disabling the 2FA
> ![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19200178/70054222-1a472200-15fd-11ea-8692-4c1215591738.gif)

Sure, I'll re-test it tomorrow, thanks. :)

**Comment by everyx** [comment]
@bjgajjar maybe I have not clone the branch with latest commit, I rebuild and it works fine for me now, thanks.
