### ISSUE TITLE
One to many should create foreign key

### ISSUE THREAD

**Issue by dur41d** [directus/api#1514]
# Feature Request

Creating a one to many relationship should create a foreign key in the database. There are 2 benefits of this:

1. Ensure data consistency. 
2. Improve performance as foreign keys are indexed and will improve join query performance considerably.

**Comment by benhaynes** [comment]
I like it... but we need to look into how this would work in a database type/vendor agnostic way.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
