### ISSUE TITLE
Hooks: passing integer as a string

### ISSUE THREAD

**Issue by dev7ch** [directus/api#1518]
# Bug Report

- Hooks create file send INT field to files id (correct)
- Hook update file sends string with number (not correct)

This is inconsistent and causes errors (if you work in combinations with other systems)

## Steps to Reproduce

1. Send Create hook
2. Send Update Hook

## Expected Behaviour

File id should be always INT

## Actual Behaviour

File id is string on update

## Other Context & Screenshots

Create: 

```
{
  "id": 45,
  ...
}
```

Update:

```
{
  "id": "45",
  ...
}
```

**Comment by bjgajjar** [comment]
Hey, @dev7ch - Can you please help me to replicate the issue? I'm getting a string for both - create as well as update.

**Comment by bjgajjar** [comment]
After having a conversation with @dev7ch in a slack channel - able to find out that it's again versioning issue. 

As this issue is not reproducible in the latest version; I am closing this. Feel free to reopen it.. :)

**Comment by bjgajjar** [comment]
Reopen it with change the definition as an integer is getting passed as a string in hook.

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1586
