### ISSUE TITLE
Length validation uses wrong encoding type to count value length

### ISSUE THREAD

**Issue by anelad** [directus/api#1521]
After you create a `Text Input` interface, set its type to `VarChar` and specify a Length; the input in the panel does not accept the text with that specified length. I think it accepts max 10 chars less.

**Comment by bjgajjar** [comment]
> could you confirm this change won't screw up anything else?

Nope - it's not a breakable change. 

And It seems like the `master` branch already contained this code - so we can close this.

**Comment by bjgajjar** [comment]
@rijkvanzanten  - Can you please help me to find out what's required to close this issue?

**Comment by rijkvanzanten** [comment]
> And It seems like the master branch already contained this code 

It _seems_ like it contains it... You were the one who merged it in @bjgajjar ! 😄

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/api/pull/1024

**Comment by bjgajjar** [comment]
> You were the one who merged it 

@rijkvanzanten - Yeah I know that. That's why I mentioned [here](https://github.com/directus/api/issues/1521#issuecomment-566223777) to get a confirmation. :)

**Comment by rijkvanzanten** [comment]
Ah, lost in translation then 😉
