### ISSUE TITLE
Discussion: output of not found when using `single` parameter

### ISSUE THREAD

**Issue by philleepflorence** [directus/api#1522]
# Bug Report

It seems when you query the Items Endpoint with Filter and Single Parameters if the filter yields no results, an error is triggered.

> **Some use cases:** 
> Checking if a user exists using an email address or username or checking if a configuration key-value pair exists.

## Steps to Reproduce

1. Query an endpoint (an example is shown below)
2. See error response (an example is shown below)

## Expected Behavior

The data object should be empty showing no rows matched (as is in SQL and NoSQL DBs).

## Actual Behavior

An exception is thrown breaking the development flow.

## Other Context & Screenshots

URL:
```
{{url}}/app/items/app_icons?access_token={{access_token}}&single=1&limit=1&filter[name][eq]=Browser
```

Response:
```
{
    "error": {
        "code": 203,
        "message": "Item not found",
        "class": "Directus\Database\Exception\ItemNotFoundException",
        "file": "~/Sites/Directus/suite/src/core/Directus/Database/TableGateway/RelationalTableGateway.php",
        "line": 1203
    }
}
```

## Technical Details

- Device: Mac Desktop
- OS: MacOS 10.14.6
- Web Server: Apache - MAMP 5.5
- PHP Version: 7.2.21 - MAMP 5.5
- Database: MySQL 5.7.26 - MAMP 5.5
- Directus Release Version: 8.0.0-rc.2
- Install Method: cloned `master` branch

**Comment by bjgajjar** [comment]
@rijkvanzanten - Can you please take a look once over this issue? Is this the recommended change?

As per the current code, there's a specific condition to return the `Item Not Found` exception if the `single` param is getting passed.

You can check it from [here](https://github.com/directus/api/blob/master/src/core/Directus/Database/TableGateway/RelationalTableGateway.php#L1180)

**Comment by rijkvanzanten** [comment]
I'm a little conflicted on this. On the one hand it makes sense to return an empty array, you're querying a specific subset of data (filters) and only returning the first match (single). If the match is empty, an empty array is returned. That being said, you can also view this as a search query ("I want the item where `name` = `Browser`") in which case it makes sense to return a "not found"..

@benhaynes any thoughts?

**Comment by philleepflorence** [comment]
Going with convention, single could return an empty array since it is using filter queries unlike getting a single item by ID which should return Not Found (i.e. invalid ID).

The issue with the single and filter returning an exception is it breaks the flow of development, especially running a search for a single item:

> Example: does anyone have this email address before continuing the authentication or registration process.

Not found means there is an error with the query parameter, versus there are zero results for your query.

**Comment by benhaynes** [comment]
Well, the `single` param makes this a bit odd... since it is designed not to return an _array_ list of items, but the actual _fields_ object of the item. That makes the response fundamentally different from other `items` responses.

So to me, a "not found" makes more sense than an empty array... because if it's an empty array, does that instead mean that this collection has no fields (or no fields you have permission to)? Thoughts?

**Comment by philleepflorence** [comment]
The reason I opened this ticket is that I currently have a lot of code imported from v6 which had the single parameter but returned an empty data object is no rows matched the query (with meta showing a total of 0). The same logic applies to almost all other APIs to which the same codes are linked.

If going the route of not found, then the docs would need to be very clear that it behaves like finding an item by Primary Key. Which like most APIs would return **Not Found** if PK is invalid.

I wanted to be sure before refactoring the code which though will affect the logic for other APIs.

**Comment by benhaynes** [comment]
Yeah, good to confirm this... the empty array (no items vs no fields) is the only bit that is weird. So let's get @rijkvanzanten and @WoLfulus thoughts on this first.

**Comment by rijkvanzanten** [comment]
I have to disagree with @philleepflorence 's statement made above:

> Not found means there is an error with the query parameter, versus there are zero results for your query.

To me, not found means that no items where found with the given search terms.  

> The reason I opened this ticket is that I currently have a lot of code imported from v6 which had the single parameter but returned an empty data object if no rows matched the query (with meta showing a total of 0)

That shouldn't affect our decision making for v8+

> The same logic applies to almost all other APIs to which the same codes are linked.

Please provide evidence with claims like these. I don't know what APIs you're referring to. 

---

As it stands, I don't think this is an issue in Directus. It was a conscience decision to return the Not Found exception when a single item couldn't be found based on the search parameters, and I believe that's the correct and wanted behavior.

**Comment by philleepflorence** [comment]
I appreciate your feedback.

A couple of NOTES:

>To me not found means that no items were found with the given search terms.

Try running a search using Google's Search API, FaceBook Places API, et al (via query parameters, 
 searching for an item that contains a term, not PK or ID) and see if you get an empty set with a message or a Not Found Exception. The issue is that the Not Found Exception breaks the flow (which terminates the running script) unless you use a try/catch, as opposed to a Not Found Response Message. I would have recommended an error parameter added to meta or just added to the response with no data property or an empty data object.

While I was developing a custom endpoint, I sat there for a while trying to understand why there was an exception, I thought I was doing something wrong. It never occurred to me that it was a code design choice. If the docs are very detailed (if the design choice is different other common patterns), this would not be a problem. But I had never seen this type of behavior before, otherwise, I would not have opened a ticket.

> Please provide evidence with claims like these. I don't know what APIs you're referring to

I power a lot of Real Estate companies in NY and they all use APIs such as `https://developers.nestio.com/api/v2/listings.html#listings-search` to power listings and searches (this is the reason for my slow migration from v6.x, because I heavily customize Directus for these companies and APIs). There are some APIs that have single parameters to return a single item if found. The single parameter was just to avoid doing `$response['data'][0]` vs `$response['data']`.

>That shouldn't affect our decision making for v8+

When making decisions to make breaking changes some consideration has to be made on the logic of the previous codebase and the impact on the users. It is not like the logic of the single parameter was inefficient or incorrect in the previous version(s). Granted some decisions have to be made to improve the newer versions, regardless of the past versions.

>As it stands, I don't think this is an issue in Directus. It was a conscious decision to return the Not Found exception when a single item couldn't be found based on the search parameters, and I believe that's the correct and wanted behavior.

I will be okay with any direction you choose since this, after all, is a project of Ranger Studio. However, I would caution against making changes that could alienate developers unnecessarily.

I am going to assume you would be treating the single parameter as you would the PK or Item ID.

**Comment by rijkvanzanten** [comment]
> The issue is that the Not Found Exception breaks the flow (which terminates the running script)

This is an implementation detail of whatever language/library you're using to perform the request. It sends a 404 HTTP status instead of a 200, as the item was not found. As per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status), that's the most suitable response to be given. "In an API, this can also mean that the endpoint is valid but the resource itself does not exist." I'm assuming you're referring to PHP where it would break the running script when using something like file_get_contents would error out on a 404. 

> When making decisions to make breaking changes some consideration has to be made on the logic of the previous codebase and the impact on the users.

Absolutely, and I'm not arguing otherwise. Directus has only seen 8 breaking changes in the ~ 15 years it's been a thing. And that's for a good reason. What I'm saying is that we shouldn't base decisions affecting the whole community based on code one person is migrating from v6 into v8. Changing it to something else now would be another breaking change, thus the more reason to discuss it thoroughly before jumping to any conclusions.

---

I'm not trying to negate the valid points you make, or silence your opinion or anything. Besides, why have an open source project if you don't take others' opinions and ideas into consideration. I'm just making sure we discuss the final solution thoroughly based on all the facts presented 🙂 

---

Using `limit=1` instead of `single` should return the data as you expect it @philleepflorence.

**Comment by philleepflorence** [comment]
Just some clarifying and ending notes ...

>This is an implementation detail of whatever language/library you're using to perform the request. It sends a 404 HTTP status instead of a 200, as the item was not found. As per MDN, that's the most suitable response to be given. 

This is using the TableGateway within Directus, not using the API via REST, so HTTP response is not expected. But I understand.

> What I'm saying is that we shouldn't base decisions affecting the whole community based on code one person is migrating from v6 into v8.

This is not an issue with a single person asking for a feature, I was noting that it broke with convention when querying a DB and could not understand the need for the change.

>Using `limit=1` instead of `single` should return the data as you expect it @philleepflorence.

I always use `limit=1` in SQL for performance reasons if I need a single item. The `single` parameter was just to avoid doing `$response['data'][0]` vs `$response['data']`.

I have decided to refactor the code ignoring `single` and sticking with the `limit` parameter to avoid any future issues.

Thanks for the consideration.

**Comment by bjgajjar** [comment]
@rijkvanzanten - Based on conclusion; we should close this issue. Right?

**Comment by philleepflorence** [comment]
Confirmed, with some clarifying notes added to the documentation for the single parameter, this issue can be closed.

**Comment by benhaynes** [comment]
@philleepflorence @rijkvanzanten is there anything we need to add to the Docs after closing this?

**Comment by rijkvanzanten** [comment]
I'm gonna go over the API reference as a whole soon; I'll clarify this some more when I do
