### ISSUE TITLE
Issue with TableGatewayFactory and ACL in Endpoints

### ISSUE THREAD

**Issue by philleepflorence** [directus/api#1523]
# Bug Report

When using the **TableGatewayFactory** on a read-only collection, when **ACL** is set to **false** (no updates are going to be performed) an exception is triggered.

Only when read and update permissions are set does it work using `ACL = $acl`.

## Steps to Reproduce

1. See Code and Response below.

## Expected Behavior

In an Endpoint, using **TableGatewayFactory**, one should be able to fetch items when permissions are set to read all. A token with read access should be able to read collections without ACL (breaking change from previous versions).

## Actual Behavior

An exception is thrown when ACL is set to false.

## Other Context & Screenshots

Sample Code:
```
use Directus\Application\Application;
use Directus\Database\TableGatewayFactory;

$container = Application::getInstance()->getContainer();
$dbConnection = $container->get('database');
$acl = $container->get('acl');

$tableGateway = TableGatewayFactory::create('<collection>', [
    'connection' => $dbConnection,
    'acl' => false
]);
```

Sample Error Response:
```
{
    "error": {
        "code": null,
        "message": "Call to a member function getStatusesOnReadFieldBlacklist() on null",
        "class": "Error",
        "file": "~/Sites/Directus/suite/src/core/Directus/Database/TableGateway/RelationalTableGateway.php",
        "line": 1803
    }
}
```

## Technical Details

- Device: Mac Desktop
- OS: MacOS 10.14.6
- Web Server: Apache - MAMP 5.5
- PHP Version: 7.2.21 - MAMP 5.5
- Database: MySQL 5.7.26 - MAMP 5.5
- Directus Release Version: 8.0.0-rc.2
- Install Method: cloned `master` branch

**Comment by bjgajjar** [comment]
Hey @philleepflorence - I guess you are trying to add this code in custom endpoint. I did the same and getting the `200` status code.

Let's connect to slack for further discussion.

**Comment by bjgajjar** [comment]
After having a conversation with @philleepflorence - able to know that this issue does not persist in the latest version. So closing this. :)

**Comment by philleepflorence** [comment]
Confirmed to be working with v8.3.1.
It seems to be fixed with the new DB Schema.

**Comment by bjgajjar** [comment]
Reopening it as It's throwing an error to fetch the item with filter.
