### ISSUE TITLE
`/files/folders` endpoint not working

### ISSUE THREAD

**Issue by phoenixtechnam** [directus/api#1526]
`GET /files/folders` does not return a list of folders, error

```json
{
  "code": 203,
  "message": "Item with id \"folders\" not found"
}
```

is returned

`GET /files/folders/1` still works and returns single folder with ID 1 as expected

**Comment by rijkvanzanten** [comment]
I'm assuming it's because 

```php
$app->get('/{id}', [$this, 'read']);
```

is matched before

```php
        $app->group('/folders', function () use ($controller) {
            $this->get('', [$controller, 'allFolder']);
```

which would cause it to try to read file with the id of `folders`.

https://github.com/directus/api/blob/51ce03bbe0a8788b60f8aa12b7e5078ab9b0b88b/src/endpoints/Files.php#L25-L47

**Comment by rijkvanzanten** [comment]
@benhaynes @bjgajjar should `folders` be a nested endpoint in `files` to begin with? Doesn't it make more sense to have a `/folders` endpoint on the same level as `/files`?

**Comment by benhaynes** [comment]
I think it makes sense to have `/folders` in the root...

**Comment by rijkvanzanten** [comment]
Just a heads up: the PR fixes support for the `/folders` endpoint, but that doesn't change anything in Directus. As of right now, Directus doesn't use the `directus_folders` table for anything yet. So even though you're currently able to assign folders to files, this won't change anything in the API output or GUI of Directus.

**Comment by phoenixtechnam** [comment]
@rijkvanzanten 
Can you please explain, I am confused. 
My Project relies on folders being used and files to be downloaded by their folder names.
So first I used to retrieve folder Names and IDs, and then the files having a specific folder ID. 

I am still trying to achieve full user separation for files and folders as described in #1044 which seemed to work quite well in v8.0.0 RC2.

Will that still work with the new endpoint ?
