### ISSUE TITLE
Call to undefined function get_random_string() on migration

### ISSUE THREAD

**Issue by gianniskarmas** [directus/api#1528]
Uploaded the backup DB of v8rc2 and pulled the updated v8.0.1.
Got the above error when tried to login app so private_hash and filename_download are still empty in DB.
![image](https://user-images.githubusercontent.com/3495993/70248008-36b89b00-1772-11ea-8051-97b0a089370a.png)

**Comment by chz** [comment]
I have 500 error on login : /

**Comment by rijkvanzanten** [comment]
Yes, as @gianniskarmas pointed out above

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/api/commit/a36106050235a9336c66e1c73914bdc3170042c5

**Comment by rijkvanzanten** [comment]
https://github.com/directus/directus/releases/tag/v8.0.2
