### ISSUE TITLE
Add PATCH and DELETE for `/activity/messages`

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#153]
_Only_ messages, not regular activity items

**Comment by WellingGuzman** [comment]
Who is allowed to edit the comments? What's updated beside the `comment`?

**Comment by WellingGuzman** [comment]
When we delete a comment, are we deleting an activity record? or flagging the activity as removed?

**Comment by rijkvanzanten** [comment]
Good questions! I would say the original message is updated _but_ we might want to show an `(edited)` flag next to the item in the future. However, there is no way of storing that right now. Storing a revision of an activity item feels a bit... hacky too for some reason..

@benhaynes Any thoughts?

**Comment by benhaynes** [comment]
I think we should use a flag for "deleted" comments/activity.

I think we should add a `datetime_edited` (or whatever naming convention we're suing elsewhere) to save when a change was made (only the most recent edit time). And I think only the `comment` and `datetime_edited` fields should be updatable.

**Comment by rijkvanzanten** [comment]
Hmm good question. Also, should admin users be able to edit comments from non-admin users? Is that a permission option for multiple groups?

**Comment by benhaynes** [comment]
Users can edit _their_ comments. Admins can edit _any_ comments.

We should not overwrite IP/user-agent... let's only update `comment` and the edit timestamp.

**Comment by rijkvanzanten** [comment]
So that permission needs to be stored somewhere to right? Do we really want to enforce this many custom permissions just based on the admin group?

**Comment by benhaynes** [comment]
For now, yes.

**Comment by benhaynes** [comment]
Yeah, we could either add a `status` column to the table, or a `deleted_comment` field. I like the second option since you should never be able to delete activity, just comments.

**Comment by WellingGuzman** [comment]
Done and moved to #177 for testing!
