### ISSUE TITLE
Broken Thumbnail in File library

### ISSUE THREAD

**Issue by laravelbap** [directus/api#1533]
# Bug Report

When uploading images on version v8.1.0 i got broken thumbnail image. I checked network and i got message that "directus-medium-crop" key is missing.

I checked same this in v8.0.2 and worked without any problem.

## Steps to Reproduce

1. Go to 'File Library'
2. Upload new image
3. Image is broken

## Expected Behavior

There should be thumbnail visible.

## Actual Behavior

Thumbnail image is broken. 

## Technical Details

- Device: [ Desktop]
- OS: [Ubuntu]
- Web Server: [nginx]
- PHP Version: [ 7.2.25 ]
- Database: [MySQL 10.3.20-MariaDB ]
- Directus Release Version: [v8.1.0]
- Install Method: [ cloned `master` branch]

**Comment by everyx** [comment]
I think it's already fix by https://github.com/directus/api/commit/4e2298af6d691848412fbe5e02d976f94c6d935a from @rijkvanzanten.

**Comment by laravelbap** [comment]
Hi, thank you for response. I will wait for next release and check if this is fixed.

**Comment by bjgajjar** [comment]
Agree with @everyx :)

**Comment by rijkvanzanten** [comment]
This was indeed fixed in 4e2298a

**Comment by laravelbap** [comment]
Hi, Please verify this one more time. As i checked this yesterday, today on clear installation. Version v.8.1.0 and its not working there.

**Comment by rijkvanzanten** [comment]
Yeah, that makes sense. Commit 4e2298af6d691848412fbe5e02d976f94c6d935a was published 3 days ago, the release of v8.1.0 was 4 days ago. This commit will make it into the next release.

**Comment by laravelbap** [comment]
Ok. Thank you!

**Comment by skrypt-nl** [comment]
I had the same issue. I originally installed v8.1.0 and upgrading to v8.2.0 did unfortunately not work, but I managed to fix it by manually updating the settings table in the database with the following query:
```
UPDATE `directus_settings` 
SET `value` = '[{"key":"directus-small-crop","width":64,"height":64,"fit":"crop","quality":80},{"key":"directus-small-contain","width":64,"height":64,"fit":"contain","quality":80},{"key":"directus-medium-crop","width":300,"height":300,"fit":"crop","quality":80},{"key":"directus-medium-contain","width":300,"height":300,"fit":"contain","quality":80},{"key":"directus-large-crop","width":800,"height":600,"fit":"crop","quality":80},{"key":"directus-large-contain","width":800,"height":600,"fit":"contain","quality":80}]' 
WHERE `key`='asset_whitelist_system';
```

**Comment by rijkvanzanten** [comment]
This migration should take care of that. I'm wondering why it didn't run for you 🤔 

https://github.com/directus/api/blob/develop/migrations/upgrades/20191205150000_update_directus_thumbnail_sizes.php

**Comment by skrypt-nl** [comment]
I followed these steps to upgrade (over FTP):
https://docs.directus.io/guides/upgrading.html#manually-upgrading-ftp-installs

So I basically just copied the new files with FileZilla to my webserver.
