### ISSUE TITLE
Upgrade from 7 (DB problems)

### ISSUE THREAD

**Issue by snakecharmer** [directus/api#1534]
Hi there - I upgraded my Directus 7 to 8.1.0 and when I run the upgrade script, I have an error:

```
/var/www/html $ php bin/directus db:upgrade
Config file for "" does not exist at: "/var/www/html"
/var/www/html $ php bin/directus db:install
```

Without the db:upgrade I receive from the api 

POST /_/auth/authenticate HTTP/1.1
Content-Type: application/json;charset=utf-8
```
{
    "error": {
        "code": null,
        "message": "Statement could not be executed (42S22 - 1054 - Unknown column 'ur.role' in 'field list')"
    }
}
```

inside my config folder there is only one file:

```
/var/www/html/config $ ls -la
total 20
drwxrwxr-x    1 nobody   nobody        4096 Dec  9 14:50 .
drwxr-xr-x    1 nobody   nobody        4096 Dec  9 14:26 ..
-rw-r--r--    1 nobody   nobody        6784 Dec  9 14:49 _.php
```

**Comment by rijkvanzanten** [comment]
`php bin/directus db:upgrade` requires you to provide the name of the project you're trying to update with the `-k` flag

`php bin/directus db:upgrade -k _`

**Comment by snakecharmer** [comment]
Same error...

```
/var/www/html $ php bin/directus db:upgrade -k _
Config file for "" does not exist at: "/var/www/html"
/var/www/html $ ls -l config/
total 8
-rw-r--r--    1 nobody   nobody        6784 Dec  9 14:49 _.php
```

**Comment by snakecharmer** [comment]
After the update to 8.3.0 the migration works, but no migration is executed

**Comment by bjgajjar** [comment]
Can you please check your `directus_migrations` table that is it contains all the migrations or not?

Let's connect to our slack [channel](https://directus.chat) for further discussion on this issue. So we can resolve it ASAP.

**Comment by snakecharmer** [comment]
I've found out, was something wrong in my docker-compose with the 8.3.0 works out of the box.

Thanks
