### ISSUE TITLE
Error logging out with redis

### ISSUE THREAD

**Issue by nachogarcia** [directus/api#1547]
# Bug Report

## Steps to Reproduce

1. Login into directus
2. Logout out of direcut
3. Can't reach API (even though API calls return a 200 status, and I can consume everything from my app without issues) and you're not able to login ever again
4. Flush redis cache
5. You can login again

## Expected Behavior
Be able to logout and login freely

## Actual Behavior
Can't login after logout

## Technical Details

- Device: Chrome
- OS: Windows
- Database: MySQL
- Directus: Docker v8

**Comment by nachogarcia** [comment]
Looks like it's not only logging out, from time to time I need to purge flush redis cache so that users can keep logging in.
It's the only big issue that I've came with v8 so far.
My exact config is here https://github.com/directus/docker/pull/84

**Comment by nachogarcia** [comment]
I didn't share any screenshot because it does not provide any information - no console errors and the network responds with a 200
![image](https://user-images.githubusercontent.com/9975630/70694731-99ed8480-1cc0-11ea-91b2-18f5117259bc.png)

**Comment by nachogarcia** [comment]
After checking the difference in responses of the get done to _/, i can see this differences.
![image](https://user-images.githubusercontent.com/9975630/70695436-fd2be680-1cc1-11ea-98e1-59a5caf1493a.png)

Only in the succesfull one there is a second request to _/

**Comment by nachogarcia** [comment]
The logs are the same - completely clear
```
172.20.1.1 - - [12/Dec/2019:08:35:33 +0000] "GET /server/ping HTTP/1.1" 200 232 "https://api.private/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
172.20.1.1 - - [12/Dec/2019:08:35:34 +0000] "GET /server/ping HTTP/1.1" 200 399 "https://api.private/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
172.20.1.1 - - [12/Dec/2019:08:35:36 +0000] "GET /server/ping HTTP/1.1" 200 396 "https://api.private/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
172.20.1.1 - - [12/Dec/2019:08:35:37 +0000] "GET /server/ping HTTP/1.1" 200 402 "https://api.private/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
::1 - - [12/Dec/2019:08:35:37 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.3.12 (internal dummy connection)"
172.20.1.1 - - [12/Dec/2019:08:35:39 +0000] "GET /server/ping HTTP/1.1" 200 233 "https://api.private/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36"
172.20.1.1 - - [12/Dec/2019:08:35:40 +0000] "GET /server/ping HTTP/1.1" 200 397 "https://api.private/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
172.20.1.1 - - [12/Dec/2019:08:35:42 +0000] "POST /_/auth/authenticate HTTP/1.1" 200 777 "https://api.private/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36"
172.20.1.1 - - [12/Dec/2019:08:35:42 +0000] "GET /_/ HTTP/1.1" 200 849 "https://api.private/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36"
172.20.1.1 - - [12/Dec/2019:08:35:43 +0000] "GET /server/ping HTTP/1.1" 200 233 "https://api.private/admin/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
172.20.1.1 - - [12/Dec/2019:08:35:43 +0000] "GET /server/ping HTTP/1.1" 200 232 "https://api.private/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
172.20.1.1 - - [12/Dec/2019:08:35:45 +0000] "GET /server/ping HTTP/1.1" 200 398 "https://api.private/admin/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36"
```

**Comment by rijkvanzanten** [comment]
Lets combine this into https://github.com/directus/api/issues/1476 🙂

**Comment by nachogarcia** [comment]
@rijkvanzanten any recommendation to avoid this issue while is fixed? I'm flushing the cache manually but can't do that for ever :P and can't disable it since our load times will skyrocket.

**Comment by rijkvanzanten** [comment]
You might be able to create a hook that empties the cache on update of directus_user_sessions :think

**Comment by bjgajjar** [comment]
>You might be able to create a hook that empties the cache on update of directus_user_sessions

That can be a solution for this issue. But at the end, we should combine it with #1476.

Thoughts? @rijkvanzanten

**Comment by rijkvanzanten** [comment]
Yeah, lets close this in favor of the bigger conversation happening in #1476
