### ISSUE TITLE
Extend functionality of maintenance module with per project support

### ISSUE THREAD

**Issue by yarick2000** [directus/api#1551]
# Feature Request
It will be nice to have maintenance mode for specific project and not for the whole API.
## What problem does this feature solve?
That can be a nice feature for situations when migrations happening for specific project database and so only project related endpoints and Application UI should be down, but for other projects things still should work

## How do you think this should be implemented?
as addition parameter for maintenance module, e.g.:
php bin/directus maintenance:on -N project_name
php bin/directus maintenance:off -N project_name

## Would you be willing to work on this?
Not sure if I have enough knowledge for this right now... That can be a pretty big task...

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
