### ISSUE TITLE
Collection Count Showing Less Than Actual

### ISSUE THREAD

**Issue by benhaynes** [directus/api#1556]
The Item Count in the search input is off: shows `198` when there are 22,000+ items in collection. I assume this is because of the math... saying there are less than page count of items (likely due to API not returning soft-deleted items).

This can be seen on the `tickets` table of the Demo.

**Comment by bjgajjar** [comment]
>likely due to API not returning soft-deleted items

@benhaynes @rijkvanzanten - Yes, that's the case. API is not returning the soft-deleted items. But as you mentioned collection has 22,000+ items. Can you please make sure that only 198 items are the non-deleted?

**Comment by rijkvanzanten** [comment]
Even if it doesn't return the soft-deleted items, it should return the first 200 not-soft-deleted items

**Comment by benhaynes** [comment]
Also, I created this dummy data... I think I set 5% to be deleted, so there are tens of thousands of active/draft items in there.
