### ISSUE TITLE
V8.2.0 hooks MailService send function get error when create item from public

### ISSUE THREAD

**Issue by everyx** [directus/api#1562]
# Bug Report

## Steps to Reproduce

1. Add `hooks` setting in project php config file.
```php
'hooks' => [
    'actions' => [
        'item.create.messages' => function ($data) {
            $container = Application::getInstance()->getContainer();
            $mailService = new MailService($container);
            $mailService->send([
                'type' => 'html',
                'subject' => "subject",
                'body' => 'new message created'',
                'data' => [],
                'to' => [
                    [ 'name' => 'Gavin Luo', 'email' => 'gavin.luo@fengsi.io' ]
                ],
            ]);
        },
    ],
],
```
2. Create message item from public post request, and error 
```json
{
  "error": {
    "code": null,
    "message": "Address in mailbox given [] does not comply with RFC 2822, 3.6.2.",
    "class": "Swift_RfcComplianceException",
    "file": "\/var\/www\/vendor\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/Headers\/MailboxHeader.php",
    "line": 345
  }
}
```
3. Login to Admin APP, and create a new message item, email sending hook worked.

## Expected Behavior

Also send email when on public api request to create message item.

## Actual Behavior

`Address in mailbox given [] does not comply with RFC 2822, 3.6.2.` error

## Other Context & Screenshots

Public role create permission has been setted and the message item can create normally, just email sending now working.

## Technical Details

- Device: Desktop
- OS: Windows 10 with Docker Desktop
- Web Server: Caddy 1.8
- PHP Version: 7.4
- Database: MySQL 8
- Install Method: cloned `v8.2.0` tagged branch, manual build and install

**Comment by everyx** [comment]
@bjgajjar I found the problem is that the `send` function `setFrom` is `false`.

Why we send false to `setFrom` and use default from from setting must have a `Admin` permission? 

Can we change it to use a `from` key from `data` to set mail from and if it not exist, we use the default mail from and without admin permission?

https://github.com/directus/api/blob/a3883473cfcbc1dae2fa015c9c808df60599f660/src/core/Directus/Services/MailService.php#L32-L43

**Comment by everyx** [comment]
looks like https://github.com/symfony/mailer is great for me, maybe I can use it and wrapped as an extension.

**Comment by bjgajjar** [comment]
@everyx -  We really appreciate you taking the time to debug an issue. As you mentioned; 

>Can we change it to use a from key from data to set mail from and if it not exist, we use the default mail from and without admin permission?

It is already doing that. `from` is set with `getFrom` method. And the `getFrom` method is doing exactly the same which you have mentioned. Please check the code [here](https://github.com/directus/api/blob/master/src/core/Directus/Services/MailService.php#L160)

**Comment by bjgajjar** [comment]
>maybe I can use it and wrapped it as an extension.

Yeah.  Please do it and feel free to send the PR also :)

**Comment by everyx** [comment]
Just close this issue and it's not a bug. :)
