### ISSUE TITLE
PHP 7.4 preload support

### ISSUE THREAD

**Issue by everyx** [directus/api#1566]
# Feature Request

## What problem does this feature solve?

reduce Directus boot time, make the  Rabbit running more faster :)

## How do you think this should be implemented?

I'm not sure, but maybe add a `preload.php` to include all php file need compiled in per load.

for reference: 
1. [Preloading in PHP 7.4](https://stitcher.io/blog/preloading-in-php-74)
2. [PHP RFC: Preloading](https://wiki.php.net/rfc/preload)

## Would you be willing to work on this?

I'm not sure, and not familiar with PHP, If I have enough time, I will have a try.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
