### ISSUE TITLE
Record Owner should be editable / assignable

### ISSUE THREAD

**Issue by tonydamage** [directus/api#1567]
# Feature Request

Add editable item owner field. Owner field allows colabolator to access / edit items, which was not created by them, but explicitly assigned by them.

## What problem does this feature solve?

Sharing / limiting edit access to items with external collaborators without requirement for them to create item.

Currently there is no way to limit / assign access to specific item after it was created. The functionality is similar to "createdBy", but this field could be editable.

In our use-case we have proposed this workflow:
Intern with lowest visibility creates record (visible to him and us).
Admin creates additional records over time and needs way to share access to this records with concrete intern (other interns should not have access to this item).

## How do you think this should be implemented?

New type could be added (owner) and ACL could be extended to use this new type as owner.
This would affect mostly Schema, ACL and TableGateway classes.

The proposed behaviour:
- If collection does have `createdBy`, does not have `ownedBy` - behaves as now (visibility `mine` is determined by createdBy field
- If collection does have  `createdBy` and  `ownedBy`
  - On Record creation if `ownedBy` is empty, use creator as owner
  - `ownedBy` is editable field
  - Visibility `mine`  is only determined by `ownedBy` (open for discussion, could be also any of two, 
    but using only `ownedBy` is simpler, since current code assumes only one owner.

## Would you be willing to work on this?

I can implement changes and propose pull request.

**Comment by rijkvanzanten** [comment]
Instead of relying on the default `created_by` field, you can create your own `owner` field and use the regular `user` interface with the `user_created` type. The `user` interface is editable

**Comment by rijkvanzanten** [comment]
We should consider renaming `user_created` to `owner` though and making that the default instead of `user_created`. @benhaynes

**Comment by benhaynes** [comment]
Yeah, that would work. I guess it's implicit that an owner would be )initially_ set by the creator. Whether it can be changed after that is more of a setting.

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1585
