### ISSUE TITLE
Return warnings / notices in API when doing something that is impossible

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1574]
When you're trying to fetch relational data that you don't have access to, the API will return the primary key (m2o) or nothing at all (o2m). It would be nice if the API could return some notices about fields you're trying to access that you don't have access to.

In the following example:

`GET /items/articles/5?fields=id,title,author.*`

```json
{
  "data": {
    "id": 5,
    "title": "My Article",
    "author": 1
  }
}
```

we're trying to read `author` relationally, but the API doesn't return it. While this is is expected and correct behavior, it isn't the most developer friendly. If you don't know that the API works this way, it's very confusing why you don't get the data you requested.

I propose adding a new top level key for notices / logs / warnings of this nature:

```json
{
  "data": {
    "id": 5,
    "title": "My Article",
    "author": 1
  },
  "notices": [
    {
      "code": "WAR_NO_ACCESS",
      "message": "You don't have access to read `authors`"
    }
  ]
}
```

**Comment by benhaynes** [comment]
I love this. Might be worth using `log` or something more general, so we can put all sorts of info in there (errors, notices, warnings, etc).

**Comment by rijkvanzanten** [comment]
We already have an `errors` top level key that's used for breaking errors:

```json
{
  "error": {
    "code": 3,
    "message": "Unauthorized request",
    "class": "Directus\\Exception\\UnauthorizedException",
    "file": "/var/www/directus/src/helpers/app.php",
    "line": 286
  }
}
```

This would be used for warnings and other notices. Although I can't really come up with an example of a non-warning message that we might surface 🤔

**Comment by rijkvanzanten** [comment]
I do agree that something a little more ambiguous gives us the flexibility to add in some other messages:

```json
{
  "data": {
    "id": 5,
    "title": "My Article",
    "author": 1
  },
  "messages": [
    "You don't have read access to `authors`",
    "Snatch the 2-for-$2 deal at your local Burger King now!"
  ]
}
```

(clearly joking on that last one of course hehe 😁 )

**Comment by benhaynes** [comment]
Yeah, I was thinking of _optimizations_ that you could do, or maybe helpers like `If you're trying to access "author" data, use the ?fileds parameter [Docs Link]`. Not really sure, just trying to leave options open for the future, but maybe all those could be considered notices.

Also, all of this should be off for `prod` mode.
