### ISSUE TITLE
Error uploading file with comma in the name

### ISSUE THREAD

**Issue by dur41d** [directus/api#1579]
If you upload a file with a comma in the name the request to the assets thumbnail will return a:

ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION

This stackoverflow article suggest adding a content disposition to the response header and putting quotes around the file name:

`Response.AddHeader("Content-Disposition", "attachment;filename=\"" + filename + "\"");`

https://stackoverflow.com/questions/13578428/duplicate-headers-received-from-server

BTW, thanks for simplifying the issue submitting process to be less formal.

**Comment by bjgajjar** [comment]
@dur41d - Thank you so much for reporting this issue as well as help us to figure it out. But It seems like file name is not only the culprit. 

The thumbnail image is not getting load. Maybe there should some other problem too along with the file name. I'll check it and send the PR.
