### ISSUE TITLE
Split Log Files into Days – Options for Pruning After X Days

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#16]
Right now, there is no limit on the filesize of the logs. This can potentially result in huge _huge_ file. We need to implement either a max filesize for the logs, or an "expiry date". (Either delete old records when filesize > threshold, or when logs.date < threshold)

**Comment by WellingGuzman** [comment]
I can create the logs to be one-liner and separated by day, which can make each file smaller, but the API shouldn't be looking at those files sizes and take actions based on it.

This should be separate job outside the API workflow.

**Comment by WellingGuzman** [comment]
The logger levels and names are flipped in the array.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/api/commit/55ccd8b8c61b9067a698281ac2577706e2b063fd

**Comment by benhaynes** [comment]
@WellingGuzman – soooo... what do we have completed here? Log files per day and a `directus_settings` option for how many days to keep before deleting?

I don't know what "levels" and "flips" means.

**Comment by rijkvanzanten** [comment]
Doc doc doc doc doc documentation!

**Comment by WellingGuzman** [comment]
There's no configuration yet as we need to implement a cronjob manager for Directus. (Created a ticket for this https://github.com/directus/api/issues/200)

> I don't know what "levels" and "flips" means.

It was a bug creating the files name. creating `400.<date>` instead of `error.<date>`

> Doc doc doc doc doc documentation!

https://github.com/directus/api/wiki/Directus-CLI#log-module
