### ISSUE TITLE
Editing "Timestamp" field throws exception if default value is CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by buenyamin** [directus/api#1600]
# Bug Report

## Steps to Reproduce

1. Create a table with a column of type "TIMESTAMP"
2. Set default value of this newly created column to "CURRENT_TIMESTAMP"
3. Add some data to this table
4. Go to directus and try to manage this as a "DateTime Created" via: Directus -> Settings -> Collection & Fields -> <your_table> -> Select <timestamp_column>

## Expected Behavior
A timestamp column with CURRENT_TIMESTAMP as the default value should be supported without any issues.

## Actual Behavior
Instead directus throws an exception.

## Other Context & Screenshots

Log of exception:
``
[2019-12-24 15:20:34] api[site].ERROR: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at' in /var/www/html/site/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Connection.php:379
Stack trace:
#0 /var/www/html/site/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Connection.php(379): PDO->query
directus/directus#1 /var/www/html/site/directus/vendor/zendframework/zend-db/src/Adapter/Adapter.php(205): Zend\Db\Adapter\Driver\Pdo\Connection->execute
directus/directus#2 /var/www/html/site/directus/src/core/Directus/Database/Schema/SchemaFactory.php(243): Zend\Db\Adapter\Adapter->query
directus/directus#3 /var/www/html/site/directus/src/core/Directus/Services/TablesService.php(1316): Directus\Database\Schema\SchemaFactory->buildTable
directus/directus#4 /var/www/html/site/directus/src/core/Directus/Services/TablesService.php(623): Directus\Services\TablesService->updateTableSchema
directus/directus#5 /var/www/html/site/directus/src/endpoints/Fields.php(112): Directus\Services\TablesService->changeColumn
directus/directus#6 [internal function]: Directus\Api\Routes\Fields->update
directus/directus#7 /var/www/html/site/directus/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func
directus/directus#8 /var/www/html/site/directus/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
directus/directus#9 /var/www/html/site/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
directus/directus#10 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
directus/directus#11 /var/www/html/site/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#12 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#13 /var/www/html/site/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#14 /var/www/html/site/directus/src/core/Directus/Application/Http/Middleware/AuthenticationMiddleware.php(124): Slim\Route->Slim\{closure}
directus/directus#15 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
directus/directus#16 /var/www/html/site/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#17 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#18 /var/www/html/site/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#19 /var/www/html/site/directus/src/core/Directus/Application/Http/Middleware/TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
directus/directus#20 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
directus/directus#21 /var/www/html/site/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#22 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#23 /var/www/html/site/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#24 /var/www/html/site/directus/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(15): Slim\Route->Slim\{closure}
directus/directus#25 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
directus/directus#26 /var/www/html/site/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#27 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#28 /var/www/html/site/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#29 /var/www/html/site/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
directus/directus#30 /var/www/html/site/directus/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
directus/directus#31 /var/www/html/site/directus/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
directus/directus#32 /var/www/html/site/directus/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
directus/directus#33 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
directus/directus#34 /var/www/html/site/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#35 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#36 /var/www/html/site/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#37 /var/www/html/site/directus/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
directus/directus#38 /var/www/html/site/directus/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
directus/directus#39 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
directus/directus#40 /var/www/html/site/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#41 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#42 /var/www/html/site/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#43 /var/www/html/site/directus/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
directus/directus#44 [internal function]: RKA\Middleware\IpAddress->__invoke
directus/directus#45 /var/www/html/site/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#46 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#47 /var/www/html/site/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#48 /var/www/html/site/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
directus/directus#49 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
directus/directus#50 /var/www/html/site/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#51 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#52 /var/www/html/site/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#53 /var/www/html/site/directus/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
directus/directus#54 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
directus/directus#55 /var/www/html/site/directus/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#56 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#57 /var/www/html/site/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#58 /var/www/html/site/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
directus/directus#59 /var/www/html/site/directus/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
directus/directus#60 /var/www/html/site/directus/vendor/slim/slim/Slim/App.php(297): Slim\App->process
directus/directus#61 /var/www/html/site/directus/src/core/Directus/Application/Application.php(161): Slim\App->run
directus/directus#62 /var/www/html/site/directus/public/index.php(5): Directus\Application\Application->run [] []
``

## Technical Details

- Device: Desktop
- OS: Win10
- Web Server: Apache 2.4.41
- PHP Version: 7.3.13
- Database: MySQL 8.0.18
- Directus Release Version: v8.3.1
- Install Method: cloned `master`

**Comment by benhaynes** [comment]
@directus/api — I assume this would mean adding some special variables that allow special "dynamic" values to be used as a default. We'll need to think through now this is possible given our database abstraction.

**Comment by buenyamin** [comment]
Maybe a hint:
To workaround this issue I've set the default value to NULL, created the interface as "Datetime created" with MySQL Datatype "DATETIME" which works just fine.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
I think the problem here might be the fact that you created the column as a `TIMESTAMP`, while the Datetime Created interface/type relies on DATETIME 🤔

**Comment by buenyamin** [comment]
> I think the problem here might be the fact that you created the column as a `TIMESTAMP`, while the Datetime Created interface/type relies on DATETIME 🤔

The exception log states that the default value is the problem. 
Also like mentioned before creating it without a default value works fine.
