### ISSUE TITLE
Unsecure exception in graphql

### ISSUE THREAD

**Issue by pahatrop** [directus/api#1604]
I detect strange api behaviour.
I call next curl request:
```
curl  --request POST 'http://mysite.loc/api/public/_/gql'
```

Response:
```
{
    "error": {
        "code": 3,
        "message": "Unauthorized request",
        "class": "Directus\\Exception\\UnauthorizedException",
        "file": "/var/www/domains/mysite.loc/directus/src/helpers/app.php",
        "line": 286
    }
}
```

I think this security vulnerability open details about project location and give information about used Directus version.

Directus version: v8.3.1
PHP version: 7.2.26
Webserver: Nginx

**Comment by bjgajjar** [comment]
Hey @pahatrop - Can you please check your token? or please send your SQL dump. So I can reproduce the issue. Currently, it's not reproducible at my end.

![image](https://user-images.githubusercontent.com/19200178/71581837-37eca600-2b2d-11ea-8b5b-d2c29f24581e.png)

**Comment by pahatrop** [comment]
Hey @bjgajjar - this behaviour is reproduced without access token.
So everybody can call this method and see server side structure.

**Comment by bjgajjar** [comment]
@pahatrop - Are you using any authentication method[Cookie/Jwt] or just trying to use it publically? 

GraphQL is only for admin. It's not for `public` role. 

You can check more details from [here](https://docs.directus.io/api/reference.html#graphql-endpoint)

**Comment by bjgajjar** [comment]
As this issue is not reproducible in the latest version as well as it seems like it's expected behavior of the system; I am closing this. Feel free to reopen it.
