### ISSUE TITLE
Failed to send email

### ISSUE THREAD

**Issue by cdwmhcc** [directus/api#1608]
# Bug Report
### Steps to Reproduce

Update config api.php on key mail
```
'mail' => [
    'default' => [
    'transport' => 'smtp',
     'host' => 'smtp.qq.com',
     'port' => '587',
     'username' => 'xxxx',
     'password' => 'xxxx',
     'from' => 'xxxx',
     'encryption' => 'tls'
   ],
]
```
Do API call to /mail with the params

```
{
  "to": "xxxx@gmail.com",
  "subject": "New Password",
  "body": "Hello <b>{{name}}</b>, this is your new password: {{password}}.",
  "type": "html",
  "data": {
    "name": "John Doe",
    "password": "secret"
  }
}
```

Error:

```
Expected response code 250 but got code "501", with message "501 mail from address must be same as authorization user
```
I edited

`/src/core/Directus/Services/MailService.php`:

``` php
protected function getFrom($defaultEmail = false)
```

to

``` php
protected function getFrom($defaultEmail = true)
```

It still doesn't work.

I edited

``` php
protected function getFrom($defaultEmail = false)
    {
        /** @var Acl $acl */
        $acl = $this->container->get('acl');
        if ($defaultEmail) {
            $config = $this->container->get('config');
            return  [
                 $config->get('mail.default.from') => $acl->getUserFullName()
            ];
        }
        else {
            return [
                $acl->getUserEmail() => $acl->getUserFullName()
            ];
        }
    }
```
to
``` php
protected function getFrom($defaultEmail = true)
    {
        /** @var Acl $acl */
        $acl = $this->container->get('acl');
         $config = $this->container->get('config');
         return  [
              $config->get('mail.default.from') => $acl->getUserFullName()
         ];
    }
```
It works.
I don't know why.

Technical Details
OS: CentOS Linux 7.6.1810 (Core)　
Web Server: Nginx 1.17
PHP Version: 7.3
Install Method: Latest version

**Comment by bjgajjar** [comment]
Hey @cdwmhcc - I'm not able to reproduce it. Sending you screen recording in the slack channel. Let's communicate over there for further discussion.

**Comment by next-direction** [comment]
The error message basically says that the authenticated user is not allowed to send mails with the given address. So I think either your configured default address or the address of the user who sends the mail is not allowed.

**Comment by cdwmhcc** [comment]
> The error message basically says that the authenticated user is not allowed to send mails with the given "From" address. So I think either your configured default address or the address of the user who sends the mail is not allowed.

After I modified the configuration, it was sent successfully. What's the reason?

**Comment by next-direction** [comment]
I don‘t know, what did you change?

**Comment by cdwmhcc** [comment]
> I don‘t know, what did you change?

![image](https://user-images.githubusercontent.com/8030134/71679974-d5610780-2dc3-11ea-8f7b-3b5b96a52a71.png)

**Comment by next-direction** [comment]
Oh ok, that‘s not the config, it’s the source code ;-). 

I think in this case the problem might be the email address configured for the user  who sends the mail. Looks like with your change the default address is used which is allowed as sender.
Check the email address of the user who is logged in when sending the mail.

**Comment by cdwmhcc** [comment]
> Oh ok, that‘s not the config, it’s the source code ;-).
> 
> I think in this case the problem might be the email address configured for the user who sends the mail. Looks like with your change the default address is used which is allowed as sender.
> 
> Check the email address of the user who is logged in when sending the mail.

After I tried gmal.com qq.com 163.com, I had the same error prompt. After checking the issue:https://github.com/directus/api/issues/1562#issuecomment-567798159, I modified the source code. It works now, but I don't know why, so I submitted the issue

**Comment by everyx** [comment]
> > Oh ok, that‘s not the config, it’s the source code ;-).
> > I think in this case the problem might be the email address configured for the user who sends the mail. Looks like with your change the default address is used which is allowed as sender.
> > Check the email address of the user who is logged in when sending the mail.
> 
> After I tried gmal.com qq.com 163.com, I had the same error prompt. After checking the issue:[#1562 (comment)](https://github.com/directus/api/issues/1562#issuecomment-567798159), I modified the source code. It works now, but I don't know why, so I submitted the issue

This function is used in api internal, so it always setfrom user information, if you call from a doesn't exist user (like public), you will get this error.

This is not a bug, just use your own mail function instead of this.

**Comment by cdwmhcc** [comment]
> > > Oh ok, that‘s not the config, it’s the source code ;-).
> > > I think in this case the problem might be the email address configured for the user who sends the mail. Looks like with your change the default address is used which is allowed as sender.
> > > Check the email address of the user who is logged in when sending the mail.
> > 
> > 
> > After I tried gmal.com qq.com 163.com, I had the same error prompt. After checking the issue:[#1562 (comment)](https://github.com/directus/api/issues/1562#issuecomment-567798159), I modified the source code. It works now, but I don't know why, so I submitted the issue
> 
> This function is used in api internal, so it always `setfrom` from user information, if you call from a doesn't exist user (like public), you will get this error.
> 
> This is not a bug, just use your own mail function instead of this.

I mean why changing $defaultemail = false to $defaultemail = false doesn't work

**Comment by next-direction** [comment]
Because you just changed the default parameter, but it depends on the function call, what value is given. Only if no value is set by caller, the default value will be used.
