### ISSUE TITLE
Complete the Directus CLI

### ISSUE THREAD

**Issue by jooola** [directus/api#1613]
Currently the Directus CLI isn't really usable, and I hoped this could be fixed somehow. I always need to check the documentation to find the right command syntax, and with the move to v8.x the commands are not always working I don't know why.

I would suggest to build a complete CLI that stand by itself, with command / flags / args description inside the CLI. Documentation could be generated from the CLI, instead of trying to keep it up to date with the few existing function.

Some kind of symfony/artisan like CLI would be really nice.

This could also be a way to include import/export utilities.

The main idea behing this is that i need to deploy directus api's but I find it difficult to work using a mix of CI and the Vue App.

• Running Directus 8.3.1

• Steps to reproduce : 
Just try to understand the CLI without the documentation on the website.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by jooola** [comment]
@benhaynes Ok.

Is it still ok if I comment here ?

What if I come up with a little PR to build a base for the CLI ?

**Comment by benhaynes** [comment]
Of course! It's only closed to better organize feature requests away from bugs (we get a LOT more requests). And we _love_ PRs! Though you should coordinate with our Core team (here or on Slack) to make sure we're all on the same page first... so there's no wasted efforts.

Core Team: @benhaynes @rijkvanzanten @WoLfulus @bjgajjar

**Comment by rijkvanzanten** [comment]
Or @directus/team for short 😉

**Comment by jooola** [comment]
My idea would be:
First create a strong base using the following : https://symfony.com/doc/current/components/console.html in a really small PR. I mean just the CLI base in a separate Console2 namespace, and bind it to the directus binary or so.

Send more PR for each command, while migratiing the old commands to the new CLI.
And finally replace the old namespace with the new one.

How does that sound ?

**Comment by rijkvanzanten** [comment]
Sounds good to me! The main thing we need to consider is backwards compatibility. Would it be possible to have this alongside the old one, and add a deprecation warning to that? I'd rather not release Directus 9 just because we updated the CLI

**Comment by jooola** [comment]
The existing commands doesn't seem really hard to replicate using the symfony console components. The migration from the old commands to the new namespace will have to be identical from the user perspective (names flags args ...). Can't agree more on backward compatibility.

**Comment by rijkvanzanten** [comment]
I remember the current cli commands being a little weird and unexpected, so I'm totally down to move to a proper set of commands but keep the old ones around just for backwards compatibilities sake 🙂

**Comment by jooola** [comment]
@rijkvanzanten Ok I'm already facing a little problem.

robmorgan/phinx ^0.9.2 requires symfony/console below version 4.4.2. Upgrading phinx would be the solution since it bring a lot of important improvement, but I'm not sure this is safe to do. The [release page](https://github.com/cakephp/phinx/releases?after=v0.10.4) show that 0.10.0 includes breaking changes (sadly not detailled). So I'm unsure how to continue. Should I install symfony/console@4.4.2 or should I upgrade phinx ?

New versions of phinx also comes with PHP4 support and more, and that is one of your future task.

**Comment by rijkvanzanten** [comment]
Yikes.. I personally prefer to keep things up to date instead of using older versions just out of fear of breaking things.

Lets update Phinx to a newer version, and patch what needs patching in the API if we run into any issues. We're not super power users of Phinx, so I'm assuming we might steer clear of the 

> Most of the user facing methods in the Migration class stay the same, some of the least used ones are gone. 

breaking change.
