### ISSUE TITLE
Replace string concatenation with sprintf

### ISSUE THREAD

**Issue by jooola** [directus/api#1616]
I suggest replacing all the string concatenation to the sprintf function which seems more powerful IMO. Also this forces the project to be consistent.

Some links:
- https://stackoverflow.com/questions/7147305/performance-of-variable-expansion-vs-sprintf-in-php

> Any performance gain would be so minuscule that you would see it (as an improvement in the hundreths of seconds) only with 10000s or 100000s of iterations - if even then.

> For specific numbers, see this benchmark. You can see it has to generate 1MB+ of data using 100,000 function calls to achieve a measurable difference in the hundreds of milliseconds. Hardly a real-life situation. Even the slowest method ("sprintf() with positional params") takes only 0.00456 milliseconds vs. 0.00282 milliseconds with the fastest. For any operation requiring 100,000 string output calls, you will have other factors (network traffic, for example) that will be an order of magniture slower than the 100ms you may be able to save by optimizing this.

> Use whatever makes your code most readable and maintainable for you and others. To me personally, the sprintf() method is a neat idea - I have to think about starting to use that myself.

**Comment by benhaynes** [comment]
Thoughts @directus/api ?

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
Yup! Ties in nicely with the formatting PR you're working on @jooola 🙂

**Comment by rijkvanzanten** [comment]
I'm wondering if this is something we should go back through and fix now, or keep in mind going forwards.

**Comment by jooola** [comment]
> I'm wondering if this is something we should go back through and fix now, or keep in mind going forwards.

Let me know which one you prefer, fixing what is already there seems to be a small but painful job, but doable.

**Comment by rijkvanzanten** [comment]
Seeing that we're already getting started in porting everything over to Laravel, I don't think it's worth the effort to go in and clean up what's going to be replaced anyway 🙂
