### ISSUE TITLE
Comply with PSR-* Coding style

### ISSUE THREAD

**Issue by jooola** [directus/api#1625]
For the future of the project, I suggest to force anyone contributing to this project to comply with one of the PSR-* Coding Style.

Even if I just added some formatting tools to comply with PHP-Cs-Fixer coding style in #1615, I think it has to be explained to any future contributor to follow the guidelines.

**Comment by benhaynes** [comment]
Curious why you closed this, @jooola ?

**Comment by jooola** [comment]
What I suggested was 2 things, one was to change **again** the coding style of the project to some PSR-* Code styling guidelines ([PSR-12](https://www.php-fig.org/psr/psr-12/) was the first idea), and the second was about getting in touch with all the developers and make them follow the same guideline. This can be done with some documentation in the CONTRIBUTING.md file or any other.

For part 1 I can still change it in my PR #1615, even if directus is supposed to discuss about this since it involves a lot of code.

And part 2 should be done internally by writing the CONTRIBUTING file. I think a link to the guidelines is required to make everyone follow them.

So I'll leave it the team to decide how to spread the word about guidelines. You're free to reopen

**Comment by benhaynes** [comment]
Thanks for the update! I'll leave it to @rijkvanzanten if this is something we'll want to pursue (and therefore reopen). :)

**Comment by rijkvanzanten** [comment]
Having a set of rules to adhere to is really useful and something we already actively enforce on the application side. @jooola on the directus/app repo, we have an auto fixer that runs every time you make a commit to ensure everybody is using the same code style in every file at all times. Is there something we could do on the PHP side of things too? Can the GH action auto fix it and push it as a commit on PRs?

**Comment by jooola** [comment]
@rijkvanzanten I use this tool but it rely on Python. I don't bother since python is shipped on all major linux distros, but I'm unsure about any other OS.

https://pre-commit.com/#intro
