### ISSUE TITLE
8.x version is more than 20ms slower than 2.6.0 version query speed!

### ISSUE THREAD

**Issue by cdwmhcc** [directus/api#1627]
My website has about 5000 IP visits every day. Since upgrading 8.x version, I have received feedback from a lot of users, they told me that the website opens faster than before. Redis is enabled!

After various investigations, it was finally determined that the 8.x version query data was about 20ms slower than the 2.6.0 version.

I use the same database and the data for the custom collections are all consistent.

Please check it.

![image](https://user-images.githubusercontent.com/8030134/72020709-537f4b80-32a7-11ea-82e3-4acc65a24907.png)

![image](https://user-images.githubusercontent.com/8030134/72020727-609c3a80-32a7-11ea-9cdf-b25bc1108894.png)

**Comment by benhaynes** [comment]
This could be for many reasons, and not all of them are necessarily Directus. This is also very subjective (speed), so I don't know if we can keep this open as a bug. Performance optimizations are all tracked under this enhancement:

https://github.com/directus/api/issues/179
