### ISSUE TITLE
Register a new user through SSO from the API?

### ISSUE THREAD

**Issue by andgar2010** [directus/api#1645]
Because I was researching Directus docs, but couldn't get it.

**Comment by benhaynes** [comment]
We don't currently have a way to register users through SSO, but you can use SCIM or the Users API to do this.

**Comment by benhaynes** [comment]
Is this a feature request? @rijkvanzanten is this something we can/want to do at some point?

**Comment by rijkvanzanten** [comment]
This ties in to the 'allow public registration of users' feature request. If we have that, I don't see why you shouldn't be able to register through SSO either

**Comment by andgar2010** [comment]
> We don't currently have a way to register users through SSO, but you can use SCIM or the Users API to do this.

I consulted SCIM in API documentation to do with Create SCIM User, I did a SCIM based request test in Doc, but it shows a "**500 Internal Server Error**".

![image](https://user-images.githubusercontent.com/19521054/72384138-ce52c700-36ea-11ea-9b78-d4ee95175816.png)


PS: I updated minutes ago directus 8.2.0 -> 8.4.0 using git (DigitalOcean).

**Comment by rijkvanzanten** [comment]
@andgar2010 Mind opening a new API issue for that? 🙂

**Comment by andgar2010** [comment]
> @andgar2010 Mind opening a new API issue for that? 🙂 Don't want that to get lost in this feature request

@rijkvanzanten 
A thousand apologies, I'll separate new issue.

**Comment by rijkvanzanten** [comment]
No worries 👍
