### ISSUE TITLE
user creation with SCIM

### ISSUE THREAD

**Issue by aswincoolsaet** [directus/api#1648]
user creation through SCIM fails, because of the validator:

password: This value should not be blank.
timezone: This value should not be blank.
locale: This value should not be blank.
roles: This value should not be blank.

according to documentation these values are not needed. 
https://docs.directus.io/api/reference.html#create-scim-user

**Comment by bjgajjar** [comment]
@aswincoolsaet - Not able to reproduce this issue on the latest version.
