### ISSUE TITLE
Error create SCIM user on updated 8.4.0

### ISSUE THREAD

**Issue by andgar2010** [directus/api#1650]
• Version of Directus 
8.4.0

• Error message (if any) 
 "500 Internal Server Error".

• PHP version
7.2.24

• MySQL version
mysqld  Ver 5.7.28

• Webserver + version
apache 2.4.29

• Steps to reproduce:

I consulted SCIM in API documentation to do with Create SCIM User, I did a SCIM based request test in Doc, but it shows a "500 Internal Server Error".
![image](https://user-images.githubusercontent.com/19521054/72384138-ce52c700-36ea-11ea-9b78-d4ee95175816.png)

PS: I updated minutes ago directus 8.2.0 -> 8.4.0 using git (DigitalOcean).

**Comment by bjgajjar** [comment]
@andgar2010 - I'm not able to reproduce this issue.

![image](https://user-images.githubusercontent.com/19200178/72546460-cf355580-38b0-11ea-9f76-ec299c184404.png)

Can you please help me if I'm missing anything?

**Comment by andgar2010** [comment]
@bjgajjar Thank you for your answer.
Trying me out again works.
![image](https://user-images.githubusercontent.com/19521054/72548569-f2361a00-385c-11ea-9e30-f7c405724827.png)

I don't understand how strange it is that it works.
I rebooted the server yesterday. I think directus updates fix db during boot up.
