### ISSUE TITLE
Error create SCIM user on Clean Install 8.4.0

### ISSUE THREAD

**Issue by andgar2010** [directus/api#1651]
• Version of Directus
8.4.0

• Error message (if any)
"403 Forbidden".
```
{
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:Error"
  ],
  "status": 403,
  "detail": "Creating item to \"directus_users\" collection was denied"
}
```

• PHP version
7.2.24

• MySQL version
mysqld Ver 5.7.28

• Webserver + version
apache 2.4.29

• Steps to reproduce:
I tried another server directus installation from fresh with last version 8.4.0 upgrade using git, but different error message:

![image](https://user-images.githubusercontent.com/19521054/72388412-e0853300-36f3-11ea-9272-b31fd8c845bb.png)

**Comment by benhaynes** [comment]
Hey @andgar2010 — curious why you closed this one...

**Comment by andgar2010** [comment]
> Hey @andgar2010 — curious why you closed this one...

@benhaynes I found that I need to put header auth Bearer, however it does not work for registration from public without auth.

**Comment by benhaynes** [comment]
Ahh, understood. Yeah, it was far too complex and non-performant to include permissions in GQL, so we opted to make it only for Admins (for now).

**Comment by andgar2010** [comment]
@benhaynes I understand. Thanks for the clarification. I'm waiting for the new feature #1645 "Register a new user through SSO from the API" for public in the pending list. I'm trying to do "public user registration" on custom endpoint
