### ISSUE TITLE
Remaining TYPE_USER_CREATED constants are preventing upgrades

### ISSUE THREAD

**Issue by cesasol** [directus/api#1652]
- Version of Directus: Upgrading from V7.4 to 8.4 
- Error message: Undefined class constant 'TYPE_USER_CREATED'
- Steps to reproduce: Upgrade using the git method
- PHP 7.4
- Mysql Version 5.7.28
- Nginx 1.16.1

When upgrading directus from V7 I encounter `Undefined class constant 'TYPE_USER_CREATED'`  on [migrations/upgrades/20191123053252_update_directus_files_field.php](https://github.com/directus/api/blob/76413ea8f5b3bf7e90f84a76858ab18c7fc0db67/migrations/upgrades/20191123053252_update_directus_files_field.php#L119) and [migrations/upgrades/20191202164209_reset_directus_fields.php](https://github.com/directus/api/blob/76413ea8f5b3bf7e90f84a76858ab18c7fc0db67/migrations/upgrades/20191202164209_reset_directus_fields.php#L621) as I can tell by blaming the repo is a change made on 17390ecc3e800fe781b65f8faab5ccbf7fda0a9a I will make a PR fixing this in hopes of getting this fixed so everyone can upgrade safely from older releases.

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1653
