### ISSUE TITLE
API call: conditional on fields

### ISSUE THREAD

**Issue by drubinskyi** [directus/api#1656]
Hi there,

Quick question, just today i ran into a small challenge. When retrieving an item from a collection, using [this endpoint](https://docs.directus.io/api/reference.html#get-items) we also retrieve the item(s) of the relationships. We want the so-called child items to only be returned when the status (of the child item) is published.

For example, we do this call: `/parent?fields=*,child_id.*`
Then the response body is this: 

```
"data": [{
        "id": 1,
        "status": "published",
        "child_id": {
            "id": 10,
            "status": "draft",
        }
    }]

```

But we expected this:
```
"data": [{
        "id": 1,
        "status": "published"
    }]
```

We tried to filter based on child_id.status but when doing that the whole parent object is not returned. (like `"data":[]`)

Of course we can split this one request into multiple requests, but we were wondering if it is possible to do it in one request.

Any ideas??

Thanks!

**Comment by benhaynes** [comment]
So you are using `getitems` on the parent item, using the `fields` param to _only_ fetch the children?

I'm a bit confused by the "but we expected this" part of your ticket... since that seems like you were expecting the parent data (based on the id and status). Aren't you trying to only get the child? Sorry if I'm misunderstanding...

**Comment by drubinskyi** [comment]
Hello @benhaynes, 
Thanks for replying. 
I think I made a mistake here in cal: /parent?fields=child_id.*
Sorry, it should look like this /parent?fields=*,child_id.*
Fixed in question, thanks for notice
We expect parents fields every time and child fields only when child's status is published

**Comment by benhaynes** [comment]
Ahh, understood. This is an interesting discussion point... should all relational data be returned, or only published relational data. We've always seen the published flag as working for the parent items fetched only, but this is a good point. 

@directus/api team?

**Comment by rijkvanzanten** [comment]
Interesting point. The filter parameter will indeed filter out the root level item based on the given query. I don't think we have any way to filter out related items like this (yet)

**Comment by drubinskyi** [comment]
Thank you for all your responses, 
Will continue using few requests for it
