### ISSUE TITLE
Which correctly type the "owner" fields on update 8.4.0?

### ISSUE THREAD

**Issue by andgar2010** [directus/api#1659]
• Version of Directus
8.4.0

• PHP version
7.2.24

• MySQL version
mysqld Ver 5.7.28

• Webserver + version
apache 2.4.29

I researched the changes "created_by" to "owner" in the #1567 discussion, but I was a little confused because I updated directus 8.2.0 to 8.4.0 this works and [Maunal Upgrade Directus Schema](https://docs.directus.io/guides/cli.html#database-module). shows no have problems Directus Dashboard but the fields not correctly update the field "created_by" to "owner". Screenshot A: 

![msedge_xcl5Ro1kmG](https://user-images.githubusercontent.com/19521054/72561920-3edb1e80-3878-11ea-836d-97aeae59e652.png)

I checked other collections "tables" I found have different format than A:

![msedge_Q0Ms2GOOI7](https://user-images.githubusercontent.com/19521054/72561942-4e5a6780-3878-11ea-9f68-040d7ff5b27f.png)
 

Then I had to manually add a new field "owner" which is different from A and B on screenshot C:

![msedge_lnKduZbcMl](https://user-images.githubusercontent.com/19521054/72561960-574b3900-3878-11ea-9946-674be7745611.png)

I'm a little confused because the documentation [Core Interfaces User Created](https://docs.directus.io/guides/interfaces.html#user-created) is correct? 

I tried out a new collection to add new field it comes out error add, but I refreshed the page shows added new field:

![kPn137OtaU](https://user-images.githubusercontent.com/19521054/72556797-65478c80-386d-11ea-8023-cc430336faf4.gif)

**Comment by bjgajjar** [comment]
https://github.com/directus/api/pull/1673 will resolve this issue partially. 

>Then I had to manually add a new field "owner" which is different from A and B on screenshot C:

Here, it seems like the field that has been added is `required`. `Required` is not working right now in [Directus](https://github.com/directus/api/issues/1660).

So let's close this with #1673 and kindly wait for #1660 to getting resolved to access the `required` feature.
