### ISSUE TITLE
SQL error when changing field to not required

### ISSUE THREAD

**Issue by AlbertoAbruzzo** [directus/api#1660]
## Steps to Reproduce

1. Go to a collection
2. Click on a field that is flagged "required"
3. Remove the required and save

## Expected Behavior
The field should save and change from required to not required

## Actual Behavior
Error 500
`Statement could not be executed (42000 - 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(16777215) Not Null' at line 1)`

- Device: DigitalOcean Server
- OS: Ubuntu Server 18.04
- Web Server: Apache/2.4.29
- PHP Version: 7.4
- Database: MySQL 8.0.18
- Directus Release Version:8.4.0
  - App Version: 8.4.0
  - API Version: 8.4.0
- Install Method: cloned `master` branch

**Comment by bjgajjar** [comment]
@AlbertoAbruzzo - May I know the datatype of your field?

**Comment by AlbertoAbruzzo** [comment]
> @AlbertoAbruzzo - May I know the datatype of your field?

boolean

**Comment by AlbertoAbruzzo** [comment]
@bjgajjar boolean
