### ISSUE TITLE
Request to any field of `File` type always returns all fields rather than requested and accepts non-existent fields.

### ISSUE THREAD

**Issue by rtaubes** [directus/api#1670]
How to reproduce:.
The example below shows the request to both `Many To Many` and `File` fields to see the difference in response.

1. Create `Many To Many` collection `C2 Files M2M` with `Text input` `cust_url`.
2. Create `C2 URL` collection with fields:
 - `file_rel` of type `File`,
 - `file_m2m` of type `Many To Many` and connect it to the created in (1) `C2 Files M2M` using an auto created junction table,
3. Request detailed fields from both `file_rel` and `file_m2m`. The request is
`items/c2_url?fields=file_rel.data.full_url,file_m2m.c2_files_m2m_id.cust_url`.
The response is:
{'data': [{'file_m2m': [{'c2_files_m2m_id': {'cust_url': 'http://cust_url'}}],
           'file_rel': {'data': {'embed': None,
                                 'full_url': 'http://127.0.0.1:8100/uploads/test_prj/originals/12da88ce-41c6-473c-af9d-714e2702efa9.jpg',
                                 'thumbnails': [{'dimension': '64x64',
                                                 'height': 64,
                                                 'relative_url': '/test_prj/assets/qvl55kb665cg480o?key=directus-small-crop',
                                                 'url': 'http://127.0.0.1:8100/test_prj/assets/qvl55kb665cg480o?key=directus-small-crop',
                                                 'width': 64},
                                                {'dimension': '64x64',
                                                 'height': 64,
                                                 'relative_url': '/test_prj/assets/qvl55kb665cg480o?key=directus-small-contain',
                                                 'url': 'http://127.0.0.1:8100/test_prj/assets/qvl55kb665cg480o?key=directus-small-contain',
                                                 'width': 64},
                                                {'dimension': '300x300',
                                                 'height': 300,
                                                 'relative_url': '/test_prj/assets/qvl55kb665cg480o?key=directus-medium-crop',
                                                 'url': 'http://127.0.0.1:8100/test_prj/assets/qvl55kb665cg480o?key=directus-medium-crop',
                                                 'width': 300},
                                                {'dimension': '300x300',
                                                 'height': 300,
                                                 'relative_url': '/test_prj/assets/qvl55kb665cg480o?key=directus-medium-contain',
                                                 'url': 'http://127.0.0.1:8100/test_prj/assets/qvl55kb665cg480o?key=directus-medium-contain',
                                                 'width': 300},
                                                {'dimension': '800x600',
                                                 'height': 600,
                                                 'relative_url': '/test_prj/assets/qvl55kb665cg480o?key=directus-large-crop',
                                                 'url': 'http://127.0.0.1:8100/test_prj/assets/qvl55kb665cg480o?key=directus-large-crop',
                                                 'width': 800},
                                                {'dimension': '800x600',
                                                 'height': 600,
                                                 'relative_url': '/test_prj/assets/qvl55kb665cg480o?key=directus-large-contain',
                                                 'url': 'http://127.0.0.1:8100/test_prj/assets/qvl55kb665cg480o?key=directus-large-contain',
                                                 'width': 800}],
                                 'url': '/uploads/test_prj/originals/12da88ce-41c6-473c-af9d-714e2702efa9.jpg'}}}]}

The response returns only the requested field for `file_m2m` and all available fields for `file_res` even only one field was requested.

The response is the same for the variations of `file_rel.data`:
`items/c2_url?fields=file_rel.data,file_m2m.c2_files_m2m_id.cust_url`,
`items/c2_url?fields=file_rel.data.full_url,file_m2m.c2_files_m2m_id.cust_url`,
`items/c2_url?fields=file_rel.data.thumbnails.url,file_m2m.c2_files_m2m_id.cust_url`.
Moreover, the request for non-existent field `file_rel.data.no_such_field`
'items/c2_url?fields=file_rel.data.no_such_field,file_m2m.c2_files_m2m_id.cust_url'  returns the same result.

**Comment by bjgajjar** [comment]
Currently, fields in the param are working with the column of database table.
The value of the `data` variable is not part of the `directus_files` table. To make this work I need to change in `ZendDb` files, which is not appropriate.

Thus as per the current structure, you need to use the data object with all the values.

**Comment by rtaubes** [comment]
Thanks. It makes the request simpler.

**Comment by bjgajjar** [comment]
@WoLfulus - I don't think so it's technically achievable. Can you please provide your thoughts on it?

**Comment by WoLfulus** [comment]
I'm not sure if I fully understand the problem here. Also, just so I can understand what you are thinking, why the changing zenddb?

**Comment by bjgajjar** [comment]
@WoLfulus - We have to change the file of `Zend-DB` as we have a `hook` to append these URLs. So we have to pass the params over there.

`hooks` are getting executed after the selection of data. Current API overwrote the method of selection and call the hooks after the data fetching process. Here, also the `params` are not getting passed. 

So to call this method we have to pass `params` from the `Zend-DB`.

Maybe it's difficult to describe whole stuff here. If you want then I can provide you the file wise changes also in slack channel for the better understanding.

**Comment by hemratna** [comment]
Not feasible
Ref. https://github.com/directus/api/issues/992#issuecomment-505351216
