### ISSUE TITLE
CLI install module use the Super Admin Token as Projectname

### ISSUE THREAD

**Issue by alrick** [directus/api#1674]
# Bug Report

## Steps to Reproduce
Based on https://docs.directus.io/guides/cli.html#install-module

1. Go to CLI
2. Run `bin/directus install:config -n <database-name> -u <database-user> -p <database-pwd> -N <projectname> -a <superadmin-token>`

## Expected Behavior
A config file is created `config/<projectname>.php`

## Actual Behavior
The config file is named after the Super Admin Token : `config/<superadmin-token>.php` and everything in the config file use the token instead of projectname too.

## Technical Details

- Directus 8.4.0

**Comment by alrick** [comment]
`php bin/directus install:database` doesn't seem to take the -N argument either.
How can I install the database without the CLI ?

**Comment by bjgajjar** [comment]
@rijkvanzanten - Should we close this as we're redeveloping the CLI module?

**Comment by rijkvanzanten** [comment]
Not unless we have it fixed. I believe I saw a PR for this the other day though

**Comment by bjgajjar** [comment]
@rijkvanzanten - TBH, I didn't see any PR related to this.  We have https://github.com/directus/api/pull/1614 only which is on hold for now. 

Let's put this also on hold until we do not merge the #1614

**Comment by hemratna** [comment]
@alrick 
Please use `-k` instaed on `-N`
`bin/directus install:config -n <database-name> -u <database-user> -p <database-pwd> -k <projectname> -a <superadmin-token>`

**Comment by alrick** [comment]
@hemratna Thanks for the follow-up, I'll try this.

Please note that the documentation isn't fully updated, there is still a reference to the `-N` option in the Configure Directus options and the Upgrade Directus Schema example.
(https://docs.directus.io/guides/cli.html)

**Comment by hemratna** [comment]
I sent a PR for doc https://github.com/directus/docs/pull/297
Thanks a lot.
