### ISSUE TITLE
Create the API as a package

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#168]
We talked about this at the beginning but I can remember if we created a ticket for it or mention it somewhere. Before I forget about this again, It would be ideal to create the API as a separate package that user can use as dependency of their projects.

In theory this repo uses this "package" but it needs to be split.

**Comment by benhaynes** [comment]
I like this! Would it need to be a new repo? Would this go into Composer?

**Comment by rijkvanzanten** [comment]
What are we discussing exactly? How is this supposed to work? What is the benefit for the end user?

**Comment by WellingGuzman** [comment]
I see two advantages:

The user can install set whatever they prefer to be the entrypoint, where the configurations are located, etc.

The user can install the API as a dependency in their project which makes easier to integrate with other project and easier to add more dependencies such as third party authentications without the directus `composer.json`.

**Comment by benhaynes** [comment]
I think we want to have clean ways for devs to integrate Directus into their existing project/workflow. Being able to add Directus into _their_ project/composer seems like a nice option... but this should wait until after 7/2 is released and stable/documented.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
