### ISSUE TITLE
Error in m2m relation, finding "visible columns"

### ISSUE THREAD

**Issue by onlinelessons** [directus/api#1680]
I have an error in one of my m2m relations. I have a courses and a lessons collection with a relational table. The lessons have a string input "name", which i want to display in the app, so i selected "name" as "visible column":
![image](https://user-images.githubusercontent.com/47600858/72886554-4aac6200-3d0a-11ea-9661-9c2d4cd6e742.png)

The I try to select an existing lesson in the app but I get an empty modal and no lessons to select. In the console I get an error 500 for the API call:
https://myapiurl.com/lessons?limit=200&offset=0&meta=*&fields[0]=name.*&fields[1]=id&sort=name

I found out that the problem is the .* after the name field. If I remove this, I get a valid result.
Why is this .* used here? Is this a bug or do I have to change something?

**Comment by bjgajjar** [comment]
>Is this a bug or do I have to change something?

Neither it's a bug not you need to change anything. As I sent you the recoding in the slack channel - it's working as expected in the latest version. 

If you can provide the SQL dump then I can debug the issue.
