### ISSUE TITLE
Make default default_locale in settings null

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#1682]
This allows the app to fallback to the browsers language if the default locale hasn't been set.

Ref https://github.com/directus/app/pull/2369

**Comment by bjgajjar** [comment]
@rijkvanzanten - Let me clear the stuff again.

As per you mentioned we need to update the default value of `default_locale` from `en-US` to `NULL` so APP can detect the user's local language from `window.navigator.language`.

But let me draw your attention that if we implement this change then those users who are using the stand-alone API will also get a `NULL`  - obviously which will not affect the system as they can set it from `settings` API.

**Comment by rijkvanzanten** [comment]
I'm talking about the `default_locale` setting in `directus_settings`. That's only used for the app right?

**Comment by bjgajjar** [comment]
The users who are using the stand-alone API can also use it for their frontend. Let's not create a confusion on that. Let's update it as we're just upading the default value only which is not a _breaking change_.

**Comment by rijkvanzanten** [comment]
I doubt that. `directus_settings` are all very clearly settings for the Directus platform itself. Even then, we're changing the default value, not overriding any setting that they already have stored in the DB

**Comment by bjgajjar** [comment]
>directus_settings are all very clearly settings for the Directus platform itself.

Okay but as per my understanding users have a `settings` API so they can use the same for their own site also.

>Even then, we're changing the default value, not overriding any setting that they already have stored in the DB

That's what I'm saying as we're just updating the default value and not overwriting it - it's not a _breaking change_
