### ISSUE TITLE
Feature request: Custom permission level

### ISSUE THREAD

**Issue by dannycoulombe** [directus/api#1684]
Level permissions are a bit limited.

Some sort of capability to extend the level permissions would be very neat.

**Scenario 1:**

- User A send a message to user B.
- User B fetch messages and should be able to fetch his messages and those sent to him (with to_user field for instance)

**Scenario 2:**

- User A, B and C join a room
- User A send a message
- User A, B and C should be able to fetch messages from A, B and C but not D, E or F

**Suggestions:**

Some way to extend the ACL interface in order to add our own permission level in the interface.

![image](https://user-images.githubusercontent.com/10353756/72918047-feb1eb00-3d12-11ea-86cb-014194ff77dd.png)

**Comment by benhaynes** [comment]
I'll reference and close this as a duplicate: https://github.com/directus/api/issues/511

We have an idea of "dynamic permissions" that we'll be looking into in our new Laravel API port. This should cover your example and anything/everything else too. 😄
