### ISSUE TITLE
Getting the error "You have an error in your SQL syntax" when migrating from V7 to V8

### ISSUE THREAD

**Issue by jasonmarysael** [directus/api#1687]
# Bug Report

When trying to upgrade from V7.0.18 to the latest version (according the instructions on https://docs.directus.io/guides/upgrading.html & the migration notes as described[ here](https://github.com/directus/directus/releases/tag/v8.0.0l)) I'm getting the following error when opening the login page:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'template\":[{\"title\":\"$t:collections\",\"include\":\"collections\"},{\"title\' at line 1

full stack trace: 

`[2020-01-22 21:15:52] api[mafest].ERROR: PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'template\":[{\"title\":\"$t:collections\",\"include\":\"collections\"},{\"title\' at line 1 in 'path to directus directory'/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:134
Stack trace:
#0 'path to directus directory'/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(134): PDO->exec
directus/directus#1 'path to directus directory'/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(171): Phinx\Db\Adapter\PdoAdapter->execute
directus/directus#2 'path to directus directory'/vendor/robmorgan/phinx/src/Phinx/Migration/AbstractMigration.php(221): Phinx\Db\Adapter\AdapterWrapper->execute
directus/directus#3 'path to directus directory'/migrations/upgrades/20190318173400_add_nav_override.php(24): Phinx\Migration\AbstractMigration->execute
directus/directus#4 'path to directus directory'/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(127): AddNavOverride->up
directus/directus#5 'path to directus directory'/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(375): Phinx\Migration\Manager\Environment->executeMigration
directus/directus#6 'path to directus directory'/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(351): Phinx\Migration\Manager->executeMigration
directus/directus#7 'path to directus directory'/src/core/Directus/Util/Installation/InstallerUtils.php(244): Phinx\Migration\Manager->migrate
directus/directus#8 'path to directus directory'/src/core/Directus/Util/Installation/InstallerUtils.php(231): Directus\Util\Installation\InstallerUtils::runMigrationAndSeeder
directus/directus#9 'path to directus directory'/src/core/Directus/Application/Http/Middleware/DatabaseMigrationMiddleware.php(13): Directus\Util\Installation\InstallerUtils::updateTables
directus/directus#10 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
directus/directus#11 'path to directus directory'/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#12 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#13 'path to directus directory'/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#14 'path to directus directory'/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
directus/directus#15 'path to directus directory'/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack
directus/directus#16 'path to directus directory'/vendor/slim/slim/Slim/App.php(503): Slim\Route->run
directus/directus#17 'path to directus directory'/src/core/Directus/Application/Http/Middleware/AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
directus/directus#18 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
directus/directus#19 'path to directus directory'/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#20 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#21 'path to directus directory'/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#22 'path to directus directory'/vendor/directus/proxy-detection/src/ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
directus/directus#23 'path to directus directory'/src/core/Directus/Application/Http/Middleware/ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
directus/directus#24 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
directus/directus#25 'path to directus directory'/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#26 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#27 'path to directus directory'/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#28 'path to directus directory'/vendor/akrabat/ip-address-middleware/src/IpAddress.php(113): Slim\App->Slim\{closure}
directus/directus#29 [internal function]: RKA\Middleware\IpAddress->__invoke
directus/directus#30 'path to directus directory'/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#31 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#32 'path to directus directory'/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#33 'path to directus directory'/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->Slim\{closure}
directus/directus#34 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
directus/directus#35 'path to directus directory'/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#36 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#37 'path to directus directory'/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#38 'path to directus directory'/src/core/Directus/Application/Http/Middleware/ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
directus/directus#39 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
directus/directus#40 'path to directus directory'/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#41 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#42 'path to directus directory'/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#43 'path to directus directory'/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
directus/directus#44 'path to directus directory'/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
directus/directus#45 'path to directus directory'/vendor/slim/slim/Slim/App.php(297): Slim\App->process
directus/directus#46 'path to directus directory'/src/core/Directus/Application/Application.php(161): Slim\App->run
directus/directus#47 'path to directus directory'/public/index.php(5): Directus\Application\Application->run [] []`

I have no issues when performing a new installation from the latest version. 

My guess is that the autom. db schema upgrade fails. I'm getting the same error when trying to upgrade the db via CLI (with the command bin/directus db:upgrade -N project-name). 

Any suggestions ?

## Technical Details

- Web Server: Apache/2.4.29
- PHP Version: 7.2.16
- Database: mysql  Ver 14.14 Distrib 5.7.28, for Linux (x86_64)
- Install Method: cloned `master` branch

**Comment by rijkvanzanten** [comment]
I haven't seen this issue before.. Might be that a specific version of MySQL / PHP doesn't handle the stringified JSON very well.. 

A temp workaround is to manually delete the `/migrations/upgrades/20190318173400_add_nav_override.php` file. I'll push a fix in a min
