### ISSUE TITLE
Throw appropriate error on wrong field name 

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#169]
Trying to POST or PATCH a non-existing fieldname returns a nasty 500 SQL error:

`Failed generating the SQL query. Statement could not be executed (42S22 - 1054 - Unknown column 'rijk' in 'field list')`

This should be a 422 error

**Comment by WellingGuzman** [comment]
Can you add more details on how to reproduce this issue?

**Comment by rijkvanzanten** [comment]
When POSTing or PATCHing to a collection, lets say `POST https://demo-api.directus.app/_/items/showtimes` with a field that doesn't exist in the body, like 
```
{"non-existent":"field"}
```

it returns

500 Internal Server Error

```json
{
  "error": {
    "code": 9,
    "message": "Failed generating the SQL query.",
    "query": "INSERT INTO `showtimes` (`non-existent`) VALUES ('field')"
  }
}
```

I think this should be a 422 instead of a 500
