### ISSUE TITLE
API removes auto increment if hidden on browse is changed

### ISSUE THREAD

**Issue by ithiru** [directus/api#1691]
Version - v8.4.0
Error Message - id: This value should not be blank.

Steps

- Created new collection - turn on the Sort toggle, Modified On and Modified By
- Edit the Default primary key column 'id' by selecting it
- Go to schema Tab, Turn off 'Hidden on Browse'
- Click on 'Next'
- Click on 'Save'
- Go to the newly created collection to add new Row
- Click  on '+' at top right
- You will see only status with default 'Draft' selected - Leave it as is
- Click on 'Tick' button at top right.
- Displays Error Message 'id: This value should not be blank.'

My expectation is that the id column should be displayed on the list, but during add/edit, should not display. During add it should auto generate the id.

**Comment by elfatherbrown** [comment]
Can confirm exact same case.

**Comment by ithiru** [comment]
I took the tag 8.5.0 and tried this, I see the same issue. It is not allowing and throwing the same error. This is the steps I followed.

git pull
git checkout v8.5.0
php bin/directus db:upgrade -N - Verified the migrations ran by checking the directus_migrations table.

Accessed the app via url,
modified the id field and disable Hidden on Browse

Add new Item to collection and gets the same error. - 'id: This value should not be blank.'

Am I missing anything? Please assist

**Comment by ithiru** [comment]
Tested the same in v8.5.4 and the default value is not saving..:-(

**Comment by urvashithakar** [comment]
@rijkvanzanten  It is related to #1601

**Comment by hemratna** [comment]
@rijkvanzanten I think it is related to #1601.

**Comment by hemratna** [comment]
@ithiru 
I fixed this issue with PR #1764.
Please check it and if issue is solved then close it.

**Comment by ithiru** [comment]
@hemratna Thanks, did this change go to directus/directus repo? I see the latest tag is v8.5.5. Should I wait the push or the 8.5.5. has all these changes?

Please confirm

**Comment by rijkvanzanten** [comment]
@ithiru this hasn't been released to directus/directus yet. I'm planning on pushing out a release tomorrow.

**Comment by rijkvanzanten** [comment]
Fixed in #1764
