### ISSUE TITLE
The X-Total-Count header is missing in the HTTP Response

### ISSUE THREAD

**Issue by chinnumv** [directus/api#1695]
Can you please add X-Total-Count header in HTTP Response for pagination?

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
This is a non-standard HTTP header. We can add it, but I believe that we already support the same use case through the meta param like @shealavington mentioned.
