### ISSUE TITLE
/:project/items/:collection/:slug

### ISSUE THREAD

**Issue by ahmtaras** [directus/api#1699]
First of all thank you for the application. Sorry my English is a little weak.
Can we call with slug instead of id? Would you consider adding something like this? I am thinking of throwing slug as a props in Vue application.
`/:project/items/:collection?filter[slug][eq]`" I can use the method, but the collections will slow down as they grow.

**Comment by benhaynes** [comment]
I defer to @directus/api , but I think the logic in the API would be the same regardless of the URL format... so I don't think there will be a performance change moving away from the filter syntax.

**Comment by benhaynes** [comment]
Wouldn't it also work to use the slug as the primary key? That solves the problem too, right!

**Comment by rijkvanzanten** [comment]
Theoretically speaking, the filter parameter shouldn't do anything different than the `/:id` endpoint if you think about it. `/:id` is selecting

```
WHERE `id` = `...`
```

just like filter. 

I also believe that adding support for setting up any field as primary key will solve this request like @benhaynes mentioned. Then you can use a slug field for the primary key, and it will be `/items/:collection/:slug`

**Comment by ahmtaras** [comment]
@benhaynes @rijkvanzanten 
Yes, it will give the same result if we set the primary area as leech. Can we currently set slug or any field as primary key?

**Comment by benhaynes** [comment]
Not through the App GUI, but you can work around it by making the changes in the database directly. We're hoping to include `string` PKs in the near future.
