### ISSUE TITLE
PHP warning updating M2O field

### ISSUE THREAD

**Issue by jeffnoparking** [directus/api#1700]
This bug happens only when "env" is set to "staging" or "development" in configuration file (because "production" value silences the error).

Here is how to reproduce it :

Create a collection "test_a" and two items of it.
Create a collection "test_b" with a "test_a" field in a M2O relation with "test_a" collection.
Create one item of test_b, the try to update its "test_a" field with a PATCH request.
Then the JSON returned by the API cannot be parsed because of a PHP warning inserted:
`warning:  array_filter() expects parameter 1 to be array, string given in [...]/src/core/Directus/Services/ItemsService.php on line 177`

(Tested with Directus 8.4.0)

**Comment by bjgajjar** [comment]
Fixed in https://github.com/directus/api/pull/1705
