### ISSUE TITLE
Add Background Job Queue

### ISSUE THREAD

**Issue by arturhasselblad** [directus/api#1703]
With risk for duplication (#560 ) i see that the scope of what a background job should do might include tasks like batch update of larger amount of articles in a table in a non-blocking fashion. Updating 200 items (2 fields) in a test database takes a number of seconds, and blocks from accessing the UI. A typical use case here would be setting a new status, or assigning a larger number of posts to a user, or 
classifying records.

**Comment by benhaynes** [comment]
So this is more about a task worker for queueing system processing?

**Comment by arturhasselblad** [comment]
Exactly, should have been more precise in the request. Basically what i think we would like to achieve is to support batch operations of different kinds - mostly writes to DB since they might become a bit expensive depending on the model,  but also bulk import of data trough UI, in a non-blocking way. This opens up for more use cases like automatic generation of thumbnails in different formats, or batch exports of data using custom code.

**Comment by arturhasselblad** [comment]
I think what i'm looking for in this specific case is a way to handle bulk updates and be able to work within the system on other tasks, and get back a notification when the task is complete. Currently if i have a number of webhooks/actions and do an update on 50-100 items i need to wait for the operation to finish.

**Comment by benhaynes** [comment]
Ahh, sounds similar to the "idea" behind this outdated and sparse issue...

https://github.com/directus/api/issues/158

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
