### ISSUE TITLE
GraphiQL integration

### ISSUE THREAD

**Issue by matepaiva** [directus/api#1711]
# Feature Request
It would be really helpful to have a GraphQL IDE (like GraphiQL) within the project, so the admin could explore the data schema and test the data separated from the backend. 

## What problem does this feature solve?
The frontend developer could use it to navigate across the data and assemble the query using the back-office.

## How do you think this should be implemented?
I am new to the project, so I don't know. But I hope this could be installed as a third-party extension that would add a page to the admin panel.

## Would you be willing to work on this?
For sure, if I had some guidance.

**Comment by rijkvanzanten** [comment]
This should be added as a `/graphiql` endpoint next to the existing `/graphql` one

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
