### ISSUE TITLE
Webhooks Setup UX

### ISSUE THREAD

**Issue by benhaynes** [directus/api#1714]
Right now, if you have 20 Collections and want all of them to trigger a webhook... you need to manually setup 60 different webhooks in settings (each permutation).

I suggest that we change the schema a bit to make this easier:

* `directus_webhooks.collection` -> `directus_webhooks.collections` (CSV of collections)
* `directus_webhooks.action` -> `directus_webhooks.create` (boolean), `directus_webhooks.update` (boolean) and `directus_webhooks.delete` (boolean)

Now you can quickly setup a global webhook (eg: Netlify), but still have all the freedom.

Does that work @bjgajjar ?

**Comment by jorisvdz** [comment]
Hi, any updates on this? Would love to use this feature! :)

**Comment by benhaynes** [comment]
We have a full UX/UI for webhooks in the App already... this ticket is just to make it easier/faster to implement them. No other updates on timing.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by jorisvdz** [comment]
I know, I meant the global webhook option.

**Comment by benhaynes** [comment]
We try to keep these threads updated when there's news to share, unfortunately, there are no updates for this ticket at the moment. Our small open-source team is busy with core stability and other priority fixes, so the best way to get tickets pushed through is to [sponsor bug fixes](https://docs.directus.io/getting-started/supporting-directus.html#sponsored-bugs) or [commission feature requests](https://docs.directus.io/getting-started/supporting-directus.html#commissioned-features). Thanks for understanding! 🙂
