### ISSUE TITLE
Collections can be created without a primary key, which makes the collection unusable.

### ISSUE THREAD

**Issue by danielfrentz** [directus/api#172]
**Describe the bug**
A user is able to create a collection where none of the fields are set as the primary key. This causes issues when the user attempts to do anything with the collection, such as retrieve the fields for the collection, because it throws an error stating that the table has no primary key.

**To Reproduce**
Steps to reproduce the behavior

1. send a post request to `/collections?access_token=admin_token` with the body:

```json
{
    "collection":"test",
    "single":false,
    "hidden": false,
    "note":"hello world",
    "fields":[
        {
            "type":"integer",
            "field":"field1",
            "interface":"check"
        }
    ]
}
```

2. send a get request to `/items/test1?access_token=admin_token`

3. The response should contain `"message": "This row object does not have a primary key column set."`

**Expected behavior**
If the primary key is required, then I would expect to get a 400 when I attempt to create the collection.

**Comment by WellingGuzman** [comment]
Hey @danielfrentz thanks for catching this bug.

You are absolutely right there must be a `primary_key` field and an error should be thrown, I would get to this ticket tomorrow!

**Comment by danielfrentz** [comment]
@WellingGuzman Should it only check that a single field has primary_key set?

**Comment by rijkvanzanten** [comment]
@danielfrentz Front-end guy here 👋 Is that `primary_key` check on the flag or the interface used?
