### ISSUE TITLE
v8.5.3: Asset whitelist key input field always disabled

### ISSUE THREAD

**Issue by everyx** [directus/api#1728]
1. Version of Directus: 8.5.3
2. Steps to reproduce:
![bug](https://user-images.githubusercontent.com/1665522/73845766-4762bb80-485e-11ea-8c42-380701e16431.gif)

**Comment by rijkvanzanten** [comment]
@bjgajjar can you update the migrations to set the slug interface option `onlyOnCreate` to false for `asset_whitelist_system` ?
