### ISSUE TITLE
Use the filename to expose files

### ISSUE THREAD

**Issue by dobl1** [directus/api#1730]
Hello,

Following of https://github.com/directus/directus/issues/2563, tested in latest 8.5.3.

The new filename_downloaded / filename_disk is causing some trouble as the filename is modified by directus and we do not have the choice to use the original filename to retrieve it through directus API.

So to be precise, we have two things :

- The filename-disk replace the `_` by `-` in the filename when importing a file.
- The filename-download is not used when choosing to use the File Name (Readable) for the links. (still using the filename-disk), No options to do that.

**Comment by hemratna** [comment]
> The filename-disk replace the _ by - in the filename when importing a file.

I send PR #1775 

> The filename-download is not used when choosing to use the File Name (Readable) for the links. (still using the filename-disk), No options to do that.

This issue has been fixed on PR #1626
