### ISSUE TITLE
No rate limit on static files

### ISSUE THREAD

**Issue by jooola** [directus/api#1741]
After working a bit on the Vue.js application, I stumbled on this https://github.com/directus/app/blob/master/vue.config.js#L22-L23

Add as continuation of https://github.com/directus/app/pull/2573 I'd like to know wether the static files are rate limited or not ? Aren't static files supposed not to be processed by PHP when running a webserver ?
If yes, It would be smart not to rate limit them.

**Comment by jooola** [comment]
Ok I guess we can remove the comment at https://github.com/directus/app/pull/2573 since I jut checked, and the app don't notice that the webserver served the static files, so I don't think there is any rate limiting. So we can clean the app code.

**Comment by rijkvanzanten** [comment]
The API does not rate limit static files. The config in the app is made to not trip up _webserver_ rate limiters. If you're using Directus in a load balanced environment, it's not uncommon to have a rate limit on the load balancer itself. Enabling the prefetch tags will most definitely trip up rate limiters, as it would case ~250 reqs on first load
