### ISSUE TITLE
If there is a collection with only 1 field, no items can be added because the single field must be the primary key

### ISSUE THREAD

**Issue by danielfrentz** [directus/api#175]
**Describe the bug**
If you have a collection which only has a single field, then you cannot add any items because the payload validation checks to see if there are 0 items, or if there is a single item that this item is not the primary key. Not sure what the expect behavior should be?

Suggestions:

1) Allow collections with a single item. This would simply require modifying the validation when inserting an item.
2) Disallow collections with a single item, but then should it allow the creation of such a collection or should an error be thrown?

**Comment by benhaynes** [comment]
I am a bit lost with this one – @danielfrentz could you confirm that you are using `item` (a database record) and `field` (a database column) correctly?

Also not sure if this applies here, but we have a setting for tables/collections that specifically will only ever have ONE item (it's called `Single`).

Could you maybe clarify the issue a bit more? @WellingGuzman does this make sense to you?

**Comment by benhaynes** [comment]
Hey @danielfrentz – any updates here?
