### ISSUE TITLE
Add Support for Permissions in GraphQL Endpoint

### ISSUE THREAD

**Issue by gianniskarmas** [directus/api#1755]
Graphql right now is unusable in the front end as it requires admin token.
How to use it from the client side without logging as an admin?
Am I missing something here?

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
