### ISSUE TITLE
ID Auto-Increment breaks when I uncheck "Hidden on Browse"

### ISSUE THREAD

**Issue by medteck** [directus/api#1756]
When I uncheck "Hidden on browse" for the ID field, I can't create Items in this collection from the API nor the UI (app).

I get a 422 error from the API and this is what I find in directus logs :
`ERROR: Directus\Validator\Exception\InvalidRequestException: id: This value should not be blank. in /var/www/directus/src/core/Directus/Services/AbstractService.php:186`

• Version of Directus : 8.5.3

Thanks!

Edit:
I still get the same error when I check it again. I had to delete the collection and create another one where "Hidden on browse" is checked to make it work.

**Comment by hemratna** [comment]
@medteck 
I fixed this issue with PR #1764.
Please check it and if issue is solved then close it.

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/api/pull/1764

**Comment by medteck** [comment]
Thanks guys!
But I can't pull the changes because my repository is directus/directus (suite).
Will you update it in the next versions ?

**Comment by rijkvanzanten** [comment]
Yup! I'm planning on pushing out a release tomorrow afternoon (EST)

**Comment by medteck** [comment]
Awesome! Keep up the great work 💯
