### ISSUE TITLE
Fresh Directus 7 installation login fails using default credentials

### ISSUE THREAD

**Issue by khollund** [directus/api#176]
My api fails with this message when I try to login with the default admin user or request a user list with the default token:
`Statement could not be executed (42S22 - 1054 - Unknown column 'DF.note' in 'field list') SQLSTATE[42S22]: Column not found: 1054 Unknown column 'DF.note' in 'field list
`

Have I forgotten something in the setup?

I have installed the app from github master and the api is a build install. I have installed the default schema, not much else is done. I am running this on a WAMP setup for now. 

Versions as follows:
Apache/2.4.23 (Win64) 
PHP/5.6.25 
MySQL 5.7.14

**Comment by WellingGuzman** [comment]
Hey @khollund I have updated the `schema.sql` with the latest schema structure.
