### ISSUE TITLE
Getting "Couldn't reach api" after upgrading to 8.5.4

### ISSUE THREAD

**Issue by AstralProgrammer** [directus/api#1762]
Version: Directus: 8.5.4
Error: Couldn't reach API
PHP version: PHP 7.3
MySQL version: 8.0.17

The story so far:
I'm upgrading from **7.9.0** to **8.5.4**. I've have the github repo setup as an upstream then pulled and merged the master branch into a local branch.
I've followed the guide for upgrading in https://github.com/directus/directus/releases/tag/v8.0.0.
I've remove the **vendor** folder then re-run **composer install** to keep everything clean.

What I currently experiencing:
The login page is loaded just fine but once I logged in, it shows the loading bar then shows the "Couldn't reach API" error.
I've checked the requested endpoints and they are all returning 200. No error found on the log file as well.

**Comment by ale-rinaldi** [comment]
Hello,

we had a very similar issue, try to see if this can help:

- in the directus_settings table, try setting "project_logo" as empty string. This can be useful if you use Redis as cache backend, see #1701 
- also, in the directus_settings table, try setting "auto_sign_out" to a non-null value, for example 10080 that is the default in Directus8. See #1702 

Hope this helps ;)

**Comment by AstralProgrammer** [comment]
Setting the project_logo to null fixed the issue. Thanks @ale-rinaldi

**Comment by hemratna** [comment]
> Setting the project_logo to null fixed the issue. Thanks @ale-rinaldi

@AstralProgrammer 
Can you please close this issue? We have an open issue for `project_logo` #1701

**Comment by hemratna** [comment]
@rijkvanzanten 
As mentation by @AstralProgrammer this issue has been fixed.
Can you please close this issue?

**Comment by rijkvanzanten** [comment]
Closed in favor of #1701
