### ISSUE TITLE
500 Server error when API accessed over subdomain

### ISSUE THREAD

**Issue by leonceaklin** [directus/api#1783]
# Bug Report
500 Server error when API accessed over subdomain

## Steps to Reproduce
Make subdomain that points to "directus/public"

## Expected Behavior
API works fine when accessing it.

## Actual Behavior
Server error 500 when accessing it.

Output in logfile:
`#0 /home/klasseyc/public_html/magazine/content/vendor/slim/slim/Slim/App.php(518): Directus\{closure}
directus/directus#1 /home/klasseyc/public_html/magazine/content/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(71): Slim\App->__invoke
directus/directus#2 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
directus/directus#3 /home/klasseyc/public_html/magazine/content/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array
directus/directus#4 [internal function]: Slim\DeferredCallable->__invoke
directus/directus#5 /home/klasseyc/public_html/magazine/content/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func
directus/directus#6 /home/klasseyc/public_html/magazine/content/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
directus/directus#7 /home/klasseyc/public_html/magazine/content/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack
directus/directus#8 /home/klasseyc/public_html/magazine/content/vendor/slim/slim/Slim/App.php(297): Slim\App->process
directus/directus#9 /home/klasseyc/public_html/magazine/content/src/core/Directus/Application/Application.php(161): Slim\App->run
directus/directus#10 /home/klasseyc/public_html/magazine/content/public/index.php(5): Directus\Application\Application->run [] []
[2020-02-24 18:57:47] api[favicon.ico].ERROR: Directus\Exception\U`

## Other Context & Screenshots
Directus is inside a public_html folder. Subdomain points to directus/public.
The admin app loads fine and shows the error "Something is wrong with this project".

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: Linux 3.10.0-962.3.2.lve1.5.26.9.el7.x86_64
- Web Server: Apache 2.4.37
- PHP Version: 7.4
- Database: MySQL 8.0.12
- Directus Release Version: v8.0.0-rc.2
  - App Version: 8.5.5
  - API Version: 8.0.0-rc.2
- Install Method: FTP

**Comment by hemratna** [comment]
@leonceaklin As mentation in issue, you are using API Version: 8.0.0-rc.2
Can you please try with latest API and let us know?

**Comment by leonceaklin** [comment]
Thank you for the information. I will try it on tuesday and share the results.

**Comment by leonceaklin** [comment]
Yes! With the latest API, it works.
Thank you very much for the fix!

**Comment by leonceaklin** [comment]
In the newest version (Directos v8.7.2), this problem reappears with the same behaviour in the same environment as mentioned above.

**Comment by leonceaklin** [comment]
Is there something I can do to solve this? It already got fixed in a previous version and is now back again.
