### ISSUE TITLE
How to request specific thumbnail

### ISSUE THREAD

**Issue by gianniskarmas** [directus/api#1787]
How to request specific thumbnail?

[https://api2.konpoli.eu/api/items/banners?fields=t.image.data.thumbnails,t.main_title,t.subtitle,t.link&lang=de](https://api2.konpoli.eu/api/items/banners?fields=t.image.data.thumbnails,t.main_title,t.subtitle,t.link&lang=de)

Whatever I tried I just can't get only the needed thumbnail as a response.
Is there any workaround?

**Comment by rijkvanzanten** [comment]
I don't think there's a way to filter the subset of related data for a specific custom thumbnail like that. The only workaround would be to fetch the asset separately using the /assets endpoint

**Comment by benhaynes** [comment]
We could return the thumbnail URLs (based on the whitelist) as a metadata option... those URLs should be enough, right?

**Comment by rijkvanzanten** [comment]
It already does that, but it returns all the available thumbnails, not just a specific one you're looking for.

**Comment by gianniskarmas** [comment]
This becomes a problem because, while I have to keep the thumbnails needed by directus unaltered and also add 2-3 needed sizes for my needs, I end up with hundreds of not needed thumbnail paths on the response thus making it slower.
It would be amazing though if we could filter by their names like 'directus-medium-crop' etc.
