### ISSUE TITLE
Support fields param in `auth/authenticate` 

### ISSUE THREAD

**Issue by reddo** [directus/api#1792]
First, I want to start off by mentioning how great of an application this is. Congrats!

I've found issue #1462 where I think it was decided that the `auth/authenticate` should also return the user object and I think it was an awesome idea, but that endpoint doesn't return the avatar, just its ID, which is useless and forces me to make another API call, just to retrieve the avatar. Or am I missing something?

**Comment by benhaynes** [comment]
Did you try the `fields` parameter?

https://docs.directus.io/api/query/fields.html

**Comment by benhaynes** [comment]
Actually — now I see that this is a system endpoint. 🤔 

@directus/api thoughts?

**Comment by reddo** [comment]
Yes, but it does nothing. It doesn't mention fields as optional query param for auth.

**Comment by rijkvanzanten** [comment]
Lets consider this a feature request to add support for the fields parameter in auth/authenticate 👍

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
