### ISSUE TITLE
Webhook for all Actions

### ISSUE THREAD

**Issue by Arcath** [directus/api#1794]
I'm using Gatsby with Netlify pulling data from Directus.

I'd like to fire a webhook whenever any collection has nay action.

Might need some debouncing so that it doesn't fire hundreds of times when a big content change is being made.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
