### ISSUE TITLE
Weird behaviour when saving repeater->multiselect field

### ISSUE THREAD

**Issue by reddo** [directus/api#1797]
Directus API version 8.6.1
PHP version 7.3
MySQL version 10.2.27-MariaDB-cll-lve
Apache version 2.2.34

I've just updated to the latest version of Directus (8.6.1). I wanted to update a multiselect field's values in a repeater because I had a typo, but there was a weird duplication error.

This is what it looks before I save:

![Annotation 2020-03-04 215638](https://user-images.githubusercontent.com/1180060/75918750-f9dd6c80-5e64-11ea-8288-60ca04f7a37b.jpg)

And this is what I get when I reopen:
![Annotation 2020-03-04 215801](https://user-images.githubusercontent.com/1180060/75918749-f944d600-5e64-11ea-9b0d-1fc2788a8d5e.jpg)
![Annotation 2020-03-04 215805](https://user-images.githubusercontent.com/1180060/75918746-f8ac3f80-5e64-11ea-976e-35f67c63eb77.jpg)
![Annotation 2020-03-04 215811](https://user-images.githubusercontent.com/1180060/75918722-ec27e700-5e64-11ea-97b9-6158ff77f68c.jpg)

**Comment by everyx** [comment]
maybe the same problem of https://github.com/directus/app/issues/2385

**Comment by reddo** [comment]
yep, sounds similar

**Comment by reddo** [comment]
I've updated to Directus to 8.6.2, but this is still happening. Any update on this? It's been a while

**Comment by reddo** [comment]
Moved this issue to /app repository, I'm closing this.
