### ISSUE TITLE
Can't create a new project

### ISSUE THREAD

**Issue by bastienlabelle** [directus/api#1799]
Hello,

I'm using directus via docker-compose, so far I used 8.5.something and recently pulled the image to update v8.6.

I don't use env vars and I run multiple projects on the same instance.

Since 8.6 when I want to create a new project it asks for my Super Admin password, which I enter, then I follow the steps (project info, DB), and when I click on install, it says "Cannot find super admin token variable."

<img width="343" alt="Capture d’écran 2020-03-05 à 02 58 41" src="https://user-images.githubusercontent.com/117162/75940778-3bced880-5e8e-11ea-84fd-ace7d1b6a06f.png">

I've quickly explored the code and noticed that there's been a change recently in `src/core/Directus/Config/SuperAdminToken.php`. there: https://github.com/directus/directus/blob/9780f20d0c97251cdfddeee1bfc1d4048a8e94ff/src/core/Directus/Config/SuperAdminToken.php#L43

I haven't looked around in depth, but I saw that the `SuperAdminToken::path()` is used like that since v8.6: `$this->getBasePath().SuperAdminToken::path();` so I assume there's one call of getBasePath() missing somewhere because when I want to create a new project it's looking for /config/__api.json full path and can't find it.

**Comment by huzaifahj** [comment]
Hey, I'm getting this exact issue too. Have you found a solution?

**Comment by rijkvanzanten** [comment]
Fixed in https://github.com/directus/api/pull/1803 and released in v8.6.2
