### ISSUE TITLE
Ability to work with SQL views

### ISSUE THREAD

**Issue by sihingbenni** [directus/api#1800]
# Feature Request
Request that Directus gets the ability to render SQL views as a "collection"

***Not being able to edit/add any fields in this particular "collection"***

## What problem does this feature solve?

We would be able to join collections, not just two but as many as you'd like.
Being able to view SQL Views with directus.
Being able to sort/filter joined collections.

e.g.: I have two collections users and companies and have an many to one relationship from users to companies (each User has one Company) 

I can create a view like this: 
`create view users_companies as SELECT 'users'.*, 'companies'.*
    FROM 'users'
    , 'companies'
    WHERE 'companies'.'id' = 'users'.'company_id';`

And now I can easily filter all the users which work at Company A and have field B.
Because in Directus this view can be treated like an table.

## How do you think this should be implemented?
removing the multible occurring condition `'ST.TABLE_TYPE' => 'BASE TABLE' in MySQLShema.php` is the first step.

An additional reason why directus wont show the view, is that the SQL view has no primery key.
Which seems to be used to sort the collection. No sorting here for collections without a primary key could fix it.

In the meantime for views one should not be able to edit/add any fields. Searching, filtering or any other read operation may be allowed.

## Would you be willing to work on this?

It depends.

**Comment by rijkvanzanten** [comment]
Interesting idea! We should think about potential IO for this though. Would this be a "readonly collection" and work the same as every other collection, or should we have a separate `/views/` endpoint or something along those lines to manage these?

I think we should add a `/views/` endpoint to manage these views, and change `/items/:collection`  to be `/items/:collection-or-view`. That might cause naming conflicts though, as you won't be able to have a collection with the same name as a view. Views don't support any of the other methods for `/items` either, like POST or PATCH, so we might consider adding a separate "readonly /items" endpoint 🤔

**Comment by Oreilles** [comment]
Any updates on this ? I'd love to be able to browse views from within directus.

**Comment by benhaynes** [comment]
Are you asking specifically about Directus 8?

**Comment by Oreilles** [comment]
> Are you asking specifically about Directus 8?

About Directus 9!

**Comment by benhaynes** [comment]
OK, wrong repo then... you're looking for:

https://github.com/directus/directus/discussions/3097
