### ISSUE TITLE
Cookies: SameSite Attribute

### ISSUE THREAD

**Issue by pgegenfurtner** [directus/api#1819]
I'm using the latest Directus release (8.6.2).

I have an app that is connecting via the sdk/js to a directus project. The app runs a different domain than my directus instance.

On login I get (now with the latest Chrome release) this warning: `A cookie associated with a cross-site resource at API_URL was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

The cookie is not set and the app not usable.

If I understand this right, directus needs to set the cookie attribute `SameSite` to `None` (combined with the `secure` flag.)

Maybe the SameSite value should be configurable via the config / settings?

**Comment by Kematia** [comment]
Having the same issue right now... let me know if more info is needed.

**Comment by rijkvanzanten** [comment]
I'd like to add here that Safari seems to be moving to blocking all third-party (non-same-origin) cookies by default: 

https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/

**Comment by pgegenfurtner** [comment]
Interesting.. that would force us to use JWT. Which is currently not working when using the sdk (https://github.com/directus/sdk-js/issues/113)

Maybe I can debug hat a bit more on the weekend

**Comment by Kematia** [comment]
> Interesting.. that would force us to use JWT. Which is currently not working when using the sdk ([directus/sdk-js#113](https://github.com/directus/sdk-js/issues/113))

I had some success reverting to 5.3.4, but the token still does not persist between refreshes. Maybe I'm doing something wrong!

**Comment by Kematia** [comment]
> Interesting.. that would force us to use JWT. Which is currently not working when using the sdk ([directus/sdk-js#113](https://github.com/directus/sdk-js/issues/113))
> 
> Maybe I can debug hat a bit more on the weekend

The js-SDK was fixed to allow for token persistence, but not having the cookies kills any chance of ssr persistence (atleast with nuxt)

**Comment by Kematia** [comment]
I have a [tentative PR](https://github.com/directus/sdk-js/pull/168) to fix the sdk, but without cookies it's not possible to persist on a ssr app right now...

**Comment by pgegenfurtner** [comment]
Oh, nice. I will try that out!

An alternative might be to proxy the api requests. Could that work...?

**Comment by rijkvanzanten** [comment]
If it's purely server to server (like SSR) I'd go with a static token instead, save some trouble
