### ISSUE TITLE
Add ability to thumbnail an mp4 file

### ISSUE THREAD

**Issue by SemaphoreMetaphor** [directus/api#1824]
At the moment I can't seem to get it to work leading me to believe it's not currently supported

**Comment by benhaynes** [comment]
I don't think we're generating thumbnails for video files (except embeds). I'll add this as a Feature Request.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
