### ISSUE TITLE
Item API cannot get relational data

### ISSUE THREAD

**Issue by Castafiore** [directus/api#1825]
I have 2 tables `users` and `roles`, `users` has a foreign key `role_id` which references `role.id`, I have also configured M2O relation between `users.role_id` and `roles.id`, but when I call  /:project/items/users api, there is only role_id data, and I don't see any data from `roles` table. Could you tell me is there a way / api to get data of relational table such as my case?

**Comment by benhaynes** [comment]
It looks like you need the `fields` parameter in the API call. Please refer to this FAQ and API Reference:

https://docs.directus.io/getting-started/troubleshooting.html#why-is-my-relational-data-file-only-returning-an-id

**Comment by Castafiore** [comment]
Thank you @benhaynes
