### ISSUE TITLE
Add `!` support to fields parameter

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#183]
! means _not_. AKA setting the value of a parameter to `!` should _not_ include any of it:

`fields=*` all fields, `fields=!` no fields (eg no data)

**Comment by WellingGuzman** [comment]
This will break every other internal function that expects a `data` attribute.
We should put this on hold for the moment as it needs more time to restructure it.

**Comment by rijkvanzanten** [comment]
Haha yeah we don't want to break everything else for sure 😅

**Comment by benhaynes** [comment]
How is this useful? Would it just include an _empty_ `data` array so that things don't break? Couldn't the user just include the PK for bare minimum data?

I'll leave this as stale unless @rijkvanzanten (or someone else) thinks it's worth keeping around.

**Comment by rijkvanzanten** [comment]
@benhaynes If you want to get the count of items in a collection, you _have_ to fetch data. This would allow the user to fetch only the `meta` information. This would also allow you to fetch everything _except_ a certain field. For example `/users?fields=*,!password`

**Comment by benhaynes** [comment]
Gotcha... makes sense!

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
