### ISSUE TITLE
Add ACL to /assets/ endpoint

### ISSUE THREAD

**Issue by polds** [directus/api#1831]
# Feature Request

Either the ability to upload files to different locations or the ability ACL files. It would be nice to be able to upload ACL'd attachments to things like customer profiles or ticket records. Even in the demo application the tickets collections has attachments that are globally accessible (if using asset proxying).

## What problem does this feature solve?

At the moment file names are only uploaded as "security through obscurity", in the case of a customer profile or ticket system those attachments could be highly sensitive (pictures of PII, signed contracts, etc.). There is a very valid use case for publicly available assets in the case of content management, but for more sensitive resources either a separate upload location and/or ACL'd solutions would be ideal.

True you could disable asset proxying but I don't think that solves the issue as there may be legitimate need for Directus Users to see that and you'd need to replicate those ACLs at that service level.

## How do you think this should be implemented?

A couple of thoughts:
Maybe have `/uploads/` and `/downloads/` do an ACL check before proxying the asset? The "Files" collection would also need some tweaks, I don't think the one collection for all files approach would work for this where you'd have a mix of ACL'd vs non-ACL'd resources.

Get rid of the global "Files" collection and have files be a standard field that can be added to any other collection and then rely on the collection ACL.

## Would you be willing to work on this?

I might consider contributing a small amount, but cannot to commit to driving the full feature.

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
