### ISSUE TITLE
Required fields throw error when they have a falsy value

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#184]
For example, when setting the `hidden` field of a collection to `0` and trying to PATCH update another field, it throws:

```js
{code: 4, message: "hidden: This value should not be blank."}
```

Hidden already has a value `0` and thus shouldn't throw this error

**Comment by rijkvanzanten** [comment]
PATCH gives the same error 😱

**Comment by WellingGuzman** [comment]
I am not being able to reproduce this locally or the demo server. can you give me more details or perhaps share a schema that I can use to replicate this issue?

**Comment by rijkvanzanten** [comment]
![image](https://user-images.githubusercontent.com/9141017/41439874-7423a5c8-6ffa-11e8-9350-457a5476fcc0.png)

![image](https://user-images.githubusercontent.com/9141017/41439889-806e5c10-6ffa-11e8-9b22-a3483b0b31a9.png)
