### ISSUE TITLE
Feature request - I18n fallback through HTTP headers

### ISSUE THREAD

**Issue by Vadorequest** [directus/api#1840]
Allowing to provide a locale fallback value(s) would be a great addition to avoid over-fetching.

For instance, I used it a lot to fetch content in French, and automatically fallback to English if there was no content found in French (per-record, per-field). It also has no impact on the client side source code as using HTTP headers doesn't impact the API request body itself.

It's a big benefit for ROI and helps avoid weeks of development.

Without this feature, the main locale and its fallbacks must all be queried (FR + EN) and then the client has to perform extra work to keep the most relevant.

This would benefit both REST/GraphQL apis.

Usage example:
```js
fetch('https://directus.api/project/gql, {
  method: 'post',
  headers: {
    'directus-locale': 'FR, DE, EN',
    'Content-Type': 'application/json',
  },
  body: '{"query": "{ robots { greeting } }"}',
})
  .then(res => res.json())
  .then(data => {
    console.log(data);
  })
  .catch(function(error) {
    console.log(error);
  });
```

Resources:
- Similar to https://docs.graphcms.com/docs/api/content-api/#passing-a-header-flag

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by Vadorequest** [comment]
@benhaynes What do you think about the 80/20 for this feature?

Also, I couldn't find any fallback i18n documentation, is there any similar feature available (or v9) that would (even partially) match this need?

**Comment by benhaynes** [comment]
It's not something we've been discussing for v9, but once 9.0.0 is out we can discuss more. I don't know enough about this to say if it's 80/20 or not, so we'll need to discuss with the team/community first.

**Comment by Vadorequest** [comment]
It's super important to avoid overfetching data, especially for people who display content in multiple potential languages. We currently use it in order to always display something to the end-user, even if it's not their native language, and this doesn't affect our programming, as it's automatically handled by the server.

How can we conduct a survey?

**Comment by benhaynes** [comment]
Our filtering should allow for choosing the multilingual data to return — and if it doesn't we'll need to update it to do so. Moving this to the headers is more of a technical question for @directus/team

**Comment by Vadorequest** [comment]
Do you mean you have a current way of doing that, or do you mean your "hypothetical filtering"? 🤔 
I couldn't find any doc related to this, so if there are any I'm interested.

**Comment by rijkvanzanten** [comment]
Re headers or not: this will most definitely be lang query parameter `?lang=nl-NL,en-GB,en-US`.

**Comment by Vadorequest** [comment]
I think they had chosen headers because it's a GraphQL backend and it makes more sense than query params.

But honestly, both seem fine to me, as long as it's REST/GraphQL compatible.
