### ISSUE TITLE
Error Code 3 Unauthorized request

### ISSUE THREAD

**Issue by Varulv1997** [directus/api#1841]
Hello there !
I deployed directus (latest release) on GCP App Engine using PHP 7.2 (changed version in composer.json for a successful deployment)
It redirects me to the admin page when accessing with the following error:

`{"error":{"code":3,"message":"Unauthorized request","class":"Directus\\Exception\\UnauthorizedException","file":"\/app\/src\/helpers\/app.php","line":287}}`

What did I miss ?

**Comment by benhaynes** [comment]
@directus/team — is GCP officially supported? Any ideas about this error?

@Varulv1997 — since this is likely a config issue or due to your server/stack, I would recommend taking this to StackOverflow or our Slack community for help.

**Comment by Varulv1997** [comment]
No GCP is not solved and many many users find difficulties to set it up on it, specifically on App Engine, any LAMP/LEMP stack should run it smoothly.
However I solved my problem on GCP App Engine. Much Thanks.

**Comment by arun-kumar-mm** [comment]
Hi Anyone,

I am also facing the same error, could you please help to resolve this issue? Any solutions or Any suggestions?
