### ISSUE TITLE
Add `field` / other info keys to errors

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#185]
In an error like:

```js
{code: 4, message: "hidden: This value should not be blank."}
```

It's quite hard to get the field (`hidden`) out of the message programmatically. It would be nice if these variables could be extracted into their own fields as well:

```json
{
  "code": 4,
  "message": "hidden: this value should not be blank",
  "field": "hidden"
}
```

That way, I can use them to translate the error messages dynamically 😄

**Comment by WellingGuzman** [comment]
Moved to #7
