### ISSUE TITLE
Generate migrations on collection changes

### ISSUE THREAD

**Issue by medteck** [directus/api#1850]
For multi-tenant applications, every time changes are made on collections, we have to create a SQL migration script by our own, and run it on each instance of directus (tenants). And sometimes, these migration scripts can create bugs because they are written by the developer instead of being generated.

That would be cool to have a migration generated, each time the user makes changes on collection fields for example. These migrations could be logged in a new table (different from directus_migrations which is made for directus updates). Or they could just be logged into a file so that the developer can pick the migrations he want from it.

I'm really struggling with that right now because I'm maintining a multi-tenant app with the same data model for all users.

Thanks!

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
