### ISSUE TITLE
Allow Editing System Collections (eg: Directus Users)

### ISSUE THREAD

**Issue by ketancmarix** [directus/api#1852]
API stopped working after disabling soft delete

# Bug Report

## Steps to Reproduce
1. Edit "directus_users" user collection 
2. Go to the "Status Mapping" section and open "Deleted" status 
3. Disable soft delete from "Deleted" status and then save

Recorded video to reproduce the problem: https://drive.google.com/open?id=1zRINHsFm1wLl5nu8_8v3er8s4n1jAfZr

## Expected Behavior
The app should work and user collection should have soft delete functionality disabled

## Actual Behavior
API and Directus backend is stopped working and getting the error "Something is wrong with this project's server or database"

## Other Context & Screenshots

Error Screenshot:
![image](https://user-images.githubusercontent.com/12895021/79120763-4fd0f880-7db1-11ea-8655-56619821c3ec.png)

## Technical Details

- Device: Desktop
- OS: Windows 10
- Web Server: Apache 2.4
- PHP Version:  7.2.0
- Database:  MySQL 8.0.12
- Directus Release Version: v8.6.2
- Install Method: cloned `master` branch

**Comment by benhaynes** [comment]
Directus does not yet allow for editing system collections — we will be enabling this soon, but as of now these Collections and Fields are locked and should not be changed. Some edits _may_ work, but this is not officially supported, and so we'll call this an enhancement (not a bug).

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by ketancmarix** [comment]
@benhaynes We don't need soft delete functionality into the user collection. What would be the right way to disable soft delete?

**Comment by benhaynes** [comment]
There's no official way to do that as of now — so the best thing is to promote/sponsor the feature request.
