### ISSUE TITLE
Feature Requests : Share users between many projects.

### ISSUE THREAD

**Issue by nathannau** [directus/api#1867]
Unless I am mistaken, it is not yet possible to centralize user management on several projects.

You should be able to copy a user from one project to another, and keep a synchronization of passwords.

In addition it would be good to be able to change the project without needing to reconnect if the user exists on the destination project.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
