### ISSUE TITLE
Auth provider icon url is tagged as the absolute url

### ISSUE THREAD

**Issue by akadoya** [directus/api#1887]
Hi, 

We have deployed directus app instances behind multiple frontend domains to separate the endpoints for the public access through CDN and for the admins that is only accessible through our VPN.
To do so, because one of the domain is shared with other services, we have set up nginx to proxy  
http://DomainA/cms/$PATH to http://<directus_app_server>/$PATH.
This seems working for most of the paths, however the okta icon is linked to an absolute uri in the html tag on the login page.
<img width="1051" alt="Screen Shot 2020-05-13 at 4 21 59 PM" src="https://user-images.githubusercontent.com/12196798/81875793-f2f26a80-9535-11ea-9f87-873c10e95b0c.png">

So even if we add a path prefix at the frontend domain and use the reverse proxy setup, this image tag is statically calling the root path level path thus returns 404. /extensions path is very generic and could be overlapping with the other tools that shares the domain so I cannot add that path to the proxy_pass rule for the directus app either.

https://github.com/directus/directus/blob/9780f20d0c97251cdfddeee1bfc1d4048a8e94ff/src/core/Directus/Services/AuthService.php#L156
I believe this is where the image URL is generated. Can this be a relative path so the use case like ours would be covered?

• Version of Directus (must be the latest) : v8

**Comment by rijkvanzanten** [comment]
Sure! I don't see any problem with that. Feel free to open a PR to change that out 🙂

**Comment by akadoya** [comment]
thanks! I made a PR for that
