### ISSUE TITLE
Underscore in config keys prevents ENV var usage

### ISSUE THREAD

**Issue by ondronix** [directus/api#1890]
Underscore '_' in config keys makes impossible to set some config via env vars.

For example: `['cache']['response_ttl']` cannot be set using `DIRECTUS_CACHE_RESPONSE_TTL`.

`Context::from_map($_ENV)` should be adjusted or no underscores have to be allowed in config keys.

**Comment by rijkvanzanten** [comment]
@WoLfulus I'm pretty sure you mentioned this before. Did we ever come to a solution on that?

**Comment by rijkvanzanten** [comment]
> no underscores have to be allowed in config keys.

This is not something we can just change like that without it being a breaking change (lets account for it in api-next @WoLfulus )

**Comment by WoLfulus** [comment]
> I'm pretty sure you mentioned this before. Did we ever come to a solution on that?

Right now, we strip the underscore out of keys and keep it just to separate between groups (like cache -> response_ttl).

The correct keys are documented on https://docs.directus.io/docker/environment.html#all-variables though
