### ISSUE TITLE
Return file data in file.save hook

### ISSUE THREAD

**Issue by vilords** [directus/api#1900]
Just wondering why file.save returns only the actual filename .. and not all data related to the file the same way as when calling file.delete

At this moment, if I need to get more info ... I need to use a db query.

Thanks!

**Comment by rijkvanzanten** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/app/projects/45) project board.

**This issue being closed does not mean it's not being considered.**
