### ISSUE TITLE
Argument 3 passed to Directus\\Services\\AbstractService::validatePayload() must be of the type array, null given

### ISSUE THREAD

**Issue by abu7elo** [directus/api#1920]
Hi All,

I was trying to add a new item "Collection name post" that have the following fields:

- title
- description
- user_id
- tags
- category < M2M Relational Field >

Below is my curl request:

`
curl --location --request POST 'http://directus.local/tajrobtak/items/post?access_token=2P50KvwMIdZrSSzwgtU*****' \
--header 'Content-Type: application/json' \
--data-raw '{

            "title": "Hello API",
            "description": "<p>Test</p>",
            "user_id": 1,
            "tags": [
                "ali",
                "mazen"
            ],
            "map": {
                "lat": 31.955330136228707,
                "lng": 35.92868328094483
            },
            "category":[1,2]
        }'
`

After consumed the endpoint, i got the below error message:

- HTTP: 500 Internal Server Error
- Response
`
{
    "error": {
        "code": null,
        "message": "Argument 3 passed to Directus\\Services\\AbstractService::validatePayload() must be of the type array, null given, called in /Users/fayezabuhilow/Projects/www/tajrobtk/src/core/Directus/Services/ItemsService.php on line 238",
        "class": "TypeError",
        "file": "/Users/fayezabuhilow/Projects/www/tajrobtk/src/core/Directus/Services/AbstractService.php",
        "line": 380
    }
}
`
So, could you please let me know how i can pass the category parameters in my request?

<img width="1095" alt="Screen Shot 2020-05-31 at 11 42 00 AM" src="https://user-images.githubusercontent.com/5948026/83348297-d75bd200-a333-11ea-80fc-b8f5a03f0915.png">

**Comment by abu7elo** [comment]
I figured out how to make the request.

**Comment by pg-bdlcm** [comment]
Could you explain to me, how you solved this problem ? (I have the same error)
