### ISSUE TITLE
Collections endpoint error returns 404

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#193]
**Describe the bug**
When `directus_collections` contains a collection that doesn't exist in the database, the API returns the following error:

```
{"error":{"code":200,"message":"Unable to find collection: test0","class":"...
```

This error is returned with a 404 status code.

**To Reproduce**
1. Add a row to `directus_collections` with a non-existing collection name
2. Fetch the collections through the `/collections` endpoint
3. See error

**Expected behavior**
I expected the API to return a 500 error

**Comment by WellingGuzman** [comment]
Why does this have to be 500?

**Comment by rijkvanzanten** [comment]
Because something is wrongly setup in the database and `/collections` is an endpoint that exists and is valid (and thus shouldn't throw a 404)

**Comment by WellingGuzman** [comment]
You are correct, I read it wrong.

I believe we should ignore collections (_and log a warning_) that has record in `directus_collections` but the table doesn't exists instead of throwing errors.
