### ISSUE TITLE
Add default_value attribute to fields endpoints

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#199]
**Describe the bug**
The API doesn't return the `default_value` field in `/fields`

**To Reproduce**
1. Request `/fields/:collection`
2. Notice the lack of `default_value`
3. Tear up a little

**Expected behavior**
I expected the API to return the `default_value` of the field together with the rest of the field info

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/api/commit/39db07c9faa79f3be8eaa68561a61adda89597a5
