### ISSUE TITLE
Fix Collections+Fields relations

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#203]
Allowing relation between fields and collections

**Comment by benhaynes** [comment]
@WellingGuzman — could you add more info to this ticket so it's clearer? I don't understand what it means.

**Comment by WellingGuzman** [comment]
Allow relationship between `directus_fields` and `directus_collections`, at the moment this relationship are fixed.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
