### ISSUE TITLE
Role Permission Values

### ISSUE THREAD

**Issue by benhaynes** [directus/api#204]
@WellingGuzman – I've updated the string values for permissions (and we had to split `comment` and `explain`). Could you take a look?

https://github.com/directus/api/wiki/Role-Permissions

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/api/commit/0c4e0d6c7d0bee450710c2dd95281358e47920c6 and https://github.com/directus/api/commit/e3e19160d7f7578dc7120651e0fd3c889017ddc0
