### ISSUE TITLE
Support full range of params on system endpoints

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#207]
**Is your feature request related to a problem? Please describe.**
Useful parameters like `filter` and `sort` don't seem to work for all system endpoints.

**Describe the solution you'd like**
All endpoints that are available for getting regular items should work for all system endpoints too

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
