### ISSUE TITLE
Allow binary uploads for files

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#211]
Uploading a file in binary (content-type: image/jpeg) results in 

```
{
    "error": {
        "code": 13,
        "message": "Invalid or Empty Payload",
        "class": "Directus\\Exception\\InvalidPayloadException",
        "file": "/Users/rijkvanzanten/Development/api/src/core/Directus/Application/Route.php",
...
```

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
