### ISSUE TITLE
Update version number in API

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#220]
The API still returns alpha 1 as version in the API info. What controls this number in the API?

**Comment by WellingGuzman** [comment]
This value is on [src/core/Directus/Application/Application.php](https://github.com/directus/api/blob/master/src/core/Directus/Application/Application.php#L16)

**Comment by benhaynes** [comment]
Do we have a document that describes exactly what needs to happen for version releases? If not let's create one now.

We need to add this (`Update version in Application.php`) to those version steps... then we can re-close this.

**Comment by WellingGuzman** [comment]
Added into https://github.com/directus/api/wiki/Deploying-Versions
