### ISSUE TITLE
Change allowed_statuses to status_blacklist

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#226]
**Is your feature request related to a problem? Please describe.**
We treat the management of fields on a blacklist bases; eg: when adding a fieldname to the column, it _disables_ the field. However, statuses work the other way around. Adding a status name to the column _activates_ it. This also means that by default all the statuses are _disabled_. 

**Describe the solution you'd like**
Instead of calling it `allowed_statuses` (and thus making it opt-in), name it `status_blacklist` (in line with `read_field_blacklist` and `write_field_blacklist` and make it opt-out.

**Describe alternatives you've considered**
The alternative would be to add all the fields on create of new rows, but this seems like an extra (unnecessary) hassle.

@benhaynes thoughts?

**Comment by benhaynes** [comment]
Very good point, I agree. 💯
