### ISSUE TITLE
Can't update / create fields

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#228]
**Describe the bug**
`"Payload fields: "length" does not exists in "directus_fields" collection."`

**To Reproduce**
1. Create a new field
2. API returns above error

**Expected behavior**
It should create the field. The `length` field should be used to set the length in MySQL

**Comment by WellingGuzman** [comment]
I can reproduce this using `PATCH`. Can you give me an example using `POST` that I can use to reproduce this issue?

**Comment by rijkvanzanten** [comment]
Ohh you separated the update / create functions ofc. I assumed it would happen to both seeing that used to be the same thing. Lemme see if I can reproduce it in POST
