### ISSUE TITLE
POST /activity/comment 404s every time

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#233]
![image](https://user-images.githubusercontent.com/9141017/42221185-91f2b2f2-7ed1-11e8-97b2-9e629f22c6e5.png)

It always returns a 404, even if the item / collection combo exists

**Comment by WellingGuzman** [comment]
I am not being able to reproduce this, can you give me an example with the demo api?

**Comment by benhaynes** [comment]
@rijkvanzanten 🔔
