### ISSUE TITLE
Add default permission rows on creation of user role

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#234]
When creating a user role, the API should automatically create a few rows in directus_permissions as well:

![image](https://user-images.githubusercontent.com/9141017/43797883-da752406-9a56-11e8-98d8-f59aabf722d2.png)

**Comment by WellingGuzman** [comment]
I added to the list that the `token` field will be read/write blacklisted, no user should be allow to see or edit any user token.

The issue here is that it also makes themselves unable to see their `token`, so they are encourage to authenticate and get an JWT token instead.

**Comment by benhaynes** [comment]
But `admin` role can still read/update the `token`, right?

**Comment by WellingGuzman** [comment]
Yes admin can still read/update tokens, this is only for new roles.
