### ISSUE TITLE
Improve querying data

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#239]
Currently we query data with multiple queries:

1. Fetch main query.
2. Iterate over the fields and fetch all items related to the field
3. Repeat step 1-2 with the new fields (based on the selected fields on fields dot notation)

... And deep go the rabbit hole (recursion)

Ideally we want to make this work with a single request or look ahead of the same tables in items relationships.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
