### ISSUE TITLE
Re-implement refresh tokens

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#24]
Implement refresh tokens or a different way to refresh a token before or after it gets invalid.

Currently for development purpose this can be fetch using the access token and `/auth/refresh` endpoint.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
