### ISSUE TITLE
Cannot set managed to true

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#240]
We cannot delete records in `directus_collections` through the API. DELETE to /collections not only deletes the row in `directus_collections`, but it also deletes the full collection in the database (by design!). This makes it impossible to use just the existence of the row in `directus_collections` as a `managed` state. To make it work, we should instead use a dedicated `managed` flag column in `directus_collections`

**Comment by WellingGuzman** [comment]
I believe it will be better to create a new endpoint to stop managing a collection instead adding a new field to the table.

If we do that, we should do the same to the `directus_fields` table.

**Comment by benhaynes** [comment]
1. The nice thing about having a flag is that if you setup a collection, and then "unmanage" it... we still have all the setup info in case you want to turn it on again. BUT, I'm fine with your approach is @rijkvanzanten agrees.

2. Remember, Fields can *not* be unmanaged. Only collections. All you can do is HIDE fields (which we can already do).

**Comment by rijkvanzanten** [comment]
Managed collections and hidden fields are basically the same IMO. We use a hidden column for fields, so we should also use a managed column for collections. That’s my two cents 😄

**Comment by rijkvanzanten** [comment]
We cannot PATCH an unmanaged collection to be managed again. PATCHing { managed: true } results in `"Collection "<collection>" is not being managed by Directus"` error
