### ISSUE TITLE
Create endpoint to check logs

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#25]
Is creating a endpoint to check the API logs useful?
a endpoint `/server/logs` to see a full list of the logs, a collection of log files. and `/server/logs/<file>` get an specific file log data.

**Comment by benhaynes** [comment]
I think so, yes. Should/can this be env specific? Also, if it's global how will we handle auth?

Would these endpoints return JSON of errors or raw logs?

**Comment by WellingGuzman** [comment]
Exactly this is a question in #18? how do we enforce permission outside `create`, `read`, `update` and `delete`?

> Would these endpoints return JSON of errors or raw logs?

it will return a JSON with the content of each log or the whole file.

Ex:

#### List of all log files
```json
{
  "data": [
    {"file": "2018-03-26.log"},
    {"file": "2018-03-27.log"}
  ]
}
```

#### A single log with all the content
```json
{
  "data": {
    "file": "2018-03-26.log",
    "content": "<ALL LOG CONTENT>"
  }
}
```

Or
#### A single log with all logs by line
```json
{
  "data": {
    "file": "2018-03-26.log",
    "lines": [
      {"content": "<LOG LINE>"}
    ]
  }
}

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
