### ISSUE TITLE
Creating a new Collection from the App returns a 422 error

### ISSUE THREAD

**Issue by LudwigNova** [directus/api#250]
Trying to create a new collection from the app GUI spits a 422 error out a on the JS console with the message "missing length for: id"

**To Reproduce**
1. Open the Directus App
2. Click on Admin Settings
3. Click on Collections and Fields
4. Click the Plus icon on the top right of the App
5. Type in a name for the collection in the popped up modal and then click the create button
6. Check the console to see the error 

**Expected behavior**
I expected to click create and have a new collection be generated with the name I typed in

**Screenshots**
![screenshot 14](https://user-images.githubusercontent.com/19542804/42771514-7ceb2aa0-88f5-11e8-80ec-d346d88fc3fc.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Version  67.0.3396.99

**Comment by rijkvanzanten** [comment]
Closed by https://github.com/directus/app/commit/925ddc71da8e9a04d33104a8bb957f8d5b6cace0
