### ISSUE TITLE
Broken link: Installation link in the readme goes to a broken link

### ISSUE THREAD

**Issue by hadihallak** [directus/api#263]
it's the same for both the api and the app
https://docs.directus.io/

**Comment by benhaynes** [comment]
Hey @hadihallak – thank you for reporting this! We're actually in the process of writing these 7.0 Docs still, and the _new_ domain will be at the docs subdomain. So this isn't an issue, just incomplete.

**Comment by jfrux** [comment]
Many other links on the README are either blank screens, error messages in JSON, or just dead.
Is this repo considered alpha?

**Comment by rijkvanzanten** [comment]
@jfrux It’s a pre-release in active development yeah 🙂 The software itself is reaching the point where we’re comfortable releasing and the docs are next up 👍🏻

**Comment by jfrux** [comment]
<3 Thanks! You guys are rocking it!
