### ISSUE TITLE
Authenticate endpoint CORS not working anymore

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#270]
`Request header field Content-Type is not allowed by Access-Control-Allow-Headers in preflight response.`

**Comment by WellingGuzman** [comment]
In the meantime you can fix this by removing the `headers` key from `cors` in your config, or you can add the header list there, example:

```
'headers' => [
  'Access-Control-Allow-Headers',
  'Content-Type',
  'Authorization',
],
```

**Comment by rijkvanzanten** [comment]
I've been using this as config forever:

![image](https://user-images.githubusercontent.com/9141017/43467998-2c5b333a-94a0-11e8-8970-79aac6c85447.png)

And didn't have issues loggin in before 🤷‍♀️

**Comment by rijkvanzanten** [comment]
Ah, I see you've updated the cors settings structure

```php
    'cors' => [
        'enabled' => false,
        'origin' => ['*'],
        'methods' => [
            'GET',
            'POST',
            'PUT',
            'PATCH',
            'DELETE',
            'HEAD',
        ],
        'headers' => [],
        'exposed_headers' => [],
        'max_age' => null, // in seconds
        'credentials' => false,
    ],
```
