### ISSUE TITLE
Updating field returns 500 error

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#272]
```
"SQLSTATE[01000]: Warning: 1265 Data truncated for column 'official_site' at row 1"
```

`PATCH http://localhost/api/public/_/fields/movies/official_site`

```json
{"id":165,"sort":12,"field":"official_site","type":"VARCHAR","interface":"text-input","default_value":null,"options":{"iconLeft":"link"},"readonly":false,"required":false,"unique":false,"note":null,"hidden_input":false,"hidden_list":false,"length":100,"validation":null}
```

**Comment by rijkvanzanten** [comment]
So what can I do to not get the error? Changing the field from text to medium text didn’t help and I’m not sending a lot of data

**Comment by WellingGuzman** [comment]
> So what can I do to not get the error?
To avoid getting this warning you must disable restrict mode from MySQL by removing `STRICT_TRANS_TABLES` and `STRICT_ALL_TABLES` from the sql modes in your mysql configuration.

> Changing the field from text to medium text didn’t help and I’m not sending a lot of data

I didn't understand what you trying to say, can you give more details?

**Comment by rijkvanzanten** [comment]
I would assume this error is caused by the fact that I'm trying to save a value that's too large for the column? I'm only saving a small size JSON into a TEXT field, so I'm wondering why that wouldn't work in strict mode..?

**Comment by rijkvanzanten** [comment]
@WellingGuzman ?

**Comment by WellingGuzman** [comment]
This was caused because you tried to reduce the length of a `varchar` column from `200` to `100`. 

When strict mode is enabled MySQL prevents this from happening, which will result in data loss.

This can also happen if you are trying to insert more data that it could fits in a column.
