### ISSUE TITLE
Reverting doesn't work on system collections

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#273]
**Describe the bug**
`PATCH http://localhost/api/public/_/users/2/revert/260 404 (Not Found)`

**To Reproduce**
1. Try reverting a system collection

**Expected behavior**
It should work the same as the regular /items endpoint

**Comment by WellingGuzman** [comment]
We agreed on removing the `revert` on system collections until we figure it out if we want to whitelist fields for reverting, such as files `filename` and users `passwords`.

I may say this is not a bug, but a feature that was postponed.

**Comment by rijkvanzanten** [comment]
Makes sense. @benhaynes thoughts on the whitelisting idea? We don’t necessarily need revert right away on _all_ system collections, but we do need it on users & files

**Comment by benhaynes** [comment]
Do we need revert for Users/Files? Can this wait and just be disabled in the app/api for now? It doesn't seem like a requirement, and I'd rather focus on other things.

@rijkvanzanten @WellingGuzman

**Comment by rijkvanzanten** [comment]
I don't know what's more of a time investment @benhaynes, copying over the /revert from items or building in conditionals in the main edit view component to remove that button for just directus_files and directus_users

**Comment by benhaynes** [comment]
It's more about taking the time to figure out how to revert these collections... and writing code to not revert certain columns in the API.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
