### ISSUE TITLE
Revert should revert full item

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#275]
**Describe the bug**
When reverting to a single revision, it should revert to the full `data` of that item, instead of reverting just the fields that were changed (delta).

**Comment by WellingGuzman** [comment]
It's not a bug, as we agreed on using the `delta` instead of the full `data` for reverting.

Is this a request to change the `delta` for `data` on revert?

**Comment by rijkvanzanten** [comment]
I can’t remember that initial change to delta. What was the reasoning behind it?
