### ISSUE TITLE
Issue with database/server after logging in

### ISSUE THREAD

**Issue by raheel** [directus/api#283]
**Describe the bug**
Database/server error shown on main screen after logging in

**To Reproduce**
I followed the instructions and ran the scripts to create the tables and add the admin user.  When I login, it shows me an error,

**Screenshots**
![image](https://user-images.githubusercontent.com/928911/43562037-28d8e20e-95e8-11e8-9f25-580a4e8e4a6c.png)

**Comment by rijkvanzanten** [comment]
Hey @raheel, what does it show in the JS console? The full errors should be logged there. Also, is this on the `master` or `build` branch? We just changed a bunch of names for the next release, so there might be some compatibility issues in the current build...

**Comment by raheel** [comment]
I believe it is the master branch.  Can you please link me to the name of
the branch I should use.

**Comment by rijkvanzanten** [comment]
[This doc](https://directus.github.io/app/developer-guide/install-dev.html) outlines the installation instructions for getting it up and running locally. I'll close this issue as I feel like this is not an issue in the platform, but rather an issue in the setup 🙂 Feel free to hit me up [on Slack](https://slack.getdirectus.com) if you're still running into problems

**Comment by raheel** [comment]
I read the documents multiple times, but i'm still having the same issue.
I even deleted my project/database and reset it.  Shouldn't issues with the
issues be considered issues?
