### ISSUE TITLE
File too large error wrong HTTP code

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#284]
Right now, the error for `The uploaded file exceeds max upload size that was specified on the server.` (code 301) uses HTTP status code `500 Internal Server Error`. This should be http status code `413 Payload Too Large`

**Comment by jooola** [comment]
@rijkvanzanten Would be nice to add a note about this error in the php-fpm and nginx  config example  files.

**Comment by rijkvanzanten** [comment]
What note where? Feel free to open a PR!

**Comment by jooola** [comment]
See directus/docs#287
