### ISSUE TITLE
POST content length max size error not handled by API

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#285]
Instead, the server returns HTML:

```html
<br />
<b>Warning</b>:  POST Content-Length of 35560409 bytes exceeds the limit of 8388608 bytes in <b>Unknown</b> on line <b>0</b><br />
```

**Comment by benhaynes** [comment]
Any idea how you got this to happen @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
I uploaded a file that was too large. Anyway, it seems to be working on the live demo so I'll consider this fixed.
