### ISSUE TITLE
Add max file upload size option to directus_settings

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#286]
That way, we can upload bigger files based on that settings. Use in combination with `ini_set()`

**Comment by benhaynes** [comment]
Related to #48

**Comment by benhaynes** [comment]
Didn't we just add something like this? @rijkvanzanten @WellingGuzman

**Comment by rijkvanzanten** [comment]
Not that I'm aware of @benhaynes. There's no way to set the max upload size from within directus at the moment.

**Comment by WellingGuzman** [comment]
You can't set `max_upload_size` nor `post_max` values using `ini_set`, this is not likely to be implemented using `ini_set`.

It requires to be updated in `php.ini`, `.htacess` or the web server.

**Comment by benhaynes** [comment]
OK. So should we close this ticket? It seems like this is something that needs to be done in server/config... not the App settings.

@WellingGuzman

**Comment by WellingGuzman** [comment]
Correctly, this must be done in server configuration.

I am closing this.
