### ISSUE TITLE
Add batch support to /files endpoint

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#290]
🎉

**Comment by rijkvanzanten** [comment]
GET `/:id,:id`
POST `/`
PATCH `/`
DELETE `/`

**Comment by WellingGuzman** [comment]
Uploading multiple files at the same time it's not a good idea. The client, in this case the app should queue all the files and make request accordingly making upload request to the API.

Updating (only data), deleting and fetching multiple files are not expensive as uploading multiple files.

I am not onboard on the upload part.

**Comment by rijkvanzanten** [comment]
Agreed. That's the way the app does it right now btw 🙂 It sequentially uploads each file separately
