### ISSUE TITLE
Add option to install the API without having to install the database

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#294]
When you already have a database, or you use an existing SQL copy, the post to /instances will fail. We should add a param that allows the user to create the config file without having to overwrite the DB

**Comment by benhaynes** [comment]
This one seems pretty straightforward... any idea how complex this is @WellingGuzman ?

**Comment by WellingGuzman** [comment]
The title and the description leads me to different thing. Do we want to create the database even when it doesn't exists, or install a new project even if that database is not empty, or both?

At the moment you can install a new project to a database that already exists, as long as there's not a single directus table. if you want to overwrite everything you set the `force` option to `true`.

Are we looking for creating the database when it doesn't exists? @benhaynes @rijkvanzanten

**Comment by rijkvanzanten** [comment]
> At the moment you can install a new project to a database that already exists, as long as there's not a single directus table.

This is what the issue is about. Installing a new project on a database that already has the directus_* tables.

**Comment by benhaynes** [comment]
Would we do a check to make sure the existing `*_directus` tables/field are correct? Would we run migrations to get things up-to-date?

**Comment by WellingGuzman** [comment]
> This is what the issue is about. Installing a new project on a database that already has the directus_* tables.

Ah understood. What we are doing is creating the config files as you described above.

Some questions:

- Do we want to just do it without an options? if `force=false (default)` and there's some table that starts with `directus_`, we avoid creating tables, and just create the config files.

- Do we want to run the db upgrade automatically, or let the user do it separately, or add an option? I prefer add an option default to `false`.

Scenario:

- If `force=false` and there's at least one of Directus table, only creates the config file.
- If `force=false` and there's at not a single Directus table, creates config and tables.
- If `force=true` and there's at least one of Directus table, remove all Directus collection, and install everything.

**Comment by rijkvanzanten** [comment]
Maybe we should add another flag, like force, that will install it on top of an existing installation.

`force=true` should clear everything and install directus fresh
`existing=true` should install just the config files (and maybe run migrations)

By default, the API will return an error if the data already exists (that way the app can render a confirm modal)

Thoughts @WellingGuzman?

**Comment by WellingGuzman** [comment]
You right, a new flag is better. The API already throws an error when there's already Directus Tables.

One more question, If `existing=true`, but there's not tables, should it install the tables. Basically what `existing=true` will means is do not warn me that the tables exists, just ignore it, and create the config only, correct?

**Comment by rijkvanzanten** [comment]
> will means is do not warn me that the tables exists, just ignore it, and create the config only, correct?

I think so, yeah!
