### ISSUE TITLE
[SECURITY] POST to /instances adds default admin token

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#297]
This means that every installation of directus uses the same admin token for the main admin user, therefore exposing every API 2 instances admin user. 

https://github.com/directus/api/blob/18ff98f66d5b174d9ae5aa6b902200a40d4f0ca8/src/core/Directus/Util/Installation/InstallerUtils.php#L198

**Comment by WellingGuzman** [comment]
The install helper has a default `email`, `password` and `token`. What I did was setting the token default to null on the `instances` endpoint.
