### ISSUE TITLE
Non-admin users can't read from directus_users

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#300]
When a non-admin user has full permissions for all directus_* tables, everything loads as expected, except for `/users` and `/users/me` (`/users/:id`). The `directus_users` table seems to only be accessible to admin users.

[directus_2018-08-07.sql.zip](https://github.com/directus/api/files/2267707/directus_2018-08-07.sql.zip)

**Comment by WellingGuzman** [comment]
The problem here is that the `directus_users.status` field in `directus_fields` is set to `varchar` type instead of `status`, also the status mapping options key is `status_mapping` instead of `statusMapping`.

If you update these two things it should works.
