### ISSUE TITLE
Directus Revisions should be limited based on permissions

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#301]
Item data and delta are stored in directus_revisions, therefore, if you give a user permission to read directus_revisions you basically give them full access to read everything.

To solve this, directus_revisions should honor directus_permissions in what it returns when getting items.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
