### ISSUE TITLE
Add parameter to skip junction table

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#305]
We've chosen to return the junction table in many to many requests:

```js
// GET /items/:collection/:pk
{
  data: {
    relationalField: [
      {
        junctionID: 1,
        left: { ...currentItem },
        rightID: { ...relatedItem }
      }
    }
}
```

While this is expected when working with m2m, lets add a parameter that allows the user to "skip" the junction table:

```js
// GET /items/:collection/:pk?skip-junction=relationalField
{
  data: {
    relationalField: [
      { ...relatedItem }
    ]
  }
}
```

This parameter could be called `skip-junction` or `skip-relation` or something else.

I think the parameter should accept a CSV of field names to 'skip'. There might be a case where you want to junction of 1 field, but not of another. It shouldn't be a modify-all-fields parameter.

Thoughts @WellingGuzman @benhaynes ?

**Comment by rijkvanzanten** [comment]
(The default should still stay as is, this is purely an extra convenience option in case you're not using the junction table for extra info)

**Comment by benhaynes** [comment]
@rijkvanzanten does this still apply now that all of our relations are M2Os? I feel like we can skip things with dot-notation and accomplish 95% of this.

**Comment by rijkvanzanten** [comment]
> does this still apply now that all of our relations are M2Os

Yes, that doesn't change a thing in the API output. If you have a M2M setup, you'll still get the junction table. There's no way to skip a nested layer with dot-notation.

**Comment by benhaynes** [comment]
@rijkvanzanten — you opened this... any feelings on this now?

**Comment by rijkvanzanten** [comment]
Hmm yes yes I still think this is a really nice to have. I know we don't tend to assume things, but I'm assuming that a majority of many to many relations aren't using any specialty fields in the junction table. By having this parameter, we can make using this relationship in projects a lot easier.

Lets keep it open!

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
