### ISSUE TITLE
Implement a password/hash field type

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#316]
At the moment `users.password` is hashed specifically for users, it will be helpful to create a specific type for hashing value.

**Comment by rijkvanzanten** [comment]
Do you think this should be a type or an interface with a hook?

**Comment by benhaynes** [comment]
Don't we have a hash endpoint now? Do we need anything else?

https://docs.directus.io/api/reference.html#hash-string

@WellingGuzman @rijkvanzanten

**Comment by rijkvanzanten** [comment]
With the combination of the hash-check endpoint and the hooks in interfaces, I think we have enough.

**Comment by benhaynes** [comment]
Cool, then let's consider this one closed.
