### ISSUE TITLE
Update composer packages

### ISSUE THREAD

**Issue by benhaynes** [directus/api#317]
Update composer dependency:

```Package akrabat/rka-ip-address-middleware is abandoned, you should avoid using it. Use akrabat/ip-address-middleware instead.```

**Comment by WellingGuzman** [comment]
The new package only supports php 7 and we are still supporting php 5.6

Ref: https://github.com/directus/api/commit/e99cc9370f973109c5dd55fa93cb449ec8218ebe

**Comment by gonzalovilaseca** [comment]
I can give a hand but not sure what need to be done?

**Comment by WellingGuzman** [comment]
It was update the `akrabat/rka-ip-address-middleware` that has been abandoned to the new package `akrabat/ip-address-middleware`, but the new package requires php 7, but we are still supporting php 5.6.

There's three option here: 
1. Keep the abandoned package
2. Fork it, rename it, updated it (when/if necessary), and release it to packagist.
3. Only support php 7 and use the package

**Comment by benhaynes** [comment]
Now that we only support PHP 7+, can we resolve/close this? @WellingGuzman
