### ISSUE TITLE
Offset doesn't work correctly when sorting by a non-primary key value

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#320]
**Describe the bug**
When sorting by another field than the primary key, the API will regularly return duplicate items when working with limit and offset. 

**To Reproduce**
1. Query https://demo-api.directus.app/_/items/sales using a `sort` value of something else than `id`, for example `sort=status`. 
2. Notice how the response changes drastically when changing offset from 0 to 1.

**Expected behavior**
Every value should have "moved" by 1 "spot":

Successful query should be:

offset = 0
- 1
- 2
- 3

offset = 2
- 3
- 4
- 5

Which works as expected when querying for the primary key field:

![image](https://user-images.githubusercontent.com/9141017/44093851-9ce3954a-9fa2-11e8-8518-5c4ecd19763d.png)

![image](https://user-images.githubusercontent.com/9141017/44093856-a1128590-9fa2-11e8-8f77-8edfb8eb4e88.png)

**The problem**:
As soon as you start sorting by something else, this doesn't work anymore:

![image](https://user-images.githubusercontent.com/9141017/44093960-e22c164a-9fa2-11e8-8a16-19ce92144d3d.png)

![image](https://user-images.githubusercontent.com/9141017/44093982-eb8b8748-9fa2-11e8-9d4a-3e22ace759fe.png)

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/api/commit/e72f2966c761bd5ad37104c5a26cc2e3525999b8

**Comment by WellingGuzman** [comment]
Re-opened by https://github.com/directus/api/commit/e5d45ca581cbe5fc01bf59199b0d318f9921cd18

This won't make the API to sort by `id` in descending order. See #331
