### ISSUE TITLE
Triple-check post /instances DB values

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#323]
A fresh installation gives a bunch of user permission errors.. 🤔

**Comment by WellingGuzman** [comment]
Can you explain a little more about those bunch of user permission errors?

**Comment by rijkvanzanten** [comment]
`directus_users.status` is a varchar, and there are some other endpoints that return a 403 for some reason. It has to be the default values in the DB 🙂

**Comment by WellingGuzman** [comment]
The `varchar` bug was fixed, @rijkvanzanten is this still happening to you? I am unable to reproduce this issue.

**Comment by WellingGuzman** [comment]
Any update on this @rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
This is more an ongoing thing. We're changing so many names in the DB recently that we should check the install often 🙂

**Comment by rijkvanzanten** [comment]
Closed by https://github.com/directus/api/pull/432
