### ISSUE TITLE
 Add default thumbnail settings to the database schema

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#324]
Ref: https://github.com/directus/api/wiki/API-Settings-(DB)

**Comment by rijkvanzanten** [comment]
> I'd like to have the thumbnail info in the DB on install... but don't know how we'd do that without this.

Just like how we add all other records on install?

I don't really understand what the status column would add

**Comment by benhaynes** [comment]
Can we add a default thumbnail setup to `directus_settings` so users can easily see/update the syntax... without actually enabling any thumbnails by default? In the config we had the syntax commented out... I'm trying to replicate that in the DB

**Comment by rijkvanzanten** [comment]
Ah!

I'd say that's a perfect job for the placeholder option in the code interface 😉

**Comment by benhaynes** [comment]
Hahaha, of course! I forgot how powerful Directus is! 😄

**Comment by rijkvanzanten** [comment]
_Only if https://github.com/directus/api/issues/296 gets implemented that is hint hint @WellingGuzman 😁 _

**Comment by benhaynes** [comment]
OK, #296 is complete... @rijkvanzanten does that mean we can finish Global Settings?

**Comment by rijkvanzanten** [comment]
Yeah @benhaynes
