### ISSUE TITLE
Move files into public env folder by default

### ISSUE THREAD

**Issue by benhaynes** [directus/api#325]
Right now thumbnails are stored in the API root, for example:

`api/[env]/100/100/crop/best/whatever.jpg`

But original files for ALL environments are stored in the public `storage` folder:

`api/public/storage/uploads/whatever.jpg`

All env files need to be separated, so I propose this:

`api/public/storage/[env]/originals/whatever.jpg`
`api/public/storage/[env]/thumbnails/100/100/crop/best/whatever.jpg`

@WellingGuzman @rijkvanzanten ... thoughts?

**Comment by WellingGuzman** [comment]
> Right now thumbnails are stored in the API root, for example:

To make this clear, it didn't store it in the API root, but in whatever the config was set to, when `null` or undefined it uses the root. There was a bug that it didn't create the thumbnail storage directory path.

I will keep the current directory name for "originals", which is `uploads`. @benhaynes, are you good with this?

**Comment by WellingGuzman** [comment]
Final decision was:

- Moving the original upload directory from `<root>/public/storage/uploads/` to `<root>/public/uploads/<env>/originals/`.
- Moving the thumbnails directory from `<root>/public/thumbnail/thumbs/<env>/` to `<root>/public/uploads/<env>/thumbnails/`.
