### ISSUE TITLE
Single File upload is broken

### ISSUE THREAD

**Issue by Zielgestalt** [directus/api#327]
I can't upload files to a single file interface. There's no input to upload the field. 

Tested locally and on next.directus.app with both apis. E.g. if you try to add a new item to the movie collection:

![image](https://user-images.githubusercontent.com/41578219/44236558-a7b6f680-a1ad-11e8-800b-411b6d871a0b.png)

Tested on MacOS with Chrome.

**Comment by rijkvanzanten** [comment]
Closed by 0b31ff3
