### ISSUE TITLE
Logging in to a non-default env gives wrong token

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#329]

**Comment by WellingGuzman** [comment]
I am unable to reproduce this issue, I am getting a valid token.

Can you give me more details? What do you mean by wrong token? invalid, expired, different type?

```http
POST /<env>/auth/authenticate

{"email": "admin@example.com", "password": "password"}
```

**Comment by rijkvanzanten** [comment]
Hmm it returned wrong token before, but seems to work as expected now. I'll re-open when it comes up again
