### ISSUE TITLE
Add junction_field column to directus_relations

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#333]
The app will use this field to "tie together" two relationships when we're dealing with a m2m interface. 

The API doesn't need to do anything with this field

**Comment by benhaynes** [comment]
@rijkvanzanten – is this done?

**Comment by WellingGuzman** [comment]
@benhaynes I think he wants to add a new column to `directus_relations` table named `junction_field`.

**Comment by benhaynes** [comment]
Yeah, we discussed it  yesterday but I thought he actually added it already. Maybe not!

**Comment by rijkvanzanten** [comment]
I added it to the demo sql file, but I don't know how / where to update the API to add it in installation / migrations too
