### ISSUE TITLE
File Naming Options

### ISSUE THREAD

**Issue by benhaynes** [directus/api#337]
Our options should be:

`uuid` (replaces the old hash)
`original` (appends `*-n` as needed)
`id` (padded with `0`)

Do ya'll agree with using `uuid` as a file naming default? We _could_ use `original`, but I think `id` is the default right now... and we definitely shouldn't use that one.

**Comment by WellingGuzman** [comment]
@benhaynes should the `id` appends the number suffix (`*-n`) to avoid duplication in case of storage not being empty. Replace the file or appends the suffix?

**Comment by benhaynes** [comment]
For `id` I would say it should overwrite it if it already exists.

**Comment by WellingGuzman** [comment]
I belive `original` should be the default one.

**Comment by WellingGuzman** [comment]
In fact, `original` it is the default option. When there's not option set, the original is the one used by default.

**Comment by benhaynes** [comment]
Original works for me, but on demo and my install it's using I'd... so I assumed that's the default

**Comment by benhaynes** [comment]
@rijkvanzanten can we update those demos?

**Comment by rijkvanzanten** [comment]
Are you sure it's the default? The demo SQL doesn't have that option set at all in directus_settings so it uses the API defaults (? 🤔

**Comment by WellingGuzman** [comment]
@rijkvanzanten I am, _although you make me doubt a bit_, the only way to use `id` or `uuid` it is to set the setting `file_naming` to either `id` or `uuid` otherwise it will use the "original" filename, and appends number if there's a existing file.

**Comment by WellingGuzman** [comment]
@rijkvanzanten I tested on the demo server, and it actually works as expected, original is the default unless `id` or `uuid` is defined as `file_naming`

**Comment by benhaynes** [comment]
Yeah, it looks like it's in the database as `file_id`.

@rijkvanzanten can we re-install the demos so the schema/seeder is up to date?

**Comment by benhaynes** [comment]
I guess it will be a little bit of each. We need to update the seeder with the defaults we set up in the demo... but we also need to look at the current seeder API defaults and make sure those are honored in the demo.

So Users/Files needs to be updated to show as Cards, but File naming should update to `original` (not `file_id`).

**Comment by computerwizjared** [comment]
Hey all, was this option removed at some point? In Directus 6 we had the option under "Global Settings" to set the ID used when uploading files. If I need to open a feature request, I can do that too.

![image](https://user-images.githubusercontent.com/2905521/51123396-9ec06480-17e1-11e9-9ebd-2ddad6e10272.png)

**Comment by benhaynes** [comment]
We currently only have file uploads saving as "the original" file name, but this used to be an option that could be changed in the Settings (I no longer see it). Users should be able to choose between different ways to save files:

* `uuid` or `hash` (default) — This is a unique hash that ensures file names can not be guessed or incremented.
* `original` — This is filenames are saved now. It sanitizes the original file name and adds `-n` (an incremented int)
* `pk` — we don't need to include this, but it would be another option that would use the primary key of `directus_files` as the file name.

Another option that may be cleaner is to convert `directus_files` to use a UUID PK... then we only have two options: `UUID` and `Original`. Thoughts?

**Comment by computerwizjared** [comment]
We are currently using this feature in v7 by manually adding a row to directus_settungs with the setting. Just FYI.

**Comment by rijkvanzanten** [comment]
Adding a row to directus_fields for this field will make it show up in the settings pane as well

**Comment by benhaynes** [comment]
Cool. So we need to:

* Update the migrations, installer, and default schema to include this by default
* Update the Docs to describe the options
* Change the default to `uuid`
* Optional: Update the collection's default PK to UUID

**Comment by benhaynes** [comment]
I was hoping that this would give us a clear default for naming... but as of now it's exactly 50/50!

https://twitter.com/directus/status/1139618994879696897

UUID seems like a "safer" default, but we need to still support "Original" as a Global Setting. BUT, let's wait the last 4 days of the poll and see what we get!

**Comment by shealavington** [comment]
>UUID seems like a "safer" default

I would agree, also thinking about server admins, many people will just install and get started, it might be best for Directus to obscure by default however provide that toggle option if original names are wanting to be kept. We could also store the original filename as the 'Title' of the file in the database.

**Comment by benhaynes** [comment]
We already store the original file name as in `directus_files.name`... so we could always add a helper endpoint later that downloads the file with the original name.

**Comment by bjgajjar** [comment]
Fixed in #1059
