### ISSUE TITLE
API Reference:

### ISSUE THREAD

**Issue by benhaynes** [directus/api#339]
- [x] `/[env]/`
- [x] `/[env]/activity`
- [x] `/[env]/auth`
- [x] `/[env]/collections`
- [x] `/[env]/collection_presets`
- [x] `/[env]/custom`
- [x] `/[env]/fields`
- [x] `/[env]/files`
- [x] `/[env]/items`
- [x] `/[env]/interfaces`
- [x] `/[env]/mail`
- [x] `/[env]/pages`
- [x] `/[env]/permissions`
- [x] `/[env]/relations`
- [x] `/[env]/revisions`
- [x] `/[env]/roles`
- [x] `/[env]/scim/v2`
- [x] `/[env]/settings`
- [x] `/[env]/users`
- [x] `/[env]/utils`
- [x] `/`
- [x] `/instances`
- [x] `/interfaces`
- [x] `/layouts`
- [x] `/pages`
- [x] `/server`
- [x] `/types`

**Comment by WellingGuzman** [comment]
All endpoints now have at least minimal description of what it does.
