### ISSUE TITLE
Add GROUP datatype & directus_fields.group column 

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#34]
The `GROUP` datatype will be similar to `ALIAS`, in that it doesn't actually store any data. It's just there so the application can know it's an interface meant to group other interfaces.

The `directus_fields.group` column will be a foreign key to the (same) `directus_fields` table. That way, we have a way of marking what interfaces go in what group.

**Comment by WellingGuzman** [comment]
`group` column was added to `directus_files` by https://github.com/directus/api/commit/9d9f2071d20a1fd5e9debb1311acd5b7b2af30d4

**Comment by rijkvanzanten** [comment]
You meant `directus_files` 😉

**Comment by WellingGuzman** [comment]
I meant `directus_fields` :)

**Comment by rijkvanzanten** [comment]
Lol, corrected it wrong

![](https://i.giphy.com/3og0INyCmHlNylks9O.gif)
