### ISSUE TITLE
Add top-level links object

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#340]
Add a top-level `links` object in the response object for pagination.

The example below follows the `links` top-level object structure.

```json
{
  "links": {
    "self": "http://example.com/_/items/projects",
    "first": "http://example.com/_/items/projects?page=1",
    "last": "http://example.com/_/items/projects?page=10",
    "prev": null,
    "next": "http://example.com/_/items/projects?page=2"
  },
  "data": {
  }
}
```

Information about this are explained in the jsonapi specification:
- http://jsonapi.org/format/#document-links
- http://jsonapi.org/format/#fetching-pagination

**Comment by rijkvanzanten** [comment]
Why?

Also, since when do we have a `page` query param?

**Comment by WellingGuzman** [comment]
> Why?

These are helper information that make it easier for consumer to fetch the next/prev/first/last items from the pagination list.

> Also, since when do we have a page query param?

We don't, I added the example as a reference. I updated the text to avoid confusion

**Comment by benhaynes** [comment]
Does it make more sense to have this inside `meta`?

**Comment by philleepflorence** [comment]
I can work on this using the `offset` and `limit` parameters already in place. 
In addition, I can also add the `total_filter` if the `filters` argument is passed.
Open to suggestions on implementation.

**Comment by benhaynes** [comment]
Thanks @philleepflorence — this would be awesome. 😄

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
I've added this one to `in progress` @philleepflorence ... cool?

**Comment by philleepflorence** [comment]
Yes, once I have the go ahead on the structure of the meta object, I can finalize.

**Comment by benhaynes** [comment]
Working on that now in the POR comments!
