### ISSUE TITLE
Implement more batch endpoints

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#353]
#### Implement batch updates on:

- Folders
- Permissions
- Relations
- Roles
- Users

Updates multiple items each with their own data.

```json
[{
   "field": "value"
}, {
   "field": "value"
}]
```

#### Implement batch create on:

- Folders
- Roles

#### Implement batch delete on:

- Users

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
