### ISSUE TITLE
Only admin can create instance after the first one

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#354]
After creating the `default` project, only admin must have access to create new project/instances.

**Comment by juanitoddd** [comment]
Hello Welling, I am looking to contribute somehow to this awesome project. After Installing the API this TODO was the first thing that I noticed. I just wonder, the idea is that the endpoint POST */projects* creates the Database and the Config file for a new project, which is not yet implemented,  am I right ?. Regards

**Comment by WellingGuzman** [comment]
Hello @juanitoddd I am referring to the `POST /<project-name>/projects` endpoint being always open, unless you add a file named `.lock` in Directus API root directory.

The goals here is to after install the default project is to find a way to protect the `/projects` endpoint from the public access.

**Comment by juanitoddd** [comment]
Ah ok, I see, thanks for the reply

**Comment by benhaynes** [comment]
From @WellingGuzman 

This needs a middleware to verify the user authentication and skip/add a middleware to avoid the creation of new project if the user is not admin.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
