### ISSUE TITLE
Node JS API (Server side)

### ISSUE THREAD

**Issue by benhaynes** [directus/api#364]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Node JS API (Server side)
### :+1: = 36
*Created 1 year ago by @WellingGuzman*
 

-----
### @WellingGuzman – (1 year ago)
Alternative to PHP API (server side)

 

-----
### @aarmand – (1 year ago)
I dont know php....

 

-----
### @Froelund – (1 year ago)
I am currently using directus-sdk-javascript in my nodejs service, and that works great. I Can't really figure out why it would be a good idea to create a Node JS API (Server side) - So please enlighten me :)

 

-----
### @rijkvanzanten – :+1: (1 year ago)
@Froelund, it would be primarily a big speed-improvement. Node's event-driven single-threaded IO is blazingly fast when it comes to database operations.

 

-----
### @Froelund – (1 year ago)
Okay. I could buy that - But I'm not sure that a nodeJS would prove faster then PHP in this scenario . If it is faster, and it might be, I think for the sake of a project architecture, we should be going for either PHP or nodeJS Server Side library. Are these things specified somewhere? Seems to me, that the title should say "Move to NodeJS"?

 

-----
### @derekshull – :+1: (10 months ago)
Is this still going to be available in Q1 of 2018?

**Comment by benhaynes** [comment]
Soooooo... @rijkvanzanten @WellingGuzman 

What are we doing with this one?

**Comment by rijkvanzanten** [comment]
_One day.._

**Comment by benhaynes** [comment]
Seeing the success of other Node-based platforms, the simplicity of install, and the total use of JS... I think this is still worth discussing.

**Comment by dban0001** [comment]
I vote for Go because of type-safety :laughing:

**Comment by wgodin** [comment]
Adding my vote to this suggestion

**Comment by nacr** [comment]
Also adding my vote to this :+1:

**Comment by tshelver** [comment]
Node and Postgresql :)

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by andgar2010** [comment]
> I vote for Go because of type-safety 😆

Typescript 😎
