### ISSUE TITLE
API get rows by filters

### ISSUE THREAD

**Issue by benhaynes** [directus/api#365]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# API get rows by filters
### :+1: = 19
*Created 1 year ago by @diegogurpegui*
 

-----
### @diegogurpegui – (1 year ago)
Possibility to get the rows of a table filtered by some value. Even consider the case of filtered by a O2M field (by ID perhaps)?

This is EXTREMELY useful. I couldn't find it yet, so if its there somewhere please let me know.

 

-----
### @diegogurpegui – (1 year ago)
I think this is already solved in API v1.1 (https://api.getdirectus.com/1.1/#Filter_Operators)

 

-----
### @Hainesy – (1 year ago)
Any explanation on how to use this?

 

-----
### @Hainesy – (1 year ago)
This ticket can now be closed as the docs have been updated.

 

-----
### @diegogurpegui – (1 year ago)
Exactly. This is working now.

**Comment by rijkvanzanten** [comment]
This has been implemented already!
