### ISSUE TITLE
Private File Support

### ISSUE THREAD

**Issue by benhaynes** [directus/api#368]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Private File Support
### :+1: = 9
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
Currently all files are publicly accessible. We should add a toggle to make files private.

In order to serve private files we have to serve it through PHP, so only through the API and Web app can be accessible.

**Comment by rijkvanzanten** [comment]
This should be based on permissions @WellingGuzman

**Comment by benhaynes** [comment]
Or Storage Adapters.

If you have two+ storage adapters and had one that's private... this would be solved. We just need the App to support _choosing_ which storage adapter to use case-by-case. (The API already does, right @WellingGuzman ?)

**Comment by benhaynes** [comment]
Does the API allow you to choose the storage adapter when uploading files? @WellingGuzman

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by metalmarco** [comment]
I'm also interested in this feature.
Permissions on File API are useless if anyone can still access directly the file https://directus.redilco-hub.it/hub/assets/matteotti1.png

Best scenario would be to have a private S3 storage, and access to the files is managed by Directys on a Folder level.

**Comment by baermathias** [comment]
Are there any news on this topic? 
I think this issue can be linked, its the same: https://github.com/directus/v8-archive/issues/1831

**Comment by rijkvanzanten** [comment]
@baermathias v9 uses ACL on the assets endpoint 👍🏻
