### ISSUE TITLE
Decouple Auth, Allow GitHub/Google/Facebook Login

### ISSUE THREAD

**Issue by benhaynes** [directus/api#371]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Decouple Auth, Allow GitHub/Google/Facebook Login
### :+1: = 9
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
In addition to the typical (Directus) login, you should be able to confirm your identity (email address) through either GitHub, Google, or Facebook authentication.

 

-----
### @benhaynes – (1 year ago)
Also: LinkedIn, Live ID, and OpenID account

 

-----
### @yair-ucando – (1 year ago)
Also LDAP (if possible)

**Comment by rijkvanzanten** [comment]
Done
