### ISSUE TITLE
Check Password – API Endpoint

### ISSUE THREAD

**Issue by benhaynes** [directus/api#377]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Check Password – API Endpoint
### :+1: = 2
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
An API/SDK endpoint to check auth on custom columns. You provide the column name (password) with optional params for adding the salt column and encryption type (defaults would be the Directus defaults).

**Comment by benhaynes** [comment]
Is this basically done with _Match Hash_ endpoint?

https://docs.directus.io/api/reference.html#match-hashed-string

@WellingGuzman @rijkvanzanten

**Comment by rijkvanzanten** [comment]
Yes 👍
