### ISSUE TITLE
Bulk Creation of Items

### ISSUE THREAD

**Issue by benhaynes** [directus/api#378]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Bulk creation of items via the API
### :+1: = 2
*Created 1 year ago by @mawrkus*
 

-----
### @mawrkus – (1 year ago)
https://github.com/directus/directus/commit/7b131f909208920337c1ba69488975aca00710cf enabled the possibility to update/delete multiple rows.

I'd love to have the possibility to POST multiple rows to the API. My use case is a massive initial importation of data.

Thanks for considering it.

**Comment by rijkvanzanten** [comment]
This has been implemented

**Comment by mawrkus** [comment]
:D thx!
