### ISSUE TITLE
Handle PHP errors/exceptions before the App starts

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#38]
Before the application start, all exceptions are thrown into the stream. When the application is in production this may not be pretty to have.

Catching these exceptions/errors and convert it to `json` can help the expected `json` from the api. Having to dump any exceptions to the stream is helpful when you are developing otherwise, no good.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
