### ISSUE TITLE
New Event: table.change

### ISSUE THREAD

**Issue by benhaynes** [directus/api#381]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# New event: table.change
### :+1: = 1
*Created 1 year ago by @Radiergummi*
 

-----
### @Radiergummi – (1 year ago)
Called for all table changes (CRUD), with the same arguments as the existing events

**Comment by WellingGuzman** [comment]
There already is a hook (action) for when a collection is changed `collection.update`, but there's a new one for when a schema is being updated `collection.schema.update`.

Realizing all the names doesn't seem to be consistent. New ticket to discuss new names: https://github.com/directus/api/issues/478

Docs: https://github.com/directus/docs-v7/commit/9ce73568fdba78ea4cca14a621c9a30dfd399c65
