### ISSUE TITLE
Abstracted Config Files (JSON)

### ISSUE THREAD

**Issue by benhaynes** [directus/api#383]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Abstracted Config Files (JSON)
### :+1: = 1
*Created 1 year ago by @benhaynes*
 

-----
### @benhaynes – (1 year ago)
@WellingGuzman

What do you think about abstracting the configuration files. Currently, they are in the API directory as PHP files – but couldn't we make them JSON files in the root so they are not tied to the server-side language? Does that seem like a good idea or overkill?

**Comment by benhaynes** [comment]
We just discussed this recently... what's our final consensus? 

@rijkvanzanten @WellingGuzman

**Comment by rijkvanzanten** [comment]
The conclusion was that it's nice to have but too big of a breaking change to implement stable now. We also had the problem that we have some dynamic code in the config file (hooks etc) which would need to move to new files

**Comment by benhaynes** [comment]
I'll keep this open since it's something we'll want to look into eventually.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
