### ISSUE TITLE
Polymorphic Relations

### ISSUE THREAD

**Issue by benhaynes** [directus/api#386]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Polymorphic Relations
### :+1: = 2
*Created 1 year ago by @cesasol*
 

-----
### @cesasol – (1 year ago)
Adding support for polymorphic relationship like laravel for distint types of data in relation to one table, for example content blocks for a page. Reference: https://laravel.com/docs/5.4/eloquent-relationships#polymorphic-relations

**Comment by benhaynes** [comment]
We're calling this `m2mm` and it is now supported by the API when you use a UUID primary key. Just waiting on the first interface to use it!

https://github.com/directus/app/issues/712

**Comment by kasparpalgi** [comment]
> We're calling this `m2mm` and it is now supported by the API when you use a UUID primary key. Just waiting on the first interface to use it!
> https://github.com/directus/app/issues/712

This URL was 404. Just wondering if m2mm is possible from the admin panel side. Don't need the API to support is as we use for the API HAsura and Directus is just a great admin panel.
