### ISSUE TITLE
With filter joins, allow the same table to be listed multiple times

### ISSUE THREAD

**Issue by benhaynes** [directus/api#388]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# With filter joins, allow the same table to be listed multiple times
### :+1: = 0
*Created 1 year ago by @stevepatter*
 

-----
### @stevepatter – (1 year ago)
Currently we can join tables while filtering data with:

    'joins' => [
                'candidate_application' => [
                    'on' => ['candidate_application.candidate', 'candidate_of_the_week.candidate']
                ]
            ]
but this restricts us to listing each table once. Instead, expand the join to an additional array layer & we can specify the same table multiple times (as would be possible in SQL).

    'joins' => [
        'candidate_application' => [
                [
            ‘on’ => [ 'candidate_application.candidate', 'candidates.id'],
            ‘type’ => ‘INNER’
                       ],
                [
            ‘on’ => [ 'candidate_application.candidate', 'jobs.id'],
            ‘type’ => ‘LEFT’
                       ]
    ],
Code changes would be processJoins in RelationalTableGateway

**Comment by benhaynes** [comment]
Is this the same as this:

https://github.com/directus/api/issues/134

@WellingGuzman @rijkvanzanten

**Comment by rijkvanzanten** [comment]
I feel like this is a M2O relation to the same table @benhaynes

**Comment by benhaynes** [comment]
Ahh, you're right... commented too fast. Join vs filter :/

**Comment by benhaynes** [comment]
@WellingGuzman – does this ticket mean I can't create a relationship from `table_a` to `table_a`?

**Comment by WellingGuzman** [comment]
Correct, you are not allowed to use same table more than once, because it uses the table name as the key in the array.

It has the same issue that #134.

**Comment by benhaynes** [comment]
OK, well this is a very common thing to do so we'll need to get it fixed before 7.0.0. In the example below, I need to related news articles to other news articles (for `related articles`).

![screen shot 2018-10-03 at 9 20 01 am](https://user-images.githubusercontent.com/522079/46412838-a0ac5f00-c6ed-11e8-87bd-50946604b93c.png)

**Comment by WellingGuzman** [comment]
That's correct, you can do this by using relations, but not the `joins` param at the moment. We need to rewrite how the `filters` and `joins` params works to accept more than one field and collection.

**Comment by rijkvanzanten** [comment]
> @WellingGuzman – does this ticket mean I can't create a relationship from table_a to table_a?

So to answer your question @benhaynes, it _is_ possible to have a relationship from A to A, but you can’t use `filters` or manual `joins`.

**Comment by benhaynes** [comment]
Any updates here @WellingGuzman ?

**Comment by WellingGuzman** [comment]
We are not going to re-implement `joins`. I will be closing this alongside with https://github.com/directus/api/issues/562.

If there's still interest in reimplementing join we can discuss this ticket as well.
