### ISSUE TITLE
Total Count for Pagination View

### ISSUE THREAD

**Issue by benhaynes** [directus/api#391]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Total Count for Pagination View
### :+1: = 0
*Created 1 year ago by @magbeat*
 

-----
### @magbeat – (1 year ago)
When working with UI Suites (like PrimeNG: https://www.primefaces.org/primeng) the paginator component expect a total number of items (when applying filters and limits) in the header to display the correct pagination elements on the bottom of table.

Already discussed in : https://github.com/directus/directus/issues/1720

Sending two requests makes it a bit harder because you cannot simply reuse the answer from the server (with meta and data properties) but you have to construct the response object from a call without the limit and a call with the limit.

**Comment by benhaynes** [comment]
This is now available in v7. returned and total counts are available (optional) as meta data.

**Comment by rijkvanzanten** [comment]
![Ahw yeah gif](https://media.giphy.com/media/8g63zqQ5RPt60/giphy.gif)
