### ISSUE TITLE
New way to add X2M data

### ISSUE THREAD

**Issue by benhaynes** [directus/api#392]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# API: New way to add X2M data
### :+1: = 1
*Created 11 months ago by @WellingGuzman*
 

-----
### @WellingGuzman – (11 months ago)
Adding new X2M data without the data param.

Ex:

```
{
  "name":"hallo",
  "regions":[
    {
      "translation_id":17,
      "region_id":8
    },
    {
      "translation_id":17,
      "region_id":8
    }
  ]
}
```

Ref: #1800

**Comment by rijkvanzanten** [comment]
This has been implemented
