### ISSUE TITLE
Swagger Documentation Generation

### ISSUE THREAD

**Issue by benhaynes** [directus/api#393]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Swagger Documentation Generation
### :+1: = 6
*Created 10 months ago by @jrefi*
 

-----
### @jrefi – :+1: (10 months ago)
It would be useful for client integrations if the API automatically generated Swagger documentation for each table.

Currently the API returns Directus specific schema at /api/1.1/tables/{table-name}, however, in order to increase interoperability, a common markup should be used. Perhaps an additional endpoint such as /api/1.1/tables/{table-name}/_swagger.

Furthermore, it would be nice to have in app swagger documentation for all the static endpoints as well.

**Comment by rijkvanzanten** [comment]
We've had some bad experiences with Swagger in terms of it not supporting all the API features that we use.. 

I think we should focus on keeping [the actual documentation](https://docs.directus.io/api/reference.html) solid and up-to-date.

If anyone feels like this is a huge mistake, please let us know so we can discuss it further 🙂
