### ISSUE TITLE
Softaculous Install Script

### ISSUE THREAD

**Issue by benhaynes** [directus/api#394]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# softaculous install script
### :+1: = 1
*Created 8 months ago by @lastlink*
 

-----
### @lastlink – :+1: (8 months ago)
http://softaculous.com/docs/Adding_Custom_Scripts It would be nice to have an install script on softaculous so people can manage and host via cpanel. This would allow for installing, backups, restoring, and cloning.

**Comment by rijkvanzanten** [comment]
I have no clue what it is or how it works. If anyone wants to have a shot at this, please do!

**Comment by lastlink** [comment]
https://www.softaculous.com/board/index.php?tid=13854

**Comment by benhaynes** [comment]
We have Scriptaculous now!

**Comment by alexut** [comment]
it will be nice to upldate it to directus 8

**Comment by rijkvanzanten** [comment]
@alexut We're not in control over that script. No idea who made / maintains it..
