### ISSUE TITLE
Nested permissions

### ISSUE THREAD

**Issue by benhaynes** [directus/api#395]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Nested permissions (complex)
### :+1: = 1
*Created 8 months ago by @lastlink*
 

-----
### @lastlink – :+1: (8 months ago)
be able to give permissions with something like organic grouping/tagging. useful for a university app needing permissions by resource not just by resource type. maybe through the use of an extension

**Comment by benhaynes** [comment]
This might be possible with "Mine" permissions... otherwise we would need a more complex way to handle it (regex?).

**Comment by rijkvanzanten** [comment]
I think this would be solved by using the status workflow. We can reopen to discuss further if that doesn't solve this usecase.

**Comment by benhaynes** [comment]
Yeah, I think that regex based permissions might be an edge case for Directus
