### ISSUE TITLE
Add status to directus_roles

### ISSUE THREAD

**Issue by benhaynes** [directus/api#397]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Disable a whole Group
### :+1: = 2
*Created 7 months ago by @WellingGuzman*
 

-----
### @WellingGuzman – :+1: (7 months ago)
This is a that may works:

Adding status to the groups table, allowing an admin to block/disable a whole group without taking down their permissions or deleting each users.

One hit, all down!

**Comment by benhaynes** [comment]
I wonder if this would work as expected now that we're moving from groups to roles (?)

**Comment by rijkvanzanten** [comment]
I wonder if we even need this as soon as updating by filter param is implemented!

If you can update a group of users by filter, you don't need to be bothered with roles 🙂

**Comment by rijkvanzanten** [comment]
This won't be needed anymore as you can achieve the same goal by using https://github.com/directus/api/issues/77

**Comment by benhaynes** [comment]
I actually agree with that, and I'd be okay if we want to close this one and use that as a solution. But we would still need to add an application interface or button to handle this with in settings.
