### ISSUE TITLE
Relational of depth 2

### ISSUE THREAD

**Issue by benhaynes** [directus/api#398]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Relational of depth 2
### :+1: = 1
*Created 6 months ago by @daniel-upzzle*
 

-----
### @daniel-upzzle – :+1: (6 months ago)
Hi,

I'm new to github contributions and I don't know if it's the way to suggest this tiny change. Or how to do that.

In api/core/Directus/Database/TableGateway/RelationalTableGateway.php

let more depth to recursive load relational values.

I've done that in a fork: https://github.com/daniel-upzzle/directus/pull/1/files

Thanks, Daniel

 

-----
### @daniel-upzzle – :+1: (6 months ago)
...

**Comment by benhaynes** [comment]
This has been added to API 2.0 (v7 of the app). Now you can go as deep as you want with `dot.notation`!!

**Comment by rijkvanzanten** [comment]
We can go infinitely deep with the `fields` param

**Comment by rijkvanzanten** [comment]
![Leo Inception gif](https://media.giphy.com/media/muZkpJaYw1PvW/giphy.gif)
