### ISSUE TITLE
Support WebP file format

### ISSUE THREAD

**Issue by benhaynes** [directus/api#399]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Support WebP file format
### :+1: = 1
*Created 6 months ago by @apexJCL*
 

-----
### @apexJCL – :+1: (6 months ago)
Maybe the feature at all it's not that significative because the format isn't widely supported (requiring polyfills for Safari and other browsers), but it surely helps when you're developing a landing site that requires high quality pictures but with the lowest size possible.

By now, webp files can be uploaded/requested, but previews aren't available at all in tables/thumbnails or similar.

**Comment by cesasol** [comment]
I guess the first step towards this is the how php could do this. And here are a couple of libraries:
- [php-webp from S1SYPHOS](https://github.com/S1SYPHOS/php-webp)
- [webp-convert from rosell-dk](https://github.com/rosell-dk/webp-convert)

Both have nice fallbacks in case some option is no available.

And the second question is how we should serve it?
First could be a explicit call with the thumbnailer (defining extension) or automatic serving by detecting the header. The first option requires the developer to use the picture+source element and the second it's seamless for everyone.

**Comment by brocgailit** [comment]
This is available via [Intervention Image](http://image.intervention.io/api/encode):

**Encode:** `$webp = (string) Image::make('public/foo.png')->encode('webp');`

This should be high priority for anyone looking for the performance perks of next gen formats (It will also make [Google Lighthouse](https://developers.google.com/web/tools/lighthouse/) happy. 

Maybe work this into the thumbnails endpoints?

**Comment by rijkvanzanten** [comment]
> Maybe work this into the thumbnails endpoints?

I don't that that idea! Would be very useful if the thumbnailer could not only change sizes, but also convert to different formats. Would be awesome if you could upload one master huge PNG file, which you can then use on the front-end in both jpg, png, and webp formats (or whatever format you require)

**Comment by brocgailit** [comment]
#878

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by brocgailit** [comment]
... NEW PR = #1001 🚀

**Comment by benhaynes** [comment]
Whoa, thanks @brocgailit!!!
