### ISSUE TITLE
Database backup

### ISSUE THREAD

**Issue by benhaynes** [directus/api#400]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Database backup
### :+1: = 1
*Created 6 months ago by @diegogurpegui*
 

-----
### @diegogurpegui – :+1: (6 months ago)
Just a simple feature allowing admin users to download a backup of the Database (a SQL dump should be enough). Additionaly, the possibility to restore that database would be great.

Even more so, those backups could be saved in a specific (customizable?) location to allow the admin user to navigate through previous backups and restore them.

This is meant to be a shortcut for admins to avoid accessing the database directly to perform the backup. Just manage everything from the UI.

**Comment by rijkvanzanten** [comment]
Ref #31

**Comment by benhaynes** [comment]
I added this to the API instead of the App because I don't think this would be an interface. I think it's just an API feature... and we can handle that int he app however we want.

**Comment by rijkvanzanten** [comment]
Theoretically, we could make a page extension that pulls in the schema information and exports it to any format we want.

I think it's more useful to have a dedicated /export and /import endpoint though

**Comment by benhaynes** [comment]
More efficient too... :)

**Comment by benhaynes** [comment]
Same as #31
