### ISSUE TITLE
Custom Email Templates

### ISSUE THREAD

**Issue by benhaynes** [directus/api#401]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Custom Email Templates
### :+1: = 1
*Created 5 months ago by @BennerGe*
 

-----
### @BennerGe – :+1: (5 months ago)
Adding own email templates, located under /customs/views/mail, which replaces the original templates.

**Comment by benhaynes** [comment]
I think we have this now in v7 (API 2.0), but we cant close it until it's 100% documented

**Comment by rijkvanzanten** [comment]
@WellingGuzman 🔔

**Comment by benhaynes** [comment]
@WellingGuzman ?
