### ISSUE TITLE
API Order by RANDOM

### ISSUE THREAD

**Issue by benhaynes** [directus/api#402]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# API Order by RANDOM
### :+1: = 1
*Created 5 months ago by @benhaynes*
 

-----
### @benhaynes – :+1: (5 months ago)
In addition to ASC and DESC, we should have a way to order by RAND(). If you want two random items with filters it is very inefficient to do this in the app (fetching a lot of info first, then randomizing, then limiting)

**Comment by rijkvanzanten** [comment]
We talked about supporting `?` for `sort` (`sort=name,?` = sort by name followed by random), not sure if it made the cut though

**Comment by benhaynes** [comment]
I think we have this, but is it documented? @WellingGuzman ?

**Comment by rijkvanzanten** [comment]
Yep, it's in the API: https://github.com/directus/api/issues/95

**Comment by rijkvanzanten** [comment]
It's also documented: https://docs.directus.io/api/reference.html#sorting

@benhaynes
