### ISSUE TITLE
Reset password through rest api

### ISSUE THREAD

**Issue by benhaynes** [directus/api#403]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# reset password through rest api
### :+1: = 1
*Created 5 months ago by @lastlink*
 

-----
### @lastlink – :+1: (5 months ago)
should be able to do this through the api such as auth/rest-password. Maybe have a group that can do this

**Comment by rijkvanzanten** [comment]
https://docs.directus.io/api/reference.html#password-reset-request
