### ISSUE TITLE
Manage Database on external server

### ISSUE THREAD

**Issue by benhaynes** [directus/api#405]
#### :rotating_light: MIGRATED FROM REQUESTS.GETDIRECTUS.COM :rotating_light: 

# Manage Database on external server
### :+1: = 1
*Created 4 months ago by @MiraiTunga*
 

-----
### @MiraiTunga – :+1: (4 months ago)
e.g Directus tables/db lives on heroku but the database it manages lives in aws

Result Directus wont need to be installed within the same database it manages.

**Comment by rijkvanzanten** [comment]
The API and the databases are separated now
