### ISSUE TITLE
Ping central telemetry endpoint

### ISSUE THREAD

**Issue by benhaynes** [directus/api#409]
On admin login we should ping the central telemetry endpoint with the body info filled in. We can also store a flag in the session so it only sends once (less frequently).

https://telemetry.directus.io/count
https://github.com/directus/telemetry#count

@rijkvanzanten will confirm that the metric is received correctly once you've implemented this @WellingGuzman.

**Comment by WellingGuzman** [comment]
Wouldn't be better that the app directly ping the server instead of the API?

Does it needs to sends both app and api version/url?

The session flag, won't guarantee the client will send cookies in subsequent request to identify itself to avoid the server from pinging the server.

If that's alright I can make the ping, but the API won't be able to tell the app version and url.

**Comment by benhaynes** [comment]
The API doesn't need to send any App info.

The API needs to send data itself because many project will _only_ use the API (no APP) and we want to count those.

**Comment by WellingGuzman** [comment]
Then the telemetry has a bug, because it's expecting both information.

I will be make the ping with the API information when an user from admin role authenticate using credentials. is that what you mean when you said login, correct?

**Comment by benhaynes** [comment]
@rijkvanzanten how would you like to handle this?

**Comment by rijkvanzanten** [comment]
This makes sense. The API will send the info on the API, the app will only send the info on the app.

I'll refactor the telemetry server a little bit so accepts the following JSON:

```json
{
    "version": "v2.0.0-rc.2",
    "url": "https://directus.app",
    "type": "api"
}
```

**Comment by WellingGuzman** [comment]
@benhaynes would this honor the `feedback` flag in the config or something else?

**Comment by benhaynes** [comment]
No, this isn't for feedback. There's no flag for this one, it just sends on Admin login and fails silently if there's no internet connection. @WellingGuzman

**Comment by WellingGuzman** [comment]
I added a ping to the central telemetry (https://github.com/directus/api/commit/6051b07c3f8b5c8c6eb295ce26c3943fbe14d966).

Feel free to close it as soon as it's working for you, otherwise let me know.

**Comment by benhaynes** [comment]
Hey @WellingGuzman – are you not able to test this on your side to make sure it's sending? Quickly looking at my network tab of dev tools I see that the API is not sending the payload (`204`). Can you fix it to actually send the data?

## API
![screen shot 2018-10-02 at 10 30 19 pm](https://user-images.githubusercontent.com/522079/46387077-fc95ca00-c692-11e8-8986-26d27a8d8d8a.png)

## APP
![screen shot 2018-10-02 at 10 30 11 pm](https://user-images.githubusercontent.com/522079/46387073-f9024300-c692-11e8-8041-fd758803f9f1.png)

**Comment by WellingGuzman** [comment]
That `204` you are seeing is the browser preflight request to check if it has access to make request to the server (CORS mechanism).

**Comment by benhaynes** [comment]
Ahh

Well the data in telemetry is all hashed so I can't tell. There are only 4 `api` items in there though... from almost a month ago. So I don't think it's working.

**Comment by benhaynes** [comment]
This is working now...
