### ISSUE TITLE
Encrypted Interface Stores Plain Text in the MySQL Database

### ISSUE THREAD

**Issue by LudwigNova** [directus/api#410]
After creating a collection with an encrypted interface, when trying to create an item, adding an encrypted interface passes through, but a quick look at the database shows that the value is stored in plain text, regardless of which hashing method is selected during creation of the collection with the encrypted interface.

**Comment by benhaynes** [comment]
Yikes! That's no good.... thank you for catching this.

@WellingGuzman @rijkvanzanten – we need to get this resolved asap.

**Comment by WellingGuzman** [comment]
What's the encrypted data type? There's not encrypted type in the API.

What field type is the app creating?

**Comment by LudwigNova** [comment]
This one right here:
![screenshot 41](https://user-images.githubusercontent.com/19542804/45317520-4104ce80-b508-11e8-9b73-d9091167a827.png)

Here's the encryption type I pick
![screenshot 42](https://user-images.githubusercontent.com/19542804/45317541-4a8e3680-b508-11e8-82ae-c85118ef476a.png)

Then I go to change the value
![screenshot 43](https://user-images.githubusercontent.com/19542804/45317549-511cae00-b508-11e8-8937-9334b0d5eedc.png)

And here's how it ends up in the database
![screenshot 44](https://user-images.githubusercontent.com/19542804/45317562-58dc5280-b508-11e8-919f-a23658e97239.png)

**Comment by WellingGuzman** [comment]
I see this is an interface named: [`encrypted`](https://github.com/directus/api/blob/7d625202230641ee373f8f1d043a1d0925493d70/extensions/core/interfaces/encrypted/meta.json), I don't see any reference to any encryption algorithm, but this is confusing as I believe this is trying to use [`hashing`](https://github.com/directus/api/blob/master/extensions/core/interfaces/encrypted/meta.json#L31) algorithm instead of encryption algorithms.

**Comment by WellingGuzman** [comment]
@LudwigNova I see, there's not problem with the API, because there's not a field type for encryption, maybe this interface was meant for hashing and it's not finished, but @rijkvanzanten will be the person to help you here.

**Comment by LudwigNova** [comment]
Right, my bad! Meant hashing, got wrapped up in the semantics of it all

**Comment by rijkvanzanten** [comment]
@WellingGuzman This is the interface that used to use it's own hashing function in the Hook. The hook contents got moved to it's own dedicated hashing endpoint, but the interface never got updated to use the new endpoint.. @WellingGuzman is there documentation on how to add a hook to interfaces?

**Comment by benhaynes** [comment]
From now on, any time the answer is: "there's no docs for this yet" we need to either:

A. Add those Docs immediately
B. Add a ticket to add Docs later

https://github.com/directus/docs-v7/issues/9

**Comment by rijkvanzanten** [comment]
Could you maybe help me figuring out how to call the APIs hashing function _from_ the interfaces hook? Or do we have to go through the endpoint somehow?

> Also the interface's name is misleading because it's not encrypting data if it's going to use the hashing functions.

You're right! It should be renamed `hash`

**Comment by WellingGuzman** [comment]
Ben, there was a ticket for this in docs already created long time ago. https://github.com/directus/docs/issues/30

> Could you maybe help me figuring out how to call the APIs hashing function from the interfaces hook? Or do we have to go through the endpoint somehow?

You don't have to go through the endpoint if you don't want to. If you want the api to handle the hashing you can do it like this:

```php
<?php

use Directus\Hook\Payload;
use Directus\Application\Application;

$hashValue = function (Payload $payload) {
    $data = $payload->getData();
    $container = Application::getInstance()->getContainer();
    $schemaManager = $container->get('schema_manager');
    $hashManager = $container->get('hash_manager');
    // the hashing algorithm are:
    // core (uses php_password default hasher)
    // bcrypt
    // md5
    // sha1
    // sha224
    // sha256
    // sha384
    // sha512
    $options = ['hasher' => 'core'];
    $collection = $schemaManager->getCollection($payload->attribute('collection_name'));

    foreach ($data as $fieldName => $value) {
        $field = $collection->getField($fieldName);
        if ($field && $field->getInterface() === 'hash') {
            $hashedString = $hashManager->hash($value, $options);
            $payload->set($fieldName, $hashedString);
        }
    }

    return $payload;
};

return [
    'filters' => [
        'collection.insert:before' => $hashValue,
        'collection.update:before' => $hashValue,
    ]
];
```

**Comment by benhaynes** [comment]
Haha, well clearly that Docs ticket was ignored since it's a year old. Anyway, these are all new Docs... so we should have/add all tickets in the `docs-v7` repo.
