### ISSUE TITLE
Connecting to Local API from Local APP results in a broken program and lots of errors

### ISSUE THREAD

**Issue by grinninglich** [directus/api#415]
**Describe the bug**
Connecting to local API from local APP results in a broken, laggy and mostly unusable environment. (See the screenshots below)

**Some of the errors on dev console**
**[Error] TypeError: Object.values requires that input parameter not be null or undefined
values**
fields — items.vue:171
get — vue.runtime.esm.js:3138
evaluate — vue.runtime.esm.js:3245
(anonymous function) — vue.runtime.esm.js:3503
fieldNames — items.vue:257
get — vue.runtime.esm.js:3138
evaluate — vue.runtime.esm.js:3245
(anonymous function) — vue.runtime.esm.js:3503
lc — items.vue:1:943
_render — vue.runtime.esm.js:4540
r — vue.runtime.esm.js:2784
get — vue.runtime.esm.js:3138
an — vue.runtime.esm.js:3127
Ut — vue.runtime.esm.js:2791
init — vue.runtime.esm.js:4133
h — vue.runtime.esm.js:5604
p — vue.runtime.esm.js:5551
E — vue.runtime.esm.js:5841
k — vue.runtime.esm.js:5932
E — vue.runtime.esm.js:5818
k — vue.runtime.esm.js:5932
(anonymous function) — vue.runtime.esm.js:6092
_update — vue.runtime.esm.js:2666
r — vue.runtime.esm.js:2784
get — vue.runtime.esm.js:3138
run — vue.runtime.esm.js:3215
en — vue.runtime.esm.js:2977
(anonymous function) — vue.runtime.esm.js:1833
it — vue.runtime.esm.js:1754
promiseReactionJob

	Qe (chunk-vendors.b2c3b114.js:37:11123)
	Ze (chunk-vendors.b2c3b114.js:37:11035)
	Je (chunk-vendors.b2c3b114.js:37:10903)
	_render (chunk-vendors.b2c3b114.js:37:31153)
	r (chunk-vendors.b2c3b114.js:37:18438)
	get (chunk-vendors.b2c3b114.js:37:20939)
	an (chunk-vendors.b2c3b114.js:37:20856)
	Ut (chunk-vendors.b2c3b114.js:37:18451)
	init (chunk-vendors.b2c3b114.js:37:28093)
	h (chunk-vendors.b2c3b114.js:37:41251)
	p (chunk-vendors.b2c3b114.js:37:40880)
	E (chunk-vendors.b2c3b114.js:37:43455)
	k (chunk-vendors.b2c3b114.js:37:44205)
	E (chunk-vendors.b2c3b114.js:37:43178)
	k (chunk-vendors.b2c3b114.js:37:44205)
	(anonymous function) (chunk-vendors.b2c3b114.js:37:45355)
	_update (chunk-vendors.b2c3b114.js:37:17511)
	r (chunk-vendors.b2c3b114.js:37:18428)
	get (chunk-vendors.b2c3b114.js:37:20939)
	run (chunk-vendors.b2c3b114.js:37:21666)
	en (chunk-vendors.b2c3b114.js:37:19905)
	(anonymous function) (chunk-vendors.b2c3b114.js:37:11890)
	it (chunk-vendors.b2c3b114.js:37:11230)
	promiseReactionJob
**[Error] TypeError: Object.values requires that input parameter not be null or undefined
values**
fields — items.vue:171
get — vue.runtime.esm.js:3138
evaluate — vue.runtime.esm.js:3245
(anonymous function) — vue.runtime.esm.js:3503
fieldNames — items.vue:257
get — vue.runtime.esm.js:3138
evaluate — vue.runtime.esm.js:3245
(anonymous function) — vue.runtime.esm.js:3503
lc — items.vue:1:943
_render — vue.runtime.esm.js:4540
r — vue.runtime.esm.js:2784
get — vue.runtime.esm.js:3138
run — vue.runtime.esm.js:3215
en — vue.runtime.esm.js:2977
(anonymous function) — vue.runtime.esm.js:1833
it — vue.runtime.esm.js:1754
promiseReactionJob

	Qe (chunk-vendors.b2c3b114.js:37:11123)
	Ze (chunk-vendors.b2c3b114.js:37:11035)
	Je (chunk-vendors.b2c3b114.js:37:10903)
	_render (chunk-vendors.b2c3b114.js:37:31153)
	r (chunk-vendors.b2c3b114.js:37:18438)
	get (chunk-vendors.b2c3b114.js:37:20939)
	run (chunk-vendors.b2c3b114.js:37:21666)
	en (chunk-vendors.b2c3b114.js:37:19905)
	(anonymous function) (chunk-vendors.b2c3b114.js:37:11890)
	it (chunk-vendors.b2c3b114.js:37:11230)
	promiseReactionJob

**[Error] Failed to load resource: the server responded with a status of 422 (Unprocessable Entity) (collections, line 0)**
**[Error] {code: 12, message: "datatype is required"}**
	Ql (app.9febad0d.js:1:125101)
	$emit (chunk-vendors.b2c3b114.js:37:16426)
	(anonymous function) (app.9febad0d.js:1:208058)
	promiseReactionJob

**To Reproduce**
1. Installed the API from source, run composer, configure api.php, create database, configure and run the docker-compose. API works fine. No error. 
2. Install the APP. Add the local API link. Run the http-server. Connect to local API.
3. See the complaint about extensions. Go to the api/extension folder and run "npm install && npm run build
4. Connect again. Wait for a very long time to connect only to a broken and very laggy environment. (See the screenshots)

**Note:** Connecting to your Remote Demo API from local APP doesn't yield any bugs. It is much much faster than local API and everything working smoothly. And it is very fast.

**Screenshots**
In first screenshot this table is created from SQL, clicked "Manage" on "Directus Admin Settings" but in collections main screen, you can't see any add (+) button on top right and no filter field either.

![screen shot 2018-09-18 at 22 05 25](https://user-images.githubusercontent.com/1384515/45710494-74420000-bb8f-11e8-8699-f721003d5fa9.png)

In second screenshot trying to add a table, results in an error.

![screen shot 2018-09-18 at 22 06 08](https://user-images.githubusercontent.com/1384515/45710508-7a37e100-bb8f-11e8-9d64-7f2bacdd4e5c.png)

**Desktop (please complete the following information):**
 - MacOS High Sierra 10.13.6
 - Chrome and Safari latest version of today.
 - APP build version from GitHub, API latest version from Git Source run with docker-compose.

**Final Question**
Why did the extensions which are a lot of JS code building into the API side instead of APP?

**Comment by WellingGuzman** [comment]
Moved to: https://github.com/directus/app/issues/825.

The app needs to implement the new API changes.
