### ISSUE TITLE
Endpoint for Storage Adapters

### ISSUE THREAD

**Issue by benhaynes** [directus/api#424]
We need an endpoint that lists all available storage adapters so that the App can offer those as options and we know the original uploads filesystem path set in the API config.

**Comment by WellingGuzman** [comment]
We never finished supporting multiple storage adapters, so configuration is attached to only one adapter per project (https://github.com/directus/api/issues/61).

**Comment by benhaynes** [comment]
What do we need to finish to support multiple storage adapters? Is there a ticket for it? @WellingGuzman

**Comment by WellingGuzman** [comment]
Added this to #61
