### ISSUE TITLE
Improve copying extensions files

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#428]
Extensions can have internal directory structure, images, including php files inside directories that needs to be copied over to the public directory.

Also we need to think about copying development or unwanted files to the public directory, maybe we allow user to add a file where they can whitelist files and directories. Allowing not copying over the vendors directory, or probably not allowing direct access.

At the moment it only copies files in the root directory: `meta.json`, `hooks.php`, `endpoints.php`.

Accessing `hooks.php` and `endpoints.php` should be disallowed.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
