### ISSUE TITLE
Check for full permissions before building the query

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#434]
Some permissions need to consider while building the query, but we should ask for permissions upfront before working with the query. the user at least should have permission on read, any kind of permission.

**Comment by benhaynes** [comment]
Is this an enhancement? Is it still valid? @WellingGuzman

**Comment by WellingGuzman** [comment]
I think I opened this to remember or finished what was implement here probably: https://github.com/directus/api/commit/68408d37250eaf9a1bfa3a37c9f7a7ec1c9b8597.

I can't recall, but the point described in this ticket was implemented long time ago.

This issue: https://github.com/directus/api/issues/627, is what next to fix in terms of permissions and ownership.

I will close this, unless there's something else related to this issue.
