### ISSUE TITLE
Add first and last name to user invitation

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#436]
Directus users' `first_name` and `last_name` are now required ([Ref](https://github.com/directus/api/commit/a0baf473f2450d5148320a468db4bacd2221fd7f#diff-bda270e2ef19060bd550ad2bdec1a08eR1021)).

Inviting an user must include `first_name`, `last_name`, and `email`.

**Comment by lex111** [comment]
Can I have more details to implement this?

**Comment by benhaynes** [comment]
@WellingGuzman – the `required` flag was really for the App (so users don't delete their names). The name shouldn't be required for inviting users (status == invited)... that should only require an email. Is that OK with you?

We can still add the name into emails once the user is active though:

https://github.com/directus/api/blob/master/src/mail/reset-password.twig
https://github.com/directus/api/blob/master/src/mail/forgot-password.twig

@lex111 – thanks for posting... we can start with the two template above but probably won't add the first/last names to the invite email.

**Comment by lex111** [comment]
> we can start with the two template above but probably won't add the first/last names to the invite email.

@benhaynes this is not related to this PR?

I made these changes to PR https://github.com/directus/api/pull/458

Right or wrong?

**Comment by WellingGuzman** [comment]
It's okay with me. if that's the case we can close this right here.

**Comment by benhaynes** [comment]
Great! I'll consider this one done...
