### ISSUE TITLE
Clear output buffer on production

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#438]
When php throws warning, notices or errors that was not caught by the API it corrupt the response JSON. In development this should be a problem because you want to see the most errors as possible, but I believe when you are running on production all these should be removed from the output buffer and return a valid JSON response.

**Comment by benhaynes** [comment]
Can't we just update the PHP error reporting when in prod? @WellingGuzman

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
