### ISSUE TITLE
Error when on Local! telemetry

### ISSUE THREAD

**Issue by Mu9tafa-Online** [directus/api#439]
**Describe the bug**
The App  stop responding when disconnect the Internet (Localhost Env) 

**To Reproduce**
1. disconnect the Internet 
2. visit admin and try to add collection
3. check brwoser console

**Screenshots**
![drcts](https://user-images.githubusercontent.com/5323832/46209679-c244c980-c32e-11e8-9b2e-ccfc6a07dd2b.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [Opera Latest, Chrome]
- PHP v7.1

**Comment by rijkvanzanten** [comment]
Hey @Mu9tafa-Online! Thanks for the heads up. This request is not affecting the Directus app itself in any way, so it's harmless if it doesn't go through offline. Good catch though! 🕵️

**Comment by Mu9tafa-Online** [comment]
So you just closed the issue without saying how to deal with it! weird enough

**Comment by rijkvanzanten** [comment]
Sorry for the confusion, but there's nothing to deal with.. This particular error means that the app can't reach the outside world which makes sense seeing you're offline. I'm adding in a little check that only sends out the request if you have a connection

**Comment by Mu9tafa-Online** [comment]
So i can't test it offline ?

**Comment by Mu9tafa-Online** [comment]
So is it impossible to use it for a local development?

**Comment by rijkvanzanten** [comment]
I'm not sure I'm following.. 

The error you showed above is harmless in local development which is why I closed the ticket. (I also added a check that it doesn't send that request if you're offline just now). Running Directus locally or on a server shouldn't make a difference. I'm working on the app & api locally as we speak.

**Comment by Mu9tafa-Online** [comment]
OK, thanks for clarifying ☺️

**Comment by benhaynes** [comment]
@rijkvanzanten – just checking to make sure this update made it into the App (since the issues closed, I don't want it to get lost).

**Comment by rijkvanzanten** [comment]
> I also added a check that it doesn't send that request if you're offline just now

Yes it's in
