### ISSUE TITLE
Combine htaccess files

### ISSUE THREAD

**Issue by benhaynes** [directus/api#443]
We seem to have many htaccess files (for apache) all over the place in the API. We need to combine them all into the root...

**Comment by rijkvanzanten** [comment]
... so it's clear what's going on where, and so it's possible to port it over to other server environments.

**Comment by rijkvanzanten** [comment]
@josephgagliardi any thoughts on this?

**Comment by josephgagliardi** [comment]
Seems highly advisable and doable to consolidate directives to the root. I'm spotting only a few directives spread across fewer than half a dozen files.

**Comment by benhaynes** [comment]
Cool. Let's make these htaccess tickets our first API task then! :)

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
