### ISSUE TITLE
Settings>Roles

### ISSUE THREAD

**Issue by benhaynes** [directus/api#444]
Name + Description should be directly below the permissions interface... right now it is below the IP Whitelist.

**Comment by benhaynes** [comment]
@rijkvanzanten I know this is in the API... but I tried to sneaky assign it to you. :)

**Comment by rijkvanzanten** [comment]
This was most likely due to https://github.com/directus/api/issues/480 and has been fixed in https://github.com/directus/api/commit/8569b40feb7a6453bc2012c5fd7fe502e6a0c421
