### ISSUE TITLE
System Column Order

### ISSUE THREAD

**Issue by benhaynes** [directus/api#445]
The schema should create fields in a specific order. Most are good, but here are a few changes:

**I have also proposed changing three column names and removing one column**. @rijkvanzanten

**directus_collections**
1. collection
1. managed
1. hidden
1. single
1. icon
1. note
1. translation

**directus_fields**
1. id
1. collection
1. field
1. type
1. interface
1. options
1. locked
1. validation
1. required
1. readonly
1. hidden_input _(should become `hidden_detail`)_
1. hidden_list _(should become `hidden_browse`)_
1. sort
1. view_width _(should become `width`)_
1. group
1. note
1. translation

**directus_files**
1. id
1. storage_adapter _(should become `storage`)_
1. filename
1. title
1. type
1. uploaded_by
1. uploaded_on
1. charset
1. filesize
1. width
1. height
1. duration
1. embed
1. folder
1. description
1. location
1. tags
1. metadata

**directus_permissions**
_Move `status_blacklist` to the end, after the other two blacklist columns_

**directus_revisions**
_Reverse these two columns so collection comes before item:_
* parent_collection
* parent_item

**directus_roles**
_Move `external_id` to the last column_

**directus_users**
1. id
1. status
1. first_name
1. last_name
1. email
1. password
1. token
1. timezone
1. locale
1. locale_options
1. avatar
1. company
1. title
1. email_notifications
1. high_contrast_mode (does this do anything? delete until later?) @rijkvanzanten ??
1. last_access_on
1. last_page
1. external_id

**Comment by benhaynes** [comment]
I am getting a lot of errors for: `hidden_input`... @WellingGuzman can you please quickly check that things work before you marking it as closed? It doesn't even let me log in... so I think there's still some issues here.

**Comment by WellingGuzman** [comment]
@benhaynes can you please details what "I am getting a lot of errors for :`hidden_input`"?

There's not issue with the API related to `hidden_input` as far as I am concern.

What I am seeing is that you edited the ticket adding a note to change `hidden_input` to `hidden_detail`, and I wasn't notified about the change. This might be the issue you are experience.

Did you change the `hidden_input` to `hidden_detail` in your database?

**Comment by benhaynes** [comment]
I edited the ticket before you started... either way, can you correct the `hidden_input` field in the API?

**Comment by WellingGuzman** [comment]
I renamed `directus_fields.hidden_input` to `hidden_detail` (https://github.com/directus/api/commit/10a82fb0fda41ac6c40bd6e3d020965a356d9f3f).

Please close it if it solves the issue, otherwise let me know.

**Comment by benhaynes** [comment]
Looking good...
