### ISSUE TITLE
Create email templates

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#45]
Create the default templates for all Directus emails

**Comment by WellingGuzman** [comment]
@benhaynes I'd like you to create the default emails template.

**Comment by benhaynes** [comment]
I would like to use the same ones that are currently on Hosted, except instead of Blue, we use Black:

![screen shot 2018-04-09 at 4 03 49 pm](https://user-images.githubusercontent.com/522079/38520146-e6d3dd00-3c0f-11e8-8904-63ad27d501bf.png)

**Comment by benhaynes** [comment]
The code for this should already exist within one of our third-party apps (Mandrill or Intercom) or maybe it can be viewed from a received email.

**Comment by WellingGuzman** [comment]
We are actually using the black color version of hosted.
