### ISSUE TITLE
can't modify already existing table

### ISSUE THREAD

**Issue by alioygur** [directus/api#451]
**Describe the bug**
can't modify already existing table, because there aren't records in the `directus_fields` table.

**To Reproduce**
1. Create a table directly in mysql.
2. Go to Settings > Collections & Fields page
3. Click the table that you have been created.
4. Click the ID field and select Primary Key interface and next and save
5. you will see the error.

```json
{"error":{"code":null,"message":"SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined","class":"PDOException","file":"\/var\/www\/vendor\/zendframework\/zend-db\/src\/Adapter\/Driver\/Pdo\/Connection.php","line":379}}
```

**Expected behavior**
Should be updated.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

I think this can be fix like this.

when client request for collection details check the `directus_table` if there is not records for the table add default values based on column types.

**Comment by WellingGuzman** [comment]
Hey @alioygur, what version you were using? I wasn't able to reproduce this issue.

Some days ago I fixed a issue related to this, can you confirm it still happens in the current version?

**Comment by alioygur** [comment]
hello @WellingGuzman the version I was use is v2.0.0-rc.4

I haven't test it in newer version.
