### ISSUE TITLE
Validate nested object in payload

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#455]
Directus validate all input data except the related data.

Known bug: Adding a file to a related field doesn't validate the required fields.

Example:

`image` is a `file` type Field.
```
{
  "image": {"data": "<base64-content>"}
}
```

It will throw an error trying to write a file with the name of "" (empty string).

**Comment by WellingGuzman** [comment]
The endpoints should validate the whole payload before starting to work with it to prevent incorrect data type in relational/nested data during the process. This could prevent problems where one query can be performed and the other failed.

**Comment by bjgajjar** [comment]
Fixed in #1002
