### ISSUE TITLE
File Title

### ISSUE THREAD

**Issue by benhaynes** [directus/api#456]
When uploading a file, the `title` should be a cleaned up version of the filename, but currently it's doubling the extension:

* Original: `animals_hero_mountains.jpg`
* Current Title: `Animals Hero Mountains.jpg.jpg`
* Ideal Title: `Animals Hero Mountains`

**Comment by ksandhu16** [comment]
Can I work on this ?

**Comment by benhaynes** [comment]
A big thanks to @Mave95 for fixing this one!
