### ISSUE TITLE
Endpoint: Get Items from Multiple Collections

### ISSUE THREAD

**Issue by benhaynes** [directus/api#460]
When creating a project with relatively few items, but a good number of collections, it might be nice to have an endpoint that *Gets All Items*. 

For example, if your project has 20 collections each with <100 items, then you might simply want to fetch all items on when you load your project's application. Having this endpoint would be faster and more efficient than making 20 API calls and would make updating a central "store" (eg: vuex) easier.

I imagine the API getting one "page" (API item max) of items for all of collections. There could also be options for which collections to fetch or how many items per collection to fetch.

### Some endpoint ideas include:

* `GET /[project]/collections` _With a flag to also return items_
* `GET /[project]/items/*`
* `GET /[project]/items/c1,c2,c3`

**Comment by WellingGuzman** [comment]
How the result of this would work?

It will get the "max limit" of each collection or the "max limit" of the combination of all items? Example, if you have 20 collections with 90 items each, and the "limit max" is 100, will it return 1800? or a combination of all items that matches 100 items?

Will the output will be grouped by collection like this:

```json
{
    "data": {
        "projects": {
            "data": []
        },
        "clients": {
            "data": []
        },
        "users": {
            "data": []
        }
    }
}
```

In short: Is this a batch items fetch by two or more collections?

**Comment by benhaynes** [comment]
I imagine it as the max limit for _each_ collection. So in your example it would return 1800 items.

**Comment by flayks** [comment]
That would be very useful to avoid multiple API calls!

**Comment by michalcharvat** [comment]
Did you implement this feature? It is very usefull for small definitions sets?

**Comment by benhaynes** [comment]
No, we focused on stability for the time being.
