### ISSUE TITLE
Check if CURL exists before using it

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#461]
Telemetry uses php_curl, but logging into the API fails if curl doesn't exist for that one request. Instead, it should check if it's possible to use and fail silently if not

**Comment by WellingGuzman** [comment]
In this case, should we bring back the error when there's a missing required extension? Even though cURL is not a strong requirement, we should always omit it for example in the case of telemetry or fetching youtube or Vimeo data?

What's the thoughts on this? because this is required it should expected to work before even using the API. should we remove it from being required and be optional?

@benhaynes 🔔

**Comment by benhaynes** [comment]
Yes, the API should return which requirements are missing during installation so the App can show this:

https://github.com/directus/app/issues/860

**Comment by benhaynes** [comment]
I think all our requirements should be... required. And we warn if they are not found (on install)

**Comment by WellingGuzman** [comment]
I am still going to add a way to do not call the function if it doesn't exists. but I wanted to know if we want to bring back that layer of "protection" to avoid calling a function that Directus required.

> Yes, the API should return which requirements are missing during installation so the App can show this:
> 
> directus/app#860

Yes, but it could be installed manually without using the app, or removed after installation, and it will throw all these errors of missing extensions. Alerting (throwing those errors) by the API after the installation will be helpful in this case.

**Comment by rijkvanzanten** [comment]
Isn’t it a bit harsh to block all of the API just if you can’t use the telemetry & YouTube? I feel like we should stop the telemetry and disable embeds if you don’t have curl. See it as an enhancement instead of a requirement

**Comment by rijkvanzanten** [comment]
95% of the api works just fine without curl

**Comment by benhaynes** [comment]
I don't want to have too many features not work in Directus because you lack server requirements, but I also don't want to have too many requirements. For cURL I think we should:

* Telemetry: Fail silently if you don't have it
* Embeds: Return an appropriate error if you don't have it
    * The App doesn't support embeds yet, but when it does we can look into making this a hard API requirements

**Comment by WellingGuzman** [comment]
This ticket is also related to https://github.com/directus/api/issues/622. Where we want to enforce the requirements before using the API.

In this case `curl` we want curl to be a silently fail or warn when we use embeds.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
