### ISSUE TITLE
Filter out extensions starting with _

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#463]
Like _demo or _example, that way we can have example interfaces / pages / etc without them showing up in the app 😄

**Comment by rijkvanzanten** [comment]
Also for hooks / endpoints / etc

**Comment by WellingGuzman** [comment]
Which one are not ignore? I believe it worked for everything in particular interfaces and endpoints.

Can you give me an example of the directory/file structure you used that didn't ignore the extension?

**Comment by benhaynes** [comment]
I have confirmed that this is working for `pages`, `layouts` and `interfaces`... not sure how to test hooks/endpoints.

**Comment by WellingGuzman** [comment]
@benhaynes there are some demo [hooks](https://github.com/directus/api/tree/master/public/extensions/custom/hooks) and [endpoints](https://github.com/directus/api/tree/master/public/extensions/custom/endpoints) in `public/extensions/custom/hooks` and `public/extensions/customs/endpoints`.

**Comment by benhaynes** [comment]
Oh great! Then this one is done...

👍
