### ISSUE TITLE
Remove status_mapping.published

### ISSUE THREAD

**Issue by benhaynes** [directus/api#464]
`getItems` (plural) respects the `status_mapping.published`

`getItem` (singular) **does not** respect the `status_mapping.published`

We need to be consistent, and I feel that the `getItem` needs to NOT return items that are un-published.

**Comment by WellingGuzman** [comment]
I thought we have agree that if you have access to a item, it doesn't matter the status you should get the data.

I will change how this work to honor the status, to match your request.

**Comment by benhaynes** [comment]
Since we have a flag that says the items are not `published` I think we need to honor that everywhere. Let's update getItem ... admins don't need to use `status` or the `published` flag if they don't want it.

**Comment by WellingGuzman** [comment]
>  admins don't need to use status or the published flag if they don't want it.

What do you mean by this?

**Comment by benhaynes** [comment]
I actually think we want to do the opposite now... I think we should get rid of the status `published` flag altogether. We have "workflow" now... so admins can set what is published in permissions.

This means we would get rid of any status.published checks and return everything based on permissions.

@rijkvanzanten @WellingGuzman do you agree?

**Comment by benhaynes** [comment]
What about `soft_delete`?

**Comment by rijkvanzanten** [comment]
I agree @benhaynes

**Comment by WellingGuzman** [comment]
I agree, the `published` is to set the default value for the `status` filter.

**Comment by benhaynes** [comment]
OK, here are my final thoughts for the status mapping:

* `published` **remove** we will use workflow permissions instead
* `soft_delete` **keep** should hide items from all endpoints
    * We will add a new param to the API Item endpoints (now or later) to include soft-deleted items (off by default). But this param will _only_ be available to the admin group. This will allow our Admin App to show soft deleted items to admins and let them "restore" them.

**Comment by benhaynes** [comment]
OK, that works! I like it... uses what we already have.
