### ISSUE TITLE
Random String Util: Add more characters

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#465]
Expand the characters pool for `StringUtil::randomString()`, it can use symbols.

Also allow the user to pick, numbers, letters, alphanumeric, symbols, (_custom users characters?_) all or any combination.

Important note: this will improvement of the `auth_secret` random generated string.

**Comment by benhaynes** [comment]
This seems pretty easy... is it?

**Comment by rijkvanzanten** [comment]
Sounds easy but low priority

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
