### ISSUE TITLE
is it possible to install it in a sub-folder ?

### ISSUE THREAD

**Issue by MoaathAlattas** [directus/api#467]
Hi!

I am really excited for the new version release. good job guys !

while trying to setup the new version in a sub-folder on nginx, It doesn't seem that's its possible as it always picks the first directory as the project name.

Thanks.

**Comment by rijkvanzanten** [comment]
> it always picks the first directory as the project name.

Could you clarify what you mean by this? 🙂 

As far as I know, the api should run just fine in a folder. Now that I think of it, I actually have been running it from a folder on my localhost for the whole dev process :)

**Comment by WellingGuzman** [comment]
@MoaathAlattas what's your nginx configuration?

**Comment by WellingGuzman** [comment]
It's possible to install directus in a sub-directory. I will close and reference this ticket https://github.com/directus/docs-v7/issues/23 to update how to install directus 7 with NGINX
