### ISSUE TITLE
Field sort value must come from directus_fields

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#470]
Fields sort value are currently fetching from MySQL sort when there's not value on `directus_fields` confusing the resulting values from both `directus_fields` and MySQL columns.

The fields should be sorted by MySQL columns sort value, but the Field sort value must always come from `directus_fields` table.

**Comment by WellingGuzman** [comment]
This [commit](https://github.com/directus/api/commit/5b566335f6688b9ef0ba044bc13133a44e792435) only removes the MySQL sort value from Directus fields.

All the fields still not sorted by the MySQL columns order, but rather the `directus_fields` record order.

**Comment by WellingGuzman** [comment]
All fields with `sort=null` are moved to the bottom of the list, but within all with `null`, it must be sorted by the database column order instead.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
