### ISSUE TITLE
Allow fields to STOP being unique

### ISSUE THREAD

**Issue by benhaynes** [directus/api#472]
We can set a field to be unique, but we need a way to turn that off too.

**Comment by benhaynes** [comment]
How difficult is this?

**Comment by rijkvanzanten** [comment]
@wellingguzman

**Comment by WellingGuzman** [comment]
This has the same issue that #440 has.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
