### ISSUE TITLE
Error Ordering By RAND

### ISSUE THREAD

**Issue by benhaynes** [directus/api#475]
I believe this is because it's pulling in relational data too, but there is an error when sorting by random:

`"sort": "?"`

```
"Failed generating the SQL query."

"SELECT `work`.`id` AS `id`, `work`.`id` AS `id`, `work`.`status` AS `status`, `work`.`sort` AS `sort`, `work`.`title` AS `title`, `work`.`client` AS `client`, `work`.`image` AS `image` FROM `work` WHERE `work`.`status` = 'published' AND `work`.`status` IN ('published', 'draft') ORDER BY `work`.`?` IS NULL, RAND(), `work`.`id` ASC LIMIT 24 OFFSET 0"
```

**Comment by mikestratton** [comment]
Can you please share which file is causing this error?

**Comment by rijkvanzanten** [comment]
@WellingGuzman ?

**Comment by WellingGuzman** [comment]
@mikestratton the query is generated in this file [Database/TableGateway/RelationalTableGateway.php](https://github.com/directus/api/blob/master/src/core/Directus/Database/TableGateway/RelationalTableGateway.php).

The sorting data is added here: https://github.com/directus/api/blob/b87de01735c0fab0cd3b0256328d585ed1d1d2f4/src/core/Directus/Database/TableGateway/RelationalTableGateway.php#L1549-L1562
