### ISSUE TITLE
Authentication logs with a future datetime

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#483]
All activity logs are saved correctly in a UTC time, except authentication which the date time is saved in the future (4hrs).

The datetime value is changed by a hook, but the weird part is that it only seems to happens to authentication activity.

**Comment by WellingGuzman** [comment]
This issue happened to both authentication (requesting token by credentials) and commenting.

It needs to rethink the solution done by https://github.com/directus/api/commit/93e6b34192bf03114ca0285514c53b736c43f821

**Comment by benhaynes** [comment]
I'll re-open this since we need to keep this around and look for a proper fix.

**Comment by benhaynes** [comment]
@rijkvanzanten – this seems to be an App issue. The API is seemingly saving these values correctly (in UTC)... but the App is not converting them back to local time.

**Comment by rijkvanzanten** [comment]
I've updated the datetime interface's display component to use the right value in https://github.com/directus/api/pull/565

**Comment by beac0n** [comment]
> the date time is saved in the future (4hrs).

this also happens with the activity "Item created" in many to many junction tables.
