### ISSUE TITLE
DateUtils should use php default timezone

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#49]
DateUtils methods should use the default timezone instead of `UTC`.

----
### Additional discussion

Should Directus convert all times to UTC or not?

We have been asked several time to allow Directus to customized the system date time timezone.

Allowing this the user can set the timezone Directus must use for the core datetime value.

--- Edit:
This being configurable means if the user change the timezone, Directus won't take consideration of this change and will serve system time incorrectly. Is this a good idea?

**Comment by WellingGuzman** [comment]
hey @benhaynes @rijkvanzanten I would like your inputs on this.

**Comment by rijkvanzanten** [comment]
I think the API should store every date in UTC, and provide an option to "translate" the date into a different timezone if possible. If we start storing / changing the actual values in the DB, there is a wide range of weirdness that is going to happen.

**Comment by rijkvanzanten** [comment]
`?timezone=America%2FNew_York`

**Comment by rijkvanzanten** [comment]
As of right now, the interfaces aren't concerned with timezones. If you enter 4:15pm in your local timezone (f.e. -5h), than it'll just save as 4:15pm for everyone. Does this mean that we want to start keeping timezones in account in the default interfaces? 

Aka all interfaces save to UTC, and when viewed get 'translated' to the local timezone?

**Comment by WellingGuzman** [comment]
Taking the interfaces out of the picture, there are two things, system datetime fields saves in UTC, the rest saves whatever was sent or if there is not value, the date time will be the default in `app.timezone` value in `config/api.php`. (Default to `America/New_York`)

**Comment by rijkvanzanten** [comment]
> (Default to America/New_York)

Which leads me to another interesting question; should `America/New_York` be the default timezone? Shouldn't the default be `GMT` instead of `EST`?

**Comment by WellingGuzman** [comment]
The user should set the timezone on installation, if nothing is set, it will you the php default timezone.

No matter which timezone is default it will only work best for the person/team/project in that timezone. we got dibs, so I suggest to be `America/New_York` as default.
