### ISSUE TITLE
Inactive User Error Code

### ISSUE THREAD

**Issue by benhaynes** [directus/api#490]
I am getting the wrong error code when trying to log in with a inactive user

1. Log out
2. Disable user (`draft`)
3. Try to log in
4. Get 104 error (should be 103)

https://docs.directus.io/api/reference.html#error-codes

![screen shot 2018-10-15 at 9 23 02 pm](https://user-images.githubusercontent.com/522079/46987133-c9a2fb80-d0c0-11e8-8d83-6186f2499ec0.png)

Ref: https://github.com/directus/app/issues/976

**Comment by LiamBailey** [comment]
Would it be ok for me to try and take this on or is it closed now?

**Comment by rijkvanzanten** [comment]
Hey @LiamBailey! It’s all yours 🙂 

I think it’s this one 

https://github.com/directus/api/blob/5939dd7423aff65b865b62ece75aed4884fa4f93/src/core/Directus/Authentication/Exception/UserInactiveException.php#L9

But I’m not a 100% sure. 

We also need to double check that it’s actually an error in the code or an error in the docs. If another error already exists with the 103 code, we shouldn’t change this

**Comment by WellingGuzman** [comment]
That would be great @LiamBailey, the file Rijk pointed out is the correct file, and the error is in the code and not in the docs.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/api/commit/fe860e8eccfa6b50545f8dea248fc0aa480760f2
