### ISSUE TITLE
Unable to find users when sending mail to user id

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#491]
Trying to send email to users' id throws a error that the users couldn't be found.

```json
{
    "error": {
        "code": 12,
        "message": "Unable to find some users"
    }
}
```

**Comment by WellingGuzman** [comment]
I wrote the incorrect error ticket. I cannot reproduce the actual error trying to send email to a user using its ID.

Using IDs seems to be working as expected, didn't know what trigger the issue I reported.

**Comment by benhaynes** [comment]
If you say it's fixed then we're good... we can re-open if it happens again.
