### ISSUE TITLE
Update Migrations for schema

### ISSUE THREAD

**Issue by benhaynes** [directus/api#501]
We absolutely need a way to update the schema for hotfixes and releases. We have migrations for instance create, but as far as I know we don't have a way to do this for changes to existing instances.

We should also have a clean way to manage schema changes, ideally changing things in ONE place and then having all the other files updated through a build script of sorts.

Finally, would we want to use the new [GitHub actions](https://github.com/features/actions) to automate any of this? Not sure if its useful... or if we're just using [phinx](http://docs.phinx.org/en/latest/migrations.html).

**Comment by benhaynes** [comment]
Don't we have this? @WellingGuzman

**Comment by WellingGuzman** [comment]
@benhaynes yes, this was already implemented by https://github.com/directus/api/commit/5f1b7b33fe5c834bb404732fa7f6f7cf1d097967
