### ISSUE TITLE
how to trigger db migrations?

### ISSUE THREAD

**Issue by Marcnuth** [directus/api#503]
I searched the docs, and does not find any API or function to trigger database migration.

So how should I trigger it?

**Comment by benhaynes** [comment]
Hey @Marcnuth – we're in the process of wrapping this up now and an `/update` endpoint (and CLI command) will be included in the 7.0.3 release this Friday.

**Comment by WellingGuzman** [comment]
@Marcnuth to run the db migrations you should use the Directus CLI.

```
$ bin/directus install:database
```

It will run all migrations and seeder. By default it expects the `config/api.php` file exists.

If you haven't create the config file, please read how to [here]( https://github.com/directus/docs/blob/master/api/admin/configure-with-script.md#create-config-file)

Use `-N` to specify the name of the project you want to use to run the migrations

```
$ bin/directus install:database -N production
```

```
$ bin/directus install:install
```

It creates the default user and default settings. [Read more](https://github.com/directus/docs/blob/master/api/admin/configure-with-script.md#create-admin-user)


You can read more about the `bin/directus` script [here](https://github.com/directus/docs/blob/master/api/admin/configure-with-script.md)

If you want to update the current installation you can use the `/[project]/update` endpoint. [Read more here](https://github.com/directus/docs/blob/master/api/reference.md#update). This will be part of Directus 7.0.3

**Comment by WellingGuzman** [comment]
Yes all are in the docs, I added a link reference the docs to each thing I mentioned in the previous comment.

**Comment by benhaynes** [comment]
Awesome.

**Comment by lluishi93** [comment]
> Read more

Hi, the migration docks link is not working anymore (404)

**Comment by hemratna** [comment]
hi @lluishi93 I am not sure what you are trying to accomplish.
Might be https://docs.directus.io/advanced/api/configuration.html#configure-with-script one will help you.
