### ISSUE TITLE
Check all CLI modules

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#507]
Check all CLI modules and delete what's not in used anymore and what needs to be fixed.

**Comment by benhaynes** [comment]
Isn't that an important one @WellingGuzman ? How difficult is this to fix?

**Comment by WellingGuzman** [comment]
There are some commands not being used, some not well implemented and other broken. This is not a critical problem, but we need to clean all these unused/broken commands.

It shouldn't be difficult to fix this. More time should go into docs and list the one we need and remove the one we don't need anymore.

**Comment by WellingGuzman** [comment]
Summary:
- Cache module was removed. it was an under development module made for Directus 6.
- `db:install` removed. Uses `install:database` instead.
- `install:migrate` removed. Use `install:database` instead.
- `log:prune` `-s` option removed. Never in used.
