### ISSUE TITLE
Slow API response time

### ISSUE THREAD

**Issue by benhaynes** [directus/api#512]
From directus created by [mbaljeetsingh](https://github.com/mbaljeetsingh) : directus/directus#2020  

Hey @WellingGuzman 
**Directus** has all the features I need for my next project. But there's one more issue related to speed, I have created the same API with **directus**, **cockpit** and **strapi**. Also, added the same data. But, Directus is taking longer than the others to return almost the same amount of data. In that case half the data.

**Directus (via Postman)**
![directus](https://user-images.githubusercontent.com/872762/34658942-6e8c3fd4-f459-11e7-89f1-d625a04e2b1c.png)

**Strapi (via Postman)**
![strapi](https://user-images.githubusercontent.com/872762/34658962-a08f3158-f459-11e7-80b7-d239c3566e11.png)

**Cockpit (via Postman)**
![cockpit](https://user-images.githubusercontent.com/872762/34658981-cb0a8720-f459-11e7-84fe-d5d93737f59e.png)

**Comment by rijkvanzanten** [comment]
The api has been sped up drastically since then and we also have a caching solution, so that should cover this
