### ISSUE TITLE
Thumbnailer: Process SVGs

### ISSUE THREAD

**Issue by benhaynes** [directus/api#513]
From directus created by [Tscheffrey](https://github.com/Tscheffrey) : directus/directus#2062  

Directus seems to try to load a JPEG preview image from the SVG.
In the focused view, the image displays correctly but it is not centered.
![image](https://user-images.githubusercontent.com/35004675/36266708-6d916136-1272-11e8-98c2-7fd24d0a5077.png)
![image](https://user-images.githubusercontent.com/35004675/36266724-76854370-1272-11e8-9e94-bb403e294e3f.png)
![image](https://user-images.githubusercontent.com/35004675/36266777-9bd32976-1272-11e8-8802-1a8789850050.png)

**Comment by benhaynes** [comment]
Is this v6? Does this work in v7?

**Comment by benhaynes** [comment]
Same issue in v7...

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by ThaDaVos** [comment]
Same also in v8 when using the assets middleware and applying height, width, format and quality
