### ISSUE TITLE
Large Video File Preupload Fails

### ISSUE THREAD

**Issue by benhaynes** [directus/api#514]
From directus created by [mdbarr73](https://github.com/mdbarr73) : directus/directus#2128  

When dragging/selecting large video files(211MB test file) to upload to files, Directus throws a javascript error in Firefox: "allocation size overflow". Error occurs on /app/helpers/file.js:48:11

## Version Info
  - Directus version and branch (Or commit hash): 6.4.7
  - PHP version: 7.1
  - MySQL version: Aurora MySQL 5.6.10a
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: Docker Directus

## Expected Behavior
File preloads in the browser and shows the thumbnail on the upload page.

## Actual Behavior
JS error "allocation size overflow" occurs.

## Steps to Reproduce
 1. Go to Files>Upload
 2. Choose > Select large video file (tested w/ 211MB)
 3. Wait, error will appear in lower right corner.

## Schema Dump, Logs, or Screenshots
![image](https://user-images.githubusercontent.com/30296775/38953700-91772424-431d-11e8-8c95-263a146324c6.png)

**Comment by WellingGuzman** [comment]
This bug is not related to the api, but to the 6.x application that couldn't handle big file. If I remember correctly the way the preview worked wasn't any good on big files making the browser or script to crash/slow down.

**Comment by rijkvanzanten** [comment]
@WellingGuzman That's correct
