### ISSUE TITLE
skip_activity_log not working for /rows/bulk

### ISSUE THREAD

**Issue by benhaynes** [directus/api#515]
From directus created by [bensteers](https://github.com/bensteers) : directus/directus#2175  

`?skip_activity_log=1` is not disabling activity logging for bulk row uploads.

## Version Info
- Directus version and branch (Or commit hash): 6.4.9
- PHP version: 7.1.17
- MySQL version: Ver 14.14 Distrib 5.5.60, for debian-linux-gnu (x86_64) using readline 6.3
- OS name and version: Debian GNU/Linux 8 (jessie)

I suspect that this is the needed update:
```php
// directus/api/core/Directus/Database/TableGateway/RelationalTableGateway.php, line 2018
...
// change
    public function updateCollection($entries)
    {
        $entries = ArrayUtils::isNumericKeys($entries) ? $entries : [$entries];
        foreach ($entries as $entry) {
            $entry = $this->updateRecord($entry);
            $entry->save();
        }
    }
// to
    public function updateCollection($entries)
    {
        $entries = ArrayUtils::isNumericKeys($entries) ? $entries : [$entries];
        foreach ($entries as $entry) {
            $entry = $this->updateRecord($entry, $this->getActivityMode());
            $entry->save();
        }
    }
...
```
I just haven't had a minute to test before submitting a pull request.

**Comment by WellingGuzman** [comment]
The new parameter is called `activity_skip` and it does work on batch request.

`/rows/bulk` doesn't exists on 2.0
