### ISSUE TITLE
Sorting by relational field fails

### ISSUE THREAD

**Issue by benhaynes** [directus/api#521]
## Version Info
  - Directus version and branch (Or commit hash): **5d1e014b13c1b20502ef969b0fcb10b60566327e**
  - PHP version: **PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )**
  - MySQL version: **mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine wrapper**
  - Web server: (Ex. Apache, nginx or IIS?): **nginx version: nginx/1.14.0 (Ubuntu)**
  - OS name and version: **Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-33-generic x86_64)**

## Expected Behavior
When adding M2M relation you should be able to sort by number of related items.

## Actual Behavior
After sorting by M2M field you get an error saying that field is invalid and you no longer have access to collection's browse page because sorting is saved in **directus_collection_presets.view_query**.

## Steps to Reproduce
 1. Add M2M relation
 2. Make field visible on browse
 3. Try to sort by that field

## Schema Dump, Logs, or Screenshots
{"error":{"code":202,"message":"Invalid field \"favorites\""}}

------

Originally posted by @shota-mentesh as https://github.com/directus/directus/issues/2218

**Comment by WellingGuzman** [comment]
Sorting by one to many and many to many relational field are not allowed at the moment, the fix was to use a clear error message.

I opened a new ticket to create this feature and allow user to sort by relational fields.

Ref: https://github.com/directus/api/issues/539.
