### ISSUE TITLE
Updating existing field without record in directus_fields fails

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#524]
# Bug Report

When a field exists in the DB (there is a column) but there is NO directus_fields row (when the user created a column in the DB directly). Sending a PATCH request to /fields/:fieldname returns an internal server error.

## Steps to Reproduce

1. Add a new column to the DB directly
2. Try updating this column by sending a PATCH request

## Expected Behavior

The API returns 200

## Actual Behavior

API returns 500 internal server error with:

```json
{"error":{"code":null,"message":"Call to a member function toArray() on null","class":"Error","file":"\/Users\/rijkvanzanten\/Development\/api\/src\/core\/Directus\/Database\/TableGateway\/RelationalTableGateway.php","line":229}}
```

Weirdly enough, it looks like the row in directus_fields was created.

**Comment by WellingGuzman** [comment]
@rijkvanzanten can you share the payload you are using that gets you that error?

**Comment by rijkvanzanten** [comment]
```json
{"id":null,"sort":null,"field":"ticket_id","type":"string","datatype":"VARCHAR","interface":"text-input","default_value":null,"options":{"trim":true,"showCharacterCount":true,"formatValue":false,"width":"auto"},"readonly":false,"required":false,"unique":false,"note":"","hidden_detail":false,"hidden_browse":false,"length":200,"validation":null}
```
