### ISSUE TITLE
Question || Interface and global settings

### ISSUE THREAD

**Issue by lookingdown** [directus/api#528]
Thanks for sharing this amazing product..

I need to access global settings values from interfaces,  "wysiwyg" in my case as I added image insert and upload and serve locally or provider.

directus_settings/ files / serve_local  a bolean default  1 for example. 
and other keys for embed and image processing providers.

Is there a a way to access the directus settings this already in place from vue ? or what is the recommended method..

Cheers

## Version Info
  - Directus API version 7.0.2
  - PHP version: 7.1.2
  - MySQL version: 5.7
  - Web server:  nginx
  - OS name and version:  debian 8

**Comment by rijkvanzanten** [comment]
The settings are in the Vuex store. They can be accessed through `this.$store.state.settings` I believe. (Double check that exact name using the dev tools, I'm on mobile and haven't confirmed this)

**Comment by lookingdown** [comment]
They can be accessed through:  this.$store.state.settings is correct Thanks again..
