### ISSUE TITLE
Add default fields relations information

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#53]
All fields and collections needs `directus_fields`, `directus_collections` and `directus_relations` information in order to work properly.

**Comment by benhaynes** [comment]
* Collections require a value within `directus_collections` to be "managed".
* Fields should always show up (even without a `directus_fields` record), unless they are blacklisted in permissions. 
* Fields not in `directus_fields` should pull the basic info from the DB schema and returned in API responses. They should also have a `managed` flag set to `true` if they have a record.

**Comment by WellingGuzman** [comment]
This will be another "big" ticket that needs to be separated from this.

What actually I wanted to do from this ticket is set the default interface and data types for all the directus fields and relations.

**Comment by WellingGuzman** [comment]
Moved your notes to a new ticket (https://github.com/directus/api/issues/60)

**Comment by WellingGuzman** [comment]
I actually wanted to add the relations information, I changed the ticket title accordingly.
