### ISSUE TITLE
if you have a table that has a field with CURRENT_TIMESTAMP you get error

### ISSUE THREAD

**Issue by alioygur** [directus/api#531]
# Bug Report

## Steps to Reproduce

if you have a table that has a field type `datetime` with `CURRENT_TIMESTAMP` default value you get error.

1. create a table with this scheme (from mysql console or sequelpro)

```sql
CREATE TABLE `chains` (
  `id` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

2. go to dashboard
3. you will get an error.

```
{"error":{"code":null,"message":"Argument 1 passed to Directus\\Util\\DateTimeUtils::createFromDateTime() must be an instance of DateTime, boolean given, called in \/var\/www\/src\/core\/Directus\/Util\/DateTimeUtils.php on line 123","class":"TypeError","file":"\/var\/www\/src\/core\/Directus\/Util\/DateTimeUtils.php","line":96}}
```

## Expected Behavior

success

## Actual Behavior

```
{"error":{"code":null,"message":"Argument 1 passed to Directus\\Util\\DateTimeUtils::createFromDateTime() must be an instance of DateTime, boolean given, called in \/var\/www\/src\/core\/Directus\/Util\/DateTimeUtils.php on line 123","class":"TypeError","file":"\/var\/www\/src\/core\/Directus\/Util\/DateTimeUtils.php","line":96}}
```

## Technical Details

- Device: Desktop
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Web Server: 2.7
- PHP Version: 7.2
- Database: 5.7
- Install Method: directus suite, clone master

**Comment by akarshsingh9** [comment]
I want to try this

**Comment by benhaynes** [comment]
Go for it @akarshsingh9 !

**Comment by WellingGuzman** [comment]
Hey @akarshsingh9 are you still interested in working with this issue?

**Comment by akarshsingh9** [comment]
Yes I want to, I tried to reproduce the issue and found some solutions on stackoverflow. This is what I found 
[stackoverflow link 1](https://stackoverflow.com/questions/23153822/mysql-datetime-default-current-timestamp-error)
[stackoverflow link 2](https://stackoverflow.com/questions/23153822/mysql-datetime-default-current-timestamp-error)

what do you think?

**Comment by alioygur** [comment]
@akarshsingh9 i think you don't understand this problem.

```php
/**
     * @param null $time
     * @param null $timezone
     *
     * @return DateTimeUtils
     */
    public static function createFromDefaultFormat($time = null, $timezone = null)
    {
        return static::createDateFromFormat(static::DEFAULT_DATETIME_FORMAT, $time, $timezone);
    }
```

if you call the above function like this, you will get error

```php
DateTimeUtils::createFromDefaultFormat('CURRENT_TIMESTAMP', 'UTC');
```

because field default value is CURRENT_TIMESTAMP
