### ISSUE TITLE
Save all user times/datetimes as-is

### ISSUE THREAD

**Issue by benhaynes** [directus/api#536]
We should not convert user-submitted times/datetimes to UTC (only our own system times).

**Comment by WellingGuzman** [comment]
How do this will actually work, not more ISO format in input or output?

If I user send `2018-10-29T16:36:02+01:00` should this value be allowed? if so, should it convert to UTC and saves it, or saves it without convert it to UTC?

Options on Input:

1. Throw error
2. Converting: `2018-10-29T16:36:02+01:00` -> `2018-10-29T15:36:02`
3. Not Converting `2018-10-29T16:36:02+01:00` -> `2018-10-29T16:36:02`
4. Field option to pick one of the first options, with one of them being the default (Option 1?)

What about the output? Now that all field are user defined, does it makes sense to use ISO format? Unless there's an option in the field options to return as ISO format against a timezone (Off by default).

**Comment by benhaynes** [comment]
Good questions! I feel like all interfaces should submit time/datetime as: `2018-10-29T15:36:02` or `15:36:02` (no time zone info). But we need to figure out what happens when timezones _are_submitted.

@rijkvanzanten ?

**Comment by rijkvanzanten** [comment]
`2018-10-29T15:36:02` is saved as `2018-10-29 15:36:02`.

`2018-10-29T15:36:02+04:00` is saved as `2018-10-29 11:36:02`\*

\* Seeing the interface knows it saves as local timezone, it can "undo" the timezone when displaying the value in the app

**Comment by benhaynes** [comment]
True – but it's not just about the interface displaying it, it's also about other Apps that read that data from the database (API or Directly). It might be confusing for them to not know if it's been saved in UTC or not... so I think we should basically say that ALL non-system times/datetimes are saved as-is. We can always add an option for them to save in UTC (though this might also be confusing).

But yes, for `updated_on` and `created_on` (system pseudo-system interfaces) we could still use ISO/UTC and convert back in the interface code. 

We just need to decide on which interfaces (if any) will use ISO and convert to/from UTC.

**Comment by Marcnuth** [comment]
+1 for the features.

I just get confused on the timestamp for my record.

Using UTC timestamp to save & process is an acceptable way.

Besides, I am not sure if the user's timezone information will be used when some internal time conversion happens, if so, why there are only serval timezone are provided?

**Comment by WellingGuzman** [comment]
All user `datetime` are saved as is at the moment, and all `datetime` on system collections are saved in UTC.

I will be working on making system datetime fields to be saved in UTC.

**Comment by WellingGuzman** [comment]
I realized the user are not allowed to populate the `created_on` and `updated_on` fields, but the API doesn't throw any error when the user sends those values. It ignores whatever the user sends and auto-populate these values.

What should we do in that case? @benhaynes @rijkvanzanten

**Comment by benhaynes** [comment]
Ideally we can throw an error, but I don't think that's a priority for now. We can say in the Docs that these fields can not be manually updated. Once we have all the major bugs resolved we can go back and improve warnings like this.

So it seems like this one is done then. @WellingGuzman you can close this once you've confirmed the system datetimes are all being saved in UTC.

@rijkvanzanten the app/interface can individually add a `UTC` options to convert and save the datetimes in specific formats... right?

**Comment by WellingGuzman** [comment]
I fixed a small bug that tries to convert system datetime field, to UTC.

Closing this as already saving datetime as-is.
