### ISSUE TITLE
Sort by x-to-many relational fields

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#539]
# Feature Request

Allow user to user by one-to-many and one-to-many fields

## What problem does this feature solve?

Sorting by non-existing columns such as one-to-many

## How do you think this should be implemented?

Allowing to sort by related items count

## Would you be willing to work on this?

Yes

**Comment by benhaynes** [comment]
> Would you be willing to work on this? ... Yes

😆

**Comment by benhaynes** [comment]
Is this a duplicate?

https://github.com/directus/api/issues/209

**Comment by rijkvanzanten** [comment]
No @benhaynes, that's one step further than what this issue is talking about.

This is about being able to sort by x2m in the first place, #209 is talking about sorting by the actual value inside the relationship.

**Comment by rijkvanzanten** [comment]
It's similar, but not the same

**Comment by Anthonyzou** [comment]
This is blocking pretty much blocking for upgrading directus

**Comment by polgiron** [comment]
Hello, I'm not sure if it is similar, I would love to be able to sort the many to many elements in my collection entry.

Very simple use case: I have a collection type "album" which can be populated by several collection type "image". Then I would love to re-order these images inside the album entry.

Thank you very much, you guys are doing an amazing job!

Paul

**Comment by rijkvanzanten** [comment]
I think you're referring to sorting items within a many to many: https://github.com/directus/app/issues/1388 @polgiron 🙂

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
