### ISSUE TITLE
Difference between alias type and alias field

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#540]
# Feature Request

Let's make a difference between an alias type and an alias field. Maybe merge these into the same thing.

An field with `alias` type is treated as an `alias` field, but in theory any field without an actual column in the database should be an alias.

## What problem does this feature solve?

List the field as an alias type instead of ignore the field altogether from the collection.

## How do you think this should be implemented?

If the field doesn't exists in the database it should be treated as an alias field.

## Would you be willing to work on this?

Yes

**Comment by WellingGuzman** [comment]
I will close this in favor of #430.

**Comment by itsmerhp** [comment]
@benhaynes 
I have tried to reproduce this issue, but when converting a non-alias field as alias(O2M, Translate field), it is been removing from database table.
What is difference between alias column and alias type, can you please give an example in context of Directus to understand this difference?
Can you please also provide steps to reproduce this issue?
