### ISSUE TITLE
Amazon s3 storage adapter doesn't work

### ISSUE THREAD

**Issue by benlo123** [directus/api#550]
# Bug Report

## Steps to Reproduce

1. edit api.php to use s3 as file storage
2. try to upload a file as item in collection.

## Expected Behavior
Upload success

## Actual Behavior
Error occur

## Other Context & Screenshots
[error.2018-10-31.log](https://github.com/directus/api/files/2535200/error.2018-10-31.log)

## Technical Details

Apache Version | 2.4.35
PHP Version | 5.6.38
MySQL Version | 5.7.24
Architecture | x86_64
Operating System | linux

**Comment by WellingGuzman** [comment]
Hey @benlo123, Thanks for reporting this.

You need to install the `aws/aws-sdk-php` package, it should've been in the suggested packages.

Can you run `composer require aws/aws-sdk-php` and try to upload again?

This package needs to be in the suggested list in `composer.json`

**Comment by WellingGuzman** [comment]
I added a note in the documentation here: https://github.com/directus/docs/commit/3fedcbc4031ab1f32cae3630aa157396265f460f.

And the package was added as `suggest` in `composer.json` in here: https://github.com/directus/api/pull/557.

**Comment by Slowwie** [comment]
Should I now require the aws/aws-sdk-php ? U use flysystem - I dont think this is required now...
