### ISSUE TITLE
2FA - Two Factor Authentication Support

### ISSUE THREAD

**Issue by vzool** [directus/api#559]
Hi,

I'm looking forward to secure this wonderful middleware system with **2FA - Two Factor Authentication** at both levels API and Web if enabled.

Thanks

**Comment by rijkvanzanten** [comment]
In terms of input, this would mean that logging in requires a 6 char code (One Time Password OTP) generated by an authenticator application.

```json
{
  "email": "rijkvanzanten@me.com",
  "password": "password",
  "otp": "123456"
}
```

**Comment by benhaynes** [comment]
Would we generate/manage this ourselves (over email), or use some library/service (potentially adds SMS too)?

**Comment by vzool** [comment]
> In terms of input, this would mean that logging in requires a 6 char code (One Time Password OTP) generated by an authenticator application.
> 
> ```json
> {
>   "email": "rijkvanzanten@me.com",
>   "password": "password",
>   "otp": "123456"
> }
> ```
Yes, 6 chars is enough for now and this could work. 🙂
But, I prefer to split this into two requests not one. Like this:

- **First request**:

```json
{
  "email": "rijkvanzanten@me.com",
  "password": "password"
}
```
- **First response**:
```
{
  "challenge": "57eabcc4-dce0-427b-bfb0-f99b56c849df",
  "type": "otp"
}
```
- **Second request**:

```json
{
   "challenge": "57eabcc4-dce0-427b-bfb0-f99b56c849df",
   "otp": "123456"
}
```

This design will help us in the future to add other options like SMS and U2F. 🤓

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by OscBacon** [comment]
Hi,
I am currently working on implementing 2FA for login. Any pointers / specific parts of the documentation I should look at?

**Comment by benhaynes** [comment]
Hey @OscBacon — that would be awesome!! 😄 

@bjgajjar @hemratna — any pointers on where this should exist within the code?

**Comment by OscBacon** [comment]
@benhaynes Thanks!
I am wondering too, could this be possible as an extension, similar to how SSO seems to be explained in the docs?

**Comment by benhaynes** [comment]
Not sure, but @bjgajjar should be able to help you here or on our Slack. :)
