### ISSUE TITLE
Background jobs (Push Notifications)

### ISSUE THREAD

**Issue by vzool** [directus/api#560]
Hi,

I'm looking for a way to do some long jobs in the background like (Custom mail sending,  SMS calls, Push Notifications, Reports generation and any Remote Service Calls). It there a way to make this and I'm not aware of?

Thanks

**Comment by rijkvanzanten** [comment]
Ideally, we'd have a system where you can have custom snippets of PHP (similar to hooks) that can be run at an interval. If these snippets have access to the Directus internal api's (like hooks), you should be able to do virtually whatever you want.

I think we should / could have a `directus_tasks` collection that keeps track of at what interval to run what function? And maybe use `directus_activity` for logs of said task?

**Comment by benhaynes** [comment]
I like that. Would the code to be executed be saved in the database (eg `directus_tasks.code`)? Would it be a reference to a file (maybe uploaded in Directus Files) so that it is language agnostic?

If the tasks define when it runs (start, frequency, end/iterations), and we have a simple CRON that fires every minute, then we can just check the tasks and run them as needed. Seems pretty straightforward.

**Comment by rijkvanzanten** [comment]
That could be even easier @benhaynes.

If the file itself starts with something to tell the API how often to run, we don't need to the database in between. We could have an `extensions/tasks` folder with `.php` files that get fired

**Comment by benhaynes** [comment]
Interesting. So naming could use [cron schedule expressions](https://crontab.guru/#5_4_*_*_sun):

### “At 04:05 on Sunday.”
```
/extensions/tasks/[5_4_*_*_sun]task-name.php
```

We could also "disable" tasks just like other extensions, by pre-pending `_` to the file-name.

Now this is starting to look like a nice clean solution that just needs a CRON parser to run/check every minute!

**Comment by benhaynes** [comment]
https://github.com/directus/api/pull/567

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
