### ISSUE TITLE
Re-implement joins parameter

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#562]
We have a `joins` parameter which implements a SQL Query Join to another collection (table). What this does is extend a record columns with another table if the conditions matches.

If I was implemented in this PR: https://github.com/directus/directus/pull/1468

Joins works differently than the collection relationship, while relations are attach to a field and in the response nested to that field, joins append the fields from another collections.

Using relationship the result will look like the example below:

```
{
    "data": {
        "name": "Jonh",
        "age": 70,
        "country": {
            "country_name": "United States"
        }
    }
}
```

And using joins it will look like the example below:

```
{
    "data": {
        "name": "Jonh",
        "age": 70,
        "country_name": "United States"
    }
}
```

We are trying to see what are the use cases and if this is an important feature to support it and re-implement it in a more simpler way.

**Comment by benhaynes** [comment]
@WellingGuzman Is this still something we want to do?

**Comment by WellingGuzman** [comment]
I haven't found a good reason to re-implement this yet. I still believe the user can create a custom endpoint to implement custom queries or create a relational field.

Also adding more columns to the main query with potential ambiguos name, such as `id`, will result in random alias fields that the user won't expect beforehand.

**Comment by benhaynes** [comment]
Gotcha. I think we can close this and focus on relationships for now. We can re-open this if someone thinks that `joins` are worth the strategy/dev time.
