### ISSUE TITLE
Adding item in One2Many Field is not work

### ISSUE THREAD

**Issue by Marcnuth** [directus/api#569]
Steps:
1. Create a collecction with a field 'xxx' and set its field type = One2Many
2. Add a record, and select existing items for the fied 'xxx'
3. API returns a failure, and the response is 500, the detail is:

```json

{
"error":
{
"code":9,
"message":"Failed generating the SQL query. Statement could not be executed (42S22 - 1054 - Unknown column 'fans' in 'field list')",
"query":"INSERT INTO `dr_tweets` (`field_a`, `xxx`, `created_on`, `created_by`) VALUES ('<p>asfasfasf<\/p>', NULL, '2018-11-04 16:07:51', '1')",
"class":"Directus\\Database\\Exception\\InvalidQueryException",
"file":"\/var\/www\/html\/src\/core\/Directus\/Database\/TableGateway\/BaseTableGateway.php",
"line":802
}
}

```

**Comment by WellingGuzman** [comment]
I can't reproduce this issue @Marcnuth, can you describe how you create the field, or better yet send us a database dump to see if we can reproduce this issue.

This may be due to a misconfiguration in the field type or missing relationship.

**Comment by AntiCZ** [comment]
I also have had a problem with O2M. Did you do exactly step by step by https://docs.directus.io/app/admin/relationships.html#one-to-many. My problem was related Collections in 3rd step in modal.  Table "directors" with column "id" has to be connected to table "movies" with column "director" (and nothing else - director_id is wrong).

Also what is important: Inspect element on the thumbnails and remove attribute width on the <img/>. After that is possible with text and images make it happen. And also make before M2O.

**Comment by WellingGuzman** [comment]
I am still unable to reproduce this issue. Due to inactivity I will close this ticket.

@AntiCZ If you see this issue still happening on the latest version please let us know.
