### ISSUE TITLE
directus_collection column icon too small.

### ISSUE THREAD

**Issue by Lapsus** [directus/api#574]
# Bug Report

## Steps to Reproduce

1. go to admin section -> collections & fields -> select a collection
2. choose "supervised_user_circle " as icon. 
3. click on save
"Failed generating the SQL query."
query: "UPDATE `directus_collections` SET `icon` = 'supervised_user_circle', `collection` = 'COLLECTION_NAME' WHERE `collection` = 'COLLECTION_NAME'"

## Other Context & Screenshots
Column is varchar(20) but apparently there are some icon names exceeding this columns max length.

**Comment by WellingGuzman** [comment]
I've increased the length of `directus_collections.icon` from `20` to `30`.

Ref: https://github.com/directus/api/commit/5c1a4cc421a06c3e5645606fa799457a55c27ed9
