### ISSUE TITLE
Endpoint /auth/authenticate returns 500 error 

### ISSUE THREAD

**Issue by shealavington** [directus/api#581]
# Bug Report

## Steps to Reproduce

There are two ways to get a 500 error that should be returning `4XX Errors`

### 1. How to get a bad 500 error
1. Create or make a user as `Draft` through the GUI
2. Create a post request with a body `{"email":"x@x.x","password":"xxx"}` *(X = User info)*
3. Authenticate at endpoint `/auth/authenticate` with the post information above
4. Receive a 500 error

### 2. How to get a bad 500 error 
1. Create or make a user as `Active` through the GUI
2. Create a post request with a body `{"email":"x@x.x","password":"yyy"}` *(X = User info, Y=Invalid info)*
3. Authenticate at endpoint `/auth/authenticate` with the post information above
4. Receive a 500 error

## Expected Behavior
Receive a `4XX Error` with a useful message about the reason for failing

## Actual Behavior
Receive a `500 Error`

## Technical Details

- Device: Desktop
- OS: Windows 10
- Web Server: Apache
- PHP Version: 7.1
- Database: MySQL 5.7
- Install Method: Cloned Direcus 7.5

**Comment by WellingGuzman** [comment]
Hey @shealavington, did you test the first way to reproduce this error in the recent version? That bug should've been fixed by https://github.com/directus/api/commit/4aa9b926d713796677f78314a09bd92ca27770ed

> ### 2. How to get a bad 500 error
> 1. Create or make a user as `Active` through the GUI
> 2. Create a post request with a body `{"email":"x@x.x","password":"yyy"}` _(X = User info, Y=Invalid info)_
> 3. Authenticate at endpoint `/auth/authenticate` with the post information above
> 4. Receive a 500 error

I will give this a try. which data did you use for Invalid Info? I will try all I can think of, but I wanted to know which one did you use.

**Comment by WellingGuzman** [comment]
The problem with invalid data on the credentials has been fixed by https://github.com/directus/api/commit/f7891dcf95b0862b651f953b33d3fda2ab785c83
