### ISSUE TITLE
Custom storage adapter PR

### ISSUE THREAD

**Issue by AntiCZ** [directus/api#582]
# Custom storage adapter

## Would you be willing to work on this? Yes, of course.

Hello, I am working on the PR for a custom adapter. This is not a big deal. But my question is. Is there a chance to change fileName? Problem is that my CDN saves files with MD5 like cdn.example.com/img/90ceffdf71bfddb7865908dc1b2a156b.jpg but Directus all the time works with fileName from the user and can not be changed after uploading to the CND. 

Only chance how to do this is in Directus\Filesystem\Files::saveData() make a switcher a to another custom method and create a filter hook. But this is pretty ugly.

My suggestion is. Directus\Filesystem\Files::write() should returns data from write() from the adapter. The same for Directus\Filesystem\Filesystem::write(). There is some magic in Directus\Filesystem\Filesystem::write(). I call write() on the adapter and it returns an array but response is true.

If I change from
```
try {
    if (!$this->getAdapter()->write($location, $data)) {
        $throwException();
    }
} catch (\Exception $e) {
    $throwException();
}
```
to

```
try {
    $result = $this->getAdapter()->write($location, $data);
    if (!$result) {
        $throwException();
    }
    return $result;
} catch (\Exception $e) {
    $throwException();
}
```
$result is only true or false. Even if write() returns an array.

And then is a little problem with thumbnails in Directus\heplres\file.php but this is one small condition.

**Comment by AntiCZ** [comment]
I have finally discovered what is actually happening.

Problem 1. 
   - League\Flysystem\Filesystem::write() retypes response from adapter to boolean....

Problem 2.
-  Directus\Filesystem\Filesystem should extend League\Flysystem\Filesystem. Or should have a different namespace like Service\Filesystem or Facade\Filesystem.  This is a little bit confusing.
- Property adapter in Directus\Filesystem\Filesystem does not contain adapter but filesystem. So method Directus\Filesystem\Filesystem::getAdapter() is confusing. 

I will send PR for some days.

**Comment by benhaynes** [comment]
Thank you @AntiCZ !! Once @WellingGuzman is back he'll be able to answer any API questions you have.

We really appreciate you taking the time to submit a PR! Thank you! 😄

**Comment by WellingGuzman** [comment]
Thanks @AntiCZ, The filesystem needs a rewrite. The problem is that Flysystem was meant to be an adapter to the Directus filesystem instead of extending the flysystem library.

**Comment by AntiCZ** [comment]
Thanks, @WellingGuzman for answer PR was sent.
