### ISSUE TITLE
Making files public in roles/permissions generates warning in API request

### ISSUE THREAD

**Issue by verbman** [directus/api#584]
Undefined index notice.

- Azure webapp
- PHP 7.2
- MySQL 5.7
- env - development

Steps to reproduce:
- Create a public collection
- Add a field for file.
- Upload an image
- Make the directus *files* system collection *read* for role *public* (in settings-user roles/permissions)
- Call the api end point (query: `/_/items/panels?fields=id,title,image.id,image.filename,image.type,image.width,image.height,image.data.full_url,website&meta=total_count,result_count&offset=0`)
Get the results as expected but with the following two lines appended:

`Notice: Undefined index: uploaded_by in D:\home\site\directus\src\core\Directus\Database\TableGateway\RelationalTableGateway.php on line 1767`

`Notice: Undefined index: folder in D:\home\site\directus\src\core\Directus\Database\TableGateway\RelationalTableGateway.php on line 1767`

**Comment by WellingGuzman** [comment]
@verbman I wasn't able to reproduce this issue, can you try this in the current version?

If this issue still exists in the current version, could you please provide a schema that we can use to reproduce this issue?

**Comment by WellingGuzman** [comment]
Due to inactivity I will be closing this ticket. If someone still experience this issue in the current version please let us know, and we will re-open this ticket.
