### ISSUE TITLE
Use last created record in relations, instead of first

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#586]
If there's multiple relations for the same field, the API should use the one with the highest ID (latest) to ensure the relationship is the correct one.

Ref https://github.com/directus/app/issues/1085

**Comment by rijkvanzanten** [comment]
@WellingGuzman This appears to be selecting the first relation it encounters, instead of the last.

When having rows like follows in directus_relations

| id | collection_many | field_many  | collection_one |
|----|-----------------|-------------|----------------|
| 18 | books           | author      | dvds           |
| 19 | books           | author      | authors        |

I can confirm with these rows, the API is trying to match items from `dvds` instead of `authors`.

**Comment by WellingGuzman** [comment]
This has been fixed by https://github.com/directus/api/commit/4cad47f433a68cec7b6868c6bd25e8998e8793e2.

This issue is somehow related with https://github.com/directus/api/issues/598, where the relations cannot be duplicated. When that happens the fixed above should be reverted (if necessary)
