### ISSUE TITLE
Define 6.x directus settings in 7.x

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#59]
Directus 6.x settings are `collection+name+value` combo, while on 7.x we create a new one (_and rename the rest_) to `scope+group+key+value`

How are the previous default settings going to fit in this new format?

Here is the current settings:

```json
[
  {
    "scope": "global",
    "key": "cms_user_auto_sign_out",
    "value": "60"
  },
  {
    "scope": "global",
    "key": "project_name",
    "value": "Directus Demo"
  },
  {
    "scope": "global",
    "key": "project_url",
    "value": "http:\/\/localhosst"
  },
  {
    "scope": "global",
    "key": "rows_per_page",
    "value": "200"
  },
  {
    "scope": "files",
    "key": "thumbnail_quality",
    "value": "100"
  },
  {
    "scope": "files",
    "key": "thumbnail_size",
    "value": "200"
  },
  {
    "scope": "global",
    "key": "cms_thumbnail_url",
    "value": ""
  },
  {
    "scope": "files",
    "key": "file_naming",
    "value": "file_id"
  },
  {
    "scope": "files",
    "key": "thumbnail_crop_enabled",
    "value": "1"
  },
  {
    "scope": "files",
    "key": "youtube_api_key",
    "value": ""
  }
]
```

One I recommend is moving project is project information:

```json
[
  {
    "scope": "global",
    "group": "project",
    "key": "name",
    "value": "Directus Demo"
  },
  {
    "scope": "global",
    "group": "global",
    "key": "url",
    "value": "http:\/\/localhosst"
  }
]
```

**Comment by WellingGuzman** [comment]
For the moment I have updated the settings for project as I recommended. You can see the changes here: https://github.com/directus/api/commit/36775721ade13973cb9a15405c84d87046e0ec6f

I did it for the sake of make this work a little bit easier, but it's not a final decision.

**Comment by WellingGuzman** [comment]
Put into consideration that Rijk recommended https://github.com/directus/api/issues/6#issuecomment-376516018 for `status_mapping`

> Group = global
> Scope = status
> Key = status_mapping

I noticed that here "global" is a group, but on the rest of the settings "global is a `scope`, I mentioned this to take in consideration the path that we are going to take.

**Comment by rijkvanzanten** [comment]
> Group = global
Scope = status
Key = status_mapping

Re-reading this now, this would result in `settings.global.status.status_mapping` when referring to it in code. Do we want to change this to `settings.global.status.mapping`? Just a small thingything

> I noticed that here "global" is a group, but on the rest of the settings "global is a scope, I mentioned this to take in consideration the path that we are going to take.

You are completely right @WellingGuzman. That should be the other way around. `scope` is the parent level, `group` is a sublevel.

The above should be:


```
scope = global
group = status
key   = mapping <<< see above question
```

**Comment by rijkvanzanten** [comment]
To answer your original question: 

I think the settings are:


    | 6.4                    | 7.0             | notes / reasoning                                  |
    |------------------------|-----------------|----------------------------------------------------|
    | auto_sign_out          | auto_sign_out   | --                                                 |
    | project_name           | --              | Moved to config file                               |
    | project_url            | --              | Moved to config file                               |
    | rows_per_page          | default_limit   | The name rows is way too specific for tabular view | 
    | thumbnail_quality      | ??              | Do we still need this with the thumbnailer?*       |
    | thumbnail_size         | ??              | *                                                  |
    | cms_thumbnail_url      | ??              | What is this?                                      |
    | file_naming            | file_naming     | --                                                 |
    | thumbnail_crop_enabled | ??              | *                                                  |
    | youtube_api_key        | youtube_api_key | Should probably be extended with Vimeo / etc       |

**Comment by WellingGuzman** [comment]
We need to add the thumbnailers to the `directus_settings`

```php
'thumbnailer' => [
        '404imageLocation' => __DIR__ . '/../public/thumbnail/img-not-found.png',
        'supportedThumbnailDimensions' => [
            // width x height
            // '100x100',
            // '300x200',
            // '100x200',
        ],
        'supportedQualityTags' => [
            'poor' => 25,
            'good' => 50,
            'better' => 75,
            'best' => 100,
        ],
        'supportedActions' => [
            'contain' => [
                'options' => [
                    'resizeCanvas' => false, // http://image.intervention.io/api/resizeCanvas
                    'position' => 'center',
                    'resizeRelative' => false,
                    'canvasBackground' => 'ccc', // http://image.intervention.io/getting_started/formats
                ]
            ],
            'crop' => [
                'options' => [
                    'position' => 'center', // http://image.intervention.io/api/fit
                ]
            ],
        ]
    ],
```

**Comment by rijkvanzanten** [comment]
> When was project_name and project_url moved to config files?

It's in the app's config file so the application can know where to try to login.

---

> We don't need the thumbnails option anymore if we want all them to be required. width, height, quality and action, right?

I'd say `width`, `height`, `quality`, and `fit` (instead of `action`).

It would be perfect if those endpoints are all valid, but that's probably very hard to get right?

---

> cms_thumbnail_url is the project thumbnail.

I renamed this to just `logo` for the app use. I can just save anything in there without the API being bothered right? I just need to know what the settings are required by the API 🙂

**Comment by WellingGuzman** [comment]
> It's in the app's config file so the application can know where to try to login.

Understood.

> I'd say width, height, quality, and fit (instead of action).
> 
> It would be perfect if those endpoints are all valid, but that's probably very hard to get right?

Yeah it can be anything in code is called `action`. actually is easier if we stick to it.

first two, `width`, and `height`, last one, `filename` then if there two left. is `quality` on left and `fit` on right. if there's one is `quality` otherwise default values. we can shuffle the priority order for fit and quality. but I believe `fit` has more priority over quality.

> I renamed this to just logo for the app use. I can just save anything in there without the API being bothered right? I just need to know what the settings are required by the API 🙂

Yeah, it was a reserved name on 6.x

**Comment by WellingGuzman** [comment]
The thumbnailer config are moved to `directus_settings` with the `scope=thumbnail`

```php
'thumbnailer' => [
        '404imageLocation' => __DIR__ . '/../public/thumbnail/img-not-found.png',
        'supportedThumbnailDimensions' => [
            // width x height
            // '100x100',
            // '300x200',
            // '100x200',
        ],
        'supportedQualityTags' => [
            'poor' => 25,
            'good' => 50,
            'better' => 75,
            'best' => 100,
        ],
        'supportedActions' => [
            'contain' => [
                'options' => [
                    'resizeCanvas' => false, // http://image.intervention.io/api/resizeCanvas
                    'position' => 'center',
                    'resizeRelative' => false,
                    'canvasBackground' => 'ccc', // http://image.intervention.io/getting_started/formats
                ]
            ],
            'crop' => [
                'options' => [
                    'position' => 'center', // http://image.intervention.io/api/fit
                ]
            ],
        ]
    ],
```

- `404imageLocation` was changed to `not_found_location`
- `supportedThumbnailDimensions` was changed to `dimenstions` a csv dimension list. Ex `100x100,200x200`
- `supportedQualityTags` to `quality_tags` a json `key-value`, where `key=tag` and `value=quality` (0-100)
- `supportedActions` was changed to `actions`. But currently only have hard coded support for `contain` and `crop`, eventually we will allow any options to be set on `actions` to be a supported action. These actions are based on the Intervention image library.

**Comment by WellingGuzman** [comment]
All settings has been updated.

Ref: https://github.com/directus/api/wiki/API-Settings-(DB)
