### ISSUE TITLE
using logical or filters with date returns wrong values

### ISSUE THREAD

**Issue by beac0n** [directus/api#592]
# Bug Report

## Steps to Reproduce

1. create a collection with a date field end_date
2. insert some items, where some have end_date = null, and others have end_date = a valid date
3. use the api to filter the items and use the following filters:
filter[end_date][empty]&
filter[end_date][logical]=or&
filter[end_date][gte]=2015-01-01

## Expected Behavior
the result should contain the correct dates:
the ones gte 2015-01-01 and the ones which do not have a date

## Actual Behavior
the result does not contain the correct dates:
the items with date == null are not returned from the api

## Technical Details

- Device: Desktop
- OS: arch linux - directus in docker
- Web Server: the one in directus 7 api docker image
- PHP Version: the one in directus 7 api docker image
- Database: MySQL
- Install Method: docker-compose with mysql database

**Comment by beac0n** [comment]
after checking the SQL logs, I think I found the issue.

The problem is with using the same column name more than once:
`'2018-11-19 19:00:17', 'directus[directus] @  [172.30.0.4]', '1364', '0', 'Query', 'SELECT `bookings`.`id` AS `id`, `bookings`.`id` AS `id`, `bookings`.`name` AS `name`, `bookings`.`is_priority` AS `is_priority`, `bookings`.`start_date` AS `start_date`, `bookings`.`end_date` AS `end_date`, `bookings`.`start_time` AS `start_time`, `bookings`.`end_time` AS `end_time`, `bookings`.`duration` AS `duration`, `bookings`.`booking_template` AS `booking_template`, `bookings`.`test1234` AS `test1234` FROM `bookings` WHERE `bookings`.`name` LIKE \'%test b%\' ORDER BY `bookings`.`id` IS NULL, `bookings`.`id` ASC, `bookings`.`id` ASC LIMIT 200 OFFSET 0'
`

as shown in the SQL statement, the only column filtered for, is the "name" column.

The query I sent looks like this:

`http://localhost:8888/_/items/bookings?filter%5Bname%5D%5Blike%5D=lego&filter%5Bname%5D%5Blike%5D=test%20b`

**Comment by benhaynes** [comment]
@WellingGuzman — any reason why this is ALIASing `id` twice?

**Comment by beac0n** [comment]
A workaround might be, to use the "between" filter (https://directus.github.io/api/#filtering).
I have not tested it though.

**Comment by WellingGuzman** [comment]
The `id` and `status` field are only added to the select fields list when they are missing, to avoid creating a query selecting those two fields twice. The result was the same as there couldn't be two field at the same result.

This was fixed by https://github.com/directus/api/commit/2993ddb8da849058357488772aa30525d4303914

---

I will close this ticket and everything about allowing multiple filter on the same field should be followed in this thread/ticket: https://github.com/directus/api/issues/134
