### ISSUE TITLE
'relations' uniqueness

### ISSUE THREAD

**Issue by lrkwz** [directus/api#598]
# Feature Request

Add unique key to `directus_relations(collection_many, field_many, collection_one, field_one, junction_field)`.
 
## What problem does this feature solve?

* Two users creating the same relation
* Two identical rows inserted by repeated changes on data structure (create a relation then modify  relation)

## How do you think this should be implemented?

CREATE INDEX...

## Would you be willing to work on this?

This is fairly easy, it's isn't that easy handle all the error condition that will arise from this change.

**Comment by benhaynes** [comment]
Thanks @lrkwz — we'll take a look at potentially adding this once @WellingGuzman is back.

**Comment by lrkwz** [comment]
Probably #537 would benefit of this

**Comment by rijkvanzanten** [comment]
I think https://github.com/directus/api/issues/586 might potentially solve this as well

**Comment by lrkwz** [comment]
Still I suggest to enforce strong bonds directly in database for relations (unique indexes, foreign keys, ...) this will eventually let code errors immediately visible.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
