### ISSUE TITLE
Don’t allow deleting the last admin user

### ISSUE THREAD

**Issue by Neville2312** [directus/api#599]
Admin user can suspend itself and this causes a server error.

An admin shouldn't be able to suspend itself and there should always be one admin that has access to Directus.

**Comment by benhaynes** [comment]
@WellingGuzman let's get this enforced by the API and then we'll transfer this to the App so that @rijkvanzanten can show the right error message in the App.

**Comment by rijkvanzanten** [comment]
Should we say that you can’t change your own role in general? 

That’s an interesting one for permissions as well btw @benhaynes. Next to `mine`, have support for `not mine`

**Comment by benhaynes** [comment]
Hmm, interesting idea. I still think we want to use dynamic rules for filtering the permission scope, but yes, then we could accomplish this with a similar "not mine" filter. 

You should never be able to _increase_ your permissions, and decreasing has issues with losing access to your current page... so I agree with: **"you can't change your own role"**

**Comment by ceruulean** [comment]
Is it possible to detect whether the admin is the original admin? Then gray-out+disable the "suspend" option so clicking it is impossible.

**Comment by rijkvanzanten** [comment]
> Is it possible to detect whether the admin is the original admin?

We should probably check if you're the last remaining admin. You should be able to suspend the original admin IMO. (Lets say the original admin is the webdev agency that created the project, but you're moving to another dev agency)

**Comment by ceruulean** [comment]
Actually, it should apply to all status. On directus.app if I set myself to "draft" or "inactive" there's errors too.

>1 Active admin : proceed with status change
otherwise : Too dangerous

**Comment by rijkvanzanten** [comment]
Conclusion the API should check that:

**You should always have 1 active admin user**

@WellingGuzman

**Comment by benhaynes** [comment]
I'm late to the 🎉  ... but yes, that is correct. API must check that there is always at least one active admin.

**Comment by benhaynes** [comment]
@bjgajjar — I just got this over an email... is this still working?

```i was looking for a cms solution and directus came up in my google search results.
I just tried the available online demo. Well, first things first...
Users -> Admin User -> delete profile -> almost everything stucked (which is normal if there is not any such error handler).

I hope that helps. You 've done an awesome work there.```

**Comment by benhaynes** [comment]
@rijkvanzanten could it be that the API doesn't handle this, but the app crashes?

**Comment by rijkvanzanten** [comment]
Seems like the API doesn't prevent you from deleting all users as stated above. If there aren't any users in the platform, the app will stop functioning too, as you have nothing to login with (which makes sense).
