### ISSUE TITLE
Default status column to first item in status mapping settings

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#6]
The status for each newly created item should default to either the status mapping as defined for the table (stored in `directus_collection.status_mapping`) or — if that's not setup — the default global status mapping in `directus_settings`

**Comment by benhaynes** [comment]
I don't think we have a "default" in the status mapping. Users can SET the status to any options they are allowed to... or, if they are NOT allowed to then it should use the column default value.

**Comment by rijkvanzanten** [comment]
In that case, we should require the default value of the status column when it's set up. As of right now, if the column defaults to `null`, the item will disappear immediately since it's basically invisible to the api @benhaynes

**Comment by benhaynes** [comment]
Yes, absolutely. We should have the ability to require/limit DEFAULT and LENGTH when creating/setting-up fields based on the interface.

**Comment by WellingGuzman** [comment]
a related question, Where in settings is going to be stored the global status mapping? (`key`, `scope` and `group` combo)?

**Comment by rijkvanzanten** [comment]
Group = global
Scope = status
Key = status_mapping

Thoughts @benhayhes @WellingGuzman?

**Comment by benhaynes** [comment]
Yeah, I like that.

**Comment by rijkvanzanten** [comment]
So at this point all that lasts is making sure the application starts giving errors when you try to create a status interface without a default value correct? If so, we can close this issue here and move it over to directus/app :)

**Comment by WellingGuzman** [comment]
Exactly, a value for status interface is required.
