### ISSUE TITLE
Fetching translated collection

### ISSUE THREAD

**Issue by lrkwz** [directus/api#601]
# Bug Report

I've configured a translated Article structure and I wish to fetch a translated article; the `lang` param added to the curl call does not seem to work as expected

## Steps to Reproduce

0. Configure a fixed access token for user admin
[garanteasy-directus.sql.gz](https://github.com/directus/api/files/2600810/garanteasy-directus.sql.gz)

1. Configure a multilingual collection and populate it
2. Call from terminal: 

* `curl -H 'Authorization: Bearer changeme' http://localhost:8083/_/items/article/1`
* `curl -H 'Authorization: Bearer changeme' http://localhost:8083/_/items/article/1?lang=it`
* `curl -H 'Authorization: Bearer changeme' http://localhost:8083/_/items/article/1?lang=1`
* `curl -H 'Authorization: Bearer changeme' http://localhost:8083/_/items/article/1?lang=*`

3. Call from browser:

* http://localhost:8083/_/items/article/1?access_token=changeme
* http://localhost:8083/_/items/article/1?lang=it&access_token=changeme
* http://localhost:8083/_/items/article/1?lang=1&access_token=changeme
* http://localhost:8083/_/items/article/1?lang=*&access_token=changeme

4. See error: all the above call lead to the seme result: and article WITHOUT the translation

    {"data":{"id":1,"status":"published","author":"lrkwz","created_on":"2018-11-17 16:01:09","updated_on":"2018-11-20 16:54:19","slug":"prova"}}

## Expected Behavior

The translated title and body.

## Actual Behavior

Only the `article` data is transferred without the `article_tranlsations`.

## Other Context & Screenshots

Some how related to #590 

Attached a db dump to ease tests

## Technical Details

- Device: desktop
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Web Server: nginx
- PHP Version: 
- Database:mariadb 10.2
- Install Method: docker api:2.0.8 app:7.0.8

**Comment by rijkvanzanten** [comment]
Did you use the `lang` data type for the field that holds the language code in translations collection? If I remember correctly, that’s what enables the `lang` param.

@WellingGuzman can you confirm this?

**Comment by WellingGuzman** [comment]
@lrkwz I confirm what @rijkvanzanten said, If you change `article_translations.language` from type `m2o` to `lang` it fixes the problem.

Also you won't see any translation until you fetch the second level (nested) fields.

Example:

- `http://localhost:8083/_/items/article/1?access_token=changeme&fields=*.*`
- `http://localhost:8083/_/items/article/1?access_token=changeme&fields=article_translations.*`

**Comment by WellingGuzman** [comment]
This ticket was clarified, there's a open ticket to improve the setting up translation documentation here: https://github.com/directus/docs/issues/57 and the OP added a note in the documentation about how the translation requires to be fetched as a normal relational field here:  https://github.com/directus/docs/pull/64.
