### ISSUE TITLE
Mail footer using "project_url" in the wrong way

### ISSUE THREAD

**Issue by Nitwel** [directus/api#609]
I have set up...

![grafik](https://user-images.githubusercontent.com/22577866/48967890-a89ac800-efe7-11e8-87d7-445b58573157.png)

...to fix having the localhost as default url and for the link it works fine,...

![grafik](https://user-images.githubusercontent.com/22577866/48967914-19da7b00-efe8-11e8-8a39-2e91ccea818b.png)

...but the login link at the bottom is totaly broken. Im using a different url to get to the app (e.g. login.example.com) and there is no way to set the surce app.

A solution to this problem would be an JSON parameter describing the surce url when making a request to the api which sends an email like this:

![grafik](https://user-images.githubusercontent.com/22577866/48967998-362ae780-efe9-11e8-903d-cddc0c649fe9.png)

**Comment by WellingGuzman** [comment]
Hey @Nitwel, there's a new setting called `app_url` and if this value exists will replace the login url in the bottom of the email, otherwise the login url won't be displayed.

**Comment by WellingGuzman** [comment]
I added the new options to the docs: https://github.com/directus/docs/commit/44df2ed95cd8657139b7b214a066998cfa724384
