### ISSUE TITLE
Clean Exceptions classes

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#616]
There still a lot of unused/old exceptions that were meant to represents http exceptions, this method was deprecated in order to use interfaces to present the type of exception.

All general exceptions can be found here: https://github.com/directus/api/tree/master/src/core/Directus/Exception.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
