### ISSUE TITLE
Support multiple levels of nested data (fields=*.*.*)

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#62]
`fields=*` = fetch all (root level)
`fields=*.*` = fetch all (root level + first level deep)
this should continue indefinitely `*.*.*.*.*.*`

**Comment by WellingGuzman** [comment]
This should work as you described can you share a schema I can use to reproduce this?

**Comment by WellingGuzman** [comment]
This should be working, otherwise share a schema that I can use to reproduce this.
