### ISSUE TITLE
Add global error if requirement is missing

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#622]
The API can know when it's _not_ gonna work (f.e. when mod_rewrite is disabled or permissions are missing).

We should globally error out if a critical requirement is missing.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
