### ISSUE TITLE
Not sure how to register a new interface

### ISSUE THREAD

**Issue by jreid06** [directus/api#625]
**For security issues, please email support@getdirectus.com directly.**

To help us resolve your issue more quickly, please use the following template:

For feature requests/voting please use the [Directus Request Tool](https://request.getdirectus.com/), or come chat with us through [getdirectus.com](http://getdirectus.com). Accepted feature requests will be added to GitHub Issues for assignment.

## Version Info
  - Directus API version (Or commit hash): 7.0.9
  - PHP version: 7
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?) Apache
  - OS name and version: 

## Expected Behavior

After interface has been created, npm run build command has been run, app page has been refreshed i expect the interface to show in the list 

## Actual Behavior

When loading the directus app and i log into my api instance i don't see any new interfaces loaded in the list on "http://domain.com/#/settings/interfaces"

## Steps to Reproduce
1. Went to /extensions/core/interfaces directory
2. I copied an existing interface such as "text-input" and renamed it "random string"
3. edited the meta.json and changed the name key
4. While in the extensions folder from the command line i run "npm run build"
5. this updates the interfaces folder in "public/extensions/core/interfaces with a random-string folder with files such as input.js, display.js, input.css and meta.json

I assume that this means the interface has been registered. However it doesnt show. The documentation doesn't clearly explain how to register the interface once its created

Any help/guidance would be much appreciated

**Comment by benhaynes** [comment]
Hey @jreid06 — how did you install? Using the combined build or from source? I believe that (as of now) the source version is needed for custom extensions... but I could be wrong.

Hey @rijkvanzanten — any idea other steps to this?

**Comment by rijkvanzanten** [comment]
You don't have to register a new interface for it to show up. The steps you mentioned sound right to me. Is your app connected to the api in which you changed the interface?

**Comment by jreid06** [comment]
Apologies. Was editing the wrong api instance
