### ISSUE TITLE
Users cannot patch collection_presets when update permissions set to "mine"

### ISSUE THREAD

**Issue by honzabilek4** [directus/api#627]
When `collection_presets` update permission is set to `mine`, which is by default. Regular user is unable to send PATCH request to update his record. This way it's impossible for them to customise their collection view unless the update permissions is manually set to `all`. 

![screenshot 2018-12-04 at 11 07 51](https://user-images.githubusercontent.com/7890555/49434664-f9af7680-f7b4-11e8-855c-ccf3c6be740d.png)

![screenshot 2018-12-04 at 11 11 14](https://user-images.githubusercontent.com/7890555/49434908-9d992200-f7b5-11e8-9118-af55fe589bd4.png)
![screenshot 2018-12-04 at 11 12 49](https://user-images.githubusercontent.com/7890555/49434909-9d992200-f7b5-11e8-9263-fa766ebd7ac5.png)
![screenshot 2018-12-04 at 11 13 02](https://user-images.githubusercontent.com/7890555/49434910-9d992200-f7b5-11e8-944b-64a1009c0428.png)

Here, you can see that the record with id 10 exists and is assigned to user with id 2, who is the currently logged in user.
![screenshot 2018-12-04 at 11 18 39](https://user-images.githubusercontent.com/7890555/49435309-9888a280-f7b6-11e8-932e-39468f173540.png)

### System
- API: [2.0.10]
- Web Server: [Nginx 1.14.1]
- PHP Version: [eg: 7.0.32]
- Database: [eg: MySQL 5.7.24]

**Comment by benhaynes** [comment]
Thanks @honzabilek4 — we're on it!

**Comment by WellingGuzman** [comment]
Also it should be noted that this also happens with any permission that needs to verify the owner of the item.

**Comment by WellingGuzman** [comment]
Another thing to add here is because at the moment we can't tell what field store the owner of `collection_presets`, we can't properly verify the permission using `mine` or `role`. The API tries to look for a field `user_created` type, and this should change for another field for owner, and one case of author this can be either a new type or a fixed logic.

**Comment by rijkvanzanten** [comment]
For `directus_collection_presets`, we can use the `user` column for this purpose.
