### ISSUE TITLE
Quick question: Best way to get relationship data in hooks/filters

### ISSUE THREAD

**Issue by DeHekOnline** [directus/api#630]
Hi Guys,

First of all; Amazing piece of software you are creating here! Great support and help too!
Just a quick question, because I'm new to the API: What is the best way to get data from a relationship field in a hook?

i.e.:

I've created a filter that generates a PDF based on the data from a newly created item; The following data is passed in the $payload:

`{"data":{"id":38,"projectnumber":"876543","customer_id":1,"status":"draft"}}`

How do I get my customer's name/e-mail from the customer table, based on the customer_id?
Was messing arround with: \Directus\Util\ArrayUtils::get($payload,"customer_id"); 
But this is just guessing xD
Planning on using the new V7 php SDK for this when it comes out, but for now.

Thank you very much!

**Comment by Nitwel** [comment]
Im not that into the php api but I would say that you can access such information by:

```
$client = \Directus\SDK\ClientFactory::create($config);
$users = $client->getItems('directus_users');
$email = "";
$name = "";
foreach ($user as $users ) {
    if($user->id == 1){
        $name = $user->first_name . " " . $user_>last_name;
        $email = $user->email;
    }
}
```

**Comment by DeHekOnline** [comment]
Hi @Nitwel, than you for responding, but the SDK does not seem to be supported just yet for the V7 api..

**Comment by Nitwel** [comment]
Oh yes, thats true, but you can use the api without a SDK instead.
For more information:
- How to do a HTTPRequest [click here](http://php.net/manual/it/httprequest.send.php)
- How to use the API [click here](https://docs.directus.io/api/reference.html#introduction)

**Comment by benhaynes** [comment]
@WellingGuzman has estimated that it would take ~3w to upgrade the PHP-SDK to v7 — so we might not be able to work on that for a while (don't have three weeks to spare!). If someone wants to take this on that would be a **huge** help... the [blueprint is ready to go](https://docs.directus.io/api/reference.html)!

Otherwise this might end up as an API Client only [when we figure out Swagger or Paw](https://github.com/directus/directus/issues/2255).

**Comment by DeHekOnline** [comment]
Would love to help out, but our knowledge of the project is not sufficient enough to get working on core stuff right now :)
We are planning on becoming a supporter some way or another soon though. Keep up the great work, you guys are making really cool stuff here!

To come back to my original question;
So while working with hooks, it is general practise to use the API itself to get data? It seems a bit odd to me to use a HTTP-request instead of using code already available.

**Comment by WellingGuzman** [comment]
> Im not that into the php api but I would say that you can access such information by:
> 
> ```
> $client = \Directus\SDK\ClientFactory::create($config);
> $users = $client->getItems('directus_users');
> $email = "";
> $name = "";
> foreach ($user as $users ) {
>     if($user->id == 1){
>         $name = $user->first_name . " " . $user_>last_name;
>         $email = $user->email;
>     }
> }
> ```

@DeHekOnline the example above is a way to get data without going through HTTP Request.

Here is a link to the documentation with a note on how to access data using the TableGateway: https://github.com/directus/docs/blob/master/api/data.md#fetching-data-within-hooks-and-endpoints.

**Comment by WellingGuzman** [comment]
I will close this ticket as it seems all was cleared out. If that's not the case let us know.
