### ISSUE TITLE
Problems with `something_id` fields when migrating from D6

### ISSUE THREAD

**Issue by Kinzi** [directus/api#633]
# Bug Report
I'm currently migrating my D6 data to a fresh D7 installation on MAMP. After connecting and setting up all the fields in D7 I run into a few issues with `something_id` columns (these are either for relational or  pure data puposes). More details below. I didn't migrate any directus tables but the files table.

## Steps to Reproduce

1. Fresh local development D7 installation according to docs
2. Migrating non-directus D6 tables w/o changes (& directus files table with changes according to docs)
3. Set up field types and relations in D7 app
4. Encounter the following oddities

## 1. Error on an M2M junction table:

D6 structure:
```
id
post_id
cat_id
```
I set up the M2M in D7 the same way I did in D6. But existing relations didn’t show up in the app. I could select an existing `category` in the `post` view but couldn’t save. The patch API call returned a 500.

API error:
`[2018-12-04 09:20:17] api[_].ERROR: Directus\Database\Exception\InvalidQueryException: Failed generating the SQL query. in /Users/seb/Code/directusapi/src/core/Directus/Database/TableGateway/BaseTableGateway.php:862`

After renaming the junction table columns in phpmyadmin to the following (and resetting the fields and relation) everything worked as expected (existing relation show up in `post` an the patch goes through):

```
id
post
category
```

I encountered the same behaviour for another M2M table.

## 2. Text Input Field
<img width="1021" alt="bildschirmfoto 2018-12-04 um 12 43 58" src="https://user-images.githubusercontent.com/6689405/49584658-aa0fad00-f964-11e8-9bb0-067f40f5ced8.png">
Original field name `tour_id`: values are not showing in the app (list and detail)
Cloned the column data into `tourid`: everything working as expected

When I now try to reverse engineer it:
1. delete `tour_id`
2. rename `tourid`-> `tour_id`
3. set up new field `tour_id`

The former working field `tourid` is again empty in list and detail. After reversing steps 1-3, content shows up again.

If I have both fields it requires `tour_id`to be populated when saving a new item - even though the field is not set to required…. maybe there is some confusion with the `id` primary key field?!?

## Other Context & Screenshots
These fields are set up identical and have identical data in the DB. One is showing the data the other one not:

<img width="355" alt="bildschirmfoto 2018-12-04 um 12 44 05" src="https://user-images.githubusercontent.com/6689405/49584680-b7c53280-f964-11e8-893c-c4df79c11517.png">
<img width="407" alt="bildschirmfoto 2018-12-04 um 12 45 08" src="https://user-images.githubusercontent.com/6689405/49584684-bb58b980-f964-11e8-918d-3bff2bd39e80.png">
<img width="1190" alt="bildschirmfoto 2018-12-04 um 12 48 30" src="https://user-images.githubusercontent.com/6689405/49584702-c4498b00-f964-11e8-92f7-4b732b57c58d.png">

## Technical Details

- Device: Desktop / MAMP
- OS: MacOS
- Web Server: Apache
- PHP Version: 7.2.8
- Database: MySQL
- Install Method: dev environment for app and api

**Comment by Kinzi** [comment]
If I find the time I'll try to reproduce this again with some demo data I can provide, but please don't wait for it as I'm quite busy atm... :)

**Comment by WellingGuzman** [comment]
I can't reproduce this issue, and due to inactivity I will close this until there's enough information to reproduce this issue.

As this is a migration this could probably be a misconfiguration.
