### ISSUE TITLE
Support grouping and sorting of collections

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#64]
Would adjust the navigation and collection overview

**Comment by rijkvanzanten** [comment]
This basically means that the directus_collections table is organized the same as directus_fields

**Comment by WellingGuzman** [comment]
I didn't understood what you meant, can you give me an example?

**Comment by benhaynes** [comment]
This applies to the Collection Listing and the Left Sidebar. Currently these are ungrouped, and sorted alphabetically – the only other option is to use the nav_blacklist or nav_override options.

If you have many collections (eg: 10+) you might want more control over presenting/organizing them for users. 

```
Current
////////////////////////////////////////
* A Table
* B Table
* C Table
* D Table
* E Table
* F Table


New Possibilities
////////////////////////////////////////

Group 1
* Table C
* Table E
* Table D

Group 2
* Table A
* Table C
* Table B
```

I think we only need to add `directus_collections.sort` and `directus_collections.group`.

**Comment by rijkvanzanten** [comment]
The only problem with `directus_collections.group` is that we have no way to store the group information. For example, `directus_fields` uses another record in `directus_fields` for the group, but this isn't applicable to collections?

**Comment by benhaynes** [comment]
Right. Well I don't think this warrants a dedicated table – any other ideas?

**Comment by WellingGuzman** [comment]
Maybe a user/group preference? maybe use `nav_override` (or a new field) to save a generated navigation (AKA sidebar customization) where they can drag and drop collections for sorting and creating "group" and dropping collections below it.

I don't know if you are following me, kind of like GitHub projects but vertically.

**Comment by benhaynes** [comment]
Hmm, that's another good option! So we would store things the same as now (`directus_groups.nav_override`) but instead of just JSON, we would have an interface to create the groups/order. The only other thing to consider is how do we easily allow for this to be _global_, not just per group?

**Comment by WellingGuzman** [comment]
We can use `directus_settings` for `global`. Ex: `scope=global` `key=nav_override`

**Comment by rijkvanzanten** [comment]
We basically we want to have WordPress' menu creator for our own internal menu

**Comment by VasiiH** [comment]
How to design the same kind of collection in one group inside the collection & fields (like all men are in one group and women are in another group)
