### ISSUE TITLE
Proxy implementation breaks CORS headers

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#652]
Removing these lines makes it work again

https://github.com/directus/api/blob/d542e8c58c36acf8e5e7858ddf8431b1af059601/src/helpers/all.php#L200-L203

**Comment by benhaynes** [comment]
@rijkvanzanten — any thoughts on how we can reproduce this so it can get fixed?

**Comment by rijkvanzanten** [comment]
This was fixed in the last release
