### ISSUE TITLE
filters behaviour unintuitive

### ISSUE THREAD

**Issue by beac0n** [directus/api#653]
# Bug Report

## Steps to Reproduce

use these filters together:
filter[id][nin]=5,6,7,8,9,10
filter[id][between]=1,15

## Expected Behavior

result list containing ids 1,2,3,4,11,12,13,14,15

## Actual Behavior

result list contains all ids

## Technical Details

using api docker image 2.0.11

**Comment by WellingGuzman** [comment]
Thanks for reporting this @beac0n, I will close this ticket in favor of https://github.com/directus/api/issues/134.

The filter should be improved to allow multiple filters for the same field.
