### ISSUE TITLE
Implement smarter caching strategy

### ISSUE THREAD

**Issue by honzabilek4** [directus/api#659]
Currently, when caching is enabled for the api, it considerably speeds up the response times. For example, it takes only around 15-20ms for us, which is awesome.

However, the whole feature becomes unusable, because all item listings are cached for the amount of TTL. This means that you cannot see any newly created items until the TTL expires.

The usual approach to solve this problem is invalidating the cache entries when an item is being added, deleted or updated. This is would be also the easiest, because new listings will be added back to cache while being read.

I think that this feature might be important to be able to scale the entire API instance and to lower some server workload.

**Comment by honzabilek4** [comment]
I'll be also able to help with this one, after some quick consultation with @WellingGuzman.

**Comment by rijkvanzanten** [comment]
There's another side to this though, if you're updating items at a very high rate, you might not want to invalidate the cache every time.

I think there should be a function that can be called to invalidate the cache that you then can call from a hook. That way, the user is in full control of when the cache gets refreshed.

**Comment by honzabilek4** [comment]
I agree, but cannot come up with any use case which would require updating items at very high rate. Do you have any example?

**Comment by rijkvanzanten** [comment]
Your IoT device is pushing the sensor value every minute, you have a web app to visualize the last hour of values

**Comment by honzabilek4** [comment]
Thanks for the example. 
Using hooks for this purpose might be a good way to go. But maybe some additional cache configuration option would be easier to manage? (I see imperative vs declarative approach)

**Comment by honzabilek4** [comment]
I wouldn't even mind caching the user created collections only.

**Comment by honzabilek4** [comment]
Can anyone take a look at this? Or can we discuss how can we implement this feature? Without the instant refresh, the cache is unusable right now. But all of us could definitely benefit from the redis (or other cache) integration. I'm personally willing to work on this, just need some discussion on how to do it exactly.

**Comment by rijkvanzanten** [comment]
I think having one `skip-cache` flag in the API would already help out tremendously. That would allow the application to work with the API. Secondly, we should have an option where the cache gets invalidated on save instead of based on time. @bjgajjar @theharshin @hemratna

**Comment by honzabilek4** [comment]
I love this Idea! 🙂😊

**Comment by theharshin** [comment]
@honzabilek4 Does this PR helps to solve your current requirement? https://github.com/directus/api/pull/892
As @rijkvanzanten suggested, we can still consider adding a `skip-cache` flag in endpoints to get live data.

**Comment by honzabilek4** [comment]
Thanks! It seems like #892 could solve the issue. I'm going to test it in the following days and close the issue if applicable.

**Comment by benhaynes** [comment]
Hey @honzabilek4 — any updates? :)

**Comment by bminer** [comment]
Just curious the /me route, which displays info about currently logged in user gets cached, and it shouldn't because it depends on the auth token.  Thoughts on this?  Should I open a separate issue?

**Comment by bminer** [comment]
^^^ Reminds me of #1476, so maybe we can continue that conversation there...
