### ISSUE TITLE
Option to automatically create user account if authenticated with SSO

### ISSUE THREAD

**Issue by kueronya** [directus/api#664]
# Feature Request
There should be an option to automatically create user accounts if they authenticate with a SSO provider. 

## What problem does this feature solve?
Right now only existent users are whitelisted for SSO authentication. So i have to expose the create user endpoint to unauthenticated users to create a new one before i'm able to authenticate them with SSO

## How do you think this should be implemented?
If the option is set, a user should be automatically created if they successfully authenticate with the SSO provider after the redirect from the oauth consent. Since the password, first and lastname are currently required for creating a new user account the fields should either be optional or the user should be created with dummy values.

## Would you be willing to work on this?
Since i'm just working a few days with directus i don't feel expierenced enough to do it on my own.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
