### ISSUE TITLE
/users/me returns 500 

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#672]
Nothing logged in error log unfortunately

**Comment by WellingGuzman** [comment]
I cannot reproduce this issue. Does the request respond with something?

**Comment by mcamacho** [comment]
This is what I got on the logs,  for a _/users/me?fields=last_page call

>  api[_].ERROR: TypeError: Argument 1 passed to Directus\Database\Query\Builder::columns() must be of the type array, integer given, called in /var/www/directus/src/core/Directus/Database/TableGateway/RelationalTableGateway.php on line 992 in /var/www/directus/src/core/Directus/Database/Query/Builder.php:100

**Comment by WellingGuzman** [comment]
@mcamacho that one in specific was already fixed, it will be included in the next version release.

Ref: https://github.com/directus/api/commit/83f5b5b982fec56e251602a843cab608b0f252c1

**Comment by rijkvanzanten** [comment]
So it's done @WellingGuzman? Safe to close?

**Comment by WellingGuzman** [comment]
@rijkvanzanten I am unable to reproduce your issue, as I can get data using `/users/me`.

What's fixed is the issue above when someone uses the `fields` param on any endpoint

**Comment by WellingGuzman** [comment]
If that was your case getting the error when `fields` was used, then lets close this ticket.

**Comment by rijkvanzanten** [comment]
Yes, it was also with `fields`. When logging in, the application will use `/_/users/me?fields=last_page` to retrieve to what page to navigate on load.
