### ISSUE TITLE
Clean up multiple filter syntax

### ISSUE THREAD

**Issue by benhaynes** [directus/api#675]
Multiple filters is now functional, but @WellingGuzman would like to clean up the syntax a bit so it's more intuitive.

-----
**From Welling:**

The problem: it could be a bit ugly, just for the sake of the "array in url" thing:

```
filter[id][][between]=1,15&filter[id][][between]=30,45
```

Although to include ranges between 1 and 15, and 30 and 45. it should be an `or`. 

Here where it gets ugly:

```
filter[id][0][between]=1,15&filter[id][0][logical]=or&filter[id][1][between]=30,45
```

This was implemented by https://github.com/directus/api/commit/b37f5bbb173849bf8383876185af48e26612f60b

----

I was thinking on trying to implement a parser to allow multiple fields without adding the array. In addiction to the default using array.

So it looks like this:

```
filter[id][between]=1,15&filter[id][between]=30,45
```
Instead of:
```
filter[id][][between]=1,15&filter[id][][between]=30,45
```

**Comment by philleepflorence** [comment]
I can tackle this next week...

May I suggest: 
`filter[<field>][<filter>][]=<value>&filter[<field>][<filter>][]=<value>&filter[<field>][logical]=<value>`

This would render:
```
{
    "access_token": "<token>",
    "filter": {
        "<field>": {
            "<filter>": [
                "<value>",
                "<value>"
            ],
            "logical": "<logical>"
        }
    }
}
```

**Comment by philleepflorence** [comment]
Related to: #576

**Comment by benhaynes** [comment]
Sorry, maybe my brain is fried... but can you post your suggested syntax as an example with dummy data? 

@bjgajjar — what are your thoughts on this approach?

**Comment by philleepflorence** [comment]
FILTERS: `filters[key][contains][]=[task]&filters[key][contains][]=[ticket]&filters[key][logical]=[or]`
RAW SQL: ```SELECT * FROM `joins_app_users_metadata` WHERE `key` LIKE '%task%' OR `key` LIKE '%ticket%';```

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
I added this to `in progress` — that sound about right @philleepflorence ? :)

**Comment by philleepflorence** [comment]
Yes, sounds about right - do we agree on the nomenclature?

**Comment by benhaynes** [comment]
Cool. Let's just get @rijkvanzanten and @bjgajjar to sign off on the naming... then we should be good!

**Comment by rijkvanzanten** [comment]
Looks good to me 👍

**Comment by philleepflorence** [comment]
Awesome!
