### ISSUE TITLE
Email validation

### ISSUE THREAD

**Issue by cheehau** [directus/api#679]
when using directus API, to create a user, I can send a invalid email in the body of the post. And this email will still be accepted.

Is there some form of validation in place? Or do I need to write it myself?

Thanks

**Comment by rijkvanzanten** [comment]
@WellingGuzman Would adding a validation regex to the directus_fields column work in this instance?

**Comment by WellingGuzman** [comment]
Yes, adding a regex in `directus_fields` for the `email` field should fix this.

@cheehau as now you have to do it yourself.

I will fix this to support field validation by default on users email.

**Comment by WellingGuzman** [comment]
I added a new custom validation named `$email` that you can use to validate email.

After the next release, `directus_users.email` will be validate by default. Current user will need to upgrade their database, or add `$email` to `directus_users.email` in `directus_fields` table.

@cheehau if you can't wait on the release, you can add a custom regex to validate the field.
