### ISSUE TITLE
"Couldn't reach API" after switching storage adapter to AWS S3

### ISSUE THREAD

**Issue by lewisdonovan** [directus/api#682]
# Bug Report
Switching to s3 storage adapter causes an error that stops me from being able to log in

## Steps to Reproduce
1. Install Directus 7 (I'm running locally on Mac/MAMP)
2. Login to admin - everything works fine
3. Change storage adapter to S3 using [steps from official docs](https://docs.directus.io/extensions/storage-adapters.html#using-aws-s3)

## Expected Behavior
Admin behaves correctly and uploads are saved to s3 bucket

## Actual Behavior
I am logged out of the admin and can see the error "Couldn't reach API". I am unable to login again.

## Other Context & Screenshots
If I skip the step to add the S3 dependency with Composer, I don't get logged out, but I'm still unable to upload files, I just get an error message.

## Technical Details
- Device: MacBook Pro
- OS: MacOS High Sierra 10.13.2
- Browser: Chrome 71.0.3578.98 
- Directus App: 7.0.0
- Directus API: 2.0.0
- Install Method: Download and extract ZIP locally

**Comment by WellingGuzman** [comment]
@lewisdonovan Any logs in the `logs` directory? are you getting any specific error from the API (in the developer tools)?

**Comment by WellingGuzman** [comment]
Two more questions:

- Did you install the flysystem (`composer require league/flysystem-aws-s3-v3`)?
- Where did you install Directus from? separately or from `directus/directus`?

**Comment by WellingGuzman** [comment]
> If I skip the step to add the S3 dependency with Composer, I don't get logged out, but I'm still unable to upload files, I just get an error message.

I believe you have found this bug: #620.

Read the steps here on how to fix it: https://github.com/directus/api/issues/620#issuecomment-449905619

I will close this as this will be fixed when this https://github.com/directus/directus/issues/2273 is implemented.

**Comment by WellingGuzman** [comment]
I closed this ticket as it potentially the same issue, otherwise please let me now.

**Comment by lewisdonovan** [comment]
Great, thanks for your help. I'll run through this tonight and let you know if I hit any issues.

**Comment by lewisdonovan** [comment]
All working, thanks again.
