### ISSUE TITLE
Add `system` flag for interfaces

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#683]
# Feature Request

**Comment by WellingGuzman** [comment]
@rijkvanzanten Is this adding `system=true` flag on all core interfaces in `/interfaces` endpoint?

**Comment by rijkvanzanten** [comment]
Oh whoops, this wasn't supposed to be posted. My bad! (that's why it's empty too)

**Comment by rijkvanzanten** [comment]
I had a plan to add a meta.json flag to certain interfaces (like file-preview) so they wouldn't show up in the settings. However, I came up with a better solution in the meantime :)
