### ISSUE TITLE
Add read-only permission for comments

### ISSUE THREAD

**Issue by Marcnuth** [directus/api#686]
**Description**:
1. Create a collection named: collection1
2. Set Role <public>'s permission on collection1: 
    - check \<All\> for Read
    - check \<Read-only\> for Comment
3. Use following url to fetch the comments
```
http://localhost:9080/_/api/activity?filter[collection][eq]=collection1&filter[item][eq]=1&filter[action][eq]=comment&sort=-action_on&fields=id,action,action_on,comment,action_by.*,action_by.avatar.data.*
```

**Result**:
Expecting to get a list of comments, but get 403<permission denied> instead.
```json
{"error":{"code":300,"message":"Reading items from \"directus_activity\" collection was denied"}}
```

**Question**:
Why 403 happens even if we allow <public> to read the comments?  If the endpoint is wrong, which one should be right for fetching comments?

**Comment by WellingGuzman** [comment]
I removed the bug label as there's not `read-only` permission for comment in the API at the moment.

I checked the app, it seems to have the option, but it doesn't exists in the API.

**Comment by Marcnuth** [comment]
@benhaynes any plan on this?

**Comment by benhaynes** [comment]
@Marcnuth — we have plans for all of these (that's why I removed the `stale` label) but our team is super busy at the moment so it will probably be a few weeks before we'd have time. Happy to review a community PR though!

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
