### ISSUE TITLE
fields parameter returns internal server error

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#687]
# Bug Report

Using the fields parameter with anything but a `*` sign returns a 500 internal server error.

## Steps to Reproduce

1. Go to https://www.kunstenkindkampen.nl/api/public/_/items/aanbod
2. Add the `fields` parameter with anything but `*` or `*.*` (etc)

## Expected Behavior

Should return the fields as requested

## Actual Behavior

Returns `{"error":{"code":null,"message":"Internal Server Error"}}`

## Other Context & Screenshots

The error in the logs is

```
TypeError: Argument 1 passed to Directus\Database\Query\Builder::columns() must be of the type array, integer given, called in /api/src/core/Directus/Database/TableGateway/RelationalTableGateway.php on line 992 in /api/src/core/Directus/Database/Query/Builder.php:100
```

_Could be a duplicate of #685_

**Comment by WellingGuzman** [comment]
This already has been fixed by https://github.com/directus/api/commit/83f5b5b982fec56e251602a843cab608b0f252c1
