### ISSUE TITLE
Add translation column to directus_collection_presets table

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#69]
That way we can support multilingual bookmark names 🤓 @benhaynes

**Comment by WellingGuzman** [comment]
Nice! What's the column name and type? Same as `directus_fields: `name=translation` and `type=text`?

**Comment by rijkvanzanten** [comment]
Column name = `translation` and column type = `JSON` / `TEXT` 🙂

**Comment by rijkvanzanten** [comment]
Not sure if it's going to be used in 7 straight away, but my goals is to have everything translatable in the long run

**Comment by WellingGuzman** [comment]
It's okay. It's better to add it now than later and avoid the schema upgrade.
