### ISSUE TITLE
System error with custom role users

### ISSUE THREAD

**Issue by marcocala90** [directus/api#692]
Hello, I'm Marco,

When the role of a new user is "ADMINISTRATOR" the CMS works perfectly, but when the user have a custom role, after the login, the system show me a "System error! Something is wrong with this instance’s server or database." If i change the role to admin the system works.

![screen_directus](https://user-images.githubusercontent.com/36272515/50957222-ee3f2180-14bd-11e9-9b4b-fc6e08a48309.png)

I try to add the fix in this comment [https://github.com/directus/directus/issues/2224#issuecomment-434306147](url)
But not working!

In the developer console i see this 500 error

![screen_directus_2](https://user-images.githubusercontent.com/36272515/50957506-a66cca00-14be-11e9-89c1-c9d30e2702f5.png)

When i try to open this link i see this

![screen_directus_3](https://user-images.githubusercontent.com/36272515/50957601-ea5fcf00-14be-11e9-8fc5-62d9896a91bf.png)

Anyone have an idea?

PHP: 7.1.25
MySql: 5.7.14

**Comment by WellingGuzman** [comment]
Hello @marcocala90, does @alrick suggestion worked for you?

If that didn't work can you please share the logs in the `logs` directory?

**Comment by marcocala90** [comment]
@alrick well done! The fix working :) Thanks

**Comment by WellingGuzman** [comment]
I am closing this as this issue is duplicated and have been already fixed, but not released.
