### ISSUE TITLE
can't send an password reset request mail,but can send an mail to one recipients

### ISSUE THREAD

**Issue by kroawen** [directus/api#693]
I use sendmail as mail transport, then send an mail for password reset requst :
`http://example.com/_/auth/password/request.` , I didn't receive any mail.
![image](https://user-images.githubusercontent.com/6927999/51071352-96094a80-168a-11e9-8bdf-9934a0e8527a.png)
When I use `http://example.com/_/mail`  send an mail to someone. it  work.
![image](https://user-images.githubusercontent.com/6927999/51071344-65291580-168a-11e9-842c-a9cc5258c0f7.png)

sendmail config :
```
 'mail' => [
      'default' => [
           'transport' => 'sendmail',
          'from' => 'xxx@X.xxx.com'
       ],
    ], 
```
Is there anything wrong elsewhere?
thanks

**Comment by WellingGuzman** [comment]
I am unable to reproduce this issue, It's working as expected in my end, both sendmail and `smtp`

**Comment by kroawen** [comment]
I changed the mail service , It work now, thanks

**Comment by WellingGuzman** [comment]
Glad to work @kroawen. Any reason why the service didn't work with `http://example.com/_/auth/password/request` and worked with `http://example.com/_/mail`?
