### ISSUE TITLE
Directus Error after logging in

### ISSUE THREAD

**Issue by Nitwel** [directus/api#694]
In version 2.0.14, I run into the issue that directus crashes after I login.
I clean installed both api and app and when I login, I get these Errors: https://pastebin.com/K9NgFQ1v
(I also clean installed the database)

I also made me a script for SSH to update directus more easily:
```bash
rm -rf api &&
rm -rf app &&
wget -O api.zip https://github.com/directus/api/archive/build.zip &&
wget -O app.zip https://github.com/directus/app/archive/build.zip &&
unzip api.zip &&
unzip app.zip &&
mv api-build api &&
mv app-build app &&
rm -rf api.zip &&
rm -rf app.zip &&
cp ./configs/api.php ./api/config/ &&
cp ./configs/config.js ./app/
```

If I forgot something, please tell me.

**Comment by Nitwel** [comment]
Ok, I changed the Script a bit, so I can change the version easily:
```
version="0.10" &&
rm -rf api &&
rm -rf app &&
wget -O api.zip https://github.com/directus/api/archive/v2.$version.zip &&
wget -O app.zip https://github.com/directus/app/archive/v7.$version.zip &&
unzip api.zip &&
unzip app.zip &&
mv api-2.$version api &&
mv app-7.$version app &&
rm -rf api.zip &&
rm -rf app.zip &&
cp ./configs/api.php ./api/config/ &&
cp ./configs/config.js ./app/
```

I have tested installing directus version x.0.14, x.0.13 and x.0.10 and only x.0.10 works for me.
Also, when trying to connect to the api, I get an http error 500

**Comment by benhaynes** [comment]
I don't know what any of this means, but it sounds serious!! 😬 

🔔 @WellingGuzman

**Comment by Nitwel** [comment]
Added comments to each step so you can understand it better.

**Comment by WellingGuzman** [comment]
@Nitwel according to the logs it seems that trying to fetch an user that doesn't exists, after a successful authentication. Your steps doesn't give me much detail on what's going on.

- When does this happens? just right after you authenticated? 
- How are the app and api configured in your server?
- What are in those configs you are copying?

**Comment by Nitwel** [comment]
> When does this happens? just right after you authenticated?

exactly

> How are the app and api configured in your server?

I try to connect to "api.nitwel.de/_/" which is routed to "/htdocs/api/public" .
You connect to the app via "login.nitwel.de" which is routed to "/htdocs/app" .

> What are in those configs you are copying?

These are a standard copy of the config for the right version, edited so, that they have all configuration already set.

**Comment by Nitwel** [comment]
Ok, sorry I wasted your time, I somehow got it working, dont ask me how.

**Comment by rijkvanzanten** [comment]
How did you get it working? 😏

**Comment by Nitwel** [comment]
The only guess I have is, that I now routed the api url to the main folder and not to the public folder in it, so Im not shure how my serverprovider handles access out of the accual url.
