### ISSUE TITLE
Unable to clear fields

### ISSUE THREAD

**Issue by bjarkeseverinsen** [directus/api#697]
# Bug Report

## Steps to Reproduce

1. Go to https://directus.app and login.
2. Go to Concessions and create new item.
3. Set Name to 'Test' and save.
4. Edit item, delete all the characters in name and save.

## Expected Behavior
Item name is saved as default value in database.

## Actual Behavior
Item name is saved as 'T'

**Comment by bjarkeseverinsen** [comment]
@rijkvanzanten Tried fixing this once.

**Comment by rijkvanzanten** [comment]
I did, didn't I 😨 

It seems to be working on my end. Could you clear your caches just to make sure and try again?

**Comment by bjarkeseverinsen** [comment]
Seems like you did yes.
I can't clear my caches "normally" though, in Chrome latest.
When i open in incognito i see the issue fixed.

Any thoughts on why it is still cached?
I tried refreshing with Cmd + Shift + R (mac)
And i have disable cache enabled in network as well

**Comment by rijkvanzanten** [comment]
I don't know really. I usually clear my caches at the dev tools > application > clear cache to make absolutely sure. Chrome has acted up for me in the past as well 🤷‍♂️
