### ISSUE TITLE
Support global / scoped extensions

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#698]
# Feature Request

Extensions are an incredibly important part of the API. As of right now, certain extensions are globally available for the whole API (eg interfaces / endpoints), while others are only available per project (hooks). Ideally, every extension can be _either_ available globally or scoped.

## What problem does this feature solve?

* Being able to have a global hook for all API activity
* Being able to have a custom interface on a specific project
* Having a custom `/export-to-csv` endpoint on my finance project

## How do you think this should be implemented?

Right now, (global) extensions are added based on the `public` folder:

```
public/
  extensions/
    core/
    custom/
```

Maybe we can consider adding a `global` vs `scoped` split in this structure:

```
public/
  extensions/
    global/
      core/
      custom/
    scoped/
      _/
      client-1/
      client-2/
```

Seeing that the core extensions are always available for all instances, we don't necessarily need the `core` vs `custom` split for scoped extensions.

_Hooks can already be scoped by adding them into the `api.<project>.php` file in the config_

Thoughts @benhaynes @WellingGuzman?

**Comment by rijkvanzanten** [comment]
1) Technically yes. I don't know how hard it would be to support the "old" structure. 
2) That's a very good question. As of right now, the "app extensions" (interfaces / layouts / pages) are all publicly available. We might want to consider making them auth only as well.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
This is important for a number of reasons:

* There's no way for Cloud users to install / use extensions right now
* When we move away from PHP based config files, scoped hooks are no longer possible
* Hooks created on the global scope have no way of differentiating from what project they're called

--- 

I would even go as far as to say that having just _scoped_ extensions makes more sense than having only _global_ extensions. But obviously it's nicer to support both.
