### ISSUE TITLE
Add separate fields for validation errors

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#7]
The API can return more than one validation error on posting / updating items. For example: wrong datatype and too long.

In order to make the error more useful, we should change the `error` message structure to something like:

```json
{
  "code": 4,
  "message": "There was a validation error on the fields",
  "info": [
    {
      "field": "name",
      "message": "This value should not be blank.",
      "code": 15
    },
    {
      "field": "age",
      "message": "The maximum length has been exceeded",
      "code": 20
    }
  ]
}
```

**Comment by WellingGuzman** [comment]
Trying to add a unique field type that already exists in a collection can throw one multiple errors.

Ex: trying to add a primary key and sort field to a collection that already have them.

**Comment by rijkvanzanten** [comment]
Maybe this is cleaner

_One error_
```json
{
  "error": {
    "code": 123,
    "message": ""
  }
}
```

_Multiple errors (eg validation)_
```json
{
  "error": [
    {
      "code": 123,
      "message": ""
    },
    {
      "code": 123,
      "message": ""
    },
    {
      "code": 123,
      "message": ""
    }
  ]
}
```

**Comment by WellingGuzman** [comment]
From #7 

----

In an error like:

```js
{code: 4, message: "hidden: This value should not be blank."}
```

It's quite hard to get the field (`hidden`) out of the message programmatically. It would be nice if these variables could be extracted into their own fields as well:

```json
{
  "code": 4,
  "message": "hidden: this value should not be blank",
  "field": "hidden"
}
```

That way, I can use them to translate the error messages dynamically

**Comment by benhaynes** [comment]
@WellingGuzman what's the status of this one? Do we need to discuss further?

**Comment by WellingGuzman** [comment]
@benhaynes still in the discussing state. We need to really figuring out how we are formatting the attributes.

We agreed on the `error` key to be either an object or an array (multiple errors), but we need to find a way to standardize the attributes that works for any case and not just input validation.

Originally suggested to add a new property named `field`, this may work, but maybe is specific to user input validation.

Another suggestion I think may be better is adding an `attributes` property with a list key-value.

Something like this:

```json
{
    "error": [
        {
            "code": 200,
            "message": "name: this value should not be blank",
            "attributes": {
                "field": "name"
            }
        },
        {
            "code": 201,
            "message": "age: this value should be numeric",
            "attributes": {
                "field": "age"
            }
        }
    ]
}
```

Example: the error code will means: `200 = Blank/Required value`, `201 = Expected number value`.

In this case you should expect any error ranging from `200` to `299` will have an `attributes.field` property.

This is my suggestion, Happy to discuss this further.

**Comment by benhaynes** [comment]
That makes sense to me! I'll defer to you two on this one's formatting.

@rijkvanzanten – any thoughts on Welling's proposed approach?

**Comment by rijkvanzanten** [comment]
LGTM!

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by Autr** [comment]
+1 for this! Here's a hack in the mean time:

```
			const msg = err.response.data.error.message;
			let formatted = [];

			for (let i = 0; i < msg.length; i++) {
				const char = msg[i];
				if ( char === ':' ) {
					let item = undefined;
					let ii = i;
					while (!item ) {
						ii -= 1;
						if ( msg[ii] === ' ' || ii === -1 ) {
							item = {
								id: msg.substring( ii + 1, i ),
								start: ii+1,
								end: i,
								message: ""
							};
							formatted.push(item);
						}
					}
				}
			}

			for (let i = 0; i < formatted.length; i++) {
				const a = formatted[i].end + 2;
				const b = (formatted[i+1]) ? formatted[i+1].start : msg.length;
				formatted[i].message = msg.substring( a, b );
			}
			return formatted;
```
