### ISSUE TITLE
Switch system interfaces to types

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#70]
System interfaces are going to be replace by System types.

We are noW creating new types to determine if a field is a system field, such as `status` and `primary_key`

**Comment by rijkvanzanten** [comment]
Types:

```
JSON
CSV
BOOLEAN
PRIMARY_KEY
GROUP
STATUS
SORT
```

@WellingGuzman am I missing any?

**Comment by rijkvanzanten** [comment]
`TRANSLATION` is another one. This one is needed to make the `lang` parameter work 😄

**Comment by benhaynes** [comment]
Not PRIMARY KEY... this will be separate so we also have the datatype

**Comment by WellingGuzman** [comment]
Also status (interface/type), it needs to be separate as it should accept string or numeric datatype.

**Comment by benhaynes** [comment]
@WellingGuzman @rijkvanzanten 

What is left to complete this ticket?

**Comment by WellingGuzman** [comment]
I believe this one is done. The API moved everything from interface to type.

**Comment by benhaynes** [comment]
OK, we'll close when Rijk confirms.

**Comment by rijkvanzanten** [comment]
Can someone double check if this is all in the docs 100% correct? It's all done on the API side, but it's important to have it documented too :) @benhaynes @WellingGuzman

**Comment by benhaynes** [comment]
I wrote descriptions, but I wouldn't know if any are missing:

https://github.com/directus/docs-v7/blob/master/api/admin-guide/field-types.md

**Comment by WellingGuzman** [comment]
I added the `binary` type that was missing. All updated.
