### ISSUE TITLE
m2m data not returned

### ISSUE THREAD

**Issue by Niekvan** [directus/api#701]
# Bug Report

## Steps to Reproduce

1. Go to 'GET /[project]/items/[collection-name]/[pk]'

## Expected Behavior
Include the m2m and o2m relations pointing to the right collection and pk, or even better return the table the m2m/o2m relation is pointing to.
## Actual Behavior
The m2m and o2m are ignored and not returned
## Technical Details

- Device: Desktop
- OS: Windows 10.1803
- Web Server: Apache 2.4.37
- PHP Version: 7.2.0
- Database: MySQL 8.0.12
- Install Method: cloned `build` branch

**Comment by rijkvanzanten** [comment]
Is this with or without using the `fields` parameter? https://docs.directus.io/api/reference.html#fields

**Comment by Niekvan** [comment]
Without. Simply calling getItems('collection-name') from the SDK
