### ISSUE TITLE
The image cannot be loaded in "File Library/Editing Item" page when use aws s3 adapter 

### ISSUE THREAD

**Issue by KKAries** [directus/api#706]
# Bug Report

## Steps to Reproduce

1. Configure s3 adapter in api configuration
2. Upload an image in File Library
3. Click on the uploaded image (the thumbnail works fine) to direct to Editing Item page
4. The display of image crash

## Expected Behavior
The image displayed correctly with right url.
## Actual Behavior
Directus tries to find the image directly on the local server but the image is on s3,thus the image cannot be loaded.
## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/35513964/50889165-416b9280-1432-11e9-9579-992c8bb70f20.png)

## Technical Details

- OS: Windows 10
- Browser: Chrome
- Directus App: 7.0.13
- Directus API: 2.0.13

**Comment by WellingGuzman** [comment]
@KKAries, if the file already has not public permission the S3 adapter will not override this permission, as far as I am aware.

In your storage config set the `ACL` option to `public-read` (Ref: https://github.com/directus/api/blob/master/config/api_sample.php#L72).

```
'options' => ['ACL' => 'public-read']
```

Now try uploading a new file and see if that one public accessible.

**Comment by KKAries** [comment]
Thanks @WellingGuzman ! After add the ACL option now I can get the image. One more thing, how can I configure to let directus read thumbnail from s3. I can see that it automatically add thumbnail on s3 but from network view, I see that the Directus still read thumbnail of images from local server url. I want the file storage completely independent from local server since I am running a docker container.

**Comment by rijkvanzanten** [comment]
>  I see that the Directus still read thumbnail of images from local server url

If I'm not mistaken, the API will only generate the actual thumbnail image file the first time the thumbnail URL is opened. Therefore, it has to go "through" the API, otherwise the file isn't generated yet.

**Comment by computerwizjared** [comment]
@KKAries The thumbnails are only proxied through the container, no thumbnails are stored within the actual container storage. It will store them in the same S3 bucket and retrieve them from there as well.

**Comment by KKAries** [comment]
Got it! Thanks @rijkvanzanten @computerwizjared
