### ISSUE TITLE
Add support for more options in /projects

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#707]
It's currently not possible to change the configuration of `cache`, `storage`, `mail`, `cors` (options), `rate_limit`, and `social_providers` when creating a project through the `/projects` endpoint. This means that you either have to manually adjust the config file or overwrite it completely using a custom script in order to change these settings

**Comment by WellingGuzman** [comment]
The following options are now supported: `cache`, `storage`, `mail`, `cors`, `rate_limit`, and `social_providers`.

Docs: https://github.com/directus/docs/blob/master/api/reference.md#body-23

Ref: https://github.com/directus/api/commit/056ccc0bd875c28656bbbd90f3780a2d69b51c1f
