### ISSUE TITLE
Don't allow users to create a directus_ prefixed collection

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#709]
# Feature Request

When the user creates a new collection, we should return an error when the collection name starts with `directus_`

## What problem does this feature solve?

At a lot of places in the application, we use the `directus_` prefix to differentiate between the regular and system collections. When the user creates a new collection (like `directus_rijk`) this collection will be hidden and treated like a system collection.

## How do you think this should be implemented?

```php
if (substr( $string_n, 0, 9 ) === "directus_") {
  return "u rebel";
}
```

**Comment by WellingGuzman** [comment]
There shouldn't be a problem with a collection starting with `directus_` being hidden or treated as system collection. At least on the API all system collection are whitelisted.

Do you still want to implement this?

**Comment by rijkvanzanten** [comment]
Yes please, we should treat `directus_` as system and off limits

**Comment by benhaynes** [comment]
We can always add a `hidden_` prepend string to hide non-system tables... but I think that can all be done through the managed flag and table blacklist. So I agree, `directus_` should be off-limits to users.

**Comment by WellingGuzman** [comment]
I prevent creating new collection that starts with `directus_` here: https://github.com/directus/api/commit/190b8552b9ac0dbde98177c0ccf49e246d21614a
