### ISSUE TITLE
support user registering & activate 

### ISSUE THREAD

**Issue by Marcnuth** [directus/api#711]
Is there any plan for supporting account register and related stuffs such as : activate a user, etc ?

**Comment by benhaynes** [comment]
There have been several discussions (Slack) and tickets (GitHub) about this. At this point we're essentially looking into whether it passes our 80/20 rule. If it seems like a feature 80% of our customers will use then we will likely add it as an option into v7.1.x

Invite (internal) and verify DIrectus users is currently in-work.
