### ISSUE TITLE
User not found - 405 not allowed

### ISSUE THREAD

**Issue by honzabilek4** [directus/api#712]
# Bug Report
This bug is preventing any other user than initial admin from logging in.
I've tried to create a new database and run the install from scratch for a specific project (other than default) as described [here](https://docs.directus.io/advanced/api/configuration.html#configure-with-script), but the only user allowed to navigate around is the initial admin. All other users are getting 405 Not Allowed.

## Steps to Reproduce
1. Having an existing project with default config create a new database, api config and a new admin user as described [here](https://docs.directus.io/advanced/api/configuration.html#configure-with-script).
2. Login with the admin account and create a new user (Admin or other profile, both didn't work).
3. Login with the new account in the same window. This should allow you to enter. However It looks like you're still seeing the old data.
4. Login in an anonymous window or refresh the page and cache (cmd+shift+r) and you should get a server error message.

## Expected Behavior
No application errors.
## Actual Behavior
Couple of errors appear. This seems to be still a problem with the shared env endpoints (layouts, pages, interfaces). However, the only confusing error is the "User not found" message, even though I'm 100% sure the user exists in the database.

![screenshot 2019-01-19 at 01 06 31](https://user-images.githubusercontent.com/7890555/51418923-d6832f80-1b86-11e9-9881-d38f61181435.png)
![screenshot 2019-01-19 at 01 07 03](https://user-images.githubusercontent.com/7890555/51418924-d6832f80-1b86-11e9-9feb-c5bd150f3732.png)
![screenshot 2019-01-19 at 01 07 26](https://user-images.githubusercontent.com/7890555/51418922-d6832f80-1b86-11e9-86f1-aaab3d7348d0.png)
![screenshot 2019-01-19 at 01 07 48](https://user-images.githubusercontent.com/7890555/51418920-d5ea9900-1b86-11e9-8fd2-f20029e89f88.png)
![screenshot 2019-01-19 at 01 08 01](https://user-images.githubusercontent.com/7890555/51418921-d5ea9900-1b86-11e9-8031-5238afda6d50.png)

## Technical Details
- API: 2.0.14
- APP: 2.0.14
- OS: Ubuntu 16.04.5 LTS
- Web Server: nginx/1.14.1
- PHP Version: 7.0.32
- Database: MySQL 5.7.24
- Install Method: pulled from `build`

**Comment by WellingGuzman** [comment]
It seems that CORS is disabled. I believe this was reported before. I can remember what it was.

I can't reproduce this issue on `master`, can you try using `master`?

**Comment by honzabilek4** [comment]
I did a clean setup again and everything works, though unfortunately I don't know the reason of this issue. 😞 If this appears again I'll open a new issue and try to investigate the problem further.
Thanks for your quick response.
