### ISSUE TITLE
Exclude deleted items from 'total_count'

### ISSUE THREAD

**Issue by theharshin** [directus/api#714]
# Bug Report

## Steps to Reproduce

1. Create a new collection with `status` option enabled
2. Add 13 items
3. Delete some and keep 7 items
4. Add this collection as M2O in other collection  
5. Check M2O interface's API response

## Expected Behavior
The `total_count` should be `7` excluding deleted items

## Actual Behavior
The `total_count` gives `13`

## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/7118937/51455270-d2b20180-1d6e-11e9-80a0-0f637ec5ad54.png)

## Technical Details

- Device: MacBook
- OS: MacOS Mojave
- Web Server: Apache/2.2.34
- PHP Version: PHP Version 7.2.7
- Database: MySQL 5.7.21
- Install Method: Cloned `master` branch

**Comment by WellingGuzman** [comment]
Hey @theharshin, this is an expected behavior, what we need to think is that we want to start ignoring "non-published" or unknown status items as part of the whole items list. It makes sense as if the item will never be present in the list, why count them? it could mess the pagination.

@benhaynes any thoughts?

The value I believe you are looking for is `result_count`, this value is the actual number of items in the result.

**Comment by benhaynes** [comment]
I would say that we should _always_ be ignoring items with a `soft_deleted` status — even in `total_count`. We could always add a `soft-deleted-count` later if we need to (or do we already have a "count by status"?).

I'm not 100% sure about the other statuses (eg `draft`). Maybe they should only be in the count if they would be returned in the dataset (ignoring offset/limit)?

Happy to discuss this one further!

**Comment by WellingGuzman** [comment]
I believe the soft-deleted shouldn't be counted. They are not going to be listed, this will result in a bad pagination. The other status are visible, so it's good to have them counted.

There's another bug, where soft-deleted are not counted in the status count list.

I will be ignoring the soft-deleted values, and fix the count by status object, and call this issue done.

**Comment by rijkvanzanten** [comment]
I agree with @WellingGuzman. soft-deleted items should be treated like "hard" deleted (eg don't exist).

**Comment by WellingGuzman** [comment]
Unknown status are being ignored (not being listed), is this a behavior we want? The API uses the Status Mapping as a whitelist of statuses, meaning the rest shouldn't allowed to be listed

**Comment by benhaynes** [comment]
Since we have a `published:true` flag, I agree that the status mapping should be a "whitelist". Therefore unknown statuses should _not_ be included.

**Comment by rijkvanzanten** [comment]
I agree, but right now it's pretty easy to forget to set a status if you're creating an item which makes it disappear. Should we make `status` required at all times in order to prevent this confusing situation?

**Comment by benhaynes** [comment]
Is there a way we can give that field a default value based on the dynamic mapping? I'm also fine making it required too.

**Comment by rijkvanzanten** [comment]
The user can theoretically set the default value just like they can for any other field. 🤔 

The only way I can imagine is that the status interface has a hook that will set the default if none was passed, but that might be a bit confusing too.

I think the status interface should have the `required` flag set to true (in the application). That way, users that don't check out the advanced option will have this failsafe activated. Users that know what they're doing can disable it if they have the need for a `null` status for some reason.

**Comment by WellingGuzman** [comment]
I agree with Rijk, it's kind of annoying to create an item that you forgot to set the status and then disappear.

Although you can set the field as required and set a default, forgetting this, will make those value hard to access.

**Comment by benhaynes** [comment]
Yeah, we will have the App set the `status` field as _required_ to avoid this. @rijkvanzanten do you have/need a ticket for this?

**Comment by WellingGuzman** [comment]
I create a patch that:
- Will avoid counting soft-deleted items in `total_count`.
- Count all status even the value is not in the status mapping.

Ref: https://github.com/directus/api/commit/95ff344dd9bb4a821ff8dacc19b8f1234a8e46b5

**Comment by rijkvanzanten** [comment]
@benhaynes I'll add a ticket to the app  👍
