### ISSUE TITLE
Enforce read blacklist permission on filter

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#717]
# Bug Report

Filtering by a read blacklisted field is not enforced. Even if the field is not on the result, you can still filter by the field value. (Ref: #667)

## Steps to Reproduce

Add any field to read blacklist, and try to filter by that field.

## Expected Behavior

It should throw an exception

## Actual Behavior

No error, filter get processed.

**Comment by WellingGuzman** [comment]
If an user has read blacklist permission set to a field it shouldn't be able to filter by its content. This is a similar issue that was reported with https://github.com/directus/api/issues/667.

**Comment by alex-vasilchenko-md** [comment]
Hi @WellingGuzman ! 

A question related: I created a "Test" collection and in Public role I disabled all permissions.
On GET request _/items/Test I get expected response:

{"error":{"code":300,"message":"Reading items from \"Test\" collection was denied"}}

Then I set read permissions on: {"data":[{"id":1,"status":"published","created_by":1,"created_on":"2019-03-12 17:19:28","modified_on":"2019-03-12 17:19:28","name":"hello"},{"id":2,"status":"draft","created_by":1,"created_on":"2019-03-13 08:12:27","modified_on":"2019-03-13 08:12:27","name":"other"}],"public":true}

But I have "name" field set to Hidden on detail and Hidden on Browse to on. 

Is this also bug related or I misunderstood something with how permissions are expected to work?

**Comment by rijkvanzanten** [comment]
Hey @alex-vasilchenko-md! 

Hidden on detail and hidden on browse means that the interface doesn't show up in the application. What you're looking for is the read field whitelist 🙂 By default all fields are on, but you can disable individual fields 

<img width="993" alt="image" src="https://user-images.githubusercontent.com/9141017/54289800-2cb99100-4580-11e9-9b17-272cb22cb564.png">

**Comment by alex-vasilchenko-md** [comment]
Oh! Thanks, @rijkvanzanten! Now I got it!

**Comment by alex-vasilchenko-md** [comment]
OK, I figured it out, I found in UI where do I set up. I would suggest to make it visible that you can actually click on "All" to expand fields. I would suggest to have a blue link "edit" next to All or something like this, it's not hard to do!

Then I had a look how to fix this permission issue in a similar way like here: https://github.com/directus/api/commit/d5edccb0868ab6537cee9c6603e5ed78e9aaa7a0

It was easy to find, that we need to add permission check here https://github.com/directus/directus/blob/master/src/core/Directus/Database/TableGateway/RelationalTableGateway.php#L815 (or probably on fetchData level later)

After that I realized, that we have different permissions for each status: for some statuses we can have read permissions for some statuses not. For example no read permission for "draft" status and have it for all other statuses. How this fix should work than? Should we block it anyway? Or should we filter only those records which have statuses with read permission?

**Comment by benhaynes** [comment]
Thanks @alex-gorovyi!! It seems that if you do *not* have permission to a field for a specific status that we should _ignore_ those items entirely, but still show/filter any other items where you *do* have permission to that field. 

Does that make sense? I know this is pretty complicated!

**Comment by bjgajjar** [comment]
@itsmerhp 

Just gone through PR and found that the behavior of collection which has `status` field and which doesn't have `status` field is different.

Let's have an example.
(1) The collection which contains `status` field and the `title` field is blacklisted; returns the blank array for filter it with `title`.
(2) The collection which doesn't contain the `status` field and the `title` field is blacklisted; throw the exception for filter it with `title`.

So let's make it common for both scenarios. Kindly replace the exception with blank array and send the PR again.

**Comment by bjgajjar** [comment]
@benhaynes 

Let's not throw the exception here. As the user will not get read blacklisted field in the listing API and still they try to implement filter on that field, then it's not meaningful to give them the exception like 'Unable to access data' as the user may or may not know the name of `field`.So instead of that, we should return them a blank data.

**Comment by bjgajjar** [comment]
Fixed in #944
