### ISSUE TITLE
Undefined index: uploaded_by/folder

### ISSUE THREAD

**Issue by computerwizjared** [directus/api#722]
# Bug Report

## Steps to Reproduce
Querying any tables with M2M to a file results in the following:

```
<b>Notice</b>:  Undefined index: uploaded_by in <b>/var/www/html/src/core/Directus/Database/TableGateway/RelationalTableGateway.php</b> on line <b>1793</b><br />
<br />
<b>Notice</b>:  Undefined index: uploaded_by in <b>/var/www/html/src/core/Directus/Database/TableGateway/RelationalTableGateway.php</b> on line <b>1793</b><br />
<br />
<b>Notice</b>:  Undefined index: uploaded_by in <b>/var/www/html/src/core/Directus/Database/TableGateway/RelationalTableGateway.php</b> on line <b>1793</b><br />
<br />
<b>Notice</b>:  Undefined index: uploaded_by in <b>/var/www/html/src/core/Directus/Database/TableGateway/RelationalTableGateway.php</b> on line <b>1793</b><br />
<br />
<b>Notice</b>:  Undefined index: uploaded_by in <b>/var/www/html/src/core/Directus/Database/TableGateway/RelationalTableGateway.php</b> on line <b>1793</b><br />
<br />
<b>Notice</b>:  Undefined index: uploaded_by in <b>/var/www/html/src/core/Directus/Database/TableGateway/RelationalTableGateway.php</b> on line <b>1793</b><br />
<br />
<b>Notice</b>:  Undefined index: folder in <b>/var/www/html/src/core/Directus/Database/TableGateway/RelationalTableGateway.php</b> on line <b>1793</b><br />
<br />
<b>Notice</b>:  Undefined index: folder in <b>/var/www/html/src/core/Directus/Database/TableGateway/RelationalTableGateway.php</b> on line <b>1793</b><br />
<br />
<b>Notice</b>:  Undefined index: folder in <b>/var/www/html/src/core/Directus/Database/TableGateway/RelationalTableGateway.php</b> on line <b>1793</b><br />
<br />
<b>Notice</b>:  Undefined index: folder in <b>/var/www/html/src/core/Directus/Database/TableGateway/RelationalTableGateway.php</b> on line <b>1793</b><br />
<br />
<b>Notice</b>:  Undefined index: folder in <b>/var/www/html/src/core/Directus/Database/TableGateway/RelationalTableGateway.php</b> on line <b>1793</b><br />
<br />
<b>Notice</b>:  Undefined index: folder in <b>/var/www/html/src/core/Directus/Database/TableGateway/RelationalTableGateway.php</b> on line <b>1793</b><br />
```

## Expected Behavior
I expect to receive the API results without the errors appended.

## Actual Behavior
I receive the API results, with errors appended to the end.

## Other Context & Screenshots
This was an upgrade from Directus v6 so I don't know if that has anything to do with it. I am running in "staging" mode... in "production" mode this does not occur. I verified the `directus_files` table does contain the `uploaded_by` and `folder` columns.

## Technical Details
Using https://github.com/directus/docker with Amazon RDS Aurora MySQL database.

**Comment by WellingGuzman** [comment]
Hey @computerwizjared can you share a database dump so I can try to reproduce this?

It was originally posted here: https://github.com/directus/api/issues/584, I closed that one due to inactivity.

**Comment by computerwizjared** [comment]
Hey @WellingGuzman sorry, I just tried to reproduce this again and it isn't seeming to happen. We moved our production Directus instance over to 7 over the weekend and re-built the tables, including the directus_files table, so maybe it was just something I missed in the first upgrade we did for our test environment. Thank you for your help!

**Comment by WellingGuzman** [comment]
Thanks for the update @computerwizjared! If by any chance it happens again, don't hesitate in letting us know.
