### ISSUE TITLE
Can't update My Profile without full update access to directus_users

### ISSUE THREAD

**Issue by KnowHowHere** [directus/api#723]
# Bug Report

## Steps to Reproduce

1. Create new role with system defaults
2. Create new user and assign to role
3. Login as new user and try to update My Profile
4. See error:

Updating item from "directus_users" collection was denied

## Expected Behavior
Can update self without "Full" update access to directus_users

## Actual Behavior
Get above error.  After updating permissions to allow Full update access it works, but then of course the user can update everyone.

## Technical Details

- Device: Desktop
- OS: OSX
- Web Server: NGINX
- PHP Version: 7.3
- Database: MariaDB
- Install Method: cloned `master` branch [c6b1ed8]

**Comment by WellingGuzman** [comment]
This is related to this one https://github.com/directus/api/issues/627.

Issue with system collection and `mine` permissions.

**Comment by KnowHowHere** [comment]
ok, I have hit that issue too.  Please let me know if there's anything I can do to help triage.

**Comment by aiomaster** [comment]
Hi, just in case it helps - I have exactly the same problem. I have non admin user that has the role with id=4.
The permissions are:
```
mysql> SELECT * FROM directus_permissions WHERE role=4 AND collection='directus_users';
+----+----------------+------+-----------+--------+------+--------+--------+---------+---------+----------------------+-----------------------+------------------+
| id | collection     | role | status    | create | read | update | delete | comment | explain | read_field_blacklist | write_field_blacklist | status_blacklist |
+----+----------------+------+-----------+--------+------+--------+--------+---------+---------+----------------------+-----------------------+------------------+
| 36 | directus_users |    4 | active    | none   | full | mine   | mine   | none    | none    | NULL                 | NULL                  | NULL             |
| 37 | directus_users |    4 | deleted   | none   | none | none   | none   | none    | none    | NULL                 | NULL                  | NULL             |
| 38 | directus_users |    4 | draft     | none   | none | none   | none   | none    | none    | NULL                 | NULL                  | NULL             |
| 39 | directus_users |    4 | invited   | none   | none | none   | none   | none    | none    | NULL                 | NULL                  | NULL             |
| 40 | directus_users |    4 | suspended | none   | none | none   | none   | none    | none    | NULL                 | NULL                  | NULL             |
+----+----------------+------+-----------+--------+------+--------+--------+---------+---------+----------------------+-----------------------+------------------+
```
so he should definitly be able to upgrade his own record.
But everytime the user tries, he gets:
`Updating item from "directus_users" collection was denied`

I am using the latest docker version of app (currently 7.0.18) and api (currently 2.0.18).
Can I do something to help testing?

**Comment by verbman** [comment]
I have also experienced precisely the same issue as described by @aiomaster and my permissions table looks exactly the same.
