### ISSUE TITLE
Can't alter TEXT fields

### ISSUE THREAD

**Issue by KnowHowHere** [directus/api#727]
# Bug Report

## Steps to Reproduce

1. Create a collection
2. Add a TEXT field (e.g. use code interface)
2. Edit the above field and try an make it TINYTEXT
3. See Display Error:
  Trouble processing request. Try again after refreshing the page.
4. See Console Error:
```
{
  "error": {
    "code": null,
    "message": "SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '(65535)' at line 2",
    "class": "PDOException",
    "file": "/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Connection.php",
    "line": 379
  }
}
```

## Expected Behavior
Should be able to alter TEXT fields in MariaDB

## Actual Behavior
The (65535) in the error is Directus trying to execute:

```
"ALTER TABLE `test` CHANGE COLUMN `text_col` `text_col` TINYTEXT(65535)
```
MariaDB doesn't allow sizes when creating/altering any TEXT fields (TINY, MEDIUM, LONG, etc).

My hack is as follows:

```
--- a/src/core/Directus/Database/Schema/SchemaFactory.php
+++ b/src/core/Directus/Database/Schema/SchemaFactory.php
@@ -234,9 +234,12 @@ class SchemaFactory
         $connection = $this->schemaManager->getSource()->getConnection();
         $sql = new Sql($connection);
 
+       // MariaDB doesn't like sizes for TEXT (tiny, medium, long, etc) columns
+       $_ = preg_replace("/TEXT\([^)]*\)/","TEXT",$sql->buildSqlString($table));
+
         // TODO: Allow charset and comment
         return $connection->query(
-            $sql->buildSqlString($table),
+            $_,
             $connection::QUERY_MODE_EXECUTE
         );
     }
```
## Technical Details

- Device: Desktop
- OS: OS X
- Web Server: NGINX
- PHP Version: 7.3
- Database: MariaDB
- Install Method: cloned `master` branch [c6b1ed8]

**Comment by WellingGuzman** [comment]
I believe this is related with https://github.com/directus/api/issues/696. Oddly the API didn't catch the `length` and throw an exception.

Thanks for reporting this @KnowHowHere

**Comment by KnowHowHere** [comment]
Hi @WellingGuzman, let me know if I can help.  I probably can't help resolve it, as the code in the bug description was my sloppy best effort at overcoming it, but if you need more information please let me know.

**Comment by WellingGuzman** [comment]
This seems to happen on both MariaDB and MySQL. These fields that doesn't need length, should ignore these values and we could avoid this issue.
