### ISSUE TITLE
Allow read permission = mine/role on directus_users

### ISSUE THREAD

**Issue by KnowHowHere** [directus/api#728]
# Feature Request
I see from the API docs that full read access is required for all roles on the directus_users table, but I can't find any discussion as to why this is?  Is this a problem to be solved or a design decision?

## What problem does this feature solve?
For privacy reasons it would be good if it was possible to allow "mine" and "role" read permissions on directus_users so that users on the system couldn't browse the personal details of other users.

## How do you think this should be implemented?
Not sure as I'm not sure why this is in place at the moment.

## Would you be willing to work on this?
Yes, if it's something that can be "fixed"

**Comment by WellingGuzman** [comment]
Hey @KnowHowHere, Where does it say this about the full read access in the docs? Also what was done that the `mine` and `role` read permission wasn't granted?

Both `mine` and `role` should be working for users.

**Comment by KnowHowHere** [comment]
Hi @WellingGuzman, I might have been conflating this issue with the inability to edit yourself or clone items in the App, without full update rights to users.

Please close this issue. When updating permissions in the database directly (rather than through the app) I can set read access on the users table to "mine" and login and query as normal.  I can't update myself, but that's another issue.

Is this something that might have been resolved in a recent release? if it has maybe you can remove the reference I referred to in the docs, unless I'm misinterpreting that?

**Comment by WellingGuzman** [comment]
I believe the app should allow this permission on `directus_users`, let's ask @rijkvanzanten to see if there's a reason for full permission on users.

**Comment by benhaynes** [comment]
🔔 @rijkvanzanten

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
