### ISSUE TITLE
API fails when relationship has conflicting name

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#730]
# Bug Report

When a many to one is created where the field name also exists in the related table, the api stops returning the values for the related collection.

If you have the following setup:

```
broken_a
--------------------
id
text (varchar)

broken_b
--------------------
id
text (m2o)
```

```
relationship
--------------------
collection_many: broken_b
field_many: text
collection_one: broken_a
```

fetching items from `broken_a` directly now doesn't return any values anymore.

## Other Context & Screenshots

I've provided an empty DB setup with an example of a working relationship and a broken one.

[tables_dump_January_25_2019.sql.txt](https://github.com/directus/api/files/2797054/tables_dump_January_25_2019.sql.txt)

## Technical Details

API v7.0.15

**Comment by WellingGuzman** [comment]
I tested this locally, and it's working as expected. I cannot reproduce this issue.

Result:

```
GET http://localhost/_/items/broken_a

{
    "data": [
        {
            "id": 1,
            "text": "Item 1"
        },
        {
            "id": 2,
            "text": "Item 2"
        },
        {
            "id": 3,
            "text": "Item 3"
        }
    ]
}
```

```
GET http://localhost/_/items/broken_b

{
    "data": [
        {
            "id": 1,
            "text": 1
        },
        {
            "id": 2,
            "text": 2
        }
    ]
}
```

```
GET http://localhost/_/items/broken_b?fields=*.*

{
    "data": [
        {
            "id": 1,
            "text": {
                "id": 1,
                "text": "Item 1"
            }
        },
        {
            "id": 2,
            "text": {
                "id": 2,
                "text": "Item 2"
            }
        }
    ]
}
```

**Comment by WellingGuzman** [comment]
Oh!

```
GET http://localhost/_/items/broken_a?fields=*.*

{
    "data": [
        {
            "id": 1,
            "text": null
        },
        {
            "id": 2,
            "text": null
        },
        {
            "id": 3,
            "text": null
        }
    ]
}
```

I believe this is the one you are talking about.

**Comment by rijkvanzanten** [comment]
Yes!

**Comment by WellingGuzman** [comment]
This was fixed by https://github.com/directus/api/commit/47d6aa34d44e8818c3c783b33bc26714cab52ecb

By also checking that the field's collection name is the same as the relation's collection.
