### ISSUE TITLE
Support public folder in different location than api basepath

### ISSUE THREAD

**Issue by dur41d** [directus/api#732]
# Feature Request

Currently the api expects the folder structure to be: $basePath . '/public' for the public folder. It would be nice not to make this assumption and allow different paths for the public folder. This is useful in shared hosting where the user doesn't have have the choice of setting the root folder.

## What problem does this feature solve?

I'm using share hosting which gives me the following structure:

/home
   /public  -- this is the path of the root website /
  /protected  -- these are files available to the website but not accessible directly

if I put the api folder in public then my api url will be:

/api/public

Also all the files in the api (ex. schema.sql ) will be exposed to the public which is not desirable. Also I would like to reserve the root of the website to my frontend (the actual website).

I would like put the api in the following locations:

/home
   /public/api -- the 'api' here is the public folder so that the URL for the api is http:/mydomain.com/api
   /protected/api -- the 'api' is the base folder that contains all the files except for the public folder

This way all the non public api files are protected.

To do that is I set the  the path in public/index.php to 
$app = require '/home/protected/api/src/web.php';

however the public folder is hard coded in several locations like src/core/Directus/Services/InterfacesService.php (line 16):

$basePath . '/public/extensions/core/interfaces',

## How do you think this should be implemented?

Make the public folder path optionally configurable in api.config.

## Would you be willing to work on this?
My php is not that good.

**Comment by WellingGuzman** [comment]
We've been thinking of this for a while. This ticket: #168 has is the goal.

At the moment there's not "official" way of doing this. I will keep an eye on this ticket, there has been similar request before.

> Make the public folder path optionally configurable in api.config.

That's a good idea.

**Comment by dur41d** [comment]
BTW, in my opinion this is an important feature because as it is the API can only be hosted at the root of the domain which means that any cms project (website) need to dedicate a separate domain for the api and another for the actual website.

**Comment by benhaynes** [comment]
This is an important feature to get working. I'm aggregating all related tickets into one place:

https://github.com/directus/api/issues/636

I'll close this as a duplicate, but will copy over the important info so it's more easily accessible.

**Comment by piotr-cz** [comment]
At first sight it looks like it should be possible as all classes which use hardcoded `/public` subdir, have also access to global container.
