### ISSUE TITLE
[v2.0.16] missing data length in query string when alter column

### ISSUE THREAD

**Issue by gnh1201** [directus/api#741]
## step by step

'Admin setting' -> 'Collection and fields' -> choose collection -> choose field -> edit default value in schema tab -> click done -> see error

## actually behaviors

on /_/fields/receipts/currency

execute with v2.0.14 (successfully query, but with issue #740):
```
ALTER TABLE `receipts`
   CHANGE COLUMN `currency` `currency` **VARCHAR(201)** DEFAULT 'KRW'"
```

execute with v2.0.16 (invalid query: missing data length #741):
```
ALTER TABLE `receipts`
  CHANGE COLUMN `currency` `currency` **VARCHAR** DEFAULT 'KRW'
```
As a result,
```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'DEFAULT 'KRW'' at line 2
```

## versions
- PHP Version 7.0.0p1
- 10.0.21-MariaDB, for Linux (x86_64)

**Comment by WellingGuzman** [comment]
The fix was included in the [2.0.17](https://github.com/directus/api/releases/tag/v2.0.17) release.
