### ISSUE TITLE
Search using (q) parameter could match a field partially, not exactly

### ISSUE THREAD

**Issue by ondrakoupil** [directus/api#743]
# Feature Request
When using "q" parameter (usually using a search field in header bar of directus app), only rows with a field that exactly matches the searched string is returned. However, in practical life, it would be better if field would be matched partially. 

Example: In demo, collection "Movies": https://directus.app/#/collections/movies
Try searching "Years". I expect the movie "18 Years Later (Diciotto anni dopo)" to be found, but no result is returned.

It can be bypassed by using a field filter using "contains" mode, however that is more difficult and less intuitive.

## What problem does this feature solve?
It is a UX improvement. Users usually expect these "quick search fields" to work this way.

## How do you think this should be implemented?
The DB query would be constructed using `field LIKE "%VALUE%"` instead of `field = "VALUE"`. Or at least for text fields.

## Would you be willing to work on this?
I could probably do this, however an experienced directus developer would do this way faster.

**Comment by WellingGuzman** [comment]
Thanks for reporting this, this is a bug, it has supposed to work this way.

This bug was created while implementing raw like operator/filter.

Ref: https://github.com/directus/api/commit/7eca9d9943770f7699f1e1f1c2ea9ed5266670a7

**Comment by WellingGuzman** [comment]
This bug has been fixed by https://github.com/directus/api/commit/b8c0cdda4293d3c41cc16a0ac5444435250dffad
