### ISSUE TITLE
Undefined error on api requests 

### ISSUE THREAD

**Issue by rjwismar** [directus/api#748]
# Bug Report

I have in the error.log sometimes a SQL error.

[2019-02-02 18:14:37] api[_].ERROR: Zend\Db\Adapter\Exception\InvalidQueryException: Statement could not be executed (22001 - 1406 - ) in /var/www/api.ssb-festival.de/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:244

The error always occurs twice in a row, but instead of not writing any data, because it is an SQL error, the API writes the record twice to the database.

In the Activity Log it says that the record was added outside of Directus instead of the user who created it.

## Technical Details

- Device: undefined
- OS: undefined
- Web Server: [nginx 1.12.x]
- PHP Version: [7.2.x]
- Database: [MySQL 5.6]
- Install Method: [cloned `master` branch]

**Comment by WellingGuzman** [comment]
We would need more information how to reproduce this in order to fix it.

- Can you show us the complete error log stack-trace?
- When this is happening?

**Comment by WellingGuzman** [comment]
@rjwismar Thanks for the complete log.

Can I get a database dump so I can use to reproduce this?

As the error is not caught by Directus, I also need to know what is the request from angular (including its payload) that use that throws this error.

**Comment by rjwismar** [comment]
I have sensitive data in this database, I can send you the dump privately.

Unfortunately I do not know the exact payload, which is sent by public users. Unless you know a way to record the payload from nginx.

**Comment by WellingGuzman** [comment]
You can send it to me via Slack, you can get a invitation here: https://slack.getdirectus.com.

If you don't know the payload can you show me the code that triggers the request? What are you trying to create? From the logs it seems this error happens trying to create an item.

**Comment by WellingGuzman** [comment]
Based on the error code (`22001 - 1406`), which means `Data too long for column x`, the error is related to a column that cannot store the data being sent.

There's nothing we can do for this error rather than create a friendly error message.

@rjwismar let me know if this seems to be the problem in your case. Does this happen to one collection in specific? or any table with huge fields or lots of fields when you create or update?

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
