### ISSUE TITLE
Fix encoded urls

### ISSUE THREAD

**Issue by WellingGuzman** [directus/api#75]
When sending a encoded url Directus doesn't decode it.

Ex: `/_/items?fields=%2A.%2A`

**Comment by rijkvanzanten** [comment]
Note: only happens when Apache's mod_rewrite encodes an encoded file

**Comment by WellingGuzman** [comment]
This won't be fixed when doubled encoded.

Sending encoded query parameters works, the issue here is that the web server encodes the encoded parameters again, encoding the original value twice.

If there's a good reason why we should make sure to double decode those value on Directus side let's discuss it, but I believe this is not a good solution. those value can be encoded three times too, and Directus still won't decode it correctly, and it goes on.
