### ISSUE TITLE
Discuss date format parameter

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#751]
I was reading this article https://medium.com/@toastui/handling-time-zone-in-javascript-547e67aa842d that raised a couple good points about the risks of relying solely on ISO-8601, and I remember someone on Slack mentioning that the time conversion was particularly tricky on Android. 

Should we add a dateformat parameter that allows the user to signal to the API to return the data in Unix timestamps instead of the ISO format? I think we should allow both, so this would be an addition instead of a breaking change.

Thoughts @WellingGuzman, @benhaynes?

**Comment by rijkvanzanten** [comment]
(Seeing that this would be timezone agnostic, I'm also hoping it will prevent more timezone errors from happening on the client side)

**Comment by WellingGuzman** [comment]
I like this. I don't know what would be the best way to do this. Query String? field options? project configuration? or all options?

**Comment by benhaynes** [comment]
I'm no expert in this matter, but I think that's a great idea. Timezones have been a tricky thing since the beginning, so having multiple options for saving datetimes agnostically seems like a good move as long as we can maintain our current way and avoid a breaking change.

The most important thing when having _multiple_ options like this is defaults and documenting... so that our users don't get even more confused when trying to decide between the options.

**Comment by WellingGuzman** [comment]
One important thing is that the timezone will be lost, unless this option append the timezone somewhere in the response, or based it on the field type (system are UTC), there will be no way to tell if it's UTC or server time,

**Comment by rijkvanzanten** [comment]
> I don't know what would be the best way to do this. Query String? field options? project configuration? or all options?

Good point. I think we should keep the current way of doing things as the default so we don't introduce a breaking change. I was thinking we could have a `?dateformat=iso-8601` (default) / `?dateformat=unix` query parameter that would make the api return it in either format.

> One important thing is that the timezone will be lost, unless this option append the timezone somewhere in the response

Good point. Is there anything we can do to make sure that the API returns Unix in UTC at all times? I guess we don't necessarily know when something was saved in UTC vs non-UTC right?

Although, if the app would send everything in Unix, the API would save everything 1-1 in Unix and would return it in Unix, there shouldn't be any timezone conversions at all which could / should work? 🤔

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
