### ISSUE TITLE
Issues going back to edit a field

### ISSUE THREAD

**Issue by shealavington** [directus/api#752]
# Bug Report

**1: Can't update the "note / comment" on a field after it's been set once**

*Replicate*
1) Create a field with a comment
2) Go back to the field and try to edit the comment
3) Get a SQL error in console

*Expected*
1) "Note/Comment" should've been updated.

---

**2: Can't update the "required" on a field after it's been set once**

*Replicate*
1) Create a collection with a text field that's not required
2) Try to edit that new field to make it required
3) Get a 500 error in console without any on-screen errors that something went wrong.

*Expected*
1) "Required" should've been updated.

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Web Server: [eg: Apache 2.4.37]
- PHP Version: 7.1.0
- Database: [eg: MySQL 8.0.12]
- Install Method: cloned `master` branch

**Comment by WellingGuzman** [comment]
@shealavington can you share logs in the api? Could this be the same as #758?

**Comment by WellingGuzman** [comment]
I don't know what are the logs in these errors, but I am starting to believe these are related to #758, which was already fixed in API `2.0.17`.

**Comment by theharshin** [comment]
Hey, @shealavington 
I see both the issues are fixed/not reproducible on the latest version. Feel free to open the issue if it persists at your end. Closing this for now. Thanks 🙂
