### ISSUE TITLE
Tags isn't working

### ISSUE THREAD

**Issue by kamlekar** [directus/api#753]
# Bug Report

## Steps to Reproduce

1. Create a collection.. "Blogs"
2. Add some fields
3. Add a blog entry
4. Then add a new field of type "tag"
5. Try to edit the existing entry and add some tags
6. Try to save the entry

## Expected Behavior
New blog entry should be created

## Actual Behavior
When clicked on "Save" button.. nothing happening. When I open console, I saw the following error:

![image](https://user-images.githubusercontent.com/2201186/52401148-06b75180-2ae7-11e9-8ea3-ac721da6f1b0.png)

## Other issues:

I am seeing issues for the following steps as well

1. Create a collection.. "Articles"
2. Add a field of type "tags"
3. Add a new entry.. save
4. Try to revisit the entry

## Expected behavior:

User should go in edit mode of the entry

## Actual behavior

User is unable to go inside the entry

**Comment by WellingGuzman** [comment]
Hey @kamlekar, can you please look at the `logs` directory and share the logs if there's any?

**Comment by benhaynes** [comment]
I have followed these steps and the tags interface is working for me. Perhaps this error is from something else in your config/setup?

As Welling said, logs help... or a database dump would be ideal!

**Comment by theharshin** [comment]
Hi @kamlekar, closing this issue as it is not reproducible at our end. Feel free to open a new issue with more details & logs if possible. Thanks.
