### ISSUE TITLE
Method not allowed

### ISSUE THREAD

**Issue by jdiericks** [directus/api#755]
## Version Info
  - Directus API version (Or commit hash): **v7.0.16**
  - PHP version: **7.2**
  - MySQL version: **5.7.25**
  - Web server: (Ex. Apache, nginx or IIS?) **nginx**
  - OS name and version: **Ubuntu 16.04 LTS**

Greetings,

This is a fresh install for me, so far I have been able to install everything correctly enough to be able to login.

However,  when I attempt to upload a image or try to save any kind of change I get the following errors:

PATCH /_/users/1/tracking/page 405 (Method Not Allowed)
Uncaught (in promise) {code: 6, message: "Method Not Allowed"}

My initial idea is there is something wrong with my server config.

Here is my .conf file for this site:

```
server 
{


listen 80;

listen [::]:80;

	


root /var/www/dir-app/public;

	

index index.php index.html index.htm index.nginx-debian.html;

	

server_name sys.thewb.co www.sys.thewb.co;
	

	

disable_symlinks if_not_owner;


location /admin {
    
rewrite ^/admin/(.*) /admin/index.html last;
}



location / {
    try_files $uri $uri/ /index.php$args;
}



location /thumbnail {
    rewrite /thumbnail/(.*) /thumbnail/index.php last;
}



location ~* /uploads/([^/]+)/originals/(.*) {
    
add_header Cache-Control "max-age=31536000";
}




location ~* /uploads/.*\.(php|phps|php5|htm|shtml|xhtml|cgi.+)?$ {
  add_header Content-Type text/plain;
}




	
		

location ~ \.php$ {
		
include snippets/fastcgi-php.conf;
	
fastcgi_pass unix:/run/php/php7.2-fpm.sock;
		
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}

	


location ~ /\.ht {
	
	deny all;
	
}


}

```

Any ideas?

**Comment by benhaynes** [comment]
🔥🥔

**Comment by WellingGuzman** [comment]
This error seems to be a issue with CORS. When the browser make a preflight request, and CORS is not enabled, the API will throw a method not allowed error.

Can you check your CORS configuration are set correctly in your project configuration?

**Comment by rijkvanzanten** [comment]
@WellingGuzman That wouldn't return the API error object though. In the example above, it looks like the API is returning the 405, based on the fact that the error code exists: `{code: 6, message: "Method Not Allowed"}`

**Comment by WellingGuzman** [comment]
@rijkvanzanten I wasn't clear, I didn't meant directly with CORS or the browser, but the API not having CORS enabled throws this error, as the browser request `OPTIONS http://directus/_/items/users/1`, and because there's no a endpoint that allows `OPTIONS`, the API will throw a "Method Not Allowed" error, unless CORS is enabled.

**Comment by jdiericks** [comment]
@WellingGuzman I made a fresh install this time with a lamp stack. I still get the same error, I am using the default config file generated from the wizard.

Here is the sample:
```
'cors' => [
    'enabled' => true,
    'origin' => ['*'],
    'methods' => [
        'GET',
        'POST',
        'PUT',
        'PATCH',
        'DELETE',
        'HEAD',
    ],
    'headers' => [],
    'exposed_headers' => [],
    'max_age' => null,
    'credentials' => false,
],
```

**Comment by jdiericks** [comment]
@WellingGuzman Thank you for your help, but it seems I have found my solution. There seems to be some interference from the network at my job as I can correctly do everything on a device not connected to the network.

**Comment by WellingGuzman** [comment]
Thanks for the update @jdiericks.
