### ISSUE TITLE
Embeds (Files) not working

### ISSUE THREAD

**Issue by benhaynes** [directus/api#757]
Posting a YouTube embed to the API (see request below) I am seeing a few issues:

* The `directus_files.embed` is not saving (eg: `dQw4w9WgXcQ`)
* The MIME type is saving as an image (`image/jpeg`) but it should be `embed/youtube`
* We don't need a checksum of embeds

@rijkvanzanten @WellingGuzman  thoughts on the MIME type?

```
POST /_/files HTTP/1.1
Authorization: Bearer demo
Content-Type: application/json
Host: local.api.com
Connection: close
User-Agent: Paw/3.1.8 (Macintosh; OS X/10.14.2) GCDHTTPRequest
Content-Length: 85

{
  "filename": "test.jpg",
  "data": "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
}```

**Comment by WellingGuzman** [comment]
the `type` value should be `embed/youtube`.

**Comment by WellingGuzman** [comment]
I have a question, what about the other data, such as `filesize`, `width`, `height`? the file record references the thumbnail rather than the embed, so all those other info should be related to the image instead?

**Comment by benhaynes** [comment]
They should not be for the thumbnail... we can leave them blank, or if they have the YouTube API Key then we can get width/height (not filesize though).
