### ISSUE TITLE
API returns thumbnail urls for non-image files

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#760]
I uploaded a PDF into Directus. The API will return the thumbnail paths as defined in directus_settings, however, the actual thumbnails are a 404 not found for pdf files.

**Comment by WellingGuzman** [comment]
What do you think should be best here: `null` or empty array (`[]`)? I prefer `null` as to me it seems to mean, "there wasn't suppose to be something here", same with `embed=null` when it's not an embedded file.

**Comment by benhaynes** [comment]
Let's do `null`... that seems to make more sense.

**Comment by WellingGuzman** [comment]
This was fixed by https://github.com/directus/api/commit/bd05cfa8ecc8de60896915f166b2bad68e986359.

All non-image files will return `thumbnails=null`, except `embed/` types files which technically are not images, but they point to a image file.
