### ISSUE TITLE
Steps for adding a new project manually

### ISSUE THREAD

**Issue by kubowler99** [directus/api#767]
Not an issue, just a question - 

What are the steps to create a new project manually?

Is it simply:

- Create a new config/api.<project-name>.php file
- Update public/admin/config.js to reflect the new api url
- Update the .gitignore file to exclude the newly created config/api.<project-name>.php file
- Execute the src/schema.sql script against the new database for your new project

Assume latest version of Directus and mysql databases, current version of php, etc.

**Comment by rijkvanzanten** [comment]
That sounds about right!

> Update the .gitignore file to exclude the newly created config/api..php file

I don't think this is necessary, as everything is ignored by default except for the migrations and sample files 🙂

**Comment by kubowler99** [comment]
Ok, and that's what I thought as well. But what I'm seeing is whey attempting to log in to the newly created project for the first time as 'admin@example.com', I'm getting 'user not found' error in the browser console (I've verified the user table in the mysql database does contain the admin@example.com user. 

I'm also getting a 500 internal server error in the console as well. 
<img width="1432" alt="directus-errors" src="https://user-images.githubusercontent.com/11196351/52711382-4b177700-2f57-11e9-9238-3eacc9975398.png">

I'm just not clear on what I've missed/done incorrectly.

**Comment by rijkvanzanten** [comment]
Hmm not too sure what's causing that.. Do you mind opening a new ticket for that issue specifically? A 500 internal should never happen. It would help a lot if you could share a dump of the database and what tech stack you're using too 🙂

**Comment by benhaynes** [comment]
I'd love another set of eyes on this, but I've created a new "Projects" guide to start organizing info.

https://docs.directus.io/guides/projects.html

🔔 @rijkvanzanten
