### ISSUE TITLE
Oauth using auth0.com

### ISSUE THREAD

**Issue by maxsivanov** [directus/api#768]
# Feature Request

Add support for Auth0 oAuth provider

## What problem does this feature solve?
Many companies use Auth0 as provider.

## How do you think this should be implemented?
Same as OKTA integration

## Would you be willing to work on this?
I can participate as far as I know modern PHP

**Comment by benhaynes** [comment]
@WellingGuzman any initial thoughts on how difficult this would be to implement?

**Comment by WellingGuzman** [comment]
There's already a provider for auth0 in the [oauth-client providers list](https://github.com/thephpleague/oauth2-client/blob/master/docs/providers/thirdparty.md#third-party-providers). It should be straightforward to implement it.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
