### ISSUE TITLE
DISCUSSION: Add filters for update endpoints

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#77]
## Description
What if we could also update items by providing a filter instead of a (set of) primary-key(s)?

In SQL for example, you could update items `where title = 'title'` etc. This could potentially work in the URL endpoints too as follows:

`PUT /items/projects?filter[title][eq]=title` (or `PATCH` for that matter)

## Usecase
I ran into this need just now when working with bookmarks. A bookmark should update a record in `directus_collection_presets` where the user ID is that of the user and where the title is not null. In order to do this now, I have to `GET` the collection presets first to retrieve the primary key, followed by a `PUT` using this primary key in order to update the value. It would save me a step if I could `PATCH /collection_presets?filter[title][nnull]=1&filter[user][eq]=12`.

**Comment by rijkvanzanten** [comment]
How do you guys feel about this @WellingGuzman @benhaynes ?

**Comment by benhaynes** [comment]
This is essentially a batch edit through filters instead of PK? I really like the idea as it gets us closer to SQL commands without opening things up to injection.

**Comment by rijkvanzanten** [comment]
Yep, that's exactly it!

**Comment by WellingGuzman** [comment]
This is really great idea, maybe batch should work like this, `DELETE`, `PATCH`, `GET` (actually works like this), and `POST` should accept filters.

**Comment by rijkvanzanten** [comment]
What would post do with filters?

**Comment by WellingGuzman** [comment]
Oh my bad, I just meant "use it everywhere", and got carried away. I don't see any usage on `POST`. I do for the others.

**Comment by rijkvanzanten** [comment]
Gotcha 😉

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
