### ISSUE TITLE
Add `slug` and `hash` field types

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#775]
# Feature Request

Add field types for slug and hash that will automatically validate / generate a slug / hash.

## What problem does this feature solve?

Right now, the slug and password / hash interfaces respectively have hooks for this system functionality. While interfaces still need to be able to have hooks, we'd like to move the core app interfaces into the app repo, to get rid of all the confusion that currently exists in this split.

NOTE: Custom interfaces will still live in the api and remain unchanged.

## How do you think this should be implemented?

Similar to the existing field types. The only thing that would be a nice to have if the types could use the options in the database to set things like field-to-mirror (slug) and hashing method (hash)

**Comment by benhaynes** [comment]
@WellingGuzman — status of this?

**Comment by WellingGuzman** [comment]
@benhaynes starting to work on it. I was working with https://github.com/directus/api/issues/707 and https://github.com/directus/api/issues/689.

**Comment by WellingGuzman** [comment]
Two new data types has been added `slug` and `hash` by https://github.com/directus/api/commit/686a2a7161a03949e2cf12635a69e541186920a2.

The `slug` interface uses [cocur/slugify](https://github.com/cocur/slugify) package, and any of its options can be used. There's a two options that came from the `slug` interface, `mirroredField` and `forceLowercase`. `forceLowercase` has priority over `lowercase` (which both do the same thing). `MirroredField` is the field the slug field is converting its value into a slug-type value.

If the `slug` type has value in the payload it will ignore the `mirroredField` value.

**Comment by sumberacstefano** [comment]
hi, is there a way in which Directus auto-generates slug based on title? I want to add field "slug" inside a collection which will be auto-generated base on "input field" called "title".

**Comment by sumberacstefano** [comment]
> hi, is there a way in which Directus auto-generates slug based on title? I want to add field "slug" inside a collection which will be auto-generated based on "input field" called "title". @rijkvanzanten

https://www.npmjs.com/package/directus-extension-wpslug-interface
Found this extension. Would be great if you can **add** this in **Directus** **in next release**, also **slug** should be **unique by default**

**Comment by rijkvanzanten** [comment]
@sumberacstefano v8 had the slug capabilities built in. If you're asking about v9 support, please use the [`directus/directus`](https://github.com/directus/directus/discussions/new) repo 👍🏻
