### ISSUE TITLE
Provide UI for password reset

### ISSUE THREAD

**Issue by samvasko** [directus/api#776]
# Feature Request
Create a UI for the password reset feature so when you click on the link in the email you see something like:

> A new password was sent to your email address.

## What problem does this feature solve?
Its confusing to just see `{public: true}` when clicking on the password reset field.
![screen shot 2019-02-14 at 14 48 55](https://user-images.githubusercontent.com/2674600/52871828-db65df80-3142-11e9-92cf-0f7f56af691d.png)

## How do you think this should be implemented?
By adding a user interface 

## Would you be willing to work on this?
Yes

**Comment by rijkvanzanten** [comment]
@WellingGuzman Can this redirect back to the application URL?

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by dev7ch** [comment]
this is a bit more a bug then an feature request i would say.

How this should be working?
Was this implemented and working already in previous version?
Is the a work around example to use a detached form for example?

**Comment by rijkvanzanten** [comment]
The API should redirect to the application with a query string indicating that the password has been reset. The application can in turn use that to render a UI with a success message.

**Comment by dev7ch** [comment]
ok thank you but how does the input of a new password should happen?

**Comment by dev7ch** [comment]
ahh ok sorry, referring to the docs theres is no possibility to enter a new password. 
you only confirm the request.

**Comment by benhaynes** [comment]
@bjgajjar — any idea how complex this one is? Let's assume that we just need the API to redirect to the App with a query string letting it know that the password has been reset/updated (and maybe the user?).
