### ISSUE TITLE
Groups Param Not Working

### ISSUE THREAD

**Issue by samcus** [directus/api#777]
## Issue
Using the groups functionality as documented (https://docs.directus.io/api/reference.html#groups) leads to error 9 SQL error. Am I doing something wrong here?

## Version Info
  - Directus API version (Or commit hash): Directus Demo
  - PHP version: Directus Demo
  - MySQL version: Directus Demo
  - Web server: (Ex. Apache, nginx or IIS?) Directus Demo
  - OS name and version: Directus Demo

## Expected Behavior
```json
{
  "data": [
    {
      "state": "FL"
    },
    {
      "state": "AZ"
    }
  ]
}
```

## Actual Behavior
```json
{
  "error": {
    "code": 9,
    "message": "Failed generating the SQL query.",
    "query": "SELECT `theaters`.`id` AS `id`, `theaters`.`status` AS `status`, `theaters`.`name` AS `name`, `theaters`.`address` AS `address`, `theaters`.`city` AS `city`, `theaters`.`state` AS `state`, `theaters`.`zip` AS `zip`, `theaters`.`general_admission_price` AS `general_admission_price`, `theaters`.`matinee_price` AS `matinee_price`, `theaters`.`child_price` AS `child_price`, `theaters`.`senior_price` AS `senior_price`, `theaters`.`concession_screen_image` AS `concession_screen_image` FROM `theaters` WHERE `theaters`.`status` IN ('published', 'deleted', 'draft') GROUP BY `theaters`.`state` ORDER BY `theaters`.`id` IS NULL, `theaters`.`id` ASC, `theaters`.`id` ASC LIMIT 200 OFFSET 0"
  }
}
```

## Steps to Reproduce
 1. Go to https://next.demo-api.directus.app/_/items/theaters?groups=state

**Comment by WellingGuzman** [comment]
@samcus can you run the query directly in your database?.

In reality this `groups` param doesn't work as you expect it to be, grouping the result based on a field. It's rather a raw SQL command to just add `GROUP BY` blindly. This error is likely to be unmatched columns in `SELECT`, `ORDER BY` and `GROUP BY`. Check if you have `ONLY_FULL_GROUP_BY` mode enabled in your MySQL settings.

I will update the docs to clarify this.

**Comment by samcus** [comment]
@WellingGuzman I was just reading through the docs and testing things out on the Directus Demo API before I setup my own environment. So I can't verify that at this time. The docs definitely made it seem like I could group items by a field (but maybe I'm interpreting it incorrectly). Any field I try results in a similar error message to the one above.

**Comment by rijkvanzanten** [comment]
@samcus In your defense, the docs do literally state 

> The groups parameter allows grouping the result by one or more fields.

But the API will only pass the list to the GROUP_BY section of the SQL query and will therefore act more like de-dupe.

What were you trying to achieve?

**Comment by itsmerhp** [comment]
Hello @wellingguzman and @rijkvanzanten 
You are right, the issue is taking place due to ONLY_FULL_GROUP_BY restriction for MySQL version greater than 5.7.

References:
https://stackoverflow.com/questions/34115174/error-related-to-only-full-group-by-when-executing-a-query-in-mysql
https://stackoverflow.com/questions/41887460/select-list-is-not-in-group-by-clause-and-contains-nonaggregated-column-inc

**Comment by bjgajjar** [comment]
This can be solved as @itsmerhp suggested. Feel free to reopen :)
