### ISSUE TITLE
API should validate collection name

### ISSUE THREAD

**Issue by samvasko** [directus/api#779]
# Bug Report

## Steps to Reproduce

1. Go to create collection
1. Create collection with invalid name eg " " or " 34" 
3. API crashes and does not respond. 

On app the following error is shown
> Trouble processing request. Try again after refreshing the page.

## Expected Behaviour
Error is returned, validation is done on server and/or client side

## Actual Behaviour

API responds with "500 Internal Server Error" 

## Other Context & Screenshots

See mysql naming rules https://dev.mysql.com/doc/refman/8.0/en/identifiers.html
## Technical Details

api version - 4fe384ba271489e9b6be67ae8c18d52f60f45546

**Comment by samvasko** [comment]
I might have jumped the gun a bit here. I am getting correct error now. I guess the 500 could've been caused by some other cause.

**Comment by rijkvanzanten** [comment]
Can you accurately reproduce the 500 though? I'd love to find out what the cause is!

**Comment by samvasko** [comment]
No :(
