### ISSUE TITLE
Custom endpoints for page extensions

### ISSUE THREAD

**Issue by jorauch** [directus/api#780]
# Feature Request
For more complex page extensions it will be great to have custom endpoints/parameters too.

EXAMPLE
https://directus.app/#/ext/[custom-page]
https://directus.app/#/ext/[custom-page]/[id]
https://directus.app/#/ext/reports/
https://directus.app/#/ext/reports/1
https://directus.app/#/ext/reports/2
https://directus.app/#/ext/reports/3

## What problem does this feature solve?
Within the directus-app, such complex extensions can be created, and it is not necessary to create a standalone application.

## How do you think this should be implemented?
The existing "custom endpoints" would have to be expanded accordingly.

## Would you be willing to work on this?
As far as I can.

**Comment by rijkvanzanten** [comment]
Do you refer to custom endpoints in the API that the app can use? Or the ability to define sub-routes in the application itself?

The example URLs you provided suggest the second?

**Comment by jorauch** [comment]
I want the ability to define sub-routes after /ext so i can extend the custom page-extensions (like described here https://docs.directus.io/extensions/pages.html)

It may already be possible to extend the endpoints and I have not understood the documentation correctly (https://docs.directus.io/extensions/custom-endpoints.html). But I understand the documentation so that only "endpoints" can be extended after /custom at the moment. Right?

**Comment by benhaynes** [comment]
@rijkvanzanten @WellingGuzman 🔔

**Comment by rijkvanzanten** [comment]
Right now you can have sub-routes in custom API endpoints, but not in custom pages in the application. 

You can't define sub routes at the component level in vue-router (yet) https://github.com/vuejs/vue-router/issues/298 so I'll need to think about a way to implement a similar functionality by adding the routes programmatically using 
https://router.vuejs.org/api/#router-addroutes

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
