### ISSUE TITLE
Datetime doesn't allow milliseconds

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#782]
# Bug Report

Submitting `2019-03-01T19:47:00Z` works as expected, `2019-03-01T19:47:00.000Z` throws an error `date_time: This value is not a valid datetime.`

## Solution

I think an extra option needs to be added to this section:

https://github.com/directus/api/blob/0ff430f827335ddbda5505a630da3d045759a01a/src/helpers/all.php#L1712-L1811

**Comment by WellingGuzman** [comment]
Currently it doesn't support milliseconds, it couldn't either save those milliseconds to the `DATETIME` field in MySQL.

To support this it probably needs to support a string type for the DATETIME and save it as is.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
