### ISSUE TITLE
Cannot save item with datetime interface that set default to current time

### ISSUE THREAD

**Issue by KKAries** [directus/api#785]
# Bug Report

## Steps to Reproduce

1. Add a datetime field and set the "Default to current datetime" to true
2. Create an item and see the datetime field is set to the current time
3. Save the item
4. See the error "This value is not a valid datetime."

## Expected Behavior
Item saved successfully
## Actual Behavior
Cannot save item.
## Technical Details

API 2.0.18 and APP 7.0.18

**Comment by benhaynes** [comment]
Thanks @KKAries — we're on it!

**Comment by WellingGuzman** [comment]
Hey @KKAries, where is the "Default to current datetime" option? What is the value that the app sends to the API when the "This value is not a valid datetime." error is thrown?

**Comment by samvasko** [comment]
I can confirm the error exists. It's due to date format being different when default. The default date is in following format: 

> 2019-03-03T17:38:45.383Z]

resulting in the `{code: 4, message: "test: This value is not a valid datetime."}` error

When change is done, the format is changed to
> 2019-03-04 19:38:03

**Comment by samvasko** [comment]
Looks like symfony validator used supports only only one type of date

https://github.com/symfony/validator/blob/55a474b37a1e5e49fabfb872011425d4ab3057d3/Constraints/DateTime.php#L34
