### ISSUE TITLE
Upload a file receive 500 Internal Server Error

### ISSUE THREAD

**Issue by KKAries** [directus/api#786]
# Bug Report

## Steps to Reproduce

1. Login to Directus
2. Navigate to File Library Page
3. Click new
4. Drag a image to the Upload Files window
5. Error happens. 
Response error: 

```
{"error":{"code":9,"message":"Failed generating the SQL query.","query":"INSERT INTO `directus_files` (`type`, `filename`, `title`, `tags`, `description`, `location`, `charset`, `filesize`, `width`, `height`, `storage`, `checksum`, `uploaded_by`, `uploaded_on`) VALUES ('image\/png', 'test-1.png', 'Test 1', '', '', '', 'binary', '12454', '110', '80', 's3', '06c266c3d6783715c857b94ada48dfb5', '1', '2019-02-19 09:32:04')"}}
```

## Expected Behavior
File can be saved.
## Actual Behavior
Upload file doesn't work.
## Technical Details

APP 7.0.18 and API 2.0.18

**Comment by WellingGuzman** [comment]
Did you upgrade the database schema? There's a new field in `directus_files` named `checksum`.

Run the command below to add the missing field, it should be working after the upgrade.

```
bin/directus db:upgrade
```

**Comment by KKAries** [comment]
@WellingGuzman You're right. The upload now works. Thanks.

**Comment by creazy231** [comment]
Ran the command above and also checked the database for the `checksum` field but every time I want to save the image I uploaded it says 500 - Internal Server Error in the right corner.
Anything I can do? Logs?

**Comment by karaoak** [comment]
I run into the exact same issue as @creazy231 
I cloned the directus repo today.

This is my log:
`user@server:~/directus.example.com/logs$ cat error.2019-06-12.log
[2019-06-12 20:47:25] api[_].ERROR: TypeError: Argument 3 passed to Directus\Database\TableGateway\RelationalTableGateway::recordActivity() must be of the type array, null given, called in /home/user/directus.example.com/src/core/Directus/Database/TableGateway/RelationalTableGateway.php on line 547 in /home/user/directus.example.com/src/core/Directus/Database/TableGateway/RelationalTableGateway.php:2300
Stack trace:
#0 /home/user/directus.example.com/src/core/Directus/Database/TableGateway/RelationalTableGateway.php(547): Directus\Database\TableGateway\RelationalTableGateway->recordActivity
#1 /home/user/directus.example.com/src/core/Directus/Services/ItemsService.php(161): Directus\Database\TableGateway\RelationalTableGateway->updateRecord`

**Comment by obruehl** [comment]
I have also the same issue and see the same error in log file. Any suggestion?

**Comment by benhaynes** [comment]
@bjgajjar @hemratna — any ideas?

**Comment by hemratna** [comment]
@obruehl If possible kindly provide the DB dump, log, your PHP version, API and APP version.
You can send me DB dump, log via slack.
You can find me as **hem** on http://directus.chat

**Comment by obruehl** [comment]
@hemratna My problem was that I installed the newest version on the production server and copied the db of a prior version from my docker development version. My solution was to delete all and install it again and configure the CMS manually again. In this case was a small project. 
Now it works fine.

**Comment by hemratna** [comment]
@obruehl Can we close this issue?
