### ISSUE TITLE
Can't sort items randomly 

### ISSUE THREAD

**Issue by DeFUCC** [directus/api#787]
I try to get 3 random items from the database. Here's the code:

```
client.getItems('items',{
      fields:'*.*',
      limit:3,
      sort:'?'
    })
```

But I get "Internal server error" as a request. Sorting by field names (even with minus in front) works great, just to mention. ;) Maybe I do simething wrong? The JS SDK docs don't show the exact filtering procedure.

**Comment by rijkvanzanten** [comment]
@DeFUCC Could you check if there's anything useful logged in the `/logs/` folder? That might give us a heads up of what the problem is

**Comment by DeFUCC** [comment]
The logs don't show any particular errors after such calls. There are mostly expired token errors in logs.

**Comment by WellingGuzman** [comment]
Thanks for reporting this @DeFUCC. I was able to reproduce it. I am going to find what the bug is and fix it on Friday.

Here is the error in the logs (without the stack trace):

```
[2019-02-20 16:59:02] api[_].ERROR: Error: Call to a member function isAlias() on null in /Users/welling/src/api/src/core/Directus/Database/TableGateway/RelationalTableGateway.php:1572
```

**Comment by DeFUCC** [comment]
Waiting for the v2.0.19 release. Is it coming soon?

**Comment by rijkvanzanten** [comment]
This Monday @DeFUCC
