### ISSUE TITLE
Add ability to customize list of supported middlewares for custom endpoints routes

### ISSUE THREAD

**Issue by yarick2000** [directus/api#789]
# Feature Request
Add ability to customize list of supported middlewares for custom endpoints routes

## What problem does this feature solve?
Custom endpoint may use some of the core services that may require some data provided by middleware, such as authentication data, for example. By giving ability to select which middlewares should be loaded for the project you giving an option to developers of custom endpoints to reuse core objects and services without reinventing the new ones.

## How do you think this should be implemented?
As a property in the api.{project}.config file, for example:
....
'custom_end_points_middlewares' => [
    'auth',
    'table_gateway'
]
....
## Would you be willing to work on this?
I don't have a required skills right now.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
