### ISSUE TITLE
Relations with string as primary key doesn't work

### ISSUE THREAD

**Issue by cesasol** [directus/api#798]
# Bug Report
Relationships doesn't work when using string based relation for example a slug relation or in the future with UUID

## Steps to Reproduce

1- Create a collection with a varchar primary key 
2- Create another collection and set a one to many or many to many relationship to the first collection
3- It will sabe to the database but will not follow relations with things like fields=*.* 

## Expected Behavior

Work the same way that it does with integer relations

## Actual Behavior

Doesn't resolver relations between collections

## Other Context & Screenshots

The record
![image](https://user-images.githubusercontent.com/3846473/53543260-b29cfd00-3ae7-11e9-9ce9-6bd401bf23ae.png)
The record with fields=*/*
![image](https://user-images.githubusercontent.com/3846473/53543241-a3b64a80-3ae7-11e9-84af-219b40af8654.png)

## Technical Details

- Device: Any
- OS: Ubuntu (server and client)
- Web Server: Nginx 1.10.3
- PHP Version: 7.2
- Database: MySQL 5.7
- Install Method: The cloned full package at v7.0.18

**Comment by kateerogers** [comment]
I am also seeing this issue with a project I am working on!
