### ISSUE TITLE
Add support for M2MM / M2X

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#8]
The API should be able to retrieve the nested (related) items based on primary key _and_ mixed collection, meaning it can nest items from multiple different tables

**Comment by benhaynes** [comment]
What do we need to do next to support this? @rijkvanzanten @WellingGuzman

**Comment by benhaynes** [comment]
I think we can avoid calling it a UUID... this would use a new Directus specific PK type that concats the collection name and id:

`articles-123`

**Comment by yarick2000** [comment]
> I think we can avoid calling it a UUID... this would use a new Directus specific PK type that concats the collection name and id:
> 
> `articles-123`

I wouldn't agree with that. What if I'm importing data from one DB to another one and there is already a data there with the same ID value? There will be a conflict then... The UUID should be something unique, probably generated basing on several data sources, not just name and id (e.g. machine name, MAC address, time, etc.)

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by bjgajjar** [comment]
Here are some initial thoughts on M2X relationship. 
M2X is kind of M2M so the flow for both of them will be the same.

I will consider 2 collections `files` and `category` with `media` M2X collection as an example for this DOC.

**Basic Info**

M2X collection will have below fields

1. id
2. files_id
3. collection_key  ( Collection Id => It will store the id of category)
4. collection_type  ( Collection Name => category )

**Creation of M2X field**

1. App Side Integration
![image](https://user-images.githubusercontent.com/19200178/61380980-fdb58200-a8c7-11e9-8139-28e826537c2c.png)

2. API Side Integration

- It will be same as an M2M for `directus_fields` table. 
- But we need a single change in `directus_relations` table.

      For M2M we had below entries in `directus_relations` table.
       
![image](https://user-images.githubusercontent.com/19200178/61381077-20e03180-a8c8-11e9-861b-89f62c837bfe.png)
                 
      For M2X we need to replace the `collection_one` with any specific keyword. (Either we can use * or any)
   
![image](https://user-images.githubusercontent.com/19200178/61381148-40775a00-a8c8-11e9-9229-fd25e9fe42c7.png)

    Note: This values will be passed from `APP` only.

**Insert Data**

1. For M2M the payload is 
  `{
  "category": [
    {
      "category_id": {
        "name" : "Lorem Ipsum"
      }
    }
  ]
}`

2. We will require the below payload for M2X
`{
  "media": [
    {
      "collection_key": {
        "type" : "category",
        "data" : {
          "name" : "Lorem Ipsum"
        }
      }
    }
  ]
}`

**Fetch Data**

Implement the needful changes into the current API for getting data of `any` collection.
Here, when we call the API of files we need to pass the type `category` to `media` table to get the category related media.

**Comment by benhaynes** [comment]
This looks great so far!

Right now we have been ideating on the Relation Settings design with something like this:

![Screen Shot 2019-07-17 at 4 46 09 PM](https://user-images.githubusercontent.com/522079/61410516-74478500-a8b2-11e9-9dfd-1c8dfab03c0e.png)

I defer to @rijkvanzanten on the data payload structure.

**Comment by lluishi93** [comment]
This would be a nice feature!!! Would take content contribution to next level, making Directus not only a CMS, but also a kind of Page builder which allows sortable and modular componentes for pages.
