### ISSUE TITLE
Extensions Directory

### ISSUE THREAD

**Issue by benhaynes** [directus/api#80]
Update the directory structure to this:

```
/ (api root)
  ...
  /public 
  ...
    /extensions
      /core
        /auth
        /hooks
        /interfaces
        /listings
        /pages
      /custom
        /auth
        /hooks
        /interfaces
        /listings
        /pages
```

Disable access to all `php` files inside the public directory using `.htaccess` and `nginx`

**Comment by WellingGuzman** [comment]
Ref: https://github.com/directus/api/commit/a4b73eceeade1411baf7d021e65eaa796f34ca0f
