### ISSUE TITLE
Add auto-loading for custom endpoints classes

### ISSUE THREAD

**Issue by yarick2000** [directus/api#803]
# Feature Request
Is it possible to include custom endpoints folder to auto loader (like Vendor folder included)? That will be really nice to have it built-in and so no need to use 'require' then. And all custom endpoints can sit then under Directus\Custom\Endpoints namespace...

## What problem does this feature solve?
It may solve several issues:
1. Potential conflicts between endpoints class names
2. Will allow developers of custom endpoints pre-load their classed and reference them same way as core and vendor classes 

## How do you think this should be implemented?
Creating autoloader.php under custom endpoints folder that will load all the classes that sitting underneath

## Would you be willing to work on this?
I don't have enough skills right now for that.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
