### ISSUE TITLE
Provide relationship collection in collection M2O field

### ISSUE THREAD

**Issue by gbtux** [directus/api#815]
# Feature Request

## What problem does this feature solve?

Get relation for a Many-to-One field

## How do you think this should be implemented?

With the JS SDK, "getCollection(collection)" method, fields are provided. In this fields, for a many-to-one field (relation), Directus API return "interface": 'many-to-one'" but not the collection in relation...

For example, I have a collection "Product" with a "creator" field.
The "creator" field is a Many-to-one relationship with the "directus_users" collection.

With the JS SDK, I need to do a getCollection('product") and API return : 
{
   "data": {
       "collection": "product",
       ..................,
      "creator": {
              "interface": "many-to-one",
              ..............
              "relation_collection": "directus_users"
     }
}
 
For the instance, I need to do a "getRelations()" and search an item with "collection_many = product" and "field_many=creator" 

Note : I try to do a getRelations('product') but It's buggy :/

## Would you be willing to work on this?
I don't know how :(

THX A LOT for the Job. Really enthusiastic for Directus !
(Use it with the JS SDK in Vue2.)
Version : 7.0.18

**Comment by benhaynes** [comment]
@rijkvanzanten — is this an API or JS-SDK issue?

**Comment by gbtux** [comment]
Hi. I Don't really know... I read the API doc and no solution for my problem. 
I Don't really know if i can have the complete description of the field (with the collection) with the API....

**Comment by 5and3shea** [comment]
**To simplify the request:**
It would be nice if `getCollection` would return a `"relation_collection"` key with the related collection is any, alongside the `"interface"` that it currently returns.

**More informationis probably needed here:**
> Note : I try to do a getRelations('product') but It's buggy :/

Though from what I see, `getRelations('product') ` doesn't take in a product.. It may simply be incorrect usage of the endpoint?..

**Comment by shealavington** [comment]
To simplify the request:
It would be nice if getCollection would return a "relation_collection" key with the related collection is any, alongside the "interface" that it currently returns.

More informationis probably needed here:

Note : I try to do a getRelations('product') but It's buggy :/

Though from what I see, getRelations('product') doesn't take in a product.. It may simply be incorrect usage of the endpoint?..

**Comment by gbtux** [comment]
Sorry . replace "getRelations('product')" by "getCollectionRelations('product')"

@shealavington :+1: for the simplification ;)

**Comment by rijkvanzanten** [comment]
I'm pretty sure this is an enhancement request for the API to be able to return the relationships nested inside the collections info.

Right now the nested field info is hardcoded too, which is unfortunate. Ideally, the `/collections` endpoint should work the same as regular `/items` by using the `fields` parameter in order to request this information: `?fields=fields.*,relations.*` (relations would be a o2m to directus_relations)

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
