### ISSUE TITLE
TinyMCE editor as an alternative to Quill.js

### ISSUE THREAD

**Issue by gitlabisbetterthangithub** [directus/api#816]
# Feature Request

TinyMCE alternative to Quill.js

## What problem does this feature solve?

TinyMCE has a lot more features than Quill.js. By integrating TinyMCE, users of Directus will have the ability to choose a different WYSIWYG editor that has more features and extensions compared to Quill.js

## How do you think this should be implemented?
As a core extension
## Would you be willing to work on this?
Yes, however I lack a lot of knowledge when it comes to coding modern JavaScript. I'm not familiar with Vue.js.

**Comment by benhaynes** [comment]
Thanks @gitlabisbetterthangithub — I agree that this is worth having! We have a ticket over here for tracking progress:

https://github.com/directus/app/issues/1234

**Comment by gitlabisbetterthangithub** [comment]
My apologies. I probably should have searched the app repo first however thought this was an api issue as extensions are on the api repo. I'll add my thoughts there.

**Comment by benhaynes** [comment]
No problem! @rijkvanzanten (App Lead) will be pulling extensions out of the API in the next week or so, hopefully the confusion around where extensions go will be gone. :)
