### ISSUE TITLE
Add more HTTP response headers

### ISSUE THREAD

**Issue by wellingguzman** [directus/api#82]
It will be nice to have more http headers in the http response, such as `ETag`, `Last-Modified`, `Date` and `Location`.

**Comment by WellingGuzman** [comment]
This is not an actual issue but a reminder that we should support more response headers.

We will be adding them as we need them.

**Comment by benhaynes** [comment]
Where is the specific note for this now? Don't want to forget!!

**Comment by WellingGuzman** [comment]
What I mean is that when we need it we will use them. (AKA we will remember).  I will leave it open then.

**Comment by benhaynes** [comment]
### Copying this over from @jsamr for more info:

ETAG headers can provide a huge benefit by

saving bandwidth with conditional gets
saving server load with a simple key value lookup
On a design perspective, ETAGs could be associated per row, with some uuid identification.

Some complexity might come with associations, where the ETAG should change when referred rows are modified, added or deleted. But the benefits should outweigh the costs.

http://fideloper.com/api-etag-conditional-get

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
