### ISSUE TITLE
Multiple asterisk cors allowed origin values

### ISSUE THREAD

**Issue by stefanvangastel** [directus/api#826]
# Bug Report

After deploying api and app (both from master) under different domains the app cannot connect due to cors issues.

## Steps to Reproduce

1. Clone both API and app as instructed on https://docs.directus.io/advanced/source.html
2. Deploy to api.myapp.com and app.myapp.com
3. Configure api
4. Configure app to point at api
5. Try to login

## Expected Behavior

I can login

## Actual Behavior

Can't login due to double `*, *,` values in Access-Control-Allow-Origin header:

```
Access to XMLHttpRequest at 'http://api.domain.nl/public/server/ping' from origin 'http://app.domain.nl' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.
```

## Other Context & Screenshots

**Direct access to the api is working as expected!**

Hardcoding 'blaat'  instead of `$origin` on https://github.com/directus/api/blob/master/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php#L158 results in: 

```
The 'Access-Control-Allow-Origin' header contains multiple values 'blaat, *', but only one is allowed.
```

## Technical Details

- Device: Desktop
- OS: MacOS, using Chrome latest stable
- Web Server: Apache 2.4
- PHP Version: 7.2
- Database: MySQL5.6.42
- Install Method: https://docs.directus.io/advanced/source.html

**Comment by rijkvanzanten** [comment]
Hey @stefanvangastel! What server stack are you using? Oftentimes when people run into an issue like this is because they've already opened up CORS on a server level (Apache) which doubles it up when also using the CORS setting in Directus 🙂

**Comment by stefanvangastel** [comment]
Hi @rijkvanzanten just installed a clean Ubuntu VPS with Ubuntu and no issues whatsoever. So it was just my sharedhosting (WebOke) that was causing the issue for some reason. I'll close this since it is not reproducible.
