### ISSUE TITLE
Have an $old and $new for Action Hooks

### ISSUE THREAD

**Issue by barnesew** [directus/api#827]
# Feature Request

Currently, I believe the only variable passed to an update action hook is a $data array that contains the new version of the item. It would be beneficial to have two variables such as $old and $new.

## What problem does this feature solve?

Having the $old and $new versions of an item would allow comparisons between the two such as sending an email when a boolean changes from false to true. Currently, the only way I have found to get this functionality is to catch it with :before and compare $data to the database.

## How do you think this should be implemented?

Passing two variables to the action functions with the two versions:

`
'actions' => [
    'item.create.[item]' => function (array $new, array $old) {}
]
`

## Would you be willing to work on this?

I wouldn't really know how to help but if I can be of any help I will!

**Comment by benhaynes** [comment]
I like this a lot and see many benefits. We'll have to look at how the passed data is structured to make sure this wouldn't be a breaking change... and that ti won't add a lot of overhead (since it adds another database query).

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
