### ISSUE TITLE
Revert saves full copy to directus_revisions, instead of just changed fields

### ISSUE THREAD

**Issue by magikstm** [directus/api#831]
# Bug Report

Related to #1299.

## Steps to Reproduce

On the demo (Directus Latest):

For an existing item:
1. Go to 'Movies'
2. Click on an item that can be reverted (if need be, do changes to it, save a few times and open it again)
3. Click on 'Revert' on the right
4. Click on 'Revert' on the modal

The behavior is the same for a new item that is reverted.

## Expected Behavior

Only fields that changed should be displayed on the right for the latest change.

## Actual Behavior

All fields are displayed on the right for the latest change.

## Technical Details

- Device: Desktop
- OS: Windows 7 x64
- Browser: Firefox 65.0
- Directus App: demo (Directus Latest)
- Directus API: -
- Install Method: -

**Comment by benhaynes** [comment]
I know it is incorrect, but I'm going to call this an enhancement instead of a bug since nothing is actually broken. Thanks for reporting this @magikstm — we'll get it sorted asap (unless someone wants to give a PR a try first!).

**Comment by srjrol** [comment]
@benhaynes Not sure if it is related but today I had to truncate the ```directus_revisions``` table because its size was growing out of control. 
![image](https://user-images.githubusercontent.com/34398302/55898700-c9c01780-5b88-11e9-8815-a75a56dacf4c.png)

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
