### ISSUE TITLE
API returns wrong casing in nested fields /collections

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#833]
# Bug Report

Note how the collection is called `Test`, but the related nested fields return the casing as `test`. It does get returned correctly on `/fields` however.

<img width="314" alt="image" src="https://user-images.githubusercontent.com/9141017/54552817-519a7380-4987-11e9-9bda-2f58d63b1536.png">

**Comment by benhaynes** [comment]
Also seems like the cause of the "Manage Collection" button issue, right?

**Comment by rijkvanzanten** [comment]
Why? How is that related?

**Comment by benhaynes** [comment]
I just assumed that there might be a connection between the case issue for collections and the endpoint for toggling "managed". But now that I think about it, things toggle correctly and it's just the App updating... so it's probably unrelated. :/

**Comment by rijkvanzanten** [comment]
Yeah, and that's about collections, this is about fields 😉

**Comment by bjgajjar** [comment]
@benhaynes @rijkvanzanten 

We need to look into below points to add capitalized table name in the system.

(1)  MySQL have 'lower_case_table_names' system variable. The capitalization of the table only possible if this variable is enabled in a file at /etc/mysql/my.cnf. 
There are three possible values for this [0,1,2] but the challenge is On Unix, the default value of lower_case_table_names is 0. On Windows, the default value is 1. On macOS, the default value is 2.
So if in the user's system it is disabled then they need to enable manually and for that, we have to check from the code base that what is the user's OS and whether it is enabled or not. You can find more details from https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html

(2) As this system variable is OS specific, a user needs to check it at the migration time too. So when someone wants to migrate the local Directus setup from Unix to Windows or Mac, this variable can create a problem.

What should be the best approach?

**Comment by benhaynes** [comment]
My opinion is: We should force lowercase when adding collections/fields through the App and API, but we should support any collections/fields that _already have_ uppercase letters (added manually in the database, or that were from a migrated schema).

Then we don't need to do any checks. If they already have uppercase in their database then it must be allowed.

BUT, this means that when we show _existing_ uppercase collections/fields that those App inputs must be disabled... and they should not "re-submit" the name to the API.

Does that make sense? Does that seem like a good solution? @rijkvanzanten @bjgajjar @hemratna

**Comment by bjgajjar** [comment]
@benhaynes  As per the current code, the flow you have recommended is already there! 
You can find the API changes in PR #859
