### ISSUE TITLE
Item.remove action hook isn't returning data

### ISSUE THREAD

**Issue by Mozz4rt** [directus/api#842]
# Bug Report
`item.delete.[colection]` action hook doesn't return $data parameter. Instead it returns an ID for a row that doesn't exists anymore in case of :after.
## Steps to Reproduce

1. Create any action hook 
2. `var_dump` the first parameter
3. See only the ID of the item

## Expected Behavior
Return full data from the item you're trying to delete
## Actual Behavior
Returning only ID from an item that in some cases doesn't exist.
## Other Context & Screenshots
This was the function for the action hook i used when testing:

`'item.create.table' => function($data){
  var_dump($data);
},`

## Technical Details

- Device: Desktop PC
- OS: Windows 10 Pro
- Browser: Chrome 72.0.3626.121 64bit
- Directus App: 7.0.19
- Directus API: 2.0.19
- Install Method: Download zip and extract.

**Comment by theharshin** [comment]
Thank you for the report @Mozz4rt 🙂 @hemratna or @bjgajjar will be having a look at this issue soon.

**Comment by bjgajjar** [comment]
@Mozz4rt 

We develop the explicitely code like the delete hook will have a ID only instead of object.

Can you please  provide the usecase of this functionality? 

We have to consider this as a feature functionality instead of bug. Let me know your thoughts @benhaynes

**Comment by benhaynes** [comment]
I'm not sure what is standard, but I could see why it would be nice to have the item info in the hook (eg: so you could send an email/notification saying `XXXXX item was deleted`. Any thoughts @rijkvanzanten ?

**Comment by Mozz4rt** [comment]
@benhaynes Funny enough, that's exactly what I was hoping to achieve.

@bjgajjar the problem with returning the id and why i see It as a bug is that :after delete you can't do much with the returned id since it's no longer in the database, the expected would be an obj copy of the deleted item for further use..

**Comment by bjgajjar** [comment]
@Mozz4rt 

This issue is resolved with #882. I just added the extra parameter along with ID. So the other user's who used this hook earlier, they will not be affected by this change.

**Comment by benhaynes** [comment]
Fixed by https://github.com/directus/api/pull/882
