### ISSUE TITLE
/users/me?fields=last_page returns no data for non admin user

### ISSUE THREAD

**Issue by Lapsus** [directus/api#843]
# Bug Report
While trying to set the page for the first login of a user to his profile page i realized that directus_users.last_page could to the trick. But unfortunately it does not work for non-admin users.

## Steps to Reproduce
Check the requests sent on the browser console during login.
First request is /auth/authenticate
Second request is /users/me?fields=last_page

Compare the request when logging in as admin user and as user with non admin permissions.
## Expected Behavior
AdminUser gets {data: last_page: "..."}
RegularUser gets {data: last_page: "..."}

## Actual Behavior
AdminUser gets {data: last_page: "..."}
RegularUser gets {data: []}

**Comment by syslogic** [comment]
the value is being set to table `directus_users`. when comparing `/_/users/1/revisions` with eg. `/_/users/2/revisions`, it seems that property `last_page` is also being returned as `null` there.
