### ISSUE TITLE
Many to Many (or One to Many) field not showing in API response

### ISSUE THREAD

**Issue by ninjabachelor** [directus/api#846]
# Bug Report

## Steps to Reproduce

1. Create a Many to Many or One to Many field in a table
2. Get one item from the table via API
3. The field is not present in the response

## Expected Behavior
Get the field value. I also tried to get it via the "fields" query parameter.
Is it by design? Should I get the value in a different way?

## Actual Behavior
The field is not present in the API response.

## Technical Details

- Device: any
- OS: MacOS 10.14.3
- Web Server: nginx
- PHP Version: 7.2.0
- Database: MySQL 5.7.24
- Install Method: cloned `7.0.16` branch

**Comment by theharshin** [comment]
Hello, @ninjabachelor Thanks for the information. I see you've cloned the `7.0.16` branch. The latest release is `7.0.19`. Can you update it to the latest and check if the issue is still there? Also, let me know if you have a specific reason to keep `7.0.16` release. 🙂

**Comment by rijkvanzanten** [comment]
This seems to be working as expected on the demo api: `https://demo-api.directus.app/_/items/members?access_token=demo&fields=*.*`

The fields parameter is required for the API to return the nested relational items for o2m (and m2m) type relationships.

**Comment by ninjabachelor** [comment]
Thanks @theharshin and @rijkvanzanten ,
Yes correct, I missed the second level in the `fields` query parameter. It works correctly.

Thanks again!
