### ISSUE TITLE
/projects fails for database with no password

### ISSUE THREAD

**Issue by dslpp056193** [directus/api#847]
# Bug Report

When creating a new project using `/projects`, leaving the db_password field empty will write `null` to the config file resulting in database connection errors when trying to use the API.

## Steps to Reproduce

1. Create a new project in /projects
2. Leave the db_password field empty (or empty string `""`)
3. See problems

## Expected Behavior

The API should support database connections with no password

**Comment by theharshin** [comment]
@bjgajjar I think we need to explicitly check for `null` from APP and replace it with blank String. Thanks @dslpp056193 for reporting the issue 🙂
