### ISSUE TITLE
Rate limit login attempts

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#850]
# Feature Request

After a certain amount of wrong login attempts, we should block the user from logging in for a certain amount of time.

## What problem does this feature solve?

Prevent brute-forcing logins on the API

## How do you think this should be implemented?

Similar as to iOS handles it. After 10 wrong login attempts, the user can't login for a minute. After 10 more wrong login attempts, the user can't login for 5 minutes, etc etc.

## Potential problem

There might be a chance of trolling by trying to login with someone else's account. I think we can tackle that by blocking it based on rate and IP address.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
