### ISSUE TITLE
Cannot add files or m2m field

### ISSUE THREAD

**Issue by luglio7** [directus/api#861]
# Bug Report

Sometimes i am not able to add a relations field (in my case the files and the many to many interface). I get  this js error : `vue.runtime.esm.js:1888 TypeError: Cannot read property 'fields' of undefined` which is caused by the file: 
`getters.js` (webpack:///./src/store/modules/relations/getters.js) 
at this line: 
`field_many: collections[result.collection_many].fields[result.field_many],`

## Steps to Reproduce

Only on certain collections, i don't know what is the cause since the relational interfaces seems to work on every other collections. I just added and removed some relational fields.

## Expected Behavior

To work as expected

## Actual Behavior

I am not able to add some interfaces due to a js errors.

## Other Context & Screenshots

https://www.dropbox.com/s/b7g0e2c91xfkpo2/Annotazione%202019-03-28%20174133.jpg?dl=0

## Technical Details

- Device: Intel Nuc
- OS: Windows 10
- Web Server: Apache
- PHP Version: 7.2
- Database: MySql 5.7
- Install Method: cloned

**Comment by wiwski** [comment]
Same error here after added a m2m relation and deleted it. 
Any workaround while we waiting for a fix ?

**Comment by benhaynes** [comment]
@bjgajjar @hemratna — any thoughts on this?

**Comment by bjgajjar** [comment]
@benhaynes 

I will look into it and let you know soon.

**Comment by theharshin** [comment]
@luglio7 @wiwski There is a known issue of relational fields that they are not being synced with VueX once updated, hence Vue does not know how to handle those. Can you refresh the app after changes are made in relational fields and try again and let me know if the error occurs?

**Comment by luglio7** [comment]
Already tried, does not work.

**Comment by blackfox00** [comment]
It seems that if you remove m2m relation, the metadata about it doesn't get completely cleaned from the database. As a workaround to make the interface work again, go to the database -> directus_relation table and find the 2 existing records about the m2m relation you previously removed and delete those records. Refresh the app and it should work again.

**Comment by bjgajjar** [comment]
Fixed in #1009

**Comment by lcdss** [comment]
Great! I had this same problem just now.

**Comment by bjgajjar** [comment]
Hey @lcdss 

Can you please elaborate on your problem? Cause after the #1009; I don't think so the issue will still persist. So It will be great if you can explain your issue.

**Comment by paolodedomini** [comment]
same issue, i deleted the m2m field in a collection, with the last version of directus 7, and then i was not able to add any new m2m field to the same collection again.
I tried also to erase and recreate the collection but with no luck.

to notice: If i try to add the field to a brand new collection then i can add an m2m field with no problem at all

need some help no doubt...
