### ISSUE TITLE
Dot notation filters don't work for public group

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#863]
# Bug Report

When setting all the collections readable by the public group, the dot notation for filters doesn't work.

## Steps to Reproduce

1. Install the provided demo sql dump
2. Go to `/_/items/tag?fields=*.*&filter[tag_type.title][eq]=Category`
3. See error

Note how it works when you add `&access_token=demo` to the end of that URL

[dump.zip](https://github.com/directus/api/files/3023520/dump.zip)

**Comment by bjgajjar** [comment]
Closed in #916
