### ISSUE TITLE
Junction table without primary key leads to error

### ISSUE THREAD

**Issue by inta** [directus/api#865]
# Bug Report

Junction tables without auto increment, numerical primary key will lead to errors.

## Steps to Reproduce

1. Create two tables person and contact (no matter which content) and a junction table like this:
```sql
CREATE TABLE `person_contact` (
  `person_id` int(11) unsigned NOT NULL,
  `contact_id` int(11) unsigned NOT NULL,
  PRIMARY KEY (`person_id`, `contact_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```
2. Go to person table and set up a many to many relation using the existing junction table
3. Go to person collection and try to add an item with relation to contact
4. a) See error: `Attempting to write an array as the value for field "contact_id" in "person_contact"`

    b) I tried removing the primary key and just use those two foreign keys (without constraint), but I got the following error on selecting a contact in the overlay and hitting save:

Firefox:
```
TypeError: "this.$lodash.find(...) is undefined"
    junctionPrimaryKey input.js:4
    VueJS 3
    render input.js:5
    Nt VueJS
    render input.js:5
    VueJS 7
vue.runtime.esm.js:1888
```
Chrome:
```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'field' of undefined
    at u.junctionPrimaryKey (input.js:4)
    at nr.get (vue.runtime.esm.js:4473)
    at nr.evaluate (vue.runtime.esm.js:4578)
    at u.junctionPrimaryKey (vue.runtime.esm.js:4830)
    at input.js:5
    at u.Nt [as _l] (vue.runtime.esm.js:2630)
    at u.render (input.js:5)
    at u.e._render (vue.runtime.esm.js:3542)
    at u.r (vue.runtime.esm.js:4060)
    at nr.get (vue.runtime.esm.js:4473)
```

## Expected Behavior
New person data set and relation will be stored in the database

## Actual Behavior
As described above I got errors using a composite primary key or using no primary key at all. I think both are valid use cases for a junction table. If I add an auto increment id column the errors are gone.

## Other Context & Screenshots

I tested this with the official docker images (currently 7.0.18 and 2.0.18) and later on by cloning https://github.com/directus/directus and following the installation docs.

I am not shure whether this belongs to the API, the App or even both.

## Technical Details

- Device: Desktop, Gnome
- OS: Debian Buster
- Browser: Firefox 66.0.2, Chrome 73.0.3683.86 (Official Build) (64-bit)
- Directus App: 7.0.18, 190325A
- Directus API: 2.0.18, 190325A
- Install Method: docker + cloned `master` branch of `directus/directus`

**Comment by inta** [comment]
Ok, thanks for having a look.

What about junction tables without primary key? Is that supposed to work or unsupported either?

**Comment by rijkvanzanten** [comment]
Junction tables with no primary keys rely on composite primary keys and therefore aren't supported at this time either.

**Comment by benhaynes** [comment]
As of now Directus needs a unique way to reference every item through the API — and as of now we need a (single) field/column for that. Composite keys would be a good feature request though!

I'll close this, but keep it referenced in the Feature Request — thanks @inta!!

Ref: https://github.com/directus/api/issues/866
