### ISSUE TITLE
Support Composite Keys

### ISSUE THREAD

**Issue by benhaynes** [directus/api#866]
Not sure how difficult this would be to implement with our current way of referencing items, but we should discuss.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by noedelcroix** [comment]
Hello,
I'm also looking to create a composite key. Did you find a way to create it properly ?
The solution I found is to create an other table just to make the key pair unique. I hope there is now a better solution...

**Comment by John0x** [comment]
I'm honestly kinda shocked that support for composite keys isn't even planned.  It's such a pain to model your database after a weird restriction caused by Directus :/
Composite Keys are extremely common and should be supported by default

**Comment by somu2208** [comment]
May I know when this feature - allow combination primary key,  will be supported?

**Comment by somu2208** [comment]
Is this features is available in Directus cloud?
