### ISSUE TITLE
File library card image limit

### ISSUE THREAD

**Issue by laravel1112** [directus/api#871]
# Bug Report

## Steps to Reproduce

3. Scroll down to '...'

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Web Server: [eg: Apache 2.4.37]
- PHP Version: [eg: 7.2.0]
- Database: [eg: MySQL 8.0.12]
- Install Method: [eg: cloned `master` branch]

**Comment by rijkvanzanten** [comment]
Do you mind explaining what's wrong / going on? The title alone unfortunately doesn't give me enough to work with..

**Comment by theharshin** [comment]
Hello @laravel1112 Can you provide more details about the issue? I'm not able to reproduce the issue. A screenshot of an issue or steps to reproduce it would be a great help 🙂

**Comment by laravel1112** [comment]
Sorry, the issue is already resolved with the latest version of directus.
I had an issue in old version.
