### ISSUE TITLE
Password stored in plain text for non default user.

### ISSUE THREAD

**Issue by YvanDaSilva** [directus/api#874]
# Bug Report
Password is stored in plain text.

## Steps to Reproduce

1. Get the latest master from both API&APP
2. Start them with a new mysql db
3. Login in as admin
4. Create a new admin user
5. Go look at the DB content

## Expected Behavior
The password is hashed and the user is able to log in (stored and provided hashes match)

## Actual Behavior
Unable to login the new user, the password is store in plain text

## Other Context & Screenshots
If you revert the following merge request (manually) the password will be hashed again.
Something in the latest commits broke the hashing of the user password, sadly I don't have time to go through everything.

https://github.com/directus/api/pull/591

## Technical Details

- Device: web
- OS: Linux
- Web Server: nginx
- PHP Version: php7.2-fpm
- Database: mariadb latest
- Install Method: clone master branch

**Comment by benhaynes** [comment]
Not sure about this one — I just used the demo (https://directus.app) and created a new user... then check the database and the password was: `$2y$10$zJ05xl5CemPdUEDe2v3B6eaOtzCCeSy/FDK1gB3hOBMKg5pfdEQMG`

Things seem to be working as far as I can tell... but this is a serious issue and I want to make sure that we don't overlook anything. Could you make sure you're on the latest version of the App, API, and database (and it's updated)?

**Comment by YvanDaSilva** [comment]
HI @benhaynes ,
Yes absolutely to all your questions, master branch up to date. New database and up to date (I even tried clicking the update script from the app)

The default user created through the ENV variables work fine.

However any new users and update of that user will not hash the password.
Something must have changed on the way of doing things, maybe when you moved extensions.
I didn't had time to investigate more than that.
But since reverting 591 fixes the issues, I think the other path or hook or however it is done is not working anymore.

If you know exactly what's the path that should be followed by the new user -> hash -> db, I can have a look, I just don't have time to go through all the project right now.

Let me know.

**Comment by YvanDaSilva** [comment]
Please see the closed merge request https://github.com/directus/api/pull/877 for more information.

**Comment by rijkvanzanten** [comment]
Closed in https://github.com/directus/api/commit/0c65c93fa990e2b4abb31cbb5e1cd6db0828a53d
