### ISSUE TITLE
Updating Collection presets denied

### ISSUE THREAD

**Issue by alrick** [directus/api#876]
# Bug Report

## Steps to Reproduce

1. Go to a collection
2. Click on Information button at top right corner
3. Change "Table" to "Cards" or vice versa

## Expected Behavior
The view is displayed, no error message.

## Actual Behavior
The view is actually changed accordingly, but the user get an error message :
UI : `Trouble processing request. Try again after refreshing the page.`
Web console : `code: 302, message: "Updating item from "directus_collection_presets" collection was denied"`

## Other Context & Screenshots
The user is not an admin.

## Technical Details

- Device: Desktop
- OS: MacOS
- Browser: Latest Chrome
- Directus App: 7.0.19
- Directus API: 
- Install Method: git clone

**Comment by bjgajjar** [comment]
@alrick @rijkvanzanten 

I'll fix the issue and send the PR ASAP!

**Comment by theharshin** [comment]
@alrick @rijkvanzanten I and @bjgajjar both are not able to reproduce this issue at our end!
@alrick can you update the API & APP to the latest version and check if the issue persists? Also, don't forget to run the database update script after updating codebase.

**Comment by rijkvanzanten** [comment]
@theharshin just to confirm, you tried the 

> I have to add that I may have changed the "user" (set to null) of my collection presets (admin) in the database in order to create global default views.

part as well? That might be the reason it's causing problems right now

**Comment by theharshin** [comment]
> @theharshin just to confirm, you tried the
> 
> > I have to add that I may have changed the "user" (set to null) of my collection presets (admin) in the database in order to create global default views.
> 
> part as well? That might be the reason it's causing problems right now

Yes, I've changed the `ID` in `user` column from admin to another user so the user can directly see the preset set by Admin. The user was able to change the preset later.

**Comment by alrick** [comment]
Thanks for your tests @theharshin 
Did you try with the user set to `null` too ?

I'll update the app next monday and test everything again.

**Comment by alrick** [comment]
Just a follow-up that I'll not update everything before the problem with the files is fixed as this is a deal-breaker for my clients.

I'll update and test everything as soon as this is fixed, next update according to a conversation on your Slack.

**Comment by alrick** [comment]
This seems indeed fixed with the last version.
