### ISSUE TITLE
Azure/Custom Storage Adapter

### ISSUE THREAD

**Issue by joe642** [directus/api#883]
# Feature Request

Azure Storage Adapter. Have had a look inside the FilesystemFactory and can see that S3 support is embedded into the core of Directus, and a switch is used based on config to use either the Local or S3 adapter. I can't see any way of creating a custom extension based on this code:

```
public static function createAdapter(Array $config, $rootKey = 'root')
    {
        // @TODO: This need to be more dynamic
        // As the app get more organized this will too
        switch ($config['adapter']) {
            case 's3':
                return self::createS3Adapter($config, $rootKey);
                break;
            case 'local':
            default:
                return self::createLocalAdapter($config, $rootKey);
        }
    }
```

## What problem does this feature solve?

Directus apps can be deployed within the Microsoft Azure ecosystem.
## How do you think this should be implemented?

Custom extension outside of the core

## Would you be willing to work on this?

I'm willing to develop a storage adapter for Azure, just need to find out if it's possible with the current version and if there is an example extension/storage adapter in existence. I've seen Rackconnect listed as a supported provider, but I can't find anything relating to the implementation of this adapter to use as a starting point.

**Comment by benydc** [comment]
@joe642 I have implement this in my project, and works great with Azure Blob storage, but is tied to the core, it's the same as S3 adapter. There is a an Azure blob flysystem adapter that integrates perfectly.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
