### ISSUE TITLE
Primary key strings with number as first char only take the number

### ISSUE THREAD

**Issue by carlwhittick** [directus/api#884]
# Bug Report
This seems to be a similar issue to one that Facebook had a while ago. When attempting to get a row by a primary key of 1abc the system will return the results for 1.

## Steps to Reproduce

1. Go to "/_/items/exampletable/1abc" on a table with numeric keys
2. See results for "1" rather than the expected error

## Expected Behavior
If no item exists for the provided primary key then show the row not found error.

## Actual Behavior
See results for an unrelated item.

**Comment by bjgajjar** [comment]
Closed out in pull #901
