### ISSUE TITLE
Primary key of 0 returns empty JSON rather than expected 203

### ISSUE THREAD

**Issue by carlwhittick** [directus/api#885]
# Bug Report
Passing a 0 as the primary key returns empty data rather than the expected 203 (item not found) error.

## Steps to Reproduce

1. Go to "/_/items/exampletable/0"
2. See empty JSON object

## Expected Behavior
Return 203 (Item not found) error

## Actual Behavior
Returns empty JSON object

**Comment by bjgajjar** [comment]
Closed out in pull #898
