### ISSUE TITLE
Passing in a mathematical shorthand representation of the primary key returns results 

### ISSUE THREAD

**Issue by carlwhittick** [directus/api#886]
# Bug Report
Passing in the mathematical shorthand for a number returns results

## Steps to Reproduce

1. Go to "/_/items/exampletable/2e1"
2. Will return results for 20

## Expected Behavior
Error as no primary key of 2e1 exists

## Actual Behavior
Returns results for the result of the representation i.e. 20

**Comment by bjgajjar** [comment]
Closed out in pull #899
