### ISSUE TITLE
What are all the different activity types and actions?

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#89]
* LOGIN
  * LOGIN
* ENTRY
  * CREATE
  * UPDATE
  * DELETE ?
* ???

**Comment by WellingGuzman** [comment]
Actions:

- ADD
- UPDATE
- DELETE
- LOGIN

Types:

- ENTRY. For Items, Except for Files, Settings and Messages (comment)
- FILES. _Same as ENTRY but for files_
- SETTINGS. _Same as ENTRY but for Settings_
- LOGIN. _User authentication_
- MESSAGE. _For Comments_

It's worth to mention this is a good time to discuss better naming if we want to, for example, Change `ENTRY` for `ITEM` and `LOGIN` (type) for `AUTH`.

**Comment by rijkvanzanten** [comment]
Yes to both those changes! Lets also add this to the Wiki :D

**Comment by benhaynes** [comment]
Add to the API Docs? Where's the wiki?

**Comment by rijkvanzanten** [comment]
The wiki is the wiki in this repo

**Comment by benhaynes** [comment]
OK, I'm going to leave this Wiki update for you Welling. 

Are we keeping this wiki? How will it be different from the API Docs? More about installation? Would this be in our `.md` docs eventually?

**Comment by rijkvanzanten** [comment]
The wiki is developer information, the docs are API reference / usage

One is for contributors, the other is for developers _using_ the API

**Comment by WellingGuzman** [comment]
Should we rename:
- Type: `ENTRY` TO `ITEM`?
- Action `LOGIN` to `AUTHENTICATED`
- Type `LOGIN` to `AUTH`
- Action `ADD` to `CREATE`

To keep things with all the rename we have made. I suggested `AUTHENTICATED`, what else should that be called `AUTH` as well?

**Comment by rijkvanzanten** [comment]
I like those changes. In terms of AUTH, I think it's login vs login through SSO?

**Comment by WellingGuzman** [comment]
All the different data types and actions are documented here: https://github.com/directus/api/blob/fb861dcf316fa5a29091f3ba52779813e8fc9795/docs/README.md#activity
