### ISSUE TITLE
Wrong MIME for uppercase extension

### ISSUE THREAD

**Issue by tmshv** [directus/api#893]
# Bug Report

Directus sets mime type for uploaded image as application/octet-stream if file extension written in uppercase

## Steps to Reproduce

1. Go to 'File Library'
2. Click on '+'
3. Open file selector
4. Select file with extension written in uppercase

## Expected Behavior

Uploaded file with image/jpg mime

## Actual Behavior

Uploaded file with application/octet-stream mime

## Technical Details

- Device: VPS
- OS: Ubuntu 16.04
- Docker image directus/api:latest
- Database: MySQL 5.7
- Install Method: docker-compose

**Comment by theharshin** [comment]
Thanks for the report @tmshv :) Should be fixed by PR https://github.com/directus/api/pull/895

**Comment by bjgajjar** [comment]
Closed out in pull #895
