### ISSUE TITLE
Add tests for batch update / delete / get

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#91]
We talked about different ways of performing batch-operations. Lets make sure we're all on the same page and that it's currently implemented like follows:

## GET
The endpoint to fetch a single item should accept the CSV style primary key too, which would serve as a replacement for the now deprecated `id` parameter:

```
GET /items/<collection>/<pk> (one item)
GET /items/<collection>/<pk>,<pk> (multiple items by primary key)
```

## POST
Seeing you don't POST by ID, posting multiple items is done by sending an _array_ instead of an _object_ to the regular POST endpoint:

```
POST /items/<collection>
```

One item (regular):
```json
{
  "title": "Project",
  "category": "Design"
}
```

Multiple items (batch):
```json
[
  {
    "title": "Project",
    "category": "Design"
  },
  {
    "title": "Another project",
    "category": "Development"
  }
]
```

## PATCH / PUT 
```
PATCH /items/<collection>/<pk>,<pk>
PUT /items/<collection>/<pk>,<pk>
```
This sets the fields for each of the provided primary keys to _the same_ value.

Also, as per the discussion in #77, updating items should/could be possible by PATCHing or PUTing to `/items/<collection>` by providing filters through the query string:

```
PUT /items/<collection>?filter[name][eq]=rijk
PATCH /items/<collection>?filter[name][eq]=rijk
```

This leaves us with 1 problem; how to update multiple items to _different values_. Usecase: updating multiple items to different `sort` values while dragging and dropping on listings.

I propose we use a similar syntax to POST, where we send an array of items _with the primary key field included_:

```json
[
  {
    "id": 5,
    "title": "New title"
  },
  {
    "id": 16,
    "title": "Another new title"
  }
]
```

## DELETE
```
DELETE /items/<collection>/<pk> (delete single item)
DELETE /items/<collection>/<pk>,<pk> (delete multiple items)
```

**Comment by rijkvanzanten** [comment]
And keep #77 in mind too!

**Comment by benhaynes** [comment]
OK, the `.md` API Docs have been updated with these notes. I have added some `@TODO`s in there that we still need to discuss. Also, just because I added it into the Docs doesn't mean it works!

**Comment by WellingGuzman** [comment]
It's working as expected. I will add tests later to make really sure it works.
