### ISSUE TITLE
/ping Response won't respect cors.max_age setting

### ISSUE THREAD

**Issue by mvhirsch** [directus/api#917]
# Bug Report

Hi, 

i just discovered a simple(?) bug while configuring my Directus setup.
I wanted to reduce that many calls that happening to my backend server. Many of them are OPTIONS-Requests. Luckily Directus got me covered: `cors.max_age`. It does it's job, all but for /ping requests.

## Steps to Reproduce

1. Configure cors.max_age setting according to https://docs.directus.io/advanced/api/configuration.html#cors, say set it to 500.
2. Request http://directus-api.local/server/ping (or wait while APP is logged in and console is open)

## Expected Behavior

Response should include "Access-Control-Max-Age: 500"

## Actual Behavior

No such header "Access-Control-Max-Age" (while others do appear).

## Technical Details

- Device: Desktop
- OS: Linux
- Web Server: Nginx
- PHP Version: 7.2
- Database: mysql 5.7
- Install Method: Docker'd version of Directus (APP v7.0.18 && API v2.0.18)

**Comment by bjgajjar** [comment]
@benhaynes 

'/ping' is a general API, not a project-specific API. As per the current code; project-specific API will consider the headers from the config file and the general API will have the default value. So I need to change the default value of `cors.max_age`.

 Let me know your thoughts.

**Comment by benhaynes** [comment]
Maybe it makes sense to eventually add a global config file for some of these non-project settings. But for now, I guess updating the default seems like the best option. 

Do you agree @bjgajjar ?

**Comment by bjgajjar** [comment]
Yeah, I think for now we should update the default setting only! Later on, will add the global config file.

**Comment by bjgajjar** [comment]
Fixed in #960
