### ISSUE TITLE
Set cors.max_age to a higher default

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#919]
# Feature Request

Set the max_age value for CORS to a default that's not null.

## What problem does this feature solve?

Every request in the application gets effectively 'doubled' by the need of a preflight CORS request. By setting the max_age option, we can cache the responses of the preflight, which negates the needs of a preflight for every individual request. (ht to @mvhirsch in https://github.com/directus/api/issues/917)

## How do you think this should be implemented?

https://github.com/directus/api/blob/56d53e695fbafc3a135034efe2f5dd2df793cf74/src/core/Directus/Util/Installation/InstallerUtils.php#L923

Swap out `null` for a value (in seconds) like `600` (10 minutes)

**Can we think of any reason why we _shouldn't_ change this?** @theharshin @bjgajjar 

Ref:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age

**Comment by mvhirsch** [comment]
:grin: #921

**Comment by rijkvanzanten** [comment]
Lets take a second before merging to verify we don't break anything 😁

**Comment by mvhirsch** [comment]
Just preparing. Closing is always an option :grin:

**Comment by theharshin** [comment]
@rijkvanzanten Looks fine to me. Just to mention that we're setting this at the maximum allowed in Chromium browsers. [Ref.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age#Directives)
