### ISSUE TITLE
Make bookmark items accessible by API

### ISSUE THREAD

**Issue by fl034** [directus/api#927]
# Feature Request

With bookmarks (aka [collection_presets](https://docs.directus.io/getting-started/concepts.html#collection-preset)) we already got a powerful way of saving filters (together with display settings) per user.
It would be great to be able to access this filtered items via the api.
[This has been discussed here](https://github.com/directus/directus/issues/2255), but I moved it to a separate issue to differentiate this feature from my OAS request.

## What problem does this feature solve?

For some use cases you just need a pre-filtered list in your client.
This would be like a GUI for custom endpoints, for fast creation and access.

### Example

Let's assume I want to develop an App natively for Android and iOS.
Via Directus I want to manage data that is being displayed. Let's say podcast items and podcast series, to group multiple items.

In the app I want to display the podcast series, but only the ones that have one or more items in it.
My idea is to be able to create a bookmark (e.g. seriesFilteredForApp) that is filtered like this and make it manageable via API (and documented via OAS hopefully soon).

With this approach we would achieve some kind of static filtering, which could be useful for basic things like my example.

## How do you think this should be implemented?

**For starters, this could be read only**. For example like this:

`GET /[project]/items/[bookmark-name]`
Of course the `[bookmark-name]` must be unique within collection names to make this work.

Further developed, this could also work with creating and updating items. 
If your bookmark is for example filtered by the field `active == true` then creating an item within the bookmark could default `active` to `true` if omitted in the request body.

## Would you be willing to work on this?

I would love to but I don't have any PHP skills and not much time to learn it, unfortunately. 
I develop native mobile apps.

---

**So what do you guys think of the idea :)?**

**Comment by rijkvanzanten** [comment]
I love this idea. We do need to think about the endpoint / way to retrieve and create this though. By using `GET /[project]/items/[bookmark-name]`, it could be very easy to accidentally cause conflicts with `GET /[project]/items/[collection-name]`.

We could also go with something like (thinking aloud here)

```
GET /bookmarks/[id]
```

or 

```
GET /items/[collection]?bookmark=[id]
```

or

?

**Comment by benhaynes** [comment]
Just adding my two cents here:

In the App we call this a bookmark, which is one way to use this data. But _generally_ these are data presets (thus the table name `directus_collection_presets`). Since we're talking about data from the API, I wonder if it makes more sense to use `preset` in the parameter instead? Would it then make sense to do both?

```
GET /bookmarks/[id]
```

and

```
GET /items/[collection]?preset=[id]
```

Not sure if/how these might be different, but both seem like good formats to me...

**Comment by fl034** [comment]
Thanks for your suggestions here.
When I think one step further like I mentioned above...

>Further developed, this could also work with creating and updating items.
If your bookmark is for example filtered by the field active == true then creating an item within the bookmark could default active to true if omitted in the request body.

... it could be helpful not to make this feature using GET-params.
When I want to create an item _inside this preset_ (so that it has all the properties set that qualifies it for this filtered collection), I use `POST`.  And a `POST` request with `GET` params maybe is against the standard, or at least not so pretty 😇.

So I'd prefer your suggestions that don't rely on `GET` params.

**Comment by rijkvanzanten** [comment]
> to create an item inside this preset (so that it has all the properties set that qualifies it for this filtered collection)

I have some trouble imagining how this would work. Could you provide a specific example?

@benhaynes I think we shouldn't duplicate the same behavior in two different syntaxes, lets keep it simple. Based on the fact that this has to work with all http request methods, lets go with a `/presets/` endpoint.

The other thing we need to think about is the difference between returning the preset and returning the items that apply to said preset. `/presets/1` should return the first preset I think, but if that's the case, what endpoint will return the items that match that preset?

**Comment by benhaynes** [comment]
I see what you're saying, and agree we shouldn't duplicate behavior... but if `/presets/1` returns the actual preset info, then we need a second way to access the preset's items (which is what you're asking). I personally think `GET /items/[collection]?preset=[id]` makes the most sense for returning the preset's items.

**Comment by rijkvanzanten** [comment]
> I personally think GET /items/[collection]?preset=[id] makes the most sense for returning the preset's items.

I agree, but that does raise a question of _creating_ new items _in_ a param.

**Comment by benhaynes** [comment]
Does it? I see it as another Get Items query param (same as `filter`). We could look into creating items in a param later, but it doesn't seem to be required for getting.

https://docs.directus.io/api/reference.html#query-parameters

**Comment by fl034** [comment]
@rijkvanzanten I think I gave a little example, see my quote :).

Since bookmarks always belong to one collection, we could do it like that:

```
(GET|POST|...) /items/[collection]/preset/[id]/...
```

But adding to a bookmark is more like a nice-to-have feature, I'd be happy with your suggestion @benhaynes.

**Comment by rijkvanzanten** [comment]
Right, this

> If your bookmark is for example filtered by the field active == true then creating an item within the bookmark could default active to true if omitted in the request body.

Besides the equals statement, settings defaults based on filters is going to be very hard. What value would be use for a filter of `score > 15`, or `row contains N related items`?

**Comment by fl034** [comment]
Yeah you're absolutely right about that.
In the app we could for example preselect/prefill values where it's clear to speed up item creation.
But we would have to take some steps to make it absolutely clear for the user what's happening.
So again, it's rather low prio.

**Comment by benhaynes** [comment]
Agree. Let's plan on focusing on the GET endpoint in this ticket — the POST seems like something completely different that could be thought about later.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
