### ISSUE TITLE
Status is not enforced in new user creation

### ISSUE THREAD

**Issue by fnicastri** [directus/api#928]
# Bug Report
Status is not enforced in new user creation
## Steps to Reproduce

1. Add a new user
2. fill all the fields but __status__
2. Save

## Expected Behavior
User is marked as Draft

## Actual Behavior
The field __status__ in __directus_users__ contain __raf__
The user is not accesible in the App

## Technical Details

- Directus bundle v.7.0.19

**Comment by rijkvanzanten** [comment]
@shealavington didn't we verify this the other day?

**Comment by shealavington** [comment]
Indeed @rijkvanzanten, I believe this was fixed and status now has a default selected, so you can't submit without a status. I'm not sure of which release, but I was on the latest when we briefly discussed.

@fnicastri Could I recommend you upgrade from `7.0.19` as there have been three releases since then, with one more due today _(which I highly recommend doing when it releases)_, then would you be able to re-confirm if you have this issue for me?

**Comment by fnicastri** [comment]
@shealavington I would like to update, but I haven't found a path to update the Directus Suite anywhere.
the docs are lacking in this area.

**Comment by rijkvanzanten** [comment]
https://docs.directus.io/guides/upgrading.html

**Comment by fnicastri** [comment]
my fault... I had opened the link before but somehow my focus was on links to other repositories

Thanks

**Comment by rijkvanzanten** [comment]
ref https://github.com/directus/app/issues/1382

**Comment by fnicastri** [comment]
I've updated but... latest version is nearly unusable.
config.js is wrong, points to the demo app `https://demo-api.directus.app/_/": "Directus Demo API`
Layout is totally a mess, the file interface is not working, the buttons are under the drop area.

**Comment by benhaynes** [comment]
I assume you _just_ pulled the latest release from a few minutes ago, ran the database update, and cleared any caches, etc?

**Comment by fnicastri** [comment]
Nope, latest was 190422A when I downloaded it, marked __11 days ago__.
I'll update to the new one.

**Comment by fnicastri** [comment]
Much better!

Thanks

**Comment by shealavington** [comment]
Seems like this issue was fixed @rijkvanzanten. 

Closing this issue.
