### ISSUE TITLE
Add support for default field information

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#93]
When a column exists in the table, it should be returned in `/fields` _even if there is no record in `directus_fields` for it. The information in `directus_fields` should be a progressive enhancement on the actual existing columns. That way, the system will work as expected, even if you setup your database directly in MySQL instead of through Directus.

**Comment by WellingGuzman** [comment]
Closed by https://github.com/directus/api/commit/c38e3e5c9144525dc6cef159b63815be7e17e1be

Filters nor any parameters are not going to be implemented yet.
