### ISSUE TITLE
New collections are created in the wrong database collation

### ISSUE THREAD

**Issue by alanford123** [directus/api#931]
# Bug Report

## Steps to Reproduce

Set utf8mb4 in api.php
Create new collection
View DB

## Expected Behavior
Should be utf8mb4
## Actual Behavior
Is latin1_swedish_ci
## Other Context & Screenshots
![image](https://user-images.githubusercontent.com/11723882/57182198-c45ea000-6e9c-11e9-8d07-e80f9de95fee.png)
![image](https://user-images.githubusercontent.com/11723882/57182205-d17b8f00-6e9c-11e9-8a07-5cbe32129010.png)

**Comment by bjgajjar** [comment]
Fixed in #936
