### ISSUE TITLE
Aliyun OSS

### ISSUE THREAD

**Issue by cdwmhcc** [directus/api#935]
# Feature Request
aliyun OSS

## What problem does this feature solve?
S3 services are not available in China.
Because Amazon does not have a server available in China
For Chinese people, we can not normally access foreign networks. If we want to access foreign networks, we need to connect VPN, which is very difficult for ordinary people. In China, people use Aliyun OSS to store files.

## How do you think this should be implemented?
Https://github.com/aliyun/aliyun-oss-php-sdk/blob/master/README.md

**Comment by benydc** [comment]
@cdwmhcc @benhaynes there is a aliyun-oss flysystem adapter

how can I contribute?

**Comment by cdwmhcc** [comment]
> @cdwmhcc @benhaynes there is a aliyun-oss flysystem adapter
> 
> how can I contribute?

nice going!

**Comment by benhaynes** [comment]
Hey @benydc — Thank you!! It'd be great to get a better understanding of how to create more custom storage adapters (one of our extension types). Here are our (incomplete) docs for storage adapters. Our previous lead dev left the team before finishing. :/

https://docs.directus.io/extensions/storage-adapters.html#core-adapters
https://docs.directus.io/advanced/api/configuration.html#storage

@bjgajjar @hemratna — do you know if we support custom storage adapters as of now? If so, how can we create them? I'd love to get these docs updated!

I don't see any `storage` directory in here, so maybe it's not supported yet? Or maybe it's all done through the config?

https://github.com/directus/api/tree/master/public/extensions/custom

**Comment by benydc** [comment]
@benhaynes the core needs to be touched to create the adapter, I created a pull request with the changes:
https://github.com/directus/api/pull/939

I have tested it and it works:
<img width="686" alt="Screenshot 2019-05-08 at 11 55 52" src="https://user-images.githubusercontent.com/19665791/57362907-7a213b80-7188-11e9-871e-01d77b05f1e5.png">

**Comment by benhaynes** [comment]
Thanks @benydc !! I commented my thoughts on the PR.

**Comment by cdwmhcc** [comment]
> @benhaynes the core needs to be touched to create the adapter, I created a pull request with the changes:
> #939
> 
> I have tested it and it works:
> <img alt="Screenshot 2019-05-08 at 11 55 52" width="686" src="https://user-images.githubusercontent.com/19665791/57362907-7a213b80-7188-11e9-871e-01d77b05f1e5.png">

Thank you very much!!!

**Comment by cdwmhcc** [comment]
> @cdwmhcc @benhaynes there is a aliyun-oss flysystem adapter
> 
> how can I contribute?

![image](https://user-images.githubusercontent.com/8030134/57494940-4405c800-72fe-11e9-8cb4-d6b0d583b0aa.png)

![image](https://user-images.githubusercontent.com/8030134/57495012-92b36200-72fe-11e9-8b6e-13551140f1b3.png)

![image](https://user-images.githubusercontent.com/8030134/57495020-a3fc6e80-72fe-11e9-9dac-f53bb83b3b0d.png)


I configured it.
But it doesn't seem to work.

**Comment by cdwmhcc** [comment]
![image](https://user-images.githubusercontent.com/8030134/57495075-f76ebc80-72fe-11e9-9fd1-efb19e9918cd.png)
![image](https://user-images.githubusercontent.com/8030134/57495093-12d9c780-72ff-11e9-9d81-d5435a62a205.png)

I see. It also needs a Bucket Domain.
But I don't know how to set it up.

**Comment by benydc** [comment]
@cdwmhcc  in the api.php replace value in `root_url` with `https://macwo.oss-cn-qingdao.aliyuncs.com/uploads/_/originals`

I don't understand your last phrase, what do you mean?

**Comment by cdwmhcc** [comment]
> @cdwmhcc in the api.php replace value in `root_url` with `https://macwo.oss-cn-qingdao.aliyuncs.com/uploads/_/originals`
> 
> I don't understand your last phrase, what do you mean?

OKK，I see，haha
Thank you!

**Comment by cdwmhcc** [comment]
> @cdwmhcc in the api.php replace value in `root_url` with `https://macwo.oss-cn-qingdao.aliyuncs.com/uploads/_/originals`
> 
> I don't understand your last phrase, what do you mean?

![image](https://user-images.githubusercontent.com/8030134/57523573-e605ce80-7357-11e9-9c4a-ab02b51b85d1.png)


The originals root URL is working properly
But how to set up the thumbnail URL


> @cdwmhcc in the api.php replace value in `root_url` with `https://macwo.oss-cn-qingdao.aliyuncs.com/uploads/_/originals`
> 
> I don't understand your last phrase, what do you mean?

The originals root URL is working properly
But how to set up the thumbnail root URL

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
