### ISSUE TITLE
"Failed generating the SQL query" when using varchar Primary key

### ISSUE THREAD

**Issue by pbsgc** [directus/api#943]
# Bug Report

## Steps to Reproduce

1. Create a collection
2. Remove 'ID'
3. Create Text Input 'key' and set as primary key
4. Create collection item with key
5. Go to collection item list and try to open created item
6. See error

## Expected Behavior
Correct SQL is created and Collection item edit screen is shown.
In my case the correct SQL would be: 
[correct_sql.txt](https://github.com/directus/api/files/3162838/correct_sql.txt)

## Actual Behavior
Wrong SQL is created: 
[wrong_sql.txt](https://github.com/directus/api/files/3162839/wrong_sql.txt)
Error message is displayed.

## Other Context & Screenshots

I'm no expert on MySQL Syntax but it seems clear that the generated syntax is wrong: 
CAST(key as CHAR) IN ('key') should be CAST(\`key\` as CHAR) IN ('key'). 

Btw. when I change the field type to CHAR instead of VARCHAR then it always sets a length of 1 for the field and all tries to save keys longer than that fail.

I am using the app, the error is returned from the api as a `500 Internal Server Error`:

{
    "error": {
        "code": 9,
        "message": "Failed generating the SQL query.",
        "query": "SELECT \`content_component_layout\`.\`created_on\` AS \`created_on\`, \`content_component_layout\`.\`modified_by\` AS \`modified_by\`, \`content_component_layout\`.\`modified_on\` AS \`modified_on\`, \`content_component_layout\`.\`key\` AS \`key\`, \`content_component_layout\`.\`layout\` AS \`layout\`, \`content_component_layout\`.\`interface_type\` AS \`interface_type\`, \`content_component_layout\`.\`created_by\` AS \`created_by\` FROM \`content_component_layout\` WHERE CAST(key as CHAR) IN ('Default_TextArea') ORDER BY \`content_component_layout\`.\`key\` IS NULL, \`content_component_layout\`.\`key\` ASC, \`content_component_layout\`.\`key\` ASC LIMIT 1 OFFSET 0"
    }
}

## Technical Details

- Device: macbook
- OS: MacOS 10.14.4 
- Web Server: Apache/2.4.34 (Unix)
- PHP Version: 7.1.23
- Database: 8.0.16 (MySQL Community Server - GPL)
- Install Method: cloned `build` branch

**Comment by bjgajjar** [comment]
Fixed in #947
