### ISSUE TITLE
Logging request data [feature request]

### ISSUE THREAD

**Issue by Nitwel** [directus/api#950]
## The Idea
The first idea was to have a counter interface which allows you to log information about how, when and who opened an item, but I think you can implement this more general. The idea is that directus logs all actions to 1: the activity table or 2: to an extra table about all requests made to the api.

## Why you might ask?
So that companys can marked their products to items that where often clicked for example or check out the activity on their webpage or mobile app or whatever.

## What should this feature include?

Logging data like:
- type of request [pull/get...]
- browser used
- request source [if it is the website or the directus app]
and so on.

It would also be possible that we could add an diagram layout for this feature so the collected data is displayed in a readable way. And I would be willing to work on this layout. ^^

It would also be nice if this feature could be enabled or disabled via the config so if somebody dont want to log such data, he can disable it.

**Comment by benhaynes** [comment]
Love it! I even had this idea a while ago 😉

https://github.com/directus/api/issues/85
