### ISSUE TITLE
Updating Decimals Interface resets precision

### ISSUE THREAD

**Issue by mvhirsch** [directus/api#952]
# Bug Report

I noticed a strange bug in API: updateding a numeric interface will reset it's decimal precision to "x,0". Can't see a reason, why?

## Steps to Reproduce

1. Go to 'Admin Settings'
2. Add 'numeric' Interface to any table, setting "decimal" and e.g. _10,4_ as length.
3. Update the same column again (you will see _10,4_ as expected), setting length to _10,2_
4. Update again (just open the modal) you will see _10,0_

## Expected Behavior

I expected it the decimals length to be _10,2_.

## Actual Behavior

I got _10,0_

## Other Context & Screenshots

This issue was already reported here: https://github.com/directus/api/issues/814

It seems that the App is sending the correct length: _10,2_. But Api is responding with _10,0_.
Also the MySQL database's column structure will be: `DECIMAL(10,0)`. 

Modify the column in MySQL directly works as a workaround.

## Technical Details

- Device: Desktop
- OS: Linux Fedora 29
- Web Server: nginx (docker)
- PHP Version: 7.2 (docker)
- Database: MySQL 5.7.20
- Install Method: (docker) directus/api:2.0.18

**Comment by itsmerhp** [comment]
@mvhirsch Please update directus/api to latest version v2.0.23 and try.

**Comment by mvhirsch** [comment]
@itsmerhp thank you for your reply! 
Waiting for updates: https://github.com/directus/docker/issues/35

**Comment by mvhirsch** [comment]
I think this is a duplicate of https://github.com/directus/api/issues/853. @benhaynes I'll close this issue.

**Comment by benhaynes** [comment]
Thanks @mvhirsch!! 😄
