### ISSUE TITLE
filter bug

### ISSUE THREAD

**Issue by cdwmhcc** [directus/api#958]
# Bug Report

## Steps to Reproduce

1. Add Collection `blog`
2. Add fileds `title`,`description`
3. Add blog posts,  title ` Hello world `,description ' Hello Directus '
4.Edit this post,click ` save as copy `

![image](https://user-images.githubusercontent.com/8030134/57797038-20b69f00-777c-11e9-8774-8b13a4f2f7dc.png)

5.delet this copy

6.filter user ` logical `
``` javascript
  const getparams = {
    meta:"result_count",
    fields: "id,title,description",
    filter: {
      title:{
        logical:'or',
        contains: 'Hello'
      },
      description:{
        logical:'or',
        contains: 'Hello'
      }
    },
    status: "published"
  }
  
  client.getItems("blog",getparams).then((res) => {
    console.log('list',res.data)
  });
```
6.The deleted data can also be queried because there is this item in the database.

## Technical Details

- Device: [eg: Desktop]
- OS: [eg: MacOS 10.13.6]
- Web Server: [eg: Nginx 1.8]
- PHP Version: [eg: 7.3]
- Database: [eg: MySQL 5.7]
- Install Method: [eg: cloned `master` branch]

**Comment by bjgajjar** [comment]
Hey @cdwmhcc ,

I am not able to reproduce this issue as when I deleted the duplicate entry, it was deleted from DB too. So I got the single entry only instead of both of them.

**Comment by cdwmhcc** [comment]
@bjgajjar @benhaynes https://rangerstudio.slack.com/files/UHQ1E2J5Q/FJV1W8073/20190528_081912.mp4

**Comment by bjgajjar** [comment]
This issue will replicate if you have `status` field in your collection. And issue occurs cause of MySQL where condition priority. For your filters; query have the condition like 

> WHERE `title` LIKE '%Hello%' OR `title_des` LIKE '%Hello%' AND `status` IN ('published', 'draft') 

But it should like 

> WHERE (`title` LIKE '%Hello%' OR `title_des` LIKE '%Hello%') AND `status` IN ('published', 'draft') 

I found the problem. Will send the PR ASAP.
