### ISSUE TITLE
Personalized and selectable email templates

### ISSUE THREAD

**Issue by cesasol** [directus/api#962]
# Feature Request

Currently you can only override existing templates but there is no way to define new custom templates and choose between them.

## What problem does this feature solve?

Using directus api as a complete backend solution for business websites

## How do you think this should be implemented?

Allowing more parameters in `MailService` to detect and use defined templates in the custom path and throw error if there is no template.

## Would you be willing to work on this?

Not right now for time constraints in the current projects I'm working on, maybe in the future.

**Comment by benhaynes** [comment]
I like it. Thanks for adding this...

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
