### ISSUE TITLE
Mails are send with html despite using "plain" as type 

### ISSUE THREAD

**Issue by cesasol** [directus/api#963]
# Bug Report

## Steps to Reproduce
Send a mail with the type option set to plain, example payload: 

```json
{
  "to": [
    1,
    "cesar@wdinamo.com",
    2,
    {"email": "cesasol@hotmail.com", "name": "Cesar Doe"}
  ],
  "subject": "Prueba",
  "body": "Este es un texto de prueba",
  "type": "plain",
  "data": {}
}
```

## Expected Behavior

Send the raw body of the payload.

## Actual Behavior

The mail is sent with html and as plain text resulting in viewing the html code.

## Other Context & Screenshots

![Screenshot_20190517_173039](https://user-images.githubusercontent.com/3846473/57959473-9da35f00-78c9-11e9-8ea3-6124a097bc61.png)

## Technical Details

- Device: Desktop
- OS: Linux
- Web Server: Nginx
- PHP Version: 7.2.x
- Database: MySQL
- Install Method: cloned the directus repo

**Comment by bjgajjar** [comment]
Fixed in #966
