### ISSUE TITLE
Update schema.sql File

### ISSUE THREAD

**Issue by benhaynes** [directus/api#972]
This isn't really a bug, but is causing bugs for certain installations (manual).

Currently the [schema.sql](https://github.com/directus/api/blob/master/src/schema.sql) file is out of date with the migrations. We need to re-generate this file every time the schema or data changes in the migration files.

Alternatively, @rijkvanzanten has requested that a CLI endpoint for generating the file... but perhaps this is not needed if we always keep the schema file up-to-date when changing migrations?

**Comment by rijkvanzanten** [comment]
> but perhaps this is not needed if we always keep the schema file up-to-date when changing migrations?

Changing the schema.sql manually is very error prone, creating it fresh every time a migration is changed is very cumbersome and easy to forget

**Comment by benhaynes** [comment]
What do you recommend @rijkvanzanten, the CLI? 

@bjgajjar — any idea how long that CLI would take to create?

I think we should focus on bugs for now, but after that we could add it.

**Comment by bjgajjar** [comment]
@benhaynes - I'll get back to you soon on this but right now let's focus on the bugs only :)

**Comment by benhaynes** [comment]
Since this file has now been manually generated, I will convert this to a feature request for the CLI/automation.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by rijkvanzanten** [comment]
> Since this file has now been manually generated

Has it?

**Comment by benhaynes** [comment]
Hmm, it says it was updated 3d ago...

https://github.com/directus/api/blob/master/src/schema.sql

@bjgajjar — have you manually updated this file so it uses all the most recent migrations, etc. It should be a 100% clean install of Directus.

**Comment by bjgajjar** [comment]
@rijkvanzanten 

Yeah you can check it from #1020

**Comment by rijkvanzanten** [comment]
Was this before or after the change that sets directus_activity to timeline?

**Comment by bjgajjar** [comment]
No, the timeline layout occurs after merging #964. So by default now we have a timeline layout instead of tabular.
