### ISSUE TITLE
Add ability to upload extensions as .zip

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#973]
# Feature Request

Using the [Directus Extension Toolkit](https://github.com/directus/extension-toolkit) you're able to easily create custom extensions that can be added to Directus. However, there's no way to easily install these custom extensions into the API. You are still required to login and put the files in the correct place manually.

## How do you think this should be implemented?

We should add a dedicated endpoint for creating (POST) and deleting (DELETE) extensions. I believe we might be able to extend the `/interfaces`, `/pages`, and `/layouts` endpoints with `POST` and `DELETE` methods to respectively create and remove these extensions. 

`POST` should only accept a single .zip file, that will be unzipped in the right location on the server for example `/public/extensions/custom/interfaces`

**Comment by benhaynes** [comment]
We could also use this for the Marketplace, right? Love it.

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**
