### ISSUE TITLE
Set up No Extensions Found 

### ISSUE THREAD

**Issue by WiebeK** [directus/api#974]
# Bug Report

**Short:** There's no npm build script for the extensions, I get a No Extensions Found error message in the app.

I'm setting up the API from source in a Docker container using the **php:7.2.2-apache** image. I try to connect to the API with the official app Docker image. The database connection is working and the API seems to be working but when I connect via the app and log in I get this message: **No Extensions Found**. According to the documentation (https://docs.directus.io/advanced/source.html#api-source) I have to run **npm install** and **npm run build** for the extensions to work, but there's no build script included.

## Steps to Reproduce

1. Open the app
2. Connect to the configured API (according to the docs)
3. Sign in with admin credentials

## Expected Behavior
Show collections.

## Actual Behavior
Returns a **No Extensions Found** message.

## Technical Details

- Device: Desktop
- OS: MacOS 10.14
- Web Server: Apache
- PHP Version: 7.2.2
- Database: MySQL 5.6
- Install Method: cloned master branch

**Comment by benhaynes** [comment]
🔔 @rijkvanzanten — any thought on this? Is this specific to Docker? Anything in the Docs we can update to clarify this?

**Comment by rijkvanzanten** [comment]
What version of the API / app are you using?

**Comment by WiebeK** [comment]
> What version of the API / app are you using?

Thanks for the quick reply. The app is on version 7.4.0, the API on 2.1.0.

**Comment by rijkvanzanten** [comment]
Did you build the app from source too?

**Comment by WiebeK** [comment]
No. The app is using the Docker image directus/app:latest from https://github.com/directus/docker.

**Comment by rijkvanzanten** [comment]
And you're positive that that's using 7.4.0? I'm asking because the extensions have been moved to the application early last month, which should mean that this issue shouldn't / can't occur in 7.4

**Comment by WiebeK** [comment]
Oh! My bad, it's using version 7.0.1. I thought I'd use the image since I couldn't get the app to run in a docker container and connect properly myself. Just decided to give it a last try; and it works! Thank you for your help anyways, I appreciate it.

**Comment by rijkvanzanten** [comment]
Ah! Glad to hear. Thanks for following up 🙂
