### ISSUE TITLE
Bug updating related tables using files and file interface

### ISSUE THREAD

**Issue by Lapsus** [directus/api#977]
# Bug Report
When you use a files or file interface you also join users and roles to the collection.
During the update the RelationalTableGateway (line 622ff) also tries to update directus_user_roles and directus_roles which is only allowed for admin users (CoreServiceProvider line 643ff). 

## Steps to Reproduce
1. Create a collection with "user-created" interface and add a "files" interface. 
2. Autocreate relations. 
3. Add a role, grant "mine" permission to "select/update/delete". 
4. Upload a file, select the file in the "files" interface.
5. Click save.
 
## Expected Behavior
Item and relation should be saved.

## Actual Behavior
Error: you can not update item in directus_user_roles.

## Other Context & Screenshots
I would suggest excluding system tables like directus_user_roles, directus_user and directus_roles from the update process in the  RelationalTableGateway.

## Technical Details
manual install with latest api and app master branch.

**Comment by itsmerhp** [comment]
Hey @Lapsus 
It will be very helpful if you provide your dump sql file! If it's private then you can provide it in Slack too!

**Comment by Lapsus** [comment]
@itsmerhp Where do i find you on slack?

**Comment by Lapsus** [comment]
you can find me here: https://rangerstudio.slack.com/team/UDUDQR5U5

**Comment by Lapsus** [comment]
This could also be related to https://github.com/directus/api/issues/888

**Comment by bjgajjar** [comment]
Hey @Lapsus  

I am getting the error of `directus_users` instead of `directus_user_roles`. Just send me your dump file so I can differentiate the scenarios!
