### ISSUE TITLE
[BUG] Invite User

### ISSUE THREAD

**Issue by ybelenko** [directus/api#989]
# Bug Report

User invitation feature doesn't work.

## Steps to Reproduce

```shell
POST http://api.directus.test/_/users/invite
```
```json
{
  "email": "new_test@example.com"
}
```

Received mail contains this activation url:

```
http://api.directus.test/_/auth/invitation/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkYXRlIjoiMjAxOS0wNS0yOSAxNzowOTowNiIsImV4cCI6IjIwMTktMDYtMjggMTc6MDk6MDYiLCJlbWFpbCI6Im5ld190ZXN0QGV4YW1wbGUuY29tIiwic2VuZGVyIjoxLCJ0eXBlIjoiaW52aXRhdGlvbiIsImtleSI6IjI0ZmVhMTQ4LWQ5YTYtNGY5My04NjQ0LTBlNjI2NDRkYTM1ZSIsInByb2plY3QiOiJfIn0.3PcwqPtXgnsoHLz0t4EVADkSNGN1-0YzBv7gsgLHn9E
```

## Expected Behavior
From [API reference](https://docs.directus.io/api/reference.html#invite-user)
> Invites one or more users to this project. It creates a user with an invited status, and then sends an email to the user with instructions on how to activate their account.
> The API will generate and send a JWT token inside the email for this specific request.

## Actual Behavior

* Generates mail with invalid link(`/[project]/auth/invitation/{token}` instead of `/[project]/users/invite/{token}`)
* Generates token with invalid payload
* User cannot accept his invitation by generated link([Accept User Invitation](https://docs.directus.io/api/reference.html#accept-user-invitation) method supports only POST)
* Does nothing if user with provided email already exists.
* `Accept User Invitation` endpoint throws `ForbiddenException` with generated token.

## Other Context & Screenshots

I figured out how to fix token payload and translate invited user status to `active` in `enableUserWithInvitation` method. I'll submit PR soon.

## Technical Details

- Device: Macbook
- OS: MacOS 10.14.5
- Web Server: Apache/2.4.34 (Unix)
- PHP Version: 7.2.10
- Database: MySQL 5.7.23
- Install Method: cloned `master`

**Comment by bjgajjar** [comment]
Fixed in #990
