### ISSUE TITLE
Dot notation to get data property for a "Single File" field by API is not working?

### ISSUE THREAD

**Issue by AstralProgrammer** [directus/api#992]
In relation to #1757 and #2292, I'm trying to get ONLY **full_url** using **fields=featured_image.data.full_url** but it returns the entire **featured_image.data object**.

Is this intentional? If so, is there a proper way to directly get the file data properties without return the entire file data?

**Comment by bjgajjar** [comment]
Fixed in #1030

**Comment by hemratna** [comment]
@AstralProgrammer 

Currently `fields` in the param is working with the column of the database table. 
The value of `data` variable is not the part of `directus_files` table. To make this work I need to change in `ZendDb` files, which is not appropriate.

I am reverting this PR.

Currently, you need to use the `data` object with all the values.
