### ISSUE TITLE
Collection index page shows wrong(?) item count

### ISSUE THREAD

**Issue by freder** [directus/api#994]
# Bug Report

## Steps to Reproduce
- create a collection
- create a new role (making things only readable to "me")
![Screenshot 2019-05-31 at 10 34 36](https://user-images.githubusercontent.com/724844/58693062-3937d380-8390-11e9-948b-0278ce3692da.png)
- create new entry as admin, and one as user with the new role

## Expected Behavior
when logged in as non-admin user, the search field should say "1 item"

## Actual Behavior
it shows "2 items" (also counting the item created by the admin user)
![Screenshot 2019-05-31 at 10 33 49](https://user-images.githubusercontent.com/724844/58693199-8451e680-8390-11e9-9a32-15718078dcd4.png)
not sure if this is intented or not.

## Technical Details

docker: `directus/api:latest` + `directus/app:latest`

**Comment by rijkvanzanten** [comment]
ref https://github.com/directus/api/pull/946

@philleepflorence I guess that filtered_count is even more important than we thought :wink:

**Comment by rijkvanzanten** [comment]
@bjgajjar @benhaynes I had some trouble deciding where to put this / how to label it. It's an enhancement on the API (adding the filtered_count that gives accurate results) but also a bug on the app cause it feels broken on that side.

**Comment by benhaynes** [comment]
Despite the App and API being decoupled, they are both part of the suite. This bug on the App needs to be fixed in the API, so I think calling it a bug/enhancement on the API repo makes most sense.

Hopefully we can close this once #946 is done.

**Comment by philleepflorence** [comment]
I will get this updated and released online tomorrow!
It is important after all.

**Comment by bjgajjar** [comment]
It should be `result_count` instead of `total_count` over there. `API` returns the expected response but this change should be done at `APP` side.
