### ISSUE TITLE
Add access token field to directus_roles

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/api#995]
# Feature Request

Right now, static access tokens are assigned per user, which in turn has their permissions managed through directus_roles. What if instead of the user having this static token, the role itself has it? This would allow Directus to show a list of 'access keys' that can be used in third party software, and it means that we can specify the permissions for each key individually without having the extra nested level of the user. 

This change will make directus access keys work very similarly as AWS IAM keys. You specify if it's programmatic (role) or not admin access (user) and then choose what permissions are available to this key.

Flow:

1. Create key
2. Programmatic or Admin?
[p]1. Add label (role name)
[p]2. Add permissions (permissions)
[p]3. Retrieve key (generated)

[a]1. Create user (email / password)
[a]2. Choose permissions group (role)
[a]3. Retrieve key (generated)

**Comment by rijkvanzanten** [comment]
Context: right now I'm creating a Netlify role with a single Netlify user (that shouldn't be able to login to the app at all) just to have a scoped safe key I can use for the automated builds. Ideally there is 1 access token that's scoped to reading specific collections that's not connected to any user.

**Comment by rijkvanzanten** [comment]
We could alternatively also introduce a `directus_tokens` collection, but it would either have to duplicate a lot of the permissions fields, or be scoped inside a role, which would still result in the 1 role-1 token setup

**Comment by benhaynes** [comment]
A few thoughts:

1. Wouldn't this be a huge breaking change?
2. When performing an action (CREATE, UPDATE, DELETE) don't we want the token attached to a "user" so that we can update activity and revisions for accountability? eg: `user_created`
3. Isn't it nice (at times) to be able to generate multiple tokens with the same permissions (users within a role) so that you can manage/remove them more granularly without having to re-setup permissions each time?

**Comment by benhaynes** [comment]
To achieve better clarity/visibility, we are now tracking feature requests within the [Feature Request](https://github.com/directus/api/projects/40) project board.

**This issue being closed does not mean it's not being considered.**

**Comment by benhaynes** [comment]
> I don't think so, it's an additional field to directus_roles. Shouldn't introduce any other major issues to existing installations

Are you saying we'd add this and _keep_ `directus_users.token`? Might be confusing to have both, but removing that field might break existing installations that are integrated with that field.

> Yeah, these tokens would be scoped to a role, so you have the same effect (eg "Item was updated through Netlify").

At the surface, but currently all those fields (system and custom) are storing `directus_users.id` PK ... and adding this would mean also storing `directus_roles.id` somehow. Not sure how this would work, but it seems a bit messier to me.

> I was thinking about that, but seeing that this is especially aimed at integrations with external services, I don't think it's as relevant (80/20). Besides, the regular user flow is not getting replaced, so you can still do that by relying on users.

👍

**Comment by rijkvanzanten** [comment]
All I'm aiming to achieve is the issue that you have to create a _user_ (including first name, last name, email address, and app password) just to generate a token for an external service to access the API. That's a lot of overhead. It also doesn't make the most sense to me to have to create a user for external services, as they're not really _users_ of the app / platform 🤷‍♂

**Comment by benhaynes** [comment]
Yeah, I get that... and agree with you. But this is looking like a _lesser of two evils_ situation.

To me, a little more overhead when setting up a token is worth keeping the schema simple. Perhaps we could look into other updates that make things easier?

For example we could combine `directus_users.first_name` and `directus_users.last_name` into `directus_users.name`. We could also use conditional fields on users to ask if this is a "User" or "Service" and then change the form/fields a bit.

If we were just creating admin tokens this would be as easy as a CSV in global settings, but with permissions involved it'd be good to not duplicate things or make them too complex.
